### ISSUE TITLE
IR: other frequencies/protocols?

### ISSUE THREAD

**Issue by abliss** [flipperdevices/flipperzero-firmware#1016]
I have an IR remote for my heat pump (Mitsubishi Electric MSZ-GL09NA) and Flipper can't recognize it.

I assume it's using some other frequency or a less-common protocol than TV remotes. It would be great if Flipper could support these someday.

**Comment by skotopes** [comment]
You sure that it uses Infrared?

If it's not recognised as raw, then it uses different carrier frequency. In that case it is still possible to send signal, but it need to be crafted manually.
