### ISSUE TITLE
NFC-V read/save/emulate

### ISSUE THREAD

**Issue by alexlanghart** [flipperdevices/flipperzero-firmware#1023]
**Describe the bug**
On an earlier firmware version I was able to scan this same NFC card and save it, but after updating to v0.50.0 (from whichever out-of-the-box FW version it came with) it doesn't display any button to save the NFC card. See screenshot

**To Reproduce**
1. Go to `NFC`
2. Go to `Read card`
3. Scan this card (which is a gym membership keychain)
4. Note that it reads the card successfully but only presents a `Retry` button - no button to save it.

**Expected behavior**
Upon successful reading of an NFC card, it should present an option to save the card.

**Logs**
I couldn't find any useful logs (even with Debug enabled and log level set to Debug)

**Target**
v0.50.0 ?

**Additional context**
![image](https://user-images.githubusercontent.com/9383856/158265755-2f3d97c4-a8d9-4b0a-ab98-607721b89dec.png)
(greyed out for privacy, but it's 8 bytes)
![image](https://user-images.githubusercontent.com/9383856/158265867-b40ed6f7-5c71-4a11-a57d-1f4d4e5c38c5.png)

Note that this happens after a fresh reinstall, SD card format, and restoration to factoring settings.

**Comment by skotopes** [comment]
Looks like it came with NFC refactoring, we will return this option in future releases.
Do you have use cases for UID emulation?

**Comment by alexlanghart** [comment]
I suppose a use case would be having a single device for multiple NFC ID cards, or backing them up.

**Comment by skotopes** [comment]
But you do understand that what we saving here is only card's UID?
Saving real card data is something that we plan to implement in future.

Also what card are we talking about right now?

**Comment by alexlanghart** [comment]
Oh I assumed the UID was the card's full data; it's simply a gym door access card, so I wouldn't be surprised if it's only a UID.

**Comment by skotopes** [comment]
Gym most likely just uses UID

**Comment by berkgercek** [comment]
gonna dredge this issue back up because I would also like NFC-V emulation support. I've run into a system where I'd really like to emulate my own NFC-V card.

Is there an interim way of just emulating the UID until there is full NFC-V emulation support?

**Comment by skotopes** [comment]
We remember about this issue. NFC-V/B/F are in backlog, we'll start working on them after NFC HAL refactoring(currently in progress).

**Comment by nezza** [comment]
To adjust expectations, my current understanding is that it's not known whether emulating NFC-V is possible using the current hardware, and if it is it will be pretty complex, correct? (NFC-B & F should be supported by the ST25R3916)

**Comment by r12f** [comment]
yea, it looks like only NFC-V reader is supported, but not emulator: https://www.st.com/en/nfc/st25r3916.html.

**Comment by MadjidZ** [comment]
It seems to be happening on this branch : https://github.com/g3gg0/flipperzero-firmware/tree/ISO15693

**Comment by skotopes** [comment]
And was merged some time ago
