### ISSUE TITLE
main prototype

### ISSUE THREAD

**Issue by trn1ty** [flipperdevices/flipperzero-firmware#1026]
I'm still digging through this project with my new Flipper, so don't take me too seriously or urgently. "Dumb n00b looks at professionals' code." etc...

It would be cool if apps could have a `main` prototype. It doesn't necessarily need to take arguments or comply with standards, but having `int main` seems like an easier start prototype than something like `int32 function_app(void *p)`. I'd especially like to see this in the plugin interface.

**Comment by skotopes** [comment]
Hi.

Apps already have this signature for entry point `int32_t (void* p)`.
Where `void* p` is a pointer to c-string with argument passed by loader (or cli).

`Plugins` name is kinda misleading, it's actually applications.
