### ISSUE TITLE
SubGHz: return 300MHz frequency

### ISSUE THREAD

**Issue by wbraswell** [flipperdevices/flipperzero-firmware#1031]
Tag @Skorpionm 
Chamberlain brand garage door remote control
FCC ID: hbw2281
300MHz

**Comment by skotopes** [comment]
@wbraswell by the way, it's already fixed in #1028

**Comment by wbraswell** [comment]
@skotopes 
Without access to Jira, I can't find any way to confirm #1028 actually adds back in 300MHz?

**Comment by MuddledBox** [comment]
@wbraswell look in https://github.com/flipperdevices/flipperzero-firmware/pull/1028/files

Specifically: 
[applications/subghz/subghz.c](https://github.com/flipperdevices/flipperzero-firmware/pull/1028/files#diff-7655a7acf96feb4c136f87657511de7dd28d88749c6d7244ccbe22adc786cec9)

**Comment by skotopes** [comment]
@wbraswell we currently migrating to github issues, we do not plan to continue to use jira.
