### ISSUE TITLE
Infrared: Saved Remote from FW 0.43.1 Does Not Open in FW 0.50.0

### ISSUE THREAD

**Issue by wbraswell** [flipperdevices/flipperzero-firmware#1032]
Tag @Skorpionm 
I saved the "power" and "input" buttons on my TV remote control using FW 0.43.1 (default as received in the mail).  I confirmed I could open, edit, and utilize these two buttons on my TV.  Now that I have updated to FW 0.50.0, my remote control is still listed under "Saved Remotes", but when I click on it, it just returns me to the previous menu as if I had clicked the back button.

**Comment by skotopes** [comment]
The reason why you can not open remotes saved with older firmware is recent migration to new flipper file format.
There were no way to provide firmware level backward support and we decided to break compatibility this time.
In future releases we are planning to add migration tools. But not this time.

This time it will be easier to relearn remote.
