### ISSUE TITLE
Snake game state storage and pausing

### ISSUE THREAD

**Issue by fennectech** [flipperdevices/flipperzero-firmware#1041]
I have really enjoyed picking up the snake game every once in a while   id like if you could have it able to pause and store its state on SD for later resuming

store its state on the SD for resuming later

**Additional context**
its fun! thanks

**Comment by skotopes** [comment]
Possible, everything is in place to implement it.
But keep in mind that this app is demo and doesn't have maintainer inside of the main team.
We'll be happy if someone from community will do it.
