### ISSUE TITLE
RFID: Unable To Detect Or Read Any Signal

### ISSUE THREAD

**Issue by wbraswell** [flipperdevices/flipperzero-firmware#1048]
Tag @skotopes & @Skorpionm 

Using a variety of different RFID tags, I have been unsuccessfully attempting to read an RFID signal.

In the **"125 kHz RFID"** menu, I simply select "Read" and I am given the animation of the Flipper dolphin with the caption **"Reading LF RFID"** while the LED rapidly blinks approx 8x red followed by 4x blue, repeating.

No matter where I locate the RFID tag in relation to the Flipper device, I do not receive any change in status on the Flipper LCD screen.  It keeps the same screen and LED blinking indefinitely.  I have tried several different unrelated RFID tags, with the same uneventful outcome.  I especially focused on placing the RFID tags along the **"bottom of Flipper's body"** as specified on the Kickstarter page.
![wbraswell_20220321-flipper_zero_kickstarter_rfid_1](https://user-images.githubusercontent.com/1772630/159400193-7432049d-48c1-454a-90c4-b39f349baafc.png)
[https://www.kickstarter.com/projects/flipper-devices/flipper-zero-tamagochi-for-hackers](https://www.kickstarter.com/projects/flipper-devices/flipper-zero-tamagochi-for-hackers)

Was my Flipper device shipped from the factory with the RFID transceiver hardware physically broken, or is this a firmware issue?

(I am running FW 0.50.0.)

**Comment by skotopes** [comment]
Do you know exact type of the card?
Are you sure that card you are reading is 125kHz RFID?
Have you tried NFC?

Also please check: https://forum.flipperzero.one/c/125khz-rfid/5

**Comment by wbraswell** [comment]
Okay I tried NFC and was able to get a successful read, and I also tried RFID with a different tag and got a successful read, so I will close this issue now, thanks @skotopes !
