### ISSUE TITLE
Cannot exit Mifare Classic screen (0.52.2)

### ISSUE THREAD

**Issue by ide** [flipperdevices/flipperzero-firmware#1059]
**Describe the bug**
After selecting the option to scan for Mifare Classic ICs, there is no way to exit the UI without a hard reset.

**To Reproduce**
1. Choose "NFC" in the main menu
2. Choose "Run special action"
3. Choose "Read Mifare Classic"
4. Cannot exit the next screen

![fz](https://user-images.githubusercontent.com/379606/160203188-4fa718bf-05ca-4c8e-807c-e5d290f68fc1.png)

**Expected behavior**
Pressing the back button should leave the Mifare Classic screen.

**Logs**
I didn't look at the logs. Can provide them if needed.

**Target**
Model FZ.1 running official firmware and bootloader 0.52.2

**Comment by jman1118** [comment]
I get a "function requires an SD card with fresh databases" message.

**Comment by gornekich** [comment]
@jman1118 you should update firmware with qFlipper, it will load all necessary databases on SD card

**Comment by gornekich** [comment]
@ide thanks for report. Fix just arrived to dev
