### ISSUE TITLE
Strange Behavior When Deleting Through Pinned/Quick Access

### ISSUE THREAD

**Issue by OMGNapples** [flipperdevices/flipperzero-firmware#1061]
**Describe the bug**
If I hit the down button to access my pinned or quick access saved subghz or infrared, open the item in app, and then delete, I see strange behavior. For subghz, I'm stuck in a blank screen loop which requires me to reboot the device. In infrared, a strange UI/UX behavior occurs.

**To Reproduce**

1. Save a subghz raw recording
2. Hit down arrow at home screen and navigate to recording
3. Select "Run in app"
4. Select "More"
5. Delete Signal
6. Flipper Graphic "Deleted" Appears
7. You now see your list of saved subghz recordings
8. The back button takes you to a blank screen
9. The back button again shows you the Flipper "deleted" graphic
10. The back button again takes you to the list of subghz recordings
11. Reboot device to restore functionality 
--------------------------------------------------------------------
1. Save an infrared remote
2. Hit down arrow at home screen and navigate to remote
3. Select "Run in app"
4. Select "Edit"
5. Delete Remote
6. Flipper Graphic "Deleted" Appears
7. You now see your list of saved infrared remotes, and the remote you deleted is still there
8. Your cursor is in the box of 4 options for the remote you deleted
9. "Run in app" will do nothing
10. "Pin" will allow you to pin/unpin repeatedly
11. "Rename" will allow you to rename, but when you confirm or go back, it will be deleted
12. "Delete" will delete
13. Hitting Left or Right arrow keys will delete

**Expected behavior**
For subghz, once I have deleted a signal and see my list of saved signals, I expect the Back button to take me back to the Home screen.

For infrared, once I have deleted the remote and see my list of saved remotes, I expect the remote I just deleted to not exist.

**Comment by skotopes** [comment]
Fixed in 0.56.1, please feel free to reopen if issue still persist
