### ISSUE TITLE
[NFC] Sub-Folder browsing not available from main app launch

### ISSUE THREAD

**Issue by TheyCallMeZ** [flipperdevices/flipperzero-firmware#1070]
Only items in the main folder are visible, I suspect this applies to other items as well.

**To Reproduce**
Load up files in the NFC folder and a subfolder under nfc

1. Switch on...
2. Press center navigation button
3. Select NFC
4. Select "Saved cards"
5. See only the files in the base folder

**Expected behavior**
Subfolder appears, and shows valid items for the NFC app 

**Additional context**
To compare behavior, take the same file setup/structure then do the following
1. Switch on...
2. Press Down Navigation Button
3. Press Right (or left) until you get to the NFC menu
4. See that the folder exists there, can be entered and devices can be emulated / ran in app

**Comment by skotopes** [comment]
Fixed in 0.5x branch
