### ISSUE TITLE
Request for 134kHz reading

### ISSUE THREAD

**Issue by cshock159** [flipperdevices/flipperzero-firmware#1077]
Request to add 134 kHz reading capability. The goal is to be able to read and decipher rfid chips injected into pets. The first half of pets/animals/livestock are covered with the 125 kHz reading, but due to https://en.wikipedia.org/wiki/ISO_11784_and_ISO_11785, there is some variation and 134 kHz would need to be added. 

https://prckc.org/wp-content/uploads/microchipping-101.pdf more details on the methods of injection, the placement, and the reading of these chips. 

https://en.wikipedia.org/wiki/Microchip_implant_(animal)

**Comment by SnowLeopard71** [comment]
FYI:  http://www.gizmolab.co.za/fdx-b-protocol/
> FDX-B, is an Animal Identification data format covered by ISO 11784/5 and normally operates at 134.2 KHz, which is slightly higher then the 125KHz RFID tags. It uses ASK modulation with BI-Phase encoding.

There is also the specs of the 128-bit stream.

This repo has ESP32 FDX-B code:  https://github.com/s60sc/ESP32_RFID_Reader

**Comment by spencerthayer** [comment]
As someone who rescues lost pets on the regular, this would be exceptionally useful. Please make this a reality. Thank you.

**Comment by ghost** [comment]
Same here. An ability to help with reading pet chips would be super usable, and saves a lot of time compared to taking them to the vet.

**Comment by decidedlygray** [comment]
As a newbie to the project, I was wondering if someone might be able to outline in broad strokes what would be required to implement this?

**Comment by gorodulin** [comment]
I have two suspicious looking stray cats in my backyard. They will bite if I try to catch them, but I could scan them to see if they are lost.
Local RFIDs operate on 134.2 KHz

**Comment by spencerthayer** [comment]
I've more or less stopped using Flipper, but if and when this gets put into the code repository I'll finally have a use for it.

**Comment by Bertus-W** [comment]
it's being implemented by @DrZlo13 atm

**Comment by exussum12** [comment]
Just tried the dev branch for this and it scans well! Great job @DrZlo13 and others involved

**Comment by hbrylkowski** [comment]
> Just tried the dev branch for this and it scans well! Great job @DrZlo13 and others involved

can you share which specific branch?

**Comment by exussum12** [comment]
https://github.com/mauimauer/flipperzero-firmware/tree/fdxb

**Comment by databonanza** [comment]
This would be a great win considering when my cat had a chip injected i was then told that I needed to "register" with some payment service to be able to identify my pet in the future.  I'd like to cut out the middle man, my cat has a chip in it.... I should be able to read it just like anyone else should be able to read it.

**Comment by exussum12** [comment]
The other service is still needed. The chip gives a number out. The number to pet info lookup is provided by a service similar to the one you are talking about.

**Comment by databonanza** [comment]
@exussum12 - wouldn't we just make a public registry?  I don't see why you'd have to pay a service to do this.  Enable the public to scan their own pets, provide a way for them to publicly register the numbers/contact info.  Seems like the right thing to do vs. catering to a private "for pay" registry.

**Comment by decidedlygray** [comment]
Couple issues with that I think:

- there isn't just 1 microchip provider, so there are actually multiple registries
- even if it's a public registry, someone has to pay to create and subsequently maintain the web app and API

More info: https://www.aaha.org/your-pet/pet-microchip-lookup/microchip-search/

Kind of like registering a domain name. There are lots of different registries, and someone has to maintain WHOIS records and pay ICANN fees and whatever

**Comment by databonanza** [comment]
I'm not sure I follow.  Github seems pretty free to me.  Why couldn't a repo here do the job?  I'm not attempting to be sly here, I'm just wondering why a paid service would be needed at all.  Yes "someone" pays for github.com to stay online, but it's not you or me.

**Comment by phptanker** [comment]
I don't really care about being able to read from any pet database. I just want to scan my cat's RFID chips so I can make cool automations, for example count how many times they visit the bathroom box every day.

**Comment by exussum12** [comment]
@databonanza time is not free either. Hosting on GitHub would mean managing pull requests.

**Comment by exussum12** [comment]
@phptanker this current version wouldn't work well. While I can scan my dog it's not trivial to find. I think you would have better luck with a dedicated scanner

**Comment by SnowLeopard71** [comment]
>  I needed to "register" with some payment service to be able to identify my pet in the future.

@databonanza  Weren't you referred to a specific service to register with?    Normally, the registration fee is included in the cost of the chip and you don't have to pay extra.

**Comment by exussum12** [comment]
I know I did not pay for it originally, but to change my info (when moving house) I had to pay a registration fee of £15 from memory.

**Comment by databonanza** [comment]
> @databonanza time is not free either. Hosting on GitHub would mean managing pull requests.

Preaching to the choir.

> > I needed to "register" with some payment service to be able to identify my pet in the future.
> 
> @databonanza Weren't you referred to a specific service to register with? Normally, the registration fee is included in the cost of the chip and you don't have to pay extra.

Yes, they wanted some yearly fee, it was like a subscription service.  I think a "free service" could easily be made w/ private donations.  If I were a multimillionaire I would gladly fund something like this out of pocket for the betterment of man.

**Comment by klimeryk** [comment]
> it's being implemented by @DrZlo13 atm

For those that want to follow the PR: https://github.com/flipperdevices/flipperzero-firmware/pull/1601

**Comment by ender003** [comment]
To add to the request - please also include the ability to read/emulate ISO17785 HDX half-duplex. 

https://www.ti.com/lit/ug/scbu037/scbu037.pdf

**Comment by exussum12** [comment]
This can be closed now, it was added in the latest stable firmware

**Comment by Taby1993** [comment]
Can flipper change number microchip?

**Comment by skotopes** [comment]
Check latest release and if you found unsupported tag then please report exact vendor/model

**Comment by Taby1993** [comment]
Just this question, Can he change the number on the chip? Please answer to me.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by skotopes** [comment]
Depends on what chip is used: if it is t5577 then yes.

**Comment by Taby1993** [comment]
Fdx B iso 11784/5 134.2 Khz?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by skotopes** [comment]
@DrZlo13

**Comment by DrZlo13** [comment]
Our RFID scheme is not designed to receive HDX protocol. The rest protocols (FDX-A, FDX-B) mentioned in this issue is done.

**Comment by Taby1993** [comment]
Ok thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
