### ISSUE TITLE
NFC-B read/save

### ISSUE THREAD

**Issue by wbraswell** [flipperdevices/flipperzero-firmware#1079]
I was able to successfully scan a NFC-B item and I see the UID displayed, but the only option is "Retry", there is no option for "Save"?

**Comment by skotopes** [comment]
Currently we only can detect this type of cards. We don't yet support getting data from it.

**Comment by QuartzMovement** [comment]
That is strange, I was able to save a transit card with the NFC feature, but now the same card cannot be saved because of the NFC-B incompatibility.

Was the feature previously there?

**Comment by skotopes** [comment]
@QuartzMovement updated NFC-B support arrived some time ago with a new NFC stack.
