### ISSUE TITLE
[NFC] Detecting Ultralight will run indefinitely when scanning 

### ISSUE THREAD

**Issue by jman1118** [flipperdevices/flipperzero-firmware#1081]
Bug - Ultralight script will run in infinite loop when scanning for tag

1. Switch on
2. Select NFC
3. Read Card
4. More
5. Run compatible app

Expected Behavior:
Flipper should time out after X seconds if no card detected or return a result

This issue is occurring while reading a hotel key card (Assa Abloy MIFARE Ultralight EV1 tag)
[https://colnect.com/en/hotel_key_cards/hotel_key_card/67638-Assa_Abloy_-_Silver_Letters_-_4817692-Assa_Abloy_Manufacturer-Manufacturers](url)

**Comment by skotopes** [comment]
Looks abnormal. Can you also switch "Settings->System->Log Level" to debug and  provide console log?

**Comment by gornekich** [comment]
Ultralight cards can protect memory area with password. In this case you have to know password to authenticate to protected memory. This functionality is not implemented in flipper so far.
However, I can say that this is the reason why you can't read card if you provide console logs

**Comment by jlaughter** [comment]
I'm seeing the same behavior.  Will try to pull a log on it

**Comment by jlaughter** [comment]
Here's the console log for this - repeats indefinitely until cancelled:

10970315 [D][NfcWorker]: Found Mifare Ultralight tag. Start reading
10970316 [D][MfUltralight]: Reading version
10970321 [D][MfUltralight]: Reading signature
10970373 [D][FuriHalNfc]: Timeout during data exchange
10970375 [D][MfUltralight]: Failed redaing signature
10970377 [D][MfUltralight]: Reading counters
10970430 [D][FuriHalNfc]: Timeout during data exchange
10970431 [D][MfUltralight]: Failed to read 0 counter
10970433 [D][MfUltralight]: Reading tearing flags
10970486 [D][FuriHalNfc]: Timeout during data exchange
10970490 [D][MfUltralight]: Reading pages 0 - 3
10970542 [D][FuriHalNfc]: Timeout during data exchange
10970544 [D][MfUltralight]: Failed to read pages 0 - 3
10970546 [D][NfcWorker]: Failed reading Mifare Ultralight

**Comment by GMMan** [comment]
Suggest trying to read this with NXP NFC TagInfo to see if there are any specific configurations on the tag. Most notably, whether the entire tag can be read without authenticating.

**Comment by skotopes** [comment]
Please check latest Release and reopen if issue persist
