### ISSUE TITLE
Byte input in signal info menu Sub-Ghz

### ISSUE THREAD

**Issue by Semeeconductor** [flipperdevices/flipperzero-firmware#1106]
I would like to have an option to input 32-bit seed value for FAAC SLH protocol to decode signals from flipper zero menu similar to manual byte input in NFC / RFID / iButton apps instead of manually putting it in source.
![seed_slh](https://user-images.githubusercontent.com/103456150/162815292-d87e3507-b60f-414d-b112-95769215a599.png)

**Comment by skotopes** [comment]
@Skorpionm take a look please

**Comment by skotopes** [comment]
Nope )
