### ISSUE TITLE
Genie Garage Door Protocol

### ISSUE THREAD

**Issue by hanui** [flipperdevices/flipperzero-firmware#1124]
Using Genie garage door opener, same button is used for opening and closing. Recorded signals do not seem to work on the garage.
[Genie_Garage.zip](https://github.com/flipperdevices/flipperzero-firmware/files/8498842/Genie_Garage.zip)

**Comment by Skorpionm** [comment]
signals are recorded incorrectly, and very short, do as it is written here
https://forum.flipperzero.one/t/my-remote-isnt-supported-how-to-add-new-sub-ghz-protocol-in-flipper-zero/2033
