### ISSUE TITLE
Sending De Bruin sequences

### ISSUE THREAD

**Issue by RChadwick7** [flipperdevices/flipperzero-firmware#1128]
Will De Bruin be added to the Sub-GHz?

**Comment by Skorpionm** [comment]
there are ready-made sequence generation scripts for RAW, we are for the fair use of flipper

**Comment by skotopes** [comment]
Most protocols designed to handle that kind of brute force attack. I don't see how it may be useful. 
But you can implement it in your application. FuriHalSubGhz are designed to work with sequence generators in the first place.
