### ISSUE TITLE
Readme points to dead link

### ISSUE THREAD

**Issue by Hackerman-the-tired** [flipperdevices/flipperzero-firmware#1143]
Trying to install the environment on a different pc and https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/$toolchain_package.tar.bz2 is connecting but can't download anything.

**Comment by skotopes** [comment]
Hi.

Looks like you've been part of the script to download tool chain. `$toolchain_package` is defined earlier and used to autodetect your linux platform.

```
toolchain="gcc-arm-none-eabi-10.3-2021.10"
toolchain_package="$toolchain-$(uname -m)-linux"

wget -P /opt "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/$toolchain_package.tar.bz2"

tar xjf /opt/$toolchain_package.tar.bz2 -C /opt
rm /opt/$toolchain_package.tar.bz2

for file in /opt/$toolchain/bin/* ; do ln -s "${file}" "/usr/bin/$(basename ${file})" ; done
```

Also you can grab package directly from arm web site: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads
