### ISSUE TITLE
Folders in saved signals/cards

### ISSUE THREAD

**Issue by Moonman0922** [flipperdevices/flipperzero-firmware#1154]
I tried to add a subfolder of door codes within my saved sub-GHz signals. The Flipper doesn't recognize the folder.

I would like to see the ability to place signals and cards in folders to sort them.

A tagging system might also work.

**Comment by ZeroXR-13mg** [comment]
Seconding this. I would love the ability to have folders, because I would love to be able to sort my Amiibo scans by folders.

It's definitely a bit messy with just having everything dumped into their respective directories (sub-GHz, NFC, IR, etc)

**Comment by Skorpionm** [comment]
already now you can lay out signals for SubGhz in any folders and subfolders, but for now it is possible to load them only through the archive (down button on the main screen)

**Comment by Moonman0922** [comment]
> already now you can lay out signals for SubGhz in any folders and subfolders, but for now it is possible to load them only through the archive (down button on the main screen)

I did find this after I made the feature request. It would be really nice to be able to see them in the menu too. Also. QFlipper doesn't allow moving existing files into folders. Just ones uploaded from a computer. Allowing drag and drop would be very cool.

**Comment by Skorpionm** [comment]
You just thought, and we have already done.  working ahead of the curve

**Comment by Moonman0922** [comment]
You all are great! This is some real 5 star service!!
