### ISSUE TITLE
Support for more 125 kHz Fobs

### ISSUE THREAD

**Issue by dankNaan** [flipperdevices/flipperzero-firmware#1155]
**Is your feature request related to a problem? Please describe.**
Flipper Zero is unable to read certain 125 kHz Key Fobs. 

**Describe the solution you'd like**
Please add support to read more fobs, specifically the Kantech P40KEY ioProx XSF/26 bit.

**Describe alternatives you've considered**
Tried reading with both apps (NFC, RFID)

**Additional context**
Also mentioned on [Reddit ](https://www.reddit.com/r/flipperzero/comments/u9obht/read_highfrequency_1356_mhz_tags/)

**Comment by dustingrady** [comment]
Yes please. I have a couple unsupported fobs that I'd love to use with Flipper :)

**Comment by skotopes** [comment]
work in progress

**Comment by Mah-Yerb** [comment]
Eth

**Comment by skotopes** [comment]
Check latest Release and create new issue if you found unsupported vendor
