### ISSUE TITLE
desktop: status bar gap mismatched for status icons vs battery icon on black background

### ISSUE THREAD

**Issue by digitalcircuit** [flipperdevices/flipperzero-firmware#1164]
**Describe the bug**
On black desktop backgrounds, the battery icon has a 2 pixel wide gap from the swooshy lines/status bar, while the status icons only have a 1 pixel wide gap.

Note that the spacing makes sense on light (orange) backgrounds.  There might need to be desktop animation specific UI logic.

![Screenshot showing the sleeping animation with the mismatching status bar icons](https://zorro.casa/sync/Hosting/Utilities/Development/FlipperDevices/flipperzero-firmware/issues/desktop-status-battery-black-bg/Screenshot-20220424-battery-charge-icon.png#v1) 

In the above screenshot, observe the black gap between the swooshy lines and the status icons vs the battery icon.

**To Reproduce**
1. Turn on and view the desktop
2. Wait for [the sleeping animation (`L1_Sleep_128x64`)](https://github.com/flipperdevices/flipperzero-firmware/tree/dev/assets/dolphin/external/L1_Sleep_128x64 )
    * This might be triggerable via other means, not sure
3. Observe status bar icons (SD card, Bluetooth, battery, etc)

**Expected behavior**
The battery icon has a 1 pixel wide gap from the swooshy lines/status bar, same as the 1 pixel wide gap of the status icons.

![Screenshot showing the sleeping animation with edits to the status bar icons to better blend them in with the black background](https://zorro.casa/sync/Hosting/Utilities/Development/FlipperDevices/flipperzero-firmware/issues/desktop-status-battery-black-bg/Screenshot-20220424-battery-charge-icon%20-%20edited.png#v1)

The above is a mockup of how it might look, adding a red arrow to help illustrate the change.

Optionally, the orange background behind the battery could be rounded by placing black pixels in the corners.

**Logs**
If logs would be helpful, let me know.

**Target**
Flipper Zero FZ.1

**Additional context**
This is a very minor graphical issue.  I wouldn't worry about this until the team's focusing on visual polish.

**Comment by skotopes** [comment]
wip

**Comment by skotopes** [comment]
Please check latest dev and reopen if issue is still there.
