### ISSUE TITLE
Can't rename folder

### ISSUE THREAD

**Issue by JulyIghor** [flipperdevices/flipperzero-firmware#1165]
**Describe the bug**
I renamed folder but instead of a new name it created a new empty folder.

**To Reproduce**
1. Use context menu to rename folder

**Expected behavior**
Folder renamed

**Actual behavior**
A new empty folder created, target folder not renamed.

**Additional troubleshooting**
1. Does the issue persist if you try multiple times?
Yes
2. Does reconnecting/rebooting Flipper solve it?
No

![telegram-cloud-photo-size-2-5416076300424165584-y](https://user-images.githubusercontent.com/3390357/164956688-8970758a-a8a4-4feb-917f-e568d7f314f9.jpg)

<img width="812" alt="image" src="https://user-images.githubusercontent.com/3390357/164956767-094031f0-7083-4491-8c4a-3d08f0f12b91.png">

<img width="813" alt="image" src="https://user-images.githubusercontent.com/3390357/164956773-ab3d0d87-ff76-48e1-baed-407ac852770e.png">

**Comment by gsurkov** [comment]
This is a known firmware issue. It is being worked on.

**Comment by skotopes** [comment]
Fixed somewhere in 0.5x.
