### ISSUE TITLE
Saved MiFare Ultralight NFC not working to target read device

### ISSUE THREAD

**Issue by idalisdesalvo** [flipperdevices/flipperzero-firmware#1169]
**Describe the bug**
Saved MiFare Ultralight NFC (Amiibo) not working to target read device (Nintendo Switch)

**To Reproduce**
1. Target read device (Nintendo Switch) is put into read mode (Read Amiibo)
2. Flipper is navigated to NFC->Saved->[file].nfc->Emulate Ultralight
3. Target device (Nintendo Switch) reports "Failed to read Amiibo". Flipper remains in "Emulating Mf Ultralight) until user intervention (back button).
4. Flashing firmware to 55.1 (from 56.1) results in working as expected.

**Expected behavior**
Target read device reads NFC tag (Amiibo) from Flipper saved NFC file.

**Logs**
Add debug logs

**Target**
Target read device is Nintendo Switch HAC-001(-01)

**Additional context**

**Comment by jlaughter** [comment]
Confirmed above behavior in 56.1, 56.1RC and Dev19f42c53.  Rolling back to 55.1 restores emulate functionality.

**Comment by gornekich** [comment]
Fix in https://github.com/flipperdevices/flipperzero-firmware/pull/1179
Soon will be in release

**Comment by skotopes** [comment]
fixed in dev, will be include in release 0.57
