### ISSUE TITLE
Stopwatch and Clock

### ISSUE THREAD

**Issue by RogueMaster** [flipperdevices/flipperzero-firmware#1172]
Would be nice to have a stopwatch and a clock. It could even be an accessible feature in the unimplemented dumb mode.

**Comment by skotopes** [comment]
Possible, low priority. Anyone who will want to implement are welcomed to do that.

**Comment by zhovner** [comment]
There is no guarantees that Flipper's internal clock is synced and  accurate. Thats why we not implement clock in it. 

About stopwatch -- doesn't your phone can do this better?

Suggested to close.

**Comment by RogueMaster** [comment]
I have a clock and stop watch application now. Seems to work well. Not sure why you would suggest to close such a valuable feature that is so easy to add. Clock is now my main favorite/first app on my flipper and my most used.

**Comment by RogueMaster** [comment]
I will confirm with CompaqDisc on his plans to submit his clock app. I modified his clock app to have the stopwatch.

**Comment by RogueMaster** [comment]
Here is the code for clock and stopwatch. https://gist.github.com/RogueMaster/ed2e16647a0ade3372dcbeb078507517 
I can remove sound alerts if it is preferred

**Comment by skotopes** [comment]
furi_hal_speaker is meant to be used throw notification service.

**Comment by RogueMaster** [comment]
How do you recommend it be changed? If that is what you are suggesting.

I am using it to throw a notification yes. Service was not needed as it is operating as desired without bug/compile errors.

**Comment by skotopes** [comment]
Something like: open notification api record, send notification sequence

**Comment by RogueMaster** [comment]
Updated gist to remove the sound notifications... https://gist.github.com/RogueMaster/ed2e16647a0ade3372dcbeb078507517

**Comment by RogueMaster** [comment]
I have updated the sound notifications so it uses the the proper process. Please see code here: https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/dev/applications/clock_app/clock_app.c

**Comment by jimilinuxguy** [comment]
@RogueMaster, what value does a stop watch bring to Flipper?

Not trying to put down @RogueMaster’s work, as I think you are attempting to make a contribution to the community and a product you support and that’s awesome!

Mirroring @zhovner’s sentiment, I already have a more accurate stop-watch on my wrist and I’m my pocket on my phone.

The flipper is supposed to be a toy/multi-tool for signal investigation and USB hid emulation.

With that in mind, as well as the limited internal storage/resources I  feel you would have an easier time selling this feature and pull request if you could state the benefit.

If you can’t explain the benefit and make it obvious why this feature is needed in the core of the firmware, perhaps that is a feature that is better suited for when loading elf from the SD card is implemented?

**Comment by RogueMaster** [comment]
A clock/stopwatch can be a feature in dumb mode, but also, has value as a Clock/Stopwatch to those that may need one. Even if it's a little "inaccurate", it gets the job done. Everyone has different use cases for this multi-tool. Not everyone may need a clock/stopwatch, but some can find it useful. People do find use from clocks / stopwatches, them being on our wrist didn't stop us from putting them in our phones too. The storage impact of the clock is minimal on the firmware image.

**Comment by staxfur** [comment]
Would be cool for Sure! I might look into this. Is there a preferred way to add applications? I know that currently they are compiled into the firmware, but is it possible to create applications outside of the firmware tree? Would be nice for applications that are not accepted from the maintainers, but are still developed and maintained by the community.

**Comment by RogueMaster** [comment]
@MCWertGaming check my github 😎 This issue is being "fixed" by #1405

**Comment by staxfur** [comment]
Really nice, thanks!

**Comment by kowalski7cc** [comment]
Stepping in, I made a quick figma how the feature could work: https://www.figma.com/file/qwhvP7uKV1kKmy08PzGjM7/clock_app?node-id=0%3A1

**Comment by hedger** [comment]
Now this can be implemented with freslhy released FAP package support outside our code base.
