### ISSUE TITLE
NFC over USB (LibNFC) functionality

### ISSUE THREAD

**Issue by tusing** [flipperdevices/flipperzero-firmware#1173]
In [this](https://www.reddit.com/r/flipperzero/comments/is31re/mifare_attacks_with_flipper/) Reddit thread, @zhovner mentions the Flipper Zero would be able to be used as a "regular USB NFC adapter along with LibNFC." He also provided this diagram:

![bb3wVfO](https://user-images.githubusercontent.com/1077203/165418327-44a7f059-e59d-44d2-bfd7-9d164b4dabe5.png)

I was wondering if this functionality is implemented yet, and if there are any plans to implement it? I was trying to run some attacks on my Mifare Classic that require a powerful CPU, but I cannot seem to find the NFC over USB option in my own Zero that just arrived (at least under "menu NFC -> USB NFC adapter" as mentioned in the Reddit post.)

https://github.com/flipperdevices/flipperzero-firmware/pull/117 seems to add this to the wiki but I still couldn't find anything in the firmware regarding this.

**Comment by skotopes** [comment]
We've been researching possibility and in theory it's possible, but it's too big overhead to emulate NXP's protocol on flipper, and too much of work to implement our protocol on libnfc side.

In general we are open to ideas like this one, question is in implementation. If you have specific ideas on how it will work and what exactly need to be implemented on flipper side then we will help.

**Comment by GMMan** [comment]
The original idea of passing through commands directly to the NFC hardware sounds like it'd work, and I think is something there are already examples for (with other chips) in libnfc. I'm willing to take a look at this as I have a couple of Mifare Classic cards I want to crack too, though probably not for another few weeks. (I started trying to implement a new driver for a PCSC reader until I found out it doesn't give low level enough control.)

**Comment by skotopes** [comment]
> The original idea of passing through commands directly to the NFC hardware sounds like it'd work, and I think is something there are already examples for (with other chips) in libnfc. I'm willing to take a look at this as I have a couple of Mifare Classic cards I want to crack too, though probably not for another few weeks. (I started trying to implement a new driver for a PCSC reader until I found out it doesn't give low level enough control.)

There are some timing issues that are going to break everything. We've made couple test and it looks hardly feasible.

**Comment by SnowLeopard71** [comment]
@skotopes 
Maybe the [*September progress* blog post](https://blog.flipperzero.one/september-progress/) could be updated with a pointer to this issue?   It's where the image is from.
If I hadn't found this closed issue accidentally, I would have been waiting for the *NFC over USB* functionality to be implemented.  Thanks.

**Comment by jevinskie** [comment]
I’ve successfully implemented NFC communications (not using libnfc though) from a host computer through USB to a MCU connected to the ST25R3916 via SPI. I was able to simple pass through most commands over a USB-SPI bridge while handling a few timing sensitive operations in the MCU firmware and custom USB commands.

**Comment by GMMan** [comment]
> I’ve successfully implemented NFC communications (not using libnfc though) from a host computer through USB to a MCU connected to the ST25R3916 via SPI. I was able to simple pass through most commands over a USB-SPI bridge while handling a few timing sensitive operations in the MCU firmware and custom USB commands.

Any plans on sharing this work?

**Comment by jevinskie** [comment]
> Any plans on sharing this work?

Sorry I can’t, it was done for work.

**Comment by eqvinox** [comment]
> > Any plans on sharing this work?
> 
> Sorry I can’t, it was done for work.

@jevinskie do you feel you can share the list of timing sensitive operations you had to implement directly in the MCU? That might make it easier for someone with limited NFC knowledge to implement this.

**Comment by tusing** [comment]
@skotopes If someone has successfully managed to implement this, even if they can't share it due to NDA, should we re-open this issue?

**Comment by skotopes** [comment]
@tusing just try to read your comment one more time and answer this question by your self. 
PS: Also @jevinskie explicitly mentioned that libnfc is not used.

**Comment by LevitatingBusinessMan** [comment]
If the cli for subghz were more flexible, would that not be enough to do some more advanced Mifare attacks?

**Comment by skotopes** [comment]
It depends.
