### ISSUE TITLE
Doesn't prompt to unlock Flipper during firmware update if PIN code is set

### ISSUE THREAD

**Issue by digitalcircuit** [flipperdevices/flipperzero-firmware#1178]
**Describe the bug**
After updating the firmware on my Flipper Zero to the latest development snapshot ([`19f42c5`](https://github.com/flipperdevices/flipperzero-firmware/commit/19f42c529004f51fdc2dba21a98fb0528c203f44 )), the firmware upgrade process gets halted by PIN code prompts.  However, qFlipper does not mention the need to unlock the Flipper to continue the firmware upgrade process.

**To Reproduce**
1. Set a PIN code on your Flipper
    * `Settings` → `Desktop` → `PIN Setup`
2. Open qFlipper and connect your Flipper
3. Start an update to a firmware version containing [`[FL-2494, FL-2497] PIN Lock refactoring, IR library fix (#1167)`](https://github.com/flipperdevices/flipperzero-firmware/commit/2034b6ac4a7dfc262ca0be959966dd6e84205bfe )
4. Wait for Flipper to reboot

**Expected behavior**
qFlipper prompts you to unlock your Flipper to continue the firmware upgrade.

OR…

qFlipper sets a one-time flag on the Flipper firmware to **not** lock the device **for the next reboot only.**

**Actual behavior**
The upgrade process stalls without explanation until you notice you need to enter your PIN code on the device.

**Additional troubleshooting**
1. Does the issue persist if you try multiple times?
    * **Yes**, and you can reinstall the latest development snapshot to test this
3. Does reconnecting/rebooting Flipper solve it?
    * **No**, that's what causes the issue

**The report *must* also include at least one of the following:**
1. A **FULL LOG** of this application run. (see below).
[qFlipper-20220427-153234-edited.txt](https://github.com/flipperdevices/qFlipper/files/8576966/qFlipper-20220427-153234-edited.txt)

**Additional context**
This happens whenever the log files mention…
```
[REG] Device went offline: VID_0x483:PID_0x5740
```
Asides from the first instance of rebooting to DFU mode, every instance afterwards requires unlocking the Flipper device.

I appreciate the PIN code lock blocking firmware updates since otherwise someone could just flash a custom firmware that disables the PIN code.

**Alternatively**, qFlipper could somehow signal to the Flipper firmware to not lock the device for the *next reboot only*, and that would reduce the number of unlock prompts.

**Comment by gsurkov** [comment]
We have reproduced the issue. It will be fixed in the firmware.

**Comment by skotopes** [comment]
fixed in dev, will be included in 0.57

**Comment by digitalcircuit** [comment]
I've updated to `0.57.0-rc` and I can confirm this works!

Steps taken:
1.  Update to `0.57.0-rc`
2.  Re-setup PIN code (as expected [due to `DESKTOP_SETTINGS_VER` update](https://github.com/flipperdevices/flipperzero-firmware/commit/0eac917f911c717071a109f916a2aedaa40d68cf#diff-4c90ba8120cab371271ad3b6a6e7ab3ffc386925c86ebc6108b2776883dfbc97L8-R8 ))
3.  With Flipper unlocked, re-install `0.57.0-rc`
     * ✅ Device remained unlocked during the update process
4.  Lock Flipper, restart device (briefly hold left arrow + back)
     * ✅ Device locked on reboot
5.  Unlock Flipper, restart device
     * ✅ Device unlocked on reboot

Thank you!
