### ISSUE TITLE
Send Sub-GHz keys to mobile app once captured and store its GPS coordinates

### ISSUE THREAD

**Issue by JulyIghor** [flipperdevices/flipperzero-firmware#1188]
If you use Sub-GHz constant monitoring, you may capture a lot of keys while walking.
But you don't know where is the keys located.
I suggest to push the keys over BlueTooth to mobile app once they found.
So mobile app can store GPS coordinates and time and it become more useful.

**Comment by skotopes** [comment]
Please open this feature request in mobile apps

**Comment by Stichoza** [comment]
This could also be possible through GPS module connected to GPIO.

BTW, if you add location data to your .sub files, they can be displayed on Flipper Map web app:

- [flipper-map.stichoza.com](https://flipper-map.stichoza.com/)

Looks like this:

![Image](https://github.com/user-attachments/assets/69fbc2c1-d656-4684-ad98-ddb1e9d95593)
