### ISSUE TITLE
Kaseikyo IR protocol

### ISSUE THREAD

**Issue by samuel** [flipperdevices/flipperzero-firmware#1199]
**Is your feature request related to a problem? Please describe.**

Currently any IR remote using the Kaseikyo protocol (e.g. Denon) is not supported. It works with raw IR support, but having a specific codec would make it possibly (easier) to construct the .ir using the manufacturers documentation without needing to record every button press or if the remote is not available.

**Describe the solution you'd like**

Encoder and decoder for the Kaseikyo IR protocol as described in the following links:

- https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/src/ir_Kaseikyo.hpp
- http://www.hifi-remote.com/johnsfine/DecodeIR.html#Kaseikyo
- https://www.denon.com/-/media/files/documentmaster/denonna/avr-x3700h_avc-x3700h_ir_code_v01_04062020.doc

**Describe alternatives you've considered**

Generating RAW ir files is possible but tedious and error prone.

**Additional context**

I've implemented encoders and decoders and can open a PR if what I've implemented looks acceptable and there isn't already a codec being worked on.

https://github.com/samuel/flipperzero-firmware/tree/kaseikyo-ir

**Comment by skotopes** [comment]
Added to back log, will be implemented after we finish Infrared Refactoring
