### ISSUE TITLE
FAT32 bug, can't delete files

### ISSUE THREAD

**Issue by JulyIghor** [flipperdevices/flipperzero-firmware#1205]
Steps to reproduce:
1) Create file using this commands:
```
touch test.txt;
chflags hidden test.txt;
chflags uchg test.txt;
```
2) Try to delete files via Flipper firmware or qFlipper app, it fails

**Comment by zhovner** [comment]
Not a bug. Just avoid this flags if you want to delete files from Flipper's menu.
