### ISSUE TITLE
Failed to read Indala RFID card

### ISSUE THREAD

**Issue by nathan9991** [flipperdevices/flipperzero-firmware#1206]
My Flipper is unable to read my INDALA RFID card. 
I've tried two different flippers, and two different INDALA cards.
(both of them are 34bit cards for the INDALA OPTUS system)
Is there a way to display the raw binary bits incoming from the card?
Is there anything I can do to debug the issue?

Thanks for helping me with this great project!

**Comment by skotopes** [comment]
We are working on it.

**Comment by nathan9991** [comment]
Can I help?

**Comment by skotopes** [comment]
@nathan9991 after RAW release, we may need card dump to confirm its type. As for now I guess no.

**Comment by skotopes** [comment]
Check latest Release and reopen if issue persist.
