### ISSUE TITLE
Add IR support for Magiquest devices

### ISSUE THREAD

**Issue by jlaughter** [flipperdevices/flipperzero-firmware#1215]
**Is your feature request related to a problem? Please describe.**
MagiQuest Infrared Wands are live roleplay game devices.  They contain a motion switch and a simple IR transmitter that sends the wand's ID to receivers at game locations to play the game.  The Flipper captures and replays wand streams fine in RAW, but it would be useful to see, store and edit wand ID.  A magnitude value is also included in a Magiquest packet and would be useful to see and capture.

**Describe the solution you'd like**
Decode support for the Magiquest protocol to display the 2-byte magnitude and 4-byte wand ID.  Protocol is detailed in C++ code here:

https://arduino-irremote.github.io/Arduino-IRremote/ir__MagiQuest_8cpp_source.html  

...and Arduino code here:

https://github.com/patricknevindwyer/arduino-magiquest/blob/master/magiquest-sensor-irremote/magiquest-sensor-irremote.ino.   

It's a 56-bit stream for a 2 byte magnitude value and a 4-byte wand ID, Timing is a 25% Mark/75% Space for 0, 50%/50% for 1 on an 1150ms bit duration.   Tested values:  “1” Mark = 580ms, “1” Space = 600ms, “0” Mark = 280ms, “0” Space = 850ms. 

**Describe alternatives you've considered**
RAW capture and replay works, but have to use Arduino to get a specific wand ID, and can't generate files from wand IDs without the physical device.  Also can't optimize the magnitude values with raw captures.

**Additional context**
Additional info on protocol:
https://www.mouser.com/applications/Magic-Wand-Project-for-Halloween-Delights/
https://arduino-irremote.github.io/Arduino-IRremote/ir__MagiQuest_8cpp_source.html

**Comment by skotopes** [comment]
I'll add it to backlog, will be implemented as soon as we finish with Infrared app refactoring

**Comment by skotopes** [comment]
Looks like people being using flipper for magiquest for some time, support arrived long time ago with infrared raw protocol.
