### ISSUE TITLE
Note playback issues with music player.

### ISSUE THREAD

**Issue by OnyxClawe** [flipperdevices/flipperzero-firmware#1225]
**Describe the bug**
Music player adjusts volume mid note distorting the sound

**To Reproduce**
1. Open music player
2. Load a music file (files with extended notes really show the issue)

**Expected behavior**
Note Maintains the same volume throughout playback

**Target**
Flipper music app

**Additional context**
This bug distorts Longer playing notes, making them hard to hear.

This could possibly be a symptom of the application adjusting the notes volume after the note starts playing. it appears to adjust to 25% volume. Manually setting the volume to 25% makes the notes sound normal.

**Comment by OnyxClawe** [comment]
Video of issue: https://cdn.discordapp.com/attachments/746304505879986267/974346030114041856/IMG_2836.mov

**Comment by OnyxClawe** [comment]
It is also possible that the flipper is rapidly switching between the set volume and 25% creating the strange sound signature

**Comment by skotopes** [comment]
I'll take a look in free time

**Comment by skotopes** [comment]
Please check latest dev and reopen if issue is still there.
