### ISSUE TITLE
Reading a file crashes Flipper

### ISSUE THREAD

**Issue by xAptive** [flipperdevices/flipperzero-firmware#1232]
**Describe the bug**
Trying to read a file over the serial port crashes the device

**To Reproduce**
1. Connect to Flipper over serial via minicom
2. Issue command to read file: storage read /ext/badusb/demo_windows.txt

**Additional context**
The OSD shows "Flipper crashes and was rebooted" "furi_check failed"

**Comment by skotopes** [comment]
@nminaylov can you take a looks?
