### ISSUE TITLE
use U2F with Windows signin

### ISSUE THREAD

**Issue by meirpro** [flipperdevices/flipperzero-firmware#1241]
# What do you want to add or change
I just thought of using the U2F mode as another windows sign-in option... just out of curiosity...

when trying it says "This security key can't be used. Please try a different one."

# What questions do you have
why doesn't it work?
is there any reason i should not use this in such a way?
what is the u2f mode usually used for?

**Comment by skotopes** [comment]
Hi, U2F for Microsoft requires extra certification, we don't have plans to do that.

**Comment by hedger** [comment]
https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key
