### ISSUE TITLE
Local sub Ghz Chat (Whistle)

### ISSUE THREAD

**Issue by OnyxClawe** [flipperdevices/flipperzero-firmware#1249]
**Describe the solution you'd like**
A pictochat style local communication application named "Whistle" utilizing the sub Ghz radio and the mobile companion app.
(Obviously name isnt set in stone i just figured it sounded neat)

Flipper would function as the communication radio with the mobile app presenting a keyboard and discord style interface. 

Communicaiton could be divided into "pods" similar to channels within a server

Edit: Mobile interface could leverage the CLI subGhz chat function to transmit messages (thank you for reminding me Aleksandr!)

(old backend suggestion below)
_Users would have a nickname and an ID. The nickname would be customizable and is set when joining a "Pod", IDs use the name of the flipper and function as a UUID._

![image](https://user-images.githubusercontent.com/58921814/169396610-a1722767-da26-461f-bc7e-7ce510acfa25.png)
(rough layout of message composition, featuring: nickname, time sent, and signal strength)

![image](https://user-images.githubusercontent.com/58921814/169398321-3b4a35a0-5d26-4825-a840-c4c6aa91458d.png)
(Rough layout of additional information screen, Opened by tapping on someones nickname)

**Additional context**
While obviously not a necessary feature, it would be quite interesting to use at a convention or other large gatherings where multiple flippers are present.

**Comment by 11OUTsane11** [comment]
Would be cool. Especially if useable, in some capacity, without the app too.

**Comment by skotopes** [comment]
Hi, as I told in discord we already have this under `subghz chat` cli command.
At this point we don't plan to implement UI for it. We will return to this topic after releasing v 1.0.0.
