### ISSUE TITLE
CLI IR TX RAW doesn't work

### ISSUE THREAD

**Issue by moosehadley** [flipperdevices/flipperzero-firmware#1254]
**Describe the bug**
ir tx RAW doesn't appear to work

**To Reproduce**
1. Open command line
2. Attempt to transmit a RAW signal

**Expected behavior**
Signal transmits

**Logs**
ir tx RAW F:10000 DC:100 23 42
Wrong arguments.

**Comment by skotopes** [comment]
Fixed in #1255
