### ISSUE TITLE
Emulating app

### ISSUE THREAD

**Issue by azaitsev** [flipperdevices/flipperzero-firmware#1275]
**Is your feature request related to a problem? Please describe.**
I'd like to get a quick access to all my stored items in one app (lfrfid, subhgz, nfc etc) to emulate it in two clicks.

**Describe the solution you'd like**
I'd like to set as my favourite app an app that contains a list of all my saved items, e.g:
[lf] Home
[lf] Work
[sg] Work barrier
[nfc] Key
[ir] TV

**Comment by DrZlo13** [comment]
"Favorites" tab in the Archive app.

**Comment by zhovner** [comment]
Please read about Archive app and Pin function here https://docs.flipperzero.one/basics/control#xw-archive

**Comment by azaitsev** [comment]
Thank you, it's exactly what I were looking for.
