### ISSUE TITLE
Support for 860 - 960 MHz UHF RFID tags (ISO/ IEC 18000-63 / EPC UHF Gen2)

### ISSUE THREAD

**Issue by crozone** [flipperdevices/flipperzero-firmware#1285]
EPC UHF Gen2 tags are frequently found in stocktaking, warehousing, retail, and industrial RFID applications. It would be useful for Flipper to support reading and emulation of these tags, as well as detection of readers and their protocols (although the "Frequency Analyzer" almost does this for free).

Here is the [fact sheet](https://www.gs1.org/sites/default/files/docs/epc/epc_gen2v2_fact_sheet.pdf). The specification is described [here](https://www.gs1.org/sites/default/files/docs/epc/gs1-epc-gen2v2-uhf-airinterface_i21_r_2018-09-04.pdf). The tags function at 860 MHz – 960 MHz and work by passively absorbing the transmitter energy and then modifying their reflection coefficient in order to back-scatter information back to the reader. The information is usually an EPC identifier unless additional information is requested. The tags support DSB-ASK, SSB-ASK, and PR-ASK modulation.

According to the CC1101 datasheet, the Sub-GHz antenna is limited to 12dBm (16mW), so Flipper is unlikely to be ever able to energize a tag on its own, however would it still be viable to:

* Emulate a tag in response to interrogation by a reader?
* Passively sniff a tag response as it is interrogated by a different reader?

**Comment by skotopes** [comment]
Hi. UHF RFID requires different design for RF. It is impossible to implement it in fllipperzero.
