### ISSUE TITLE
Cannot return to main menu after deleting file

### ISSUE THREAD

**Issue by vuribe1221** [flipperdevices/flipperzero-firmware#1293]
**Describe the bug**
Using the quick menu (down key press) then deleting a Sub-Ghz raw file from the "app" will get you stuck in a sub menu, need to hard reset.

Prerequisites: Have a saved Sub-Ghz Raw file

**To Reproduce**
Starting from the lock screen

unlock device
press down (favorites menu)
press right (Sub-GHz menu)
Select a Raw file (press center button) > Run in app
press Right (More menu) > Press Delete > Delete
File is deleted and are returned to a list of Sub-Ghz files but cannot press back to return to main menu. A reset is required.

**Expected behavior**
Go back to main menu

**Comment by skotopes** [comment]
Fixed in #1292
Please reopen if you still experiencing this issue.
