### ISSUE TITLE
Missing pulses on TX - SubGhz

### ISSUE THREAD

**Issue by alfie65536** [flipperdevices/flipperzero-firmware#1299]
**Describe the bug**
Pulse is missing on TX every 16 pulses on sending 30 microseconds signal

**To Reproduce**
1. Create a RAW .sub file with alternating signals (Example: RAW_Data: -30 30 -30 30 and so forth)
2. Play from Flipper device (650AM - 433.9254Mhz)

**Expected behavior**
Using SDR, I expected the values to read as 101010 directly. Result turned out that every 16 pulses, Flipper would not send the signal and skip a value, changing the overall packet.

**Logs**
Using 30 values in the .sub (Example: RAW_Data: -30 30 -30 30 and so forth)
![image](https://user-images.githubusercontent.com/105245811/172068964-1a7acbe0-4b1a-4488-834b-35ce46b05fb2.png)
Sample from the stream:
1010101010101010010101010101010110101010101010100101010101010101101

Using 100 values in the .sub (Example: RAW_Data: -100 100 -100 100 and so forth)
![image](https://user-images.githubusercontent.com/105245811/172068907-3a6717b2-1b2b-4b99-95d9-226158efed9d.png)
Sample from the stream:
1010101010101010101010101010101010101010101010101010101010101010101

Closer look between the missing pulse shows failure to send:
![image](https://user-images.githubusercontent.com/105245811/172069366-5ae2ca25-cc63-4362-8001-ac8782fd3740.png)

**Target**
Unsure. I was able to find a workaround with the 100 microseconds and might use that. Possibly relay in the Flipper docs that if values intended to be sent are too short, that Flipper may not send reliably?

**Additional context**
Attempting to have Flipper send packets to a RFM69HCW device, exciting project. Trying to have them read as the same with the SDR and attempt to finetune things until they read the same. Did a AAAA repeating hex test to see if they can read the same.

**Comment by pelrun** [comment]
Just a note that it doesn't look like pulses are being lost, but instead it's a hard real-time failure where the flipper is too busy servicing a different task and so the next edge is delayed.

**Comment by Skorpionm** [comment]
failure is unlikely. just like the flipper is very busy. transfer goes through DMA. if I understood everything correctly, then with durations of 100us everything is fine at 30 it fails? I will see what is really happening there, but I have not seen durations smaller than 150us in any protocol

**Comment by Skorpionm** [comment]
![image](https://user-images.githubusercontent.com/85568270/172204260-ac5ee0da-d007-466f-9ee9-1f726c5018a3.png)
30 us 
![image](https://user-images.githubusercontent.com/85568270/172204379-6400672f-5ba2-4f5c-ae12-86c17f57957a.png)

**Comment by Skorpionm** [comment]
![image](https://user-images.githubusercontent.com/85568270/172207285-42807e51-b056-443b-b77a-c3750813ef77.png)
I can’t capture such a fast signal, I have a pickup of 50Hz. 
![image](https://user-images.githubusercontent.com/85568270/172212254-0c97a0b3-6efc-476e-89bf-b3575c7e996a.png)
reception to another module, it seems that CC1101 in RAW format does not have time to send such short signals (in fact, the flipper transmits all data without delay, see photo above), but once again I repeat such short intervals for remote controls

**Comment by skotopes** [comment]
Please re-test current dev and reopen issue if problem is still there.
