### ISSUE TITLE
Bluetooth Debug fails "Incorrect RadioStack

### ISSUE THREAD

**Issue by Vaelatern** [flipperdevices/flipperzero-firmware#1302]
**Describe the bug**

A few pictures are worth a thousand words

![image](https://user-images.githubusercontent.com/7906072/172521981-325de5d2-e5c2-4bc6-baf5-70ed8be4350f.png)
![image](https://user-images.githubusercontent.com/7906072/172522000-c8e3fa41-778d-45df-89c9-0c7e25a2fd82.png)
![image](https://user-images.githubusercontent.com/7906072/172522022-8dc797d8-5ae9-45ff-a9d0-5798ed7e338e.png)
![image](https://user-images.githubusercontent.com/7906072/172522045-af3f5eb3-6f0c-46d0-ac44-7bb5ab47a317.png)

**To Reproduce**
Duplicated on both 0.59.1 and Dev 8b544369

Radio FW 1.13.3 LITE

**Expected behavior**
I expect to be able to poke at this menu to try and understand the bluetooth behaviour of the device.

**Comment by skotopes** [comment]
This is not a bug, those are factory test apps and they require HCI Full radio stack.
