### ISSUE TITLE
Where to suggest documentation suggestions? (docs.flipperzero.one)

### ISSUE THREAD

**Issue by patricknomad** [flipperdevices/flipperzero-firmware#1329]
I'd like to recommend suggestions for https://docs.flipperzero.one/ for new undocumented features.

There used to be https://github.com/flipperdevices/docs but this is now archived.

Is there another place where PRs can be sent for docs?

**Comment by DrZlo13** [comment]
We are working on it, hopefully there will be some solution in the coming weeks.

**Comment by rcprcp** [comment]
I would like to +1 this request, as i think crowd sourcing documentation from the community would greatly improve the quality (and quantity) of documentation. 

Thank you.

**Comment by AkechiShiro** [comment]
I'm waiting for this as well, to help document some stuff.

**Comment by skotopes** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/1633132/224649253-f41fbc23-1c27-448c-9cc1-a2f7441bbfec.png">

Please use this buttons to suggest changes.
