### ISSUE TITLE
Running apps in the background

### ISSUE THREAD

**Issue by otanim** [flipperdevices/flipperzero-firmware#1331]
**Is your feature request related to a problem? Please describe.**
no problems

**Describe the solution you'd like**
have an option to run programs in the background, i.e. you run **Sub-GHz**, meanwhile, you can play Snake, then go back to **Sub-GHz** and see its progress.

**Describe alternatives you've considered**
it's straightforward, sure would've been great to have a task manager as well where you could kill processes.

**Additional context**
n/a

**Comment by DrZlo13** [comment]
No, this feature adds resource synchronization problem and too much entropy. One application at a time is the intended behavior.
