### ISSUE TITLE
infrared: In C rewrite, can't exit with Back if launched via 'Run in app'

### ISSUE THREAD

**Issue by digitalcircuit** [flipperdevices/flipperzero-firmware#1338]
**Describe the bug**
With [the new Infrared C port](https://github.com/flipperdevices/flipperzero-firmware/commit/a8acfcabb4104045b6eadd6c215fc3c88b88614e ), it's not possible to exit with the Back button after launching a saved Infrared remote via the `Run in app` archive browser option or from the `Favorites` (pinned) section.

**To Reproduce**
1. Save (or copy) an infrared remote
2. Go back to the Flipper desktop
3. Press Down to enter archive view
4. Press Right multiple times to navigate to `Infrared`
5. Select the saved remote and press OK, then `Run in app`
6. Press Back to try to exit the Infrared app's saved remote view

**Expected behavior**
Pressing Back exits the Infrared app's saved remote view, as it did before the C rewrite.

In reality, you have to force-reboot the Flipper Zero (hold Left and Back) to exit the Infrared app after launching a saved remote via `Run in app` or from the `Favorites` screen.

**Logs**
*I am not sure what debug logs are relevant.  Does this involve using the WiFi debugging probe?  I can try setting that up if it would help.*

**Target**
Flipper Zero

**Additional context**
This problem occurred after updating from [Change "cad" to "card"](https://github.com/flipperdevices/flipperzero-firmware/commit/7618c8ba6ffe3026858373f8346b052dd45193ef) to [nfc: NTAG21x complete emulation](https://github.com/flipperdevices/flipperzero-firmware/commit/556af0b82b4965c3def35ef2779d37b153038f4d).  It's possible other changes impacted this, but as the SubGhz app correctly exits when launched via `Run in app` or from `Favorites`, I suspect it's the Infrared app C port.

**Comment by gsurkov** [comment]
Fix is in the dev branch.

**Comment by digitalcircuit** [comment]
I've confirmed that https://github.com/flipperdevices/flipperzero-firmware/commit/0b8331656069bbbd011f2dfa0b0c2a03b5d8a859 (https://github.com/flipperdevices/flipperzero-firmware/pull/1340) has fixed this issue, thank you!
