### ISSUE TITLE
NFC: MIFARE Classic 1K: Add support for Infineon Chips

### ISSUE THREAD

**Issue by quantum-x** [flipperdevices/flipperzero-firmware#1342]
MIFARE Classic 1k cards have two main manufacturers, NXP and INFINEON.
NXP's MIFARE Classic 1k cards have an SAK value of 0x08.
INFINEON's MIFARE Classic 1k cards have an SAK value of 0x88.

I suggest updating the mifare.c and nfc_types.c lib files in order to recognise INFINEON MIFARE Classic 1k Tags.

I plan on contributing the code, this issue serves as a discussion point!

**Comment by skotopes** [comment]
Will be released in 0.62
