### ISSUE TITLE
Support for HITAG S 

### ISSUE THREAD

**Issue by COssfeld** [flipperdevices/flipperzero-firmware#1349]
Please add support for reading and emulating 125 kHz HITAG S transponders in plain mode:
https://www.nxp.com/products/rfid-nfc/hitag-lf/hitag-s-transponder-ic:HTSX
The uid should be enough.

**Comment by skotopes** [comment]
@DrZlo13

**Comment by skotopes** [comment]
Check latest Release and reopen if issue persist.

**Comment by COssfeld** [comment]
Just tried 0.66.1, none of my HITAG S transponders are working.

**Comment by skotopes** [comment]
@COssfeld yep, sorry, your ticket was first, but there is another one that actually describes issue with hitag  #1534
