### ISSUE TITLE
Support writing NFC tags

### ISSUE THREAD

**Issue by virtualdxs** [flipperdevices/flipperzero-firmware#1353]
**Is your feature request related to a problem? Please describe.**
I would like to be able to write a new copy of NFC tags I can emulate with Flipper.

**Describe the solution you'd like**
Add a Write option for the different NFC protocols.

**Describe alternatives you've considered**
Emulating from Flipper is a partial workaround

**Additional context**
I'm personally interested in Mifare Classic, but unless it's drastically different effort between the protocols (which it may well be) it seems to make sense to track the overall feature under one issue.

**Comment by GMMan** [comment]
One consideration for implementation is how you are going to handle writing to a tag sized differently than the original. Due to lock bits and other control options, this is not trivial and requires positively identifying the tag type and whether the data is fully writeable before attempting to write the tag.

**Comment by skotopes** [comment]
Hi. We are currently working on it.

**Comment by simkard69** [comment]
Thanks for working on that Feature Request, greatly appreciated !
Cheers from France !

**Comment by meirpro** [comment]
Just wanted to do this and found that I couldn't...
But I can from my phone (quite a few nfc apps available for android)... 
Is there any ETA for this to happen soon or is it planned for a further down the road update?

**Comment by ac1dburnz** [comment]
Any updates?

**Comment by skotopes** [comment]
@colinborins MFC cards write are already in release and next release will add mifare magic card

**Comment by ac1dburnz** [comment]
@skotopes, it seems that I can only write to the same tag and not a new one though, is that going to change?

**Comment by skotopes** [comment]
Yes. Next release will include mfc magic card support.

**Comment by Vitnir** [comment]
@skotopes will it also be possible to write to an new card/other? <3

**Comment by superyarik** [comment]
@skotopes is where is another NFC types write ability planned? NTAG213 f.e.?

**Comment by skotopes** [comment]
Yes.

**Comment by superswiegie** [comment]
The write magic card option now only gives room voor 4 byte UID. Could this be expended with 7 byte UID? ❤️

**Comment by skotopes** [comment]
Yes, other generations of magic cards coming in future releases. I'll close this issue, if you need something specific please create new issue.

**Comment by patrikcze** [comment]
Writing NTAG215 Planned? 👍
