### ISSUE TITLE
Adding mouse_jiggler as a plugin

### ISSUE THREAD

**Issue by ghost** [flipperdevices/flipperzero-firmware#1375]
Hi,

Is it possible to add a mouse jiggler plugin ?
https://github.com/MuddledBox/flipperzero-firmware/blob/Mouse_Jiggler/applications/mouse_jiggler/mouse_jiggler.c

**Comment by RogueMaster** [comment]
You can message me on discord and I can help you...

**Comment by skotopes** [comment]
We are ready to accept it as external application.

**Comment by RogueMaster** [comment]
Hi @skotopes, Can you take this code for that? https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/unleashed/applications/mouse_jiggler/mouse_jiggler.c

**Comment by skotopes** [comment]
@RogueMaster if there will be PR
