### ISSUE TITLE
picopass plugin not installed by default

### ISSUE THREAD

**Issue by DHowett** [flipperdevices/flipperzero-firmware#1391]
The 0.62.1 release notes mention the new picopass plugin, but it is not installed by default.
Calling this out explicitly in the release notes may help people figure out why they can't see it after upgrading!

(This probably won't be a problem once #1387 lands; until then, though, there's no way to install it.)

**Comment by andyt10** [comment]
This does help, thanks very much @DHowett 
Save for Discord, which is horrible to search, there's no mention that a specific Plugin is not installed by default....or that there's even a concept of plugins not being installed by default when in the main branch of code :)

I spent a good hour scratching my head on this one after updating, and reading the release notes, before eventually finding a clue in Discord

**Comment by skotopes** [comment]
Will be included in next release as external elf app

**Comment by DHowett** [comment]
Since 0.67 came out with Picopass included with the application bundle, I consider this fixed. Thanks!
