### ISSUE TITLE
slow down LED flashing

### ISSUE THREAD

**Issue by voidlily** [flipperdevices/flipperzero-firmware#1393]
**Is your feature request related to a problem? Please describe.**
The flashing LED in certain modes like emulating RFID flashes very fast and gives me a headache. I'm worried it might do worse to other people, such as photosensitive epilepsy.

**Describe the solution you'd like**
LED should flash at a much slower rate than it does currently. [According to the Epilepsy Society](https://epilepsysociety.org.uk/about-epilepsy/epileptic-seizures/seizure-triggers/photosensitive-epilepsy) flashing lights anywhere between 3-60hz can trigger seizures

**Describe alternatives you've considered**

**Additional context**
```


static const NotificationSequence blink_test_sequence_hw_blink_start_red = {
--
21 | &message_blink_start_10,
22 | &message_blink_set_color_red,
23 | &message_do_not_reset,

```

```
const NotificationMessage message_blink_start_10 = {
    .type = NotificationMessageTypeLedBlinkStart,
    .data.led_blink.color = 0,
    .data.led_blink.on_time = 10,
    .data.led_blink.period = 100,
};

const NotificationMessage message_blink_start_100 = {
    .type = NotificationMessageTypeLedBlinkStart,
    .data.led_blink.color = 0,
    .data.led_blink.on_time = 100,
    .data.led_blink.period = 1000,
};
```

Does this mean `message_blink_start_10` is on for 10 ms every 100 ms? Does this mean it's somewhere between 10-100hz? Is `message_blink_start_100` 1-10hz? That might still be too fast, but I'm having trouble figuring out exactly how the LED code works

**Comment by voidlily** [comment]
Previous work: https://github.com/flipperdevices/flipperzero-firmware/pull/1303

**Comment by possibly-not** [comment]
A workaround for this is to set the LED brightness to 0% in the "LCD and Notifications" settings.
