### ISSUE TITLE
Can't read database on SD card after using 3V3 port

### ISSUE THREAD

**Issue by mprisciano** [flipperdevices/flipperzero-firmware#1411]
**Bug**
Whenever the 3V3 port is used to supply current to some hardware, upon coming back the Flipper has issues using the SD card and consequently cannot read anything out of it until rebooted.

**To Reproduce**
1. Switch on the Flipper
2. Attach hardware to 3V3 port
3. Try using the Infrared Remote or whatever thing that uses the SD card
4. Receive error message "Cannot create app folder" or "No databases found on SD card"

**Expected behavior**
I expect the Flipper to keep using the SD card while supplying current to external hardware

**Target**
In this case I used an ESP32 connected to the pins GND and 3V3 of the Flipper.

![IMG_6505](https://user-images.githubusercontent.com/12964909/179401919-3535d28d-5423-46d5-b1a8-e6833d67ed23.jpg)
![IMG_6506](https://user-images.githubusercontent.com/12964909/179401921-43b82885-b1fc-4056-9935-cabc86f5ffc9.jpg)
![IMG_6507](https://user-images.githubusercontent.com/12964909/179401922-782cdb41-e590-461f-9283-fe524b58f525.jpg)

**Comment by skotopes** [comment]
That is expected behavior.

ext3.3 is used for SD and ext modules, so if you disturb this power line with external module hot plugging then SD becomes unusable. 

We are researching workarounds for this issue, just keep in mind that this line is NOT OK with hot plugging things.

**Comment by tomholford** [comment]
Having this issue after the latest update, but it seems to occur randomly (ie., not after using the 3v3 port)

**Comment by skotopes** [comment]
@tomholford Try to format sd card

**Comment by skotopes** [comment]
Was fixed some time ago. Flipper will handle SD-Card errors and re-init card if it was power cycled.
We still don't recommend high capacity/current load hot-plug on 3v3, it may cause filesystem corrupt.
