### ISSUE TITLE
SubGhz encoder ignores repeat parameter in receiver_info scene

### ISSUE THREAD

**Issue by xMasterX** [flipperdevices/flipperzero-firmware#1414]
**Describe the bug**
`Repeat` parameter of encoder seems being ignored while sending signal from receiver_info scene with button hold - it only sends just one payload. 
When sending saved signal from transmitter scene - repeat is working properly while holding send button.

**To Reproduce**
1. Receive signal in subghz Read mode
2. Open signal and hold send button (while monitoring output signal) - only 1 payload is sent, ignoring repeat parameter

**Expected behavior**
It should work same as it is in transmitter scene - (can be opened from selecting subghz file in filebrowser)

**Target**
F7

**Additional context**
Button events logic are same between 
`applications/subghz/views/transmitter.c `
and 
`applications/subghz/scenes/subghz_scene_receiver_info.c`
But it works not same way, maybe problem is in another place

**Comment by Skorpionm** [comment]
what exactly are you trying to pass from subghz_scene_receiver_info.c
? make a video of how it doesn't work for you. I just checked on Pricenton, the transmission goes on while the button is held down

**Comment by xMasterX** [comment]
Tested again with sdr, this must be an issue with receiver, all works fine
