### ISSUE TITLE
subghz CLi transmitting in 12bit instead of 24bit

### ISSUE THREAD

**Issue by BitcoinRaven** [flipperdevices/flipperzero-firmware#1418]
# subghz CLi transmitting in 12bit instead of 24bit
I'm trying to transmit using subghz Cli using the following command (12bits):
subghz tx ECA 433920000 10
but it sends nothing, when I change the code to 24bits it works.
Is there a specific argument to make it send in 12bits ??

**Comment by Skorpionm** [comment]
in CLI, only 24-bit key transfer is supported, I'll think about what can be done with this!
