### ISSUE TITLE
Unable to Read Mifare Ultralight card

### ISSUE THREAD

**Issue by casconed** [flipperdevices/flipperzero-firmware#1427]
**Describe the bug**
Using NFC -> Read Card the card is correctly identified but when running Read MifareUltral/Ntag the device just stalls on 'Detecting Ultralight'

**Expected behavior**
Card is read.

**Logs**
[debug.pcap.zip](https://github.com/flipperdevices/flipperzero-firmware/files/9159913/debug.pcap.zip)

**Comment by gornekich** [comment]
Hi.
Looks like your card has read protection. We are going to notify about it in GUI and add extra action to try to unlock these cards

**Comment by awilkins** [comment]
Tesco Clubcard (UK) is an example of one of one of these cards.

**Comment by skotopes** [comment]
Please check latest release and reopen if issue persist.
