### ISSUE TITLE
Import frequency from frequency analyzer to read raw

### ISSUE THREAD

**Issue by Project-Code-Name** [flipperdevices/flipperzero-firmware#1442]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

The workflow would be this: Open the frequency analyzer, get the frequency the device transmits on, you now have the option to either throw away that frequency or you can "import" it to read raw where it would then pre-set that frequency.

**Describe alternatives you've considered**

A way to keep the found frequncy from the analyzer on-screen till the user presses a button.

**Additional context**

**Comment by Skorpionm** [comment]
What if the remote control is multi-frequency?  and if the frequency stabilization at the remote control floats?  how to be then?

**Comment by pmarrapese** [comment]
I opened a related feature request that could incorporate the desired functionality in an elegant way: #1466
