### ISSUE TITLE
Bluetooth and / or NFC U2F

### ISSUE THREAD

**Issue by guilhem** [flipperdevices/flipperzero-firmware#1445]
### Description of the feature you're suggesting.

It's possible to do U2F with bluetooth or NFC.
Flipper has both ;)

### Anything else?

Bluetooth can be market "Bluetooth ENBL"

protocol:
- https://fidoalliance.org/specs/u2f-specs-master/fido-u2f-bt-protocol.html
- https://fidoalliance.org/specs/u2f-specs-master/fido-u2f-nfc-protocol.html

**Comment by skotopes** [comment]
Hi. In theory yes, but it extremely narrow field of application and some platforms require certification (microsoft) which we do not plan to do.
