### ISSUE TITLE
DESfire app does not read cards with "Random UID" feature set

### ISSUE THREAD

**Issue by craftbyte** [flipperdevices/flipperzero-firmware#1447]
### Desctibe the bug.

The DESfire reader app does not seem to be able to read cards with Random UIDs set. The UID is 4-byte, starting with 0x08.

### Reproduction

1. Configure a DESfire card with Random UID (issue SetConfiguration command with option 0x00 and bit 1 set, see Datasheet section 7.4.3.1)
2. Try reading with Flipper
3. Flipper will be stuck reading

**Comment by skotopes** [comment]
@gornekich what do you think ?

**Comment by gornekich** [comment]
Need to get these cards on hand. Need to do more, can't fix it right now
