### ISSUE TITLE
Can't rename or delete RX-only sub-1GHz signals

### ISSUE THREAD

**Issue by ppseprus** [flipperdevices/flipperzero-firmware#1470]
### Describe the bug.

Firmware Version: 0.62.1, 2022-07-13

### Reproduction

1. Record a sub-1GHz signal that is RX-only according to respected regional restrictions (eg. 315MHz for EU-Russia region)
2. Save the signal
3. Navigate to "Saved"
4. Select the saved signal

**Expected Behaviour**
When opening the saved signal, one can select to "Emulate", "Rename" or "Delete"

Just like the linked illustration shows and as other features allow
https://docs.flipperzero.one/sub-ghz/frequencies

**Actual Behaviour**
* The signal is immediately emulated, skipping the sub menu
  * Cannot rename the signal
  * Cannot delete the signal
* Flipper is stuck in _"Transmission is blocked"_ screen and
  * The "back" button returns the user to the SubGHz menu instead of the Saved files

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/1724
check
