### ISSUE TITLE
NFC Reading wrong bank card number

### ISSUE THREAD

**Issue by vladicha7** [flipperdevices/flipperzero-firmware#1476]
### Describe the bug.

Hey all, when i try to read a bank card, it gives me different bank card code. For example if my card ends with 1234, and i read it with the flipperzero it  will show totally different code. Same thing with a different card. 

### Reproduction

1. NFC
2. Read card
3. Reads card, shows the bank
4. Click run
5. Shows the wrong bank card code, exp, UID...

**Comment by skotopes** [comment]
Hi. Which bank it is? Also it looks like intended behavior: card number used for EMV doesn't have to be same.

**Comment by vladicha7** [comment]
> Hi. Which bank it is? Also it looks like intended behavior: card number used for EMV doesn't have to be same.

Raifaisen bank, visa. Oh okay, because a guy said that when he reads his bank card it shows the real numbers.
