### ISSUE TITLE
Frequency Analyzer flash backlight and beep Sound when detected Frequency 

### ISSUE THREAD

**Issue by PeterCheungHK** [flipperdevices/flipperzero-firmware#1480]
### Describe the enhancement you're suggesting.

When the frequency Analyzer detected the frequency  flash backlight and beep sound

**Comment by m1ga** [comment]
But please as an option to turn on light and/or sound. Having it turn on light + https://github.com/flipperdevices/flipperzero-firmware/issues/1466 would make it a lot better!

**Comment by skotopes** [comment]
Please check latest version.
