### ISSUE TITLE
replay serial data from file

### ISSUE THREAD

**Issue by dakhnod** [flipperdevices/flipperzero-firmware#1486]
### Description of the feature you're suggesting.

I am planning on attaching a 40mhz module and would like to be able to have my payload in a file, just like the sub-files.
But instead of outputting that payload through the internal antenna, it should be output on a GPIO / the UART TX, so it can be send through the 40mhz AM module.

Baud rate and possibly the pin should be selectable through the file, just like the sub files.

**Comment by skotopes** [comment]
Very specialized thing. You are welcome to implement it as external application.
