### ISSUE TITLE
Alow universal IR for AC and Audio

### ISSUE THREAD

**Issue by jaroslavmraz** [flipperdevices/flipperzero-firmware#1494]
### Description of the feature you're suggesting.

Hi,

Would it be possible to enable the universal controller for Air Conditioning and Audio devices with brutforce? I have already prepared an ir file for Air Conditioners based on the tv.ir pattern from the assets folder. And I'm happy to share it.

**Comment by skotopes** [comment]
@gsurkov is currently working on it. @jaroslavmraz your file will be quite useful.

**Comment by jaroslavmraz** [comment]
Happy for it :)

Last and more uptodate version made by comunity are here. Comnuity random adding new irs find it here @skotopes 

https://github.com/UberGuidoZ/Flipper/tree/main/Infrared

**Comment by UberGuidoZ** [comment]
Also note: There have been custom-developed remote GUI too that supports the needs (like Mode) for AC. Others for Speakers, Fan, etc.

**Comment by gsurkov** [comment]
A/C universal remote is available now, and there is a [manual](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/UniversalRemotes.md#air-conditioners) for adding new signals.
As for the Audio, I think the library linked above would suffice to start, will add it soon.

**Comment by UberGuidoZ** [comment]
Sounds great. We are trying to keep these files up to date, pulling from the IRDB. 2-3 people are adding while another few are verifying functionality and duplicate/corruption removal. There are linked scripts from @darmiel used for this.

**Comment by gsurkov** [comment]
The Audio universal remote is done as well. However, the aforementioned database could not be used as it lacked the buttons we wanted to include. 
The [manual](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/UniversalRemotes.md) was updated with the Audio-specific info, too.
