### ISSUE TITLE
Saved files are not sorted alphabetically

### ISSUE THREAD

**Issue by ppseprus** [flipperdevices/flipperzero-firmware#1505]
### Describe the bug.

The files of saved signals are not sorted alphabetically.

SubGHz, RFID and Infra are definitely affecetd.

### Reproduction

Since I could not puzzle out to exact sorting logic, It would be rather hard to write a definitive guide to reproduce the issue.

However, saving multiple files with different names would most probably, eventually, result in the same issue.

**Comment by skotopes** [comment]
Never will be. It is a limitation of fatfs driver.

**Comment by ppseprus** [comment]
Thanks for the follow up @skotopes !

**Comment by WillyJL** [comment]
> Never will be. It is a limitation of fatfs driver.

https://github.com/ClaraCrazy/Flipper-Xtreme/commit/e98ad6fc2c2bcce58b3b5e726286fb56b2abeef0

and

https://github.com/ClaraCrazy/Flipper-Xtreme/commit/d6dcf0efa26f77f99d9aac9cba00ad6636e1ebc4

:kekw:

(psst... https://github.com/DarkFlippers/unleashed-firmware/pull/327)

**Comment by Rikarducho** [comment]
> Never will be. It is a limitation of fatfs driver.

Never say never

**Comment by skotopes** [comment]
Try that PR with a couple thousands files

**Comment by ClaraCrazy** [comment]
runs fine with ubers repo & the entire irdb

**Comment by WillyJL** [comment]
also kinda your problem at that point? what you even doing with thousands of files in a folder? are you going to scroll through them on flipper? thats gonna take a while mate

**Comment by skotopes** [comment]
My point is O(N)

**Comment by ClaraCrazy** [comment]
eh, kinda yes. But hes also still got a point, it should ofc run smoothly.. which it does. 

im more bugged by the fact he said its not doable bc of a driver, when its in fact doable and, at the very best, a 200ms delay cost at the scale of ubers massive repo

**Comment by skotopes** [comment]
it will crash flipper on big folders

**Comment by ClaraCrazy** [comment]
> it will crash flipper on big folders

It doesnt crash on the IRDB, it doesnt crash on UberGuidoZs entire dump.. how big of a folder are we talking here? 

At that point I can make the argument that windows will not handle 12exabyte folders, so its not possible to have folders sorted there either?

Feel free to give me a size to test with. maybe you are right, right now with the tests done it just doesnt look like it

**Comment by skotopes** [comment]
Problem with archive that it's running in background while you opening something with it. Any extra memory that you use in archive at that point is going to bite your apps.

We've designed it in a way that it consumes constant amount of ram, what you did totally kills whole idea.

**Comment by ClaraCrazy** [comment]
> Problem with archive that it's running in background while you opening something with it. Any extra memory that you use in archive at that point is going to bite your apps.
> 
> We've designed it in a way that it consumes constant amount of ram, what you did totally kills whole idea. 

Now that is info i can work with and understand where you're coming from. Thanks.

**Comment by skotopes** [comment]
U r welcome. Also the real solution that you looking for is https://www.codeproject.com/Articles/95721/FAT-32-Sorter embedded into storage service that performs background sorting in FAT, but we decided that it doesn't worth it.

**Comment by ClaraCrazy** [comment]
Interesting. Well, thanks for the info. Appreciate it, good work on the FZ btw 🧡 excited to see where this goes
