### ISSUE TITLE
Support Noolite (433)

### ISSUE THREAD

**Issue by iShift** [flipperdevices/flipperzero-firmware#1507]
### Description of the feature you're suggesting.

Add support for recognizing Noolite (433) protocol - it is not encrypted protocol for controlling different smart devices (light/socket/etc) 

So after capturing packages we can show devices in the flipper UI and by clicking - send proper command (enable/disable) 

https://noo.by/produkcia/vykluchateli-besprovodnye.html (in Russian)
https://habr.com/ru/company/contactless/blog/216023/ (In Russian)

https://wirenboard.com/wiki/index.php?title=433MHz/en&mobileaction=toggle_view_desktop  (In English)

**Comment by Skorpionm** [comment]
transmission records?

**Comment by skotopes** [comment]
@iShift we need raw files with it.

**Comment by iShift** [comment]
sorry, can't provide it in near future, if it is critical - we can close the issue @skotopes

**Comment by JstSnt** [comment]
I can provide raw files 
recently found some old switches and use them for holiday lights.
