### ISSUE TITLE
Changing the order of Saved Remote Buttons

### ISSUE THREAD

**Issue by DrJ735** [flipperdevices/flipperzero-firmware#1508]
### Description of the feature you're suggesting.

I saved my first remote the other day and was just thinking about something.  I have my list of buttons and it would be great if I can reorder them.  For an example in the screenshot below I would like to place "Vol_down" under "Vol_Up", and put "Mute" under my volumes. 
![Screenshot_20220731-103140_Flipper](https://user-images.githubusercontent.com/110344895/182035197-136df214-7112-4193-921d-95bbcd3f6b04.jpg)

**Comment by skotopes** [comment]
We have something like that in archive, there is a reorder option. I'll add this issue to backlog.

**Comment by DrJ735** [comment]
Thanks.  It will be just easier to reorder them if you accidently programed the buttons out of order.

**Comment by gsurkov** [comment]
I would like to hear some suggestions on how it should be implemented. A mock-up or a text description would be nice.
Can't do this exactly like in the archive, because short and long presses mean different things here.

**Comment by skotopes** [comment]
Was implemented some time ago
