### ISSUE TITLE
NFC UID bruteforcing

### ISSUE THREAD

**Issue by firefart** [flipperdevices/flipperzero-firmware#1522]
### Description of the feature you're suggesting.

on some entry systems that use NFC chips only the UID is checked against a database to check if a chip should be allowed. The problem arises when companys order a large amount of chips, as the ID on them is most likely only incremented by 1. So you can get a valid UID and start counting down or up until you find a valid ID.

I would suggest implemeting this by supplying a start UID and a direction and then either adding or subtracing one from it until cancelled

**Comment by FLX-0x00** [comment]
I think this should be enough: Start UID, increment or decrement value and maybe the delay used to hop to the next id.

**Comment by skotopes** [comment]
More like some thing for external application. In theory possible.
