### ISSUE TITLE
QR (and other barcodes) from text files

### ISSUE THREAD

**Issue by sliceratwork** [flipperdevices/flipperzero-firmware#1541]
### Description of the feature you're suggesting.

It would be interesting if the Flipper could generate QR codes or other types of barcodes, from text files uploaded on the SD card.

Because of the Flipper's screen size, I know the maximum size a QR code can have is 64x64px, so not too much data, but here are other types of barcodes that could prove useful.

References:
[https://github.com/h0nus/QRGen](https://github.com/h0nus/QRGen)
[https://null-byte.wonderhowto.com/how-to/create-malicious-qr-codes-hack-phones-other-scanners-0197416/](https://null-byte.wonderhowto.com/how-to/create-malicious-qr-codes-hack-phones-other-scanners-0197416/)

**Comment by hedger** [comment]
That's a good idea for a custom app. Once we release support for loadable apps, it should be easy to implement.
