### ISSUE TITLE
Custom “Dolphins”

### ISSUE THREAD

**Issue by darklite80** [flipperdevices/flipperzero-firmware#1543]
### Description of the feature you're suggesting.

Have a guide on how to make a custom “dolphin” wanting to make something like Pickle Rick to armored pickle Rick for level ups or DBZ Goku from kid to adult to SS to God for level ups. Or make some available to download and add to the flipper

**Comment by RogueMaster** [comment]
here is a start: https://github.com/RogueMaster/awesome-flipperzero-withModules/tree/rogue_main/graphics/assets/icons/Passport

**Comment by darklite80** [comment]
You are awesome.

**Comment by incyi** [comment]
Why not build a complete tamagotchi inside ? Like the originals ... https://en.wikipedia.org/wiki/Tamagotchi
