### ISSUE TITLE
Lowercase keyboard displays instead of uppercase.

### ISSUE THREAD

**Issue by DrEverr** [flipperdevices/flipperzero-firmware#1546]
### Describe the bug.

Lowercase keyboard displays after going to `name the file` screen, even though first letter we input is uppercase letter.

### Reproduction

(example one of many)
1. Go to Sub-GHz
2. Read RAW
3. REC (anything, doesn't matter if you have something to record, we just need to enter `Save` mode)
4. STOP
5. Go to Save
6. As you can see. Lowercase keyboard is displayed
7. Type a letter
8. It is uppercase letter

### Anything else?

Fix: keyboard should display uppercase letters on default

**Comment by skotopes** [comment]
fixed in dev
