### ISSUE TITLE
No charging indicator on the screen when in Lock Menu

### ISSUE THREAD

**Issue by grafjan** [flipperdevices/flipperzero-firmware#1552]
### Describe the bug.

If the charger is plugged in or unplugged while the Flipper is in the Lock Menu, the charging indicator on the screen does not change accordingly (the LED does).
Firmware: 0.62.1

### Reproduction

1. Flipper is not charged.
2. Entering the Lock Menu -> no charging indicator on the screen and no LED)
3. Plugging in the charger.
4. LED starts to shine. Battery symbol on the screen remains unchanged.

### Target

The charging indicator adapts to the current charging status like it does in the other screens/menus.

**Comment by skotopes** [comment]
@nminaylov can you take a look?
