### ISSUE TITLE
When running Marauder application with Wifi Dev Board, FZ reports "no databases installed"

### ISSUE THREAD

**Issue by nastea1** [flipperdevices/flipperzero-firmware#1558]
### Describe the bug.

After you run the Marauder application for say 5 minutes or so, sometimes less. When you try and operate the FZ it states "No databases found on SD card.
![Screenshot-20220808-090557](https://user-images.githubusercontent.com/44655438/183468746-1d35712f-c216-40c5-bec4-cde4c6483d0a.png)
"
Holding Left and Back for a hard reboot, resolves this every time. Not sure where to start, however it's like the database is disconnected some how. qFlipper when connected also states no databases installed when this occurs. 

### Reproduction

Turn on FZ
Run Mauarder
ScanAP
List -a
Select -a (pick one)
Run DeAuth Attack for 5 minutes or so
Exit to Main Screen
"No databases found on SD Card"

### Logs

```Text
Tell me what you want and I'll get them.
```

**Comment by nastea1** [comment]
SD Card Manufacturer is SanDisk.

**Comment by Astrrra** [comment]
The marauder app is not a part of our firmware. You're probably using a fork, please file the issue in their repo as we have no relation to them.

**Comment by skotopes** [comment]
Do you hotplug wifi module?

3.3v ext shared with sd card, abnormal load spikes may cause DCDC to reset power, which is causing SD reset.
In general it's better to enable 5V-ext and not to hotplug wifi module.

**Comment by nastea1** [comment]
> Do you hotplug wifi module?
> 
> 3.3v ext shared with sd card, abnormal load spikes may cause DCDC to reset power, which is causing SD reset. In general it's better to enable 5V-ext and not to hotplug wifi module.

Yes I do.  This was mentioned that it might be a voltage issue.  I will attempt all this, thanks for the info.

**Comment by nastea1** [comment]
I can confirm that hot-plugging and not-hotplugging both work fine with 5V enabled. Thank you!

**Comment by lomalkin** [comment]
~~Do this reproduces also in case when Flipper powered via USB?~~
