### ISSUE TITLE
Capture subfolders

### ISSUE THREAD

**Issue by FalsePhilosopher** [flipperdevices/flipperzero-firmware#1559]
### Description of the feature you're suggesting.

Can we please have a subfolder for captures? By that I mean a captures folder in each category that dumps the captures of whatever it is into that folder. I noticed while reading my friends car remote creating a lot of captures just spams your main folder.

### Anything else?

It also makes using qflipper on linux not very fun, having to download each file instead of just a captures folder. Or you gotta go find your sd card reader and play with them that way. Much love for all the other hard work you all are putting in!

**Comment by skotopes** [comment]
Technically subfolders are supported
