### ISSUE TITLE
Flipper freezes when connected to iOS app on dev build

### ISSUE THREAD

**Issue by D4DB0DY** [flipperdevices/flipperzero-firmware#1570]
If I can make it to file browser before it freezes I get this also..

![image](https://user-images.githubusercontent.com/106566379/183792558-5cb0e25c-abb0-4acf-8a1d-3b37bafa979e.png)

Details of the build

![image](https://user-images.githubusercontent.com/106566379/183792804-b980539e-ee8e-4404-9601-ebb179b247d5.jpeg)

**Comment by D4DB0DY** [comment]
Force quitting the iOS app and rebooting the flipper makes the flipper work again. It freezes again when the app reconnects to flipper over bluetooth.

**Comment by UberGuidoZ** [comment]
## I am NOT having the same issues as below on the latest dev build 1d50a598

```
>: log
Press CTRL+C to stop...
46161 [I][BtGap] Connection parameters: Connection Interval: 24 (30 ms), Slave Latency: 0, Supervision Timeout: 72
46418 [I][BtGap] Pairing complete
46422 [I][BtSrv] Open RPC connection
46568 [I][BtGap] Rx MTU size: 414
>:
```
The screen freezes but that appears to be it. Requires a reboot. Nothing is logged, CLI doesn't disconnect.

# The below is for the latest Unleashed firmware
## It's what I was testing at the time...

On connect with Bluetooth (first time), this happened instantly:

![Bluetooth_on_Connect](https://user-images.githubusercontent.com/57457139/183807804-4d3e952d-47de-4383-852f-4c8cc50a8b46.png)

In process of debugging and gather logs.

**Comment by UberGuidoZ** [comment]
![FW](https://user-images.githubusercontent.com/57457139/183809540-a2af19e5-d1b3-4358-a80b-60c11a6e0127.png)

**Comment by UberGuidoZ** [comment]
Pay attention to time stamps to compare to log file

iOS version (iPhone 13)
![iOS_Version](https://user-images.githubusercontent.com/57457139/183809955-39ea3591-b6ae-4d46-8c63-993bcea9f76e.jpg)

-----

Initial connecting screen

![1](https://user-images.githubusercontent.com/57457139/183809680-e51756ec-29db-48b5-b163-30b74d28cd58.png)

-----

Successful connection

![2](https://user-images.githubusercontent.com/57457139/183809685-42dafd37-0f9a-4de0-ac61-7a31608bc0af.png)

-----

Crashed and disconnected

![3](https://user-images.githubusercontent.com/57457139/183809691-96769189-3dd7-4c8f-8bb2-d46adcfe12e8.png)

**Comment by UberGuidoZ** [comment]
Both iOS app and Flipper crashed (HardFault)
[Full_Crash_Log.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9296521/Full_Crash_Log.txt)

Flipper did not crash, just iOS app cycling through the screenshots above
[Repeating_crash_log.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9296523/Repeating_crash_log.txt)

Quickest crash I could log (both crashed)
[Quick_Crash.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9296524/Quick_Crash.txt)

**Comment by skotopes** [comment]
Please check latest dev: there were multiple closed issues.
