### ISSUE TITLE
[FL-1907] storage_file_seek() does not support negative offset

### ISSUE THREAD

**Issue by dummy-decoy** [flipperdevices/flipperzero-firmware#1572]
### Describe the bug.

the signature for the storage_file_seek function is:
bool storage_file_seek(File* file, uint32_t offset, bool from_start);

the uint32_t type (unsigned) used for offset precludes the use of negative offset, thus we cannot go backward in the file.
also, the use of a 32 bit offset looks strange when storage_file_tell() returns a 64 bit position. 

### Reproduction

File* file = storage_file_alloc(furi_record_open(RECORD_STORAGE));
storage_file_open(file, string_get_cstr("dummy"), FSAM_WRITE, FSOM_OPEN_ALWAYS);
storage_file_write(file, "abcdefghi", 9); 
storage_file_close(file);
storage_file_open(file, string_get_cstr("dummy"), FSAM_READ, FSOM_OPEN_EXISTING);
char chr;
storage_file_read(file, &chr, 1);
assert(chr == 'a');
storage_file_read(file, &chr, 1);
assert(chr == 'b');
storage_file_read(file, &chr, 1);
assert(chr == 'c');
storage_file_seek(file, -1, false); // negative offset ?!?
storage_file_read(file, &chr, 1);
assert(chr == 'c');
storage_file_close(file);
storage_file_free(file);

**Comment by skotopes** [comment]
Yep, we were having discussions on this issue. Definitely going to implement it.

Also it's not a bug, offset type is explicitly saying that it's unsigned:
```/** Moves the r/w pointer 
 * @param file pointer to file object.
 * @param offset offset to move the r/w pointer
 * @param from_start set an offset from the start or from the current position
 * @return success flag
 */
bool storage_file_seek(File* file, uint32_t offset, bool from_start);
```

**Comment by DrZlo13** [comment]
Intended behavior to keep storage simple. If you need a negative offset - seek from the beginning of the file, or take furi_stream, it will do it for you.
