### ISSUE TITLE
Favorites- Unpin from favorites when click on favorited item

### ISSUE THREAD

**Issue by RocketGod-git** [flipperdevices/flipperzero-firmware#1586]
### Description of the feature you're suggesting.

When in favorites menu, it would be nice when you click on an item to have "unpin" in the options listed.

### Anything else?

Thanks for an amazing team of devs!

**Comment by skotopes** [comment]
If you talking about favorites on flipper then it's already implemented: OK long press will show you the menu where you can unpin item.
