### ISSUE TITLE
Right button under SubGHz Saved to trigger signal send (without visual rendering)

### ISSUE THREAD

**Issue by ppseprus** [flipperdevices/flipperzero-firmware#1587]
### Description of the feature you're suggesting.

**Background**
* Sometimes, you want to click through a bunch of sub files, try each one-by-one
* Having to open each file, clicking Emulate, then Send, then navigating back to the list of files again is more than troublesome
* Meanwhile, at the file structure level, the right button is unused

**Feature Request**
Under Saved for SubGHz,
* when the focus is on a file
  * the Right button triggers a signal send,
  * the usual Emulate/Send screens are **not** rendered (only the led flickers), unless,
  * if the signal is "longer" than x, the usual Emulate/Send screens are do rendered
    * note: In this case, the user still has to navigate back to the files the usual way — this feature is not for long signals, but for quick access to the send functionality

* when the focus is on a folder
  * the Right button triggers a bulk signal send,
  * the current file name is displayed while the signal is being sent

### Anything else?

Please, consider this request as an idea.
The final implementation could differ — I just think that the "send" functionality should be made accessible through a quick, alternative path.

**Comment by skotopes** [comment]
Our UI framework and general UI/UX guidelines are built on idea that all operations are explicit and visible. Your proposal in current form is just impossible to implement.
Maybe some 3rd party applications can do that.
