### ISSUE TITLE
snake game: briefly vibrate when "Game Over" 

### ISSUE THREAD

**Issue by rcprcp** [flipperdevices/flipperzero-firmware#1593]
### Describe the enhancement you're suggesting.

I think there is an interesting newbie project to enhance the snake game to briefly vibrate when "Game Over" 

Thanks.

**Comment by skotopes** [comment]
Yep, there is a #1577 that implements it. Will be merged soon and included in next release.

**Comment by rcprcp** [comment]
Hi @skotopes  - I have some code for this - I  will put in a PR. 
-- rcprcp
