### ISSUE TITLE
iclass support

### ISSUE THREAD

**Issue by d0mnik** [flipperdevices/flipperzero-firmware#1600]
### Description of the feature you're suggesting.

Currently, the firmware does not seem to provide iclass support. I found an iclass plugin under an alternative firmware for flipper on [another repository](https://github.com/Eng1n33r/flipperzero-firmware). Is it possible to merge the iclass/picoclass plugin into the official firmware? 
Code for the plugin can be found [here](https://github.com/Eng1n33r/flipperzero-firmware/tree/dev/applications/picopass).

**Comment by skotopes** [comment]
Technically it's already merged, just not built by default. It will be included as external application as soon as we release apps SDK.

**Comment by d0mnik** [comment]
is there instructions to build for the feature? I can't find anything regarding this under build instructions.

**Comment by skotopes** [comment]
`./fbt flash --extra-int-apps=picopass`
