### ISSUE TITLE
Can't see details of saved SubGhz you can't replay

### ISSUE THREAD

**Issue by LoZio** [flipperdevices/flipperzero-firmware#1608]
### Describe the enhancement you're suggesting.

I can read signals on bands I cannot transmit to (in my case 315 Mhz).
When I capture that signal I can see the details.
After saving just opening the file results in the "Transmission is blocked" screen.
You should be able to see the details, just like you do when capturing and block the send function only.

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/1724
check
