### ISSUE TITLE
Issues w/ `includePath` on mac

### ISSUE THREAD

**Issue by ppseprus** [flipperdevices/flipperzero-firmware#1617]
### Describe the bug.

Yesterday, I was still able to experiment with an application Im working on. Writing code, flashing it onto my Flipper.
As of today, I've been having all kinds of issues w/ `#include`, but only on in folders I have created.

I have issues w/ the following lines
* `#pragma once`
* `#include <furi.h>`
* `#include <furi_hal.h>`
* `#include <furi_hal_resources.h>`
* etc.

What am I missing? 🤔 

### Reproduction

Not sure what happened.
I rolled back to `0.64.2`, thinking maybe its the latest `dev` that has issues — nothing.
My `.vscode` folder is setup with the `./fbt vscode_dist` command
I stashed all my changes, navigated to `0.64.2` (`7a672038`) and simply added the [Hello World plugin](https://github.com/mfulz/Flipper-Plugin-Tutorial) and I got the exact same issues.

<img width="1113" alt="Screenshot 2022-08-17 at 23 19 52" src="https://user-images.githubusercontent.com/1323285/185245251-c3f948c8-b5f4-4ef1-bdd9-4b111e4ebd91.png">

### Logs

```Text
[8/17/2022, 11:17:00 PM] "hello_world.c" not found in "${workspaceFolder}/build/latest/compile_commands.json". 'includePath' from c_cpp_properties.json in folder 'flipperzero-firmware' will be used for this file instead.
[8/17/2022, 11:17:50 PM] "hello_world.c" not found in "${workspaceFolder}/build/latest/compile_commands.json". 'includePath' from c_cpp_properties.json in folder 'flipperzero-firmware' will be used for this file instead.
```
```


### Anything else?

_No response_

**Comment by DrZlo13** [comment]
Have you compiled this code at least once?
compile_commands.json is generated on first build, so you need to build the code before processing the file with vscode.

**Comment by skotopes** [comment]
Please reopen issue if problem persist.

**Comment by DrEverr** [comment]
Had the same problem, rebuild whole project with `./fbt` fixed it. Thank you @DrZlo13.
