### ISSUE TITLE
broken archive functionality

### ISSUE THREAD

**Issue by ellegix** [flipperdevices/flipperzero-firmware#1623]
### Describe the bug.

Before commit 2a452063c62e35111073cf68623322d7388dc1e5 when i click the down button i was seeing favorites screen. Now instead appears NFC folder and i have to navigate with left-right arrow to go to favorites.

### Reproduction

1. Switch On
2. Press down button
3. It appears the wrong archive.

**Comment by skotopes** [comment]
Fix merged in dev, please check
