### ISSUE TITLE
Settings to hide doftfiles from macOS in flipperzero browser 

### ISSUE THREAD

**Issue by jonas18z** [flipperdevices/flipperzero-firmware#1653]
### Description of the feature you're suggesting.

I wish there is a settings to hide dotfiles created by Macos  also linux i think has thoose kind of files. 
._xxxxxx.xxx 
.xxxxx.xxxx

should be avable to hidden because they give error. Fro system settings or maybe setting in browser.

**Comment by skotopes** [comment]
Was fixed long time ago )
