### ISSUE TITLE
Stealth capture

### ISSUE THREAD

**Issue by Foul** [flipperdevices/flipperzero-firmware#1663]
### Description of the feature you're suggesting.

No led
No sound
No rumble when capturing..

With of course on/off possibility

Just an idea 💡

**Comment by FalsePhilosopher** [comment]
@Foul  settings>LCD and Notifications>LCD backlight 0% or set backlight time to 1S,LED bightness 0%,Volume 0%,Vibro off

**Comment by Foul** [comment]
that's also an idea :D

**Comment by skotopes** [comment]
Yep, already in notification settings. No other work planned in this direction.
