### ISSUE TITLE
Infrared Crashes - Flipper Crashed and rebooted. Usage Fault

### ISSUE THREAD

**Issue by Mastahh** [flipperdevices/flipperzero-firmware#1664]
### Describe the bug.

Flipper crashes, only [<] and [return] buttons works, to turn it on again

### Reproduction

Go to Infrared, Learn New Remote, wait 2 seconds.
Go to Saved remotes and select any one and just hold button to sent command.
Flipper crashes.

### Target

Infrared

**Comment by alkesander** [comment]
I have the same problem

**Comment by gsurkov** [comment]
Fixed in #1675.
