### ISSUE TITLE
Emergency button

### ISSUE THREAD

**Issue by yeomid** [flipperdevices/flipperzero-firmware#1708]
### Description of the feature you're suggesting.

If a person finds the flipper suspicious, there should be a key combination that puts the flipper into an "innocent" mode. Where you can only play games, for example.

**Comment by jagotu** [comment]
What you're requesting will be implemented by the DUMB mode in the lock menu. It is not yet done, but is planned: https://forum.flipperzero.one/t/when-will-dumb-mode-come-out/4348

**Comment by skotopes** [comment]
Yep, dumb mode coming soon.
