### ISSUE TITLE
Generic Keeloq 64 Bit with 2 buttons pair

### ISSUE THREAD

**Issue by BrunoTCouto** [flipperdevices/flipperzero-firmware#1720]
### Description of the feature you're suggesting.

Hi !  I have a **generic keeloq 64bit remote**, that’s is the most common over here in Brazil. 

I tried paring my flipper with the receiver using the DoorHan_433 but the receiver asks for pressing two buttons at the same time, so I was unable to pair.

Speaking with @skotopes on discord he asked me to open an issue here in github for implementation.

### Sub-GHz Captures by Flipper
<details>

![leitura_1](https://user-images.githubusercontent.com/23619646/189001544-7854b2c3-7216-4a58-aa2f-830c44c939ba.jpeg)
![leitura_2](https://user-images.githubusercontent.com/23619646/189001546-85d456ed-69a9-40c0-9ce4-705ce9db3c1f.jpeg)
![leitura_3](https://user-images.githubusercontent.com/23619646/189001541-27fa06fc-f782-4ec4-b07c-25ebc437c4a6.jpeg)

</details>

### Remote
<details>

![controle_1](https://user-images.githubusercontent.com/23619646/189000135-81525730-f2e7-4e6b-9cf9-0c7f35630f68.jpeg)
![controle_2](https://user-images.githubusercontent.com/23619646/189000132-0e55b3c8-b953-43db-b37a-b33928560f42.jpeg)
![controle_3](https://user-images.githubusercontent.com/23619646/189000126-95b7788b-f564-4ebc-97e6-4838aa171433.jpeg)
![controle_4](https://user-images.githubusercontent.com/23619646/189000136-c293b4c8-2bd2-4d2c-b2f5-afb366898666.jpeg)

</details>

### Receiver
<details>

>   ![guarita_1](https://user-images.githubusercontent.com/23619646/188996999-a5dcb380-729e-4122-8377-6bf79e3556c4.jpeg)
>   **🇧🇷 Pressione duas vezes B1+B2 de um TX**
>   **🇺🇸 Press two times B1+B2 of one TX**

  

>   ![guarita_2](https://user-images.githubusercontent.com/23619646/188997001-934d213d-a24f-476f-99b7-7a71c06c934d.jpeg)
>   **🇧🇷 Pressione duas vezes B1+B2 de um TX**
>   **🇺🇸 Press two times B1+B2 of one TX**

</details>

**Comment by Skorpionm** [comment]
your system is not Dorhan, but something like BFT. Flipper does not save or transmit dynamic protocols, Dorhan exception

**Comment by BrunoTCouto** [comment]
So flipper will never be able to pair with gates that are dynamic protocols?

I wasn't thinking of cloning my controller, but using the flipper instead of my current controller

Should I close this issue ?

**Comment by skotopes** [comment]
Yep. I think we can close it. We don't know MF key for this system.
