### ISSUE TITLE
FAP : Unsatisfied imports

### ISSUE THREAD

**Issue by csBlueChip** [flipperdevices/flipperzero-firmware#1747]
### Describe the bug.

When I run my (previously working plugin) as a FAP, I get :
```
[W][elf_hashtable] Cant find symbol 'LL_TIM_DeInit' (hash d462ee02)!
[W][elf_hashtable] Cant find symbol 'calloc' (hash f5e616f3)!
[E][fap_loader_app] FAP Loader failed to map to memory /ext/apps/Cyborg Systems/bc_pwm_demo.fap: Found unsatisfied imports
```
The `calloc()` is easy to workaround: {`malloc`, `memset`}

...But the lack of an export for `LL_TIM_DeInit()` is not so obvious:
https://github.com/csBlueChip/FlipperZero_plugin_PWM/blob/main/bc_pwm.c#L40

This GPIO Pin configuration-strategy was lifted directly from `targets/f7/furi_hal/furi_hal_speaker.c`

### Reproduction

```
cd /path/to/flipper/
mkdir applications_user/bc_pwm_demo
git clone https://github.com/csBlueChip/FlipperZero_plugin_PWM.git
./fbt launch_app APPSRC=applications/bc_pwm_demo
```
* FZ: Exit the fap
* FZ: settings->system->log level = Warning
* PC: start putty/minicom/whatever
* PC: log
* FZ: Restart the fap
* PC: watch the error log

### Target

https://github.com/flipperdevices/flipperzero-firmware/tree/60bce7b8d8f2712d985352d1e38795dd8f18f3a3

### Logs

```Text
[W][elf_hashtable] Cant find symbol 'LL_TIM_DeInit' (hash d462ee02)!
[W][elf_hashtable] Cant find symbol 'calloc' (hash f5e616f3)!
[E][fapp-i] Error relocating section '.text'
[E][fap_loader_app] FAP Loader failed to map to memory /ext/apps/Cyborg Systems/bc_pwm_demo.fap: Found unsatisfied imports
```
```

### Anything else?

Please provide exports for `calloc()` and the "LowLevel" interface.

**Comment by skotopes** [comment]
Do you experience this issue in latest RC?

**Comment by hedger** [comment]
calloc() is redundant, since our malloc() implementation goes beyond specs and fills allocated block with zeroes.
As for LL_* APIs, we'll expose them in the upcoming RC.

**Comment by hedger** [comment]
Please check out 0.67-RC1, we've added more LL APIs to symbol table.

**Comment by csBlueChip** [comment]
> ... our malloc() implementation goes beyond specs and fills allocated block with zeroes ...

https://linux.die.net/man/3/malloc
"The memory is not initialized" [in italics]

It's very unlikely to become relevant for Flipper code, but do be aware that changing the way memory is initialised (or not) can have critical [security] ramifications, doing in "standard" libraries [ie. stdlib] might make arising issues very hard to spot.
https://www.schneier.com/blog/archives/2008/05/random_number_b.html

**Comment by csBlueChip** [comment]
> Please check out 0.67-RC1, we've added more LL APIs to symbol table.

I found the csv, and added in the exports that I needed.  I will revert the file before I do my next pull.

Thanks.
