### ISSUE TITLE
Applications Menu Back Key function

### ISSUE THREAD

**Issue by csBlueChip** [flipperdevices/flipperzero-firmware#1754]
### Description of the feature you're suggesting.

When browsing sub-folders within the Applications Menu...

Current action:
* Any press of the [back] key exits to the Main Menu

Proposed action:
* A short press of the [back] key performs `cd ..`
* A long press of the [back] key exits to the Main Menu

**Comment by djsime1** [comment]
Pressing LEFT goes up a level, while back exits the scene. It took me a while to understand it as well. However, this could be an easy change if the Flipper team agrees.

**Comment by skotopes** [comment]
Was fixed some time ago.
