### ISSUE TITLE
FAP: Example for FAP applications

### ISSUE THREAD

**Issue by michelinok** [flipperdevices/flipperzero-firmware#1756]
### Description of the feature you're suggesting.

It would be great if we could have a complete example of a FAP **external** application.

**Comment by vmeurisse** [comment]
@michelinok 
Here are some:  https://github.com/vmeurisse/flipperzero-plugins ;)

**Comment by michelinok** [comment]
> 

WOW! Many thanks! I hope to find something very easy to use the gpio pins....let's see!

**Comment by skotopes** [comment]
Some examples already shipped with firmware. We'll add more in future.
