### ISSUE TITLE
UI LED flashes should match with IR LED flashes during Universal Remote emulation

### ISSUE THREAD

**Issue by qubist** [flipperdevices/flipperzero-firmware#1758]
### Describe the enhancement you're suggesting.

Firmware: `0.66.1`

Just tried Universal Remote mode. Awesome. Made one as a kid with Arduino, excited to have the buff superhero older brother version of that in my pocket now.

I used my phone camera to see the infrared LEDs flashing. Noticed the UI LED next to the keypad flashes rapidly while the codes are being tried.

Thought it would be a better experience if the UI LED flashed the same as the IR LEDs so the user has a better sense of what's being broadcast to any listening TV. Without having to use a camera w/o IR filter to see the IR LEDs.

Just got my Flipper so not sure this fits with the UI design language of the rest of the device but I think it'd be nice.

### Anything else?

Willing to try working on this if anyone can point me in the right direction to start!

**Comment by skotopes** [comment]
It is impossible. Infrared TX path directly wired specialized MCU block.
