### ISSUE TITLE
Faster scrolling in NFC info view

### ISSUE THREAD

**Issue by qubist** [flipperdevices/flipperzero-firmware#1759]
### Describe the enhancement you're suggesting.

Firmware: `0.66.1`

I've scanned and saved an NFC card. I select it from the list of saved cards, select `Info` and then press `>` to see more. I'm presented with the raw bytes which is great. But it has hundreds of pages. I have to click `v` each time to progress through the pages.

I'd like to be able to hold `v` to flip faster through the pages. This is already implemented in the Flipper Firmware in the keyboard UI when naming a scanned card: You can hold down a directional key to move through the letters faster.

### Anything else?

Willing to try working on this if anyone can point me in the right direction to start!

**Comment by djsime1** [comment]
I considered opening a PR to address this awhile ago, but never got around to it then. How does this sound: Holding up/down scrolls single lines repeatedly, while left/right scroll a full screen. It's not that hard to implement either.

**Comment by qubist** [comment]
@djsime1 Sounds great! Where should I look to start implementing this?

**Comment by djsime1** [comment]
Text box GUI module.

**Comment by skotopes** [comment]
was implemented some time ago
