### ISSUE TITLE
Channel Island Regions should be UK frequencies for Sub-GHz

### ISSUE THREAD

**Issue by Ads-Decadence** [flipperdevices/flipperzero-firmware#1760]
### Describe the bug.

Good day peeps, I have an issue I live in Jersey Channel Islands United Kingdom, flipper hardware provisioned marks me as JE (this is correct) but only gives me radio frequencies available to R03, not the UK.
I believe any users in Gurnsey (or the other Channel Islands) will have the same issue

Yours Ads 

### Reproduction

updating via a Channel island VPN?

### Target

Sub-GHz

**Comment by anna-oake** [comment]
Hi,

Please ignore R01/R02/R03 in the device info. This is legacy and doesn’t mean anything. If it says JE, you have frequencies unlocked that are allowed for JE. 

Or are you saying these actual frequencies don’t match with the local law?

**Comment by anna-oake** [comment]
Oh, I just checked that we don’t have specific config for JE, so it falls back to the default region.

Do you have any legal proof other frequencies should be unlocked too, so we could reconsider the config?

**Comment by skotopes** [comment]
@aprosvetova they are some kind of Europe, I think it will be safe to assume that they got same regulations as EU. Fallback to JP is kinda strange.

**Comment by Ads-Decadence** [comment]
We are in the same jurisdiction as the united kingdom when it comes to radio systems 
i will try to find the relevant regulations but as our legal system is all written in french this may take me some time

**Comment by Ads-Decadence** [comment]
https://www.ofcom.org.uk/ Ofcom is the Regulatory body of the United Kingdom and the Channel Islands 

Jersey Legal Information Board provides copies of local law and cites Ofcom https://www.jerseylaw.je/

**Comment by skotopes** [comment]
I've added JE region data same as EU/GB. Please update your flipper.

**Comment by Ads-Decadence** [comment]
you star! 
you may want to ad Gurnsey in as well ii think they are GE or GY

**Comment by skotopes** [comment]
We'll revise this table later with certification laboratory and add all existing countries.
