### ISSUE TITLE
Debug option to keep flipper unlocked when connected to USB

### ISSUE THREAD

**Issue by kowalski7cc** [flipperdevices/flipperzero-firmware#1779]
### Description of the feature you're suggesting.

Similar to Android Debug "Keep screen on" when in charge, so it allows for faster sideload, test and debug when the auto-lock feature is on.
Optionally, it can happen when a serial connection is open.

**Comment by skotopes** [comment]
We've been experimenting with debugger detection for some time: there are issues with detecting disconnect. I'll close this issue because there are no reliable way to implement it.
