### ISSUE TITLE
RFID data resets on edit

### ISSUE THREAD

**Issue by UndedInside** [flipperdevices/flipperzero-firmware#1780]
### Describe the bug.

On version 0.67.2, when editing RFID tags they seem to remember what they were created with, and when you edit the tag it resets to what it was created with. I haven't seen anyone else with this issue so feel free to close this off if it's just me. 

### Reproduction

1. Add RFID chip (Either scan or create manually)
2. Give it a value
3. Check info and this will be correct
4. Edit value
5. Check info and it will show what you edited it to
6. Edit value again
7. The value will have changed to what it was created as

**Comment by nminaylov** [comment]
Fixed in #1835
