### ISSUE TITLE
Sane keyboard input not working in GDB when using the fbt tool

### ISSUE THREAD

**Issue by Semptum** [flipperdevices/flipperzero-firmware#1787]
### Describe the bug.

When using `./fbt blackmagic`, a `gdb` interface appears. However, pressing backspace graphically adds a space to the prompt (as long as there is text to erase). Functionnally the text is erased but not graphically. 
Similar behavior arises as soon as the text is changed in any way such as pressing the left arrow and typing something as illustrated below.

![blackmagic_backspace](https://user-images.githubusercontent.com/12534224/192277014-7a5fac76-44ad-49c7-8fd8-fa6cc98fc04d.gif)

### Reproduction

1. `cd` to the directory of the firmware
2. Turn on `gdb`
3. Type _abcd_
4. Press Left
5. Press backspace
6. Hopefully _abd_ will remain
7. Exit gdb
8. Execute `./fbt blackmagic`
9. Type _abcd_
10. Press Left
11. Press backspace
12. The result is _abcdd_ (with a space at the end)

### Anything else?

The system is Arch Linux with KDE. The Terminal emulator is Konsole but the problem persists in the virtual console and in XTerm. The shell is ZSH but the problem persists in SH and BASH.

I was advised to add "TERM" to the environment variables at line 15 of `environ.scons` but this did not help.

EDIT: The problem comes from the binary `arm-none-eabi-gdb` in the `toolchain` folder. The system version works fine. The shipped version has this problem.

**Comment by hedger** [comment]
@drunkbatya we might need your help with that one.

**Comment by Semptum** [comment]
OK, in case it helps, it appears to be basically an issue with ncurses. If I remove the ncurses library from the path that the scripts append, it works fine with the system ncurses.

**Comment by skotopes** [comment]
@Semptum we've pushed couple updates, is your issue still there?

**Comment by Semptum** [comment]
> @Semptum we've pushed couple updates, is your issue still there?

Yup, just checked, the problem persists on the latest dev even though it pulled in newer versions of the tools

**Comment by Semptum** [comment]
> @Semptum we've pushed couple updates, is your issue still there?

Yup, just checked, the problem persists on the latest dev even though it pulled in newer versions of the tools.
If I remember correctly, the problem is with ncurses, using the system library it works fine

**Comment by skotopes** [comment]
@hedger @drunkbatya your turn ;)

**Comment by skotopes** [comment]
@Semptum we've pushed couple toolchain updates, do you still have this issue?

**Comment by Semptum** [comment]
> @Semptum we've pushed couple toolchain updates, do you still have this issue?

Yup, still there...

**Comment by drunkbatya** [comment]
> > @Semptum we've pushed couple toolchain updates, do you still have this issue?
> 
> Yup, still there...

 Ok, I'll look at this soon

**Comment by skotopes** [comment]
@drunkbatya any updates?

**Comment by drunkbatya** [comment]
> @drunkbatya any updates?

Not yet, I'll look at this today.

**Comment by drunkbatya** [comment]
@Semptum 
Hey! I found a core of the problem, it was a missing libtinfo ncurses compiling dependency. I'm released the new toolchain with this fix. Can you test it?
```
git pull
git checkout drunkbatya/23-toolchain
./fbt blackmagic
```
