### ISSUE TITLE
Incorrect regional restrictions for Singapore

### ISSUE THREAD

**Issue by ehn** [flipperdevices/flipperzero-firmware#1791]
### Describe the enhancement you're suggesting.

The current regional restrictions prohibit transmitting on the widely used 433 MHz band in Singapore, despite its being allowed according to IMDA's [Spectrum Management Handbook](https://www.imda.gov.sg/~/media/imda/files/regulation%20licensing%20and%20consultations/frameworks%20and%20policies/spectrum%20management%20and%20coordination/spectrummgmthb.pdf).

**Comment by skotopes** [comment]
Sorry for delay. I've updated region database. Please update your flipper to provision new data.
