### ISSUE TITLE
Need help with FBT error.

### ISSUE THREAD

**Issue by dtuando** [flipperdevices/flipperzero-firmware#1798]
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
scons: *** [build/f7-firmware-D/toolbox/version.inc.h] Error 1
********** ERRORS **********
Failed building build/f7-firmware-D/toolbox/version.inc.h: Error 1

using the ./fbt command this error gets thrown. 
anyone know what this could possibly be?

**Comment by hedger** [comment]
How did you get the source code? Did you download .zip archive or ran `git clone --recursive ...`?

**Comment by skotopes** [comment]
Feel free to reopen issue if you still have this problem.

**Comment by jayashree505** [comment]
Hi I get the same error, May I know how to overcome this?

**Comment by JustDr00py** [comment]
It happened to be an issue with one of the folders. I removed it and fixed the issue

**Comment by jayashree505** [comment]
Could you please tell me which folder it was?
