### ISSUE TITLE
Integration with IDE

### ISSUE THREAD

**Issue by glitchcore** [flipperdevices/flipperzero-firmware#18]
Now we're using docker for build. It have some pros:

* user doesn't need to setup environment: install compilers, libraries, etc.
* container can be used for CI

I use sublime editor for programming, but I understand that many people used to use IDE like CLion/Eclipse/etc. How do we make integration?

**Comment by gelin** [comment]
```
+-------------------------------------------------+
|                                                 |
|      Hello, this is Flipper team speaking!      |
|                                                 |
|       We've migrated to new build system        |
|          It's nice and based on scons           |
...
```
:cry:
