### ISSUE TITLE
Compact menu, that can be switch on/off in the settings.

### ISSUE THREAD

**Issue by I3elphegor** [flipperdevices/flipperzero-firmware#1804]
### Description of the feature you're suggesting.

It would be great to have a compact main menu, because all icons are easy to remember and in a compact menu, you wouldn't just use the up and down buttons (much less stress on those two), but all 4 of them. Being able to turn this on and off in the settings would also be great.
<img width="265" alt="flipper-zero-file-manager v2" src="https://user-images.githubusercontent.com/56094270/193086487-49764966-915a-4c29-96ee-e4a056f11fbf.png">

**Comment by skotopes** [comment]
That will require another set of icons, clearly something that we'd like to avoid. We may return to this topic in future, but clearly not till version 1.0.

**Comment by skotopes** [comment]
Not going to implement: too difficult to maintain
