### ISSUE TITLE
fbt/fap: C++ entry point name mangling documentation/handling

### ISSUE THREAD

**Issue by GMMan** [flipperdevices/flipperzero-firmware#1869]
### Describe the enhancement you're suggesting.

Currently if you try to build a C++ app and use a C++ entry point function's name directly in `application.fam`, you may receive the following cryptic linker error:

```
.../flipperzero-firmware/toolchain/i686-windows/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: --gc-sections requires a defined symbol root specified by -e or -u
collect2.exe: error: ld returned 1 exit status
```

This is the result of the compiler mangling the name. To resolve this, either change the `entry_point` within `application.fam` to the mangled name, or apply `extern "C"` to the function. Name mangling should be handled by fbt when passing to g++, or the `extern "C"` should be documented somewhere.

**Comment by hedger** [comment]
Good point, we'll add that to documentation.
