### ISSUE TITLE
Cannot exit picopass reader

### ISSUE THREAD

**Issue by azlekov** [flipperdevices/flipperzero-firmware#1870]
### Describe the bug.

I installed the latest one firmware and play around with the new stuff. I found in apps a picopass reader which I open. Unfortunately I do not have a picopass near me and cannot exit the app. It says "Detecting picopass card" and that's it. For 3 days I'm waiting the battery to drain. :sad

The device is not responding cannot connect to it via Bluetooth, etc.

Help!

### Reproduction

1. Go to menu
2. Navigate to `Applications`
3. Find `PicoPass Reader` under `Tools` folder
4. Open it and click `Read Card`
6. Device became non responding, trying to click all buttons hold them, no success

### Target

0.68.1

**Comment by GMMan** [comment]
Seems to be working here. If you're seeing the hourglass animation, there might be an issue loading the app. Otherwise, if the back button doesn't work, perhaps there was some other issue causing a crash. You can reboot your Flipper by pressing Left + Back.

**Comment by azlekov** [comment]
Thanks @GMMan after restart the `PicoPass Reader` is responsive and can cancel reading the card. Maybe is something related with the firmware update and the first open of `PicoPass Reader`

**Comment by LowSkillDeveloper** [comment]
I confirm. After a clean installation of the firmware, when you first open "PicoPass Reader" and click "Read Card", there is nothing else you can do. Back action doesn't work. Forced reboot only. And after the reboot, when you go in the second time everything works fine, you can go back.
