### ISSUE TITLE
Resources wont get updated if older update folder exists

### ISSUE THREAD

**Issue by ankris812** [flipperdevices/flipperzero-firmware#1881]
### Describe the bug.

If i upload an update, and there is already a folder on ext/update with that name,no files will be updated, it will skip them
it happened when trying to update a local build of the firm, i was trying to change the flipper dict, deleted previous one, copied the new, without seeing that it had a typo on name, i fixed the typo, but when updating again error was still there.

### Reproduction

Reproduction for my case:

 delete mf_classic_dict.nfc ( i was setting my sd from zero, so this file didnt exist), 
rename on assets/resources/nfc/assets mf_classic_dict.nfc  to mfc_classic_dict.nfc (i copied it without noticing the typo)
compile, and update.
fix the typo. compile again.
load tgz with qflipper
it will skip uploading and update again with old update
error will still be there

### Target

qflipper

### Logs

```Text
37936 [UTL] Prepare Update @Korai SUCCESS
37936 [DBG] Update package has been already uploaded, skipping to update...
37937 [UTL] Start Update @Korai START
```

### Anything else?

my build always take the name local, so folder inside update is always f7-update-local,  so i dont know if this will happen on offical releases.

**Comment by DrZlo13** [comment]
I do not think that this problem relates to the firmware, rather to the qFlipper.

**Comment by ankris812** [comment]
> I do not think that this problem relates to the firmware, rather to the qFlipper.

the firmware? is the firmware who uploads the updates files?

**Comment by emory** [comment]
i don't do updates with qflipper, i do them on-device. i keep a directory of my SD card layout as a repo and use rsync (`rsync -azvP --delete local-copy/ /Volumes/SDCARD/`) to refresh and i don't think i see the same behavior you're reporting. i haven't deleted an entire folder from my SDCARD yet if that's the test you're hoping to get confirmation on @ankris812 but i don't think i will ever use qflipper to do firmware installation personaly.

**Comment by ankris812** [comment]
@emory the problem only happens when updating with qflipper. And i'll check what You do to update

**Comment by skotopes** [comment]
Upload script actually verifies checksums and skips upload if file was not changed. Are you sure that you have something to upload?

**Comment by ankris812** [comment]
Yes. But i'll check It again anyways

**Comment by hedger** [comment]
This is qFlipper's issue, not the firmware's.

**Comment by hedger** [comment]
Also please use `fbt flash_usb_full`.
