### ISSUE TITLE
Rename unknown files and folders from file browser

### ISSUE THREAD

**Issue by kowalski7cc** [flipperdevices/flipperzero-firmware#1883]
### Describe the bug.

Currently file browser doesn't allow to rename unknown files and folders.

### Reproduction

1. Open file browser
2. Find a file (like a .txt) or a folder
3. Open contextual menu
4. Rename option is unavailable

**Comment by skotopes** [comment]
Sounds reasonable. We'll fix it in future releases.

**Comment by skotopes** [comment]
fixed in dev, will be included in 0.71 release
