### ISSUE TITLE
Scrolling text when longer than screen

### ISSUE THREAD

**Issue by krisss117** [flipperdevices/flipperzero-firmware#1901]
### Description of the feature you're suggesting.

Please add text scrolling when text is longer than screen. I think only selected position will scroll text. Then it allow to read longer text for example NFC, SUBGHZ.

It will be very usefull.

**Comment by skotopes** [comment]
We'll come back to this task after v1.0

**Comment by ahumeniy** [comment]
Something like this? 
https://drive.google.com/file/d/12yFBldnQ5us1lq8ejsAJJNFWMUM8a1n0/view?usp=sharing

**Comment by skotopes** [comment]
@ahumeniy yep, looks like you've nailed it.

**Comment by ahumeniy** [comment]
Should I submit a PR?

**Comment by skotopes** [comment]
@ahumeniy feel free to do that ;-)

**Comment by skotopes** [comment]
fixed
