### ISSUE TITLE
Run bad USB script over bluetooth

### ISSUE THREAD

**Issue by krisss117** [flipperdevices/flipperzero-firmware#1902]
### Description of the feature you're suggesting.

Hi, plese add function to send BAD USB script over Bluetooth. 

1. Connect Flipper Keyboard over Bluetooth
2. Allow to select BAD USB script to run

**Comment by skotopes** [comment]
Will require RPC mode implementation in BadUSB application and corresponding part in apps. We'll come back to this task after application catalog.

**Comment by ggaljoen** [comment]
Running scripts will also require to read, and if needed toggle, the keyboard (caps/num) locks status, otherwise you won't get the intended key strokes.

**Comment by UnsavorySpirit** [comment]
> 

if you install the xtreme fw (i use unleashed) you can see te badkb function and now i'm trying to transfer that function to the unleashed fw is there a way you could do thath or at least help me?

**Comment by krisss117** [comment]
Finctionality was add in Xtreme Firmware :)

**Comment by UnsavorySpirit** [comment]
I already know

**Comment by intech** [comment]
@skotopes The application catalog is already running. Can we expect updates on this task shortly?

**Comment by skotopes** [comment]
@intech sorry for delay, we'll try to pack it in 1.0 release

**Comment by pk3zip** [comment]
I would like to see this feature as well but it seems like this has been forgotten

**Comment by skotopes** [comment]
@sk337 more like it's coming as a part of the scripting language

**Comment by skotopes** [comment]
Done
