### ISSUE TITLE
Run BAD USB immediately after connect to device

### ISSUE THREAD

**Issue by krisss117** [flipperdevices/flipperzero-firmware#1903]
### Description of the feature you're suggesting.

Add option to run script immediately after connect to device

1. select BAD USB
2. select script
3. Click RUN
4. Connect to device 
5. Flipper immediately run script after connect (optional vibrate when start running)

I thin option with connect and then trigger script after click run is usefull too - don't remove this option :)

**Comment by skotopes** [comment]
We'll come back to this task after application catalog.

**Comment by head47** [comment]
Probably solved by #1955.

**Comment by head47** [comment]
Probably solved by #1955.
