### ISSUE TITLE
Infrared Macro/Playlist

### ISSUE THREAD

**Issue by johne8** [flipperdevices/flipperzero-firmware#1906]
### Description of the feature you're suggesting.

Is it possible to add macro/playlist support for Infrared signals?

**Comment by skotopes** [comment]
The best option will be to implement it as external application. We don't plan to do that, but someone from community may take the task.

**Comment by gsurkov** [comment]
Looks like a duplicate of #1800. As said above, there are no immediate plans on implementing it, but we will welcome every community effort in that direction.
