### ISSUE TITLE
Opening .sub files in a folder

### ISSUE THREAD

**Issue by Llama-Master** [flipperdevices/flipperzero-firmware#1907]
### Description of the feature you're suggesting.

I know I have posted about this multiple times, but I need a reply.

Here is what I need, and if you could, please help me

I cannot open a .sub file from my android app if the file is inside a folder. I have them inside a folder to organize them to find them easier. The problem is, I cannot open them while they are inside a folder to broadcast to my flipper from my device. What I am trying to say is please make it possible to open them while they are in a folder, it would make things much easier.

Thank you

### Anything else?

[Mario-head.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9843152/Mario-head.txt)

**Comment by skotopes** [comment]
This should be addressed in Mobile apps. Please open issue in https://github.com/flipperdevices/Flipper-Android-App
