### ISSUE TITLE
Flipper repeatedly shows internal storage full when attempting to flash firmware

### ISSUE THREAD

**Issue by d0mnik** [flipperdevices/flipperzero-firmware#1915]
### Describe the bug.

when attempting to flash the firmware updates via `fbt updater_package`, the flipper always show unsuccessful with error message: Internal Storage is full.

### Reproduction

1. Compiler firmware
2. Upload to SD card
3. flash firmware

**Comment by skotopes** [comment]
It says so for a reason. Usually it means that you have only couple pages left.
How big is your firmware, how much space is left on internal storage?

**Comment by d0mnik** [comment]
> It says so for a reason. Usually it means that you have only couple pages left.
> 
> How big is your firmware, how much space is left on internal storage?

My internal storage is totally used. How can i free up internal storage?

**Comment by skotopes** [comment]
You can use qFlipper to manage files.

**Comment by d0mnik** [comment]
qflipper shows several files within internal flash, but no sizes are indicated. May i find out what files are crucial and what can I remove to free up space?
![image](https://user-images.githubusercontent.com/32241418/197402569-6d6d3cfe-678f-4dab-9a4c-460cffcfa90d.png)

**Comment by skotopes** [comment]
critical files are starting with `.`

**Comment by d0mnik** [comment]
kindly refer to my updated comment with screenshot. it seems that there isn't any other files apart from crucial files.

**Comment by skotopes** [comment]
Yep, all of them are critical.
So how much free space do you have. What's in your firmware that occupies so much?

**Comment by d0mnik** [comment]
Currently, i have 0kb free.
I am currently using the firmware in the release branch, with slight modifications to remove region locks, and compiled with the picopass plugin.

**Comment by skotopes** [comment]
Oh, that firmware. Please talk with that firmware maintainer. We only support official firmware here.

**Comment by d0mnik** [comment]
I believe there is a misunderstanding. @skotopes  I am using the firmware here, but just with the region checks removed.

**Comment by skotopes** [comment]
Picopass is included in official firmware as external application and should not be compiled into firmware.
Open "Menu->Setting->Storage->About internal storage": you should see 116kb there.
In case if you see 116k and 0k free most likely lfs is corrupted. Use "Factory Reset" to restore it.

**Comment by d0mnik** [comment]
> Picopass is included in official firmware as external application and should not be compiled into firmware. Open "Menu->Setting->Storage->About internal storage": you should see 116kb there. In case if you see 116k and 0k free most likely lfs is corrupted. Use "Factory Reset" to restore it.

I only see 24KB total, 8KB free on my device. Kindly advice steps going forward

**Comment by skotopes** [comment]
8kb is 2 pages. That is what updater is telling to you.

qFlipper can install dfu files directly, but internal storage in that case may be wiped. Same goes for flashing in recovery mode: it always succeed but internal data will be lost.

Don't compile apps into firmware, compile them as external apps.

**Comment by d0mnik** [comment]
> 8kb is 2 pages. That is what updater is telling to you.
> 
> qFlipper can install dfu files directly, but internal storage in that case may be wiped. Same goes for flashing in recovery mode: it always succeed but internal data will be lost.
> 
> Don't compile apps into firmware, compile them as external apps.

How can I flash new firmware onto the device in the current state? I am unable to flash any firmware due to the space limitation. Even booting into dfu mode and repairing it is not working.

Update:
Attempting to flash the firmware the second time in DFU mode works.

**Comment by skotopes** [comment]
qFlipper is always can do flash from recovery:

- Press left + back 
- Release left - device will go into recovery mode
- open qFlipper and press recover button
