### ISSUE TITLE
Subghz raw sub transmits an unwanted signal at the beginning (OOK 433MHz)

### ISSUE THREAD

**Issue by coded-with-claws** [flipperdevices/flipperzero-firmware#1923]
### Describe the bug.

Hi!

I'm generating a raw sub file and when I play it with my flipper, it starts with some kind of preamble which I didn't write into the raw sub file:
- unwanted preamble
  - sends ON for duration ~3000 (selected in blue on the screenshot)
  - sends OFF for ~1000 (just after the selected blue)
- then applies the content of the raw sub.

I can't see any reason for this behavior, so I'm creating an issue (as I couldn't get info on discord when I asked about that).

Thanks :)

### Reproduction

Download the attached .sub.txt file, rename to remove the ".txt" (which was added because of github supported file types).
Open it in the Subghz application and hit Send, and capture in urh with a RTL SDR dongle.

![pb_rawsub](https://user-images.githubusercontent.com/79459323/197585773-a89fdb97-b646-4b36-bf6c-eaf04e6f4dad.png)
[example.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/9853813/example.sub.txt)

**Comment by skotopes** [comment]
@Skorpionm do you remember why we start transmission before furi_hal_subghz_start_async_tx is actually started?
https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/main/subghz/subghz_i.c#L106

**Comment by Skorpionm** [comment]
check current dev

**Comment by skotopes** [comment]
One more fix and unit tests arrived in latest dev. Please reopen if you still experiencing issue
