### ISSUE TITLE
Acurite-606TX not picking up weather sensor

### ISSUE THREAD

**Issue by Maycuz** [flipperdevices/flipperzero-firmware#1932]
### Describe the bug.

Trying to get the information off a weather sensor using the Acurite-606TX protocol with the weather station app (v0.3). Using an RTL-SDR and rtl_433, the information is correctly read and identified as Acurite-606TX @ 433.92MHz. Flipper is just stuck on "Scanning..." at the same frequency.

rtl_433 output:
![image](https://user-images.githubusercontent.com/6267267/198113531-912af8c4-785d-4f73-9f46-1e9a2cd178b4.png)

### Reproduction

1. Open weather station app
2. Start reading
3. Trigger TX event on weather station
4. Nothing happens

RAW recording:
[acurite_issue.zip](https://github.com/flipperdevices/flipperzero-firmware/files/9873670/acurite_issue.zip)

**Comment by skotopes** [comment]
Please attach RAW recording

**Comment by Maycuz** [comment]
Raw recording can be found here:
[acurite_issue.zip](https://github.com/flipperdevices/flipperzero-firmware/files/9873646/acurite_issue.zip)

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/1938|


check. this sensor has a protocol slightly different from what was originally added

**Comment by Maycuz** [comment]
That works great! Thanks for the quick fix!

**Comment by Skorpionm** [comment]
close the issue if the error is fixed)
