### ISSUE TITLE
Fresh cloned repo with bunch of errors (intellisense)

### ISSUE THREAD

**Issue by ASoldo** [flipperdevices/flipperzero-firmware#1936]
### Describe the bug.

Hi, I'm waiting on my flipper zero and in the mean time I wanted to see how firmware looks like. When I open flipperzero-firmware with nvim on Linux Mint it gives me a lot of warnings but also errors. Did I forget to do some step maybe?  
![image](https://user-images.githubusercontent.com/1175537/198156486-c807cc85-595e-4f6e-92d2-a36fbbf1bb0c.png)
 This is how it looks like. Thank you!

### Reproduction

1. clone repository
2. open repository with nvim code editor

**Comment by DrZlo13** [comment]
As we discussed earlier on Discord, you need to configure your LSP to use compile_commands.json and arm-none-eabi-gcc compiler.
