### ISSUE TITLE
Add time delay for favorite emulation

### ISSUE THREAD

**Issue by ximik666** [flipperdevices/flipperzero-firmware#1943]
### Description of the feature you're suggesting.

Add a time delay to the setting (5,10,15,30 seconds). This delay will disable key emulation from favorites after a specified period of time.
For example, the user has selected 5 seconds. It selects the desired key from the favorites and emulates it. After a specified period of time, the emulation is turned off and there is no need to force it to turn off by pressing the Back button.
Thank you.

**Comment by skotopes** [comment]
Sounds very niche and going to break flow for many things.
That could be potentially implemented in mobile companions, please forward this issue to them.
