### ISSUE TITLE
Self contained FAP's

### ISSUE THREAD

**Issue by FalsePhilosopher** [flipperdevices/flipperzero-firmware#1947]
### Description of the feature you're suggesting.

Make faps self-contained by copying in the libraries and plugins that the application uses into the fap in the build process. Here is one FOSS project for creating appimages for an idea of building self contained executables.
https://github.com/probonopd/linuxdeployqt

### Anything else?

./fbt fap_{APPID} -e or --ext to build all the required libraries and modules the fap needs to be self contained into the fap.

**Comment by skotopes** [comment]
Faps are already self contained: external libraries are linked into fap itself and API throw relocatable symbols.
