### ISSUE TITLE
settings_user | ignore flag for firmware updates

### ISSUE THREAD

**Issue by RocketGod-git** [flipperdevices/flipperzero-firmware#1953]
### Description of the feature you're suggesting.

Can we please add an ignore flag to the settings_user file in subghz/assets?

allow_firmware_update_replace=true
(Default)

but when set to false this file will be skipped. 

### Anything else?

The reason for this is because I have custom frequencies and modulations which get replaced every time I update the firmware. It’s a hassle to have to make a backup on every edit and swap the files on firmware updates.

**Comment by skotopes** [comment]
This issue is already fixed and will be available in 0.70 release. settings_user now excluded from updated files.
