### ISSUE TITLE
Add ESL IR protocol

### ISSUE THREAD

**Issue by FalsePhilosopher** [flipperdevices/flipperzero-firmware#1959]
### Description of the feature you're suggesting.

Here is a bunch of captures for the electronic shelf labels so as to make a protocol for them.
https://github.com/dandri/ESL
This also might be useful
https://github.com/furrtek/PrecIR

**Comment by gsurkov** [comment]
Thanks for the idea, this whole class of devices looks promising.
Will look into it, but on low priority.

**Comment by skotopes** [comment]
That's a good idea for application.
