### ISSUE TITLE
DAP Link app in infinite loading screen when closing

### ISSUE THREAD

**Issue by SgtHotshot** [flipperdevices/flipperzero-firmware#1969]
### Describe the bug.

Open the DAP link app while connected to qflipper on windows.  Then click the back button.  It goes to an infinite loading screen and doesn't go out of it.  Have to hard power of the device and restart it. I'm on version 0.70.1

### Reproduction

1. Connect flipper to Qflipper.  (I'm on windows 10)
2. Open up the DAP link app under applications/tools
3. Click the back button.

https://user-images.githubusercontent.com/3375243/199612131-7732bb61-02e5-484f-a4d1-cdd58c129a2b.mp4

### Target

0.70.1

**Comment by DrZlo13** [comment]
Fixed in #1982
