### ISSUE TITLE
Missing wheel in scripts/requirements.txt

### ISSUE THREAD

**Issue by lslrt** [flipperdevices/flipperzero-firmware#1976]
### Describe the bug.

Running `pip3 install -r scripts/requirements.txt` in a fresh python3 virtual env fails with the following error:
```
Building wheels for collected packages: heatshrink2
  Building wheel for heatshrink2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lsa/Projects/flipperzero-firmware/scons-venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5de3j9t1/heatshrink2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5de3j9t1/heatshrink2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_u9leoqe
       cwd: /tmp/pip-install-5de3j9t1/heatshrink2/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for heatshrink2
  Running setup.py clean for heatshrink2
Failed to build heatshrink2
```
To fix the build issue, a solution is to pip install wheel.
`pip3 install wheel`
Then run again
`pip3 install -r scripts/requirements.txt`

### Reproduction

`python3 -m venv scons-venv`
`source scons-venv/bin/activate`
`pip3 install -r scripts/requirements.txt`

### Target

Build system

### Anything else?
pip 20.0.2
Python 3.8.10

After installing wheel, here is the installed packages in the virtual env:
```
Package           Version
----------------- -------
ansi              0.3.6  
black             22.6.0 
click             8.1.3  
colorlog          6.7.0  
heatshrink2       0.11.0 
mypy-extensions   0.4.3  
pathspec          0.10.1 
Pillow            9.1.1  
pip               20.0.2 
pkg-resources     0.0.0  
platformdirs      2.5.2  
protobuf          3.20.1 
pyserial          3.5    
python3-protobuf  2.5.0  
SCons             4.4.0  
setuptools        44.0.0 
tomli             2.0.1  
typing-extensions 4.4.0  
wheel             0.38.2 
```

_No response_

**Comment by skotopes** [comment]
Normally those requirements are included in toolchain.

**Comment by skotopes** [comment]
Any reason why you want to use python other than included in toolchain?

**Comment by lslrt** [comment]
@skotopes I'm just following https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/fbt.md, there is no mention of toolchain anywhere.
Is there is some other instructions that I've missed?

**Comment by skotopes** [comment]
Yep, ignore this part. The only requirement is git and wget/curl to download toolchain. Everything else will be automatically pulled by fbt.

@hedger it make sense to clarify it in documentation.

**Comment by lslrt** [comment]
@skotopes ok, thank!
