### ISSUE TITLE
BadUSB hold/release

### ISSUE THREAD

**Issue by stashymane** [flipperdevices/flipperzero-firmware#1989]
### Description of the feature you're suggesting.

Currently, doing more advanced keychords is not possible, at least from my limited testing. For example, `ALT TAB` can only switch to the last opened app, since `ALT-TAB TAB` does not function as expected. Having a HOLD/RELEASE keyword [as described here](https://docs.hak5.org/hak5-usb-rubber-ducky/advanced-features/holding-keys#hold-and-release) would be very useful.

**Comment by skotopes** [comment]
implemented in #2448
