### ISSUE TITLE
Universal Remote not working on new Sony TV’s

### ISSUE THREAD

**Issue by ALD53105** [flipperdevices/flipperzero-firmware#2013]
### Describe the enhancement you're suggesting.

Universal Remote does not change volume or channels on newer Sony TV’s. Only the power can be cycled.

**Comment by Crsarmv7l** [comment]
Many of the newer tv's use ir for the power button and bluetooth for the other buttons.

**Comment by ALD53105** [comment]
> Many of the newer tv's use ir for the power button and bluetooth for the other buttons.

I can read and duplicate the IR signals from the remote with flipper and control both volume and channel on the TV.

**Comment by Crsarmv7l** [comment]
> > Many of the newer tv's use ir for the power button and bluetooth for the other buttons.
> 
> I can read and duplicate the IR signals from the remote with flipper and control both volume and channel on the TV.

Ok so maybe submit those files for inclusion instead of making people guess what model.

**Comment by ALD53105** [comment]
> Ok so maybe submit those files for inclusion instead of making people guess what model.

Maybe if I knew to do that or how to do that, I would. I was just making a simple suggestion saying it didn't work. If there is a way of uploading, I would do so, but I am completely unfamiliar with GitHub as a whole.

**Comment by Crsarmv7l** [comment]
> > Ok so maybe submit those files for inclusion instead of making people guess what model.
> 
> Maybe if I knew to do that or how to do that, I would. I was just making a simple suggestion saying it didn't work. If there is a way of uploading, I would do so, but I am completely unfamiliar with GitHub as a whole.

![Screenshot 2022-11-18 10 27 01 PM](https://user-images.githubusercontent.com/85343771/202832253-346d229f-8958-40bf-ad9b-281b3f4c09ec.png)

**Comment by gsurkov** [comment]
@ALD53105 There already are instructions on adding other types of universal remotes [here](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/UniversalRemotes.md). It doesn't cover the TV part yet, as it requires a bit of refactoring, but it's pretty similar to audio players, so you might try to figure that out yourself (or wait until the proper instruction will be available, which is soon).

It won't cover making pull requests, however, but there is lots of info on that on the Internet.
