### ISSUE TITLE
Bluetooth remote for camera

### ISSUE THREAD

**Issue by ivanbarsukov** [flipperdevices/flipperzero-firmware#2015]
### Description of the feature you're suggesting.

I think it would be convenient to be able to manage camera captures from the Flipper in the corresponding app menu item. While searching, I found  that you can open the "media" and press the volume buttons, but it seems to me that I'm not the only one for whom this was not obvious without researching the changes in the PRs. Also I think it's more convenient to click on ok to do this

**Comment by skotopes** [comment]
I think this request is too broad. Which specific camera, which bluetooth type and mode, which specific buttons it uses?

**Comment by ivanbarsukov** [comment]
As I know, most devices just use the volume buttons for taking photos. This also confirms the simple bluetooth remote I have

**Comment by skotopes** [comment]
We already have Bluetooth Remote application that got this feature. Also keep in mind that Flipper MCU only support BLE. No Bluetooth classic.

I think it's safe to close this issue. It's either already implemented and working or impossible to implement.

**Comment by ivanbarsukov** [comment]
Yes, I am talking about this Bluetooth Remote application and also wrote in the issue that it already works fine with camera when I click on the volume buttons. But it is absolutely not obvious for most people and I propose just page in this app with camera control. I think it would be easier to find option for new users and just convenient to take a photo on ok button

**Comment by skotopes** [comment]
I'll ask our technical writer to take a look on this thread
