### ISSUE TITLE
AZERTY is not working as expected on badusb

### ISSUE THREAD

**Issue by babou63** [flipperdevices/flipperzero-firmware#2018]
### Describe the bug.

When i use bad usb on a computer working with AZERTY keyboard it's not working, the flipper write like if it was in azerty, so would it be possible to check the keyboard language before writing something ? 

### Reproduction

change your language keyboard from QWERTY to AZERTY and launch a badusb program ( for me it's the demo for windows ),
it shouldn't work

### Target

badusb

**Comment by skotopes** [comment]
This is known issue. Currently we don't support azerty and other keyboard layouts.

**Comment by babou63** [comment]
okay, do you know if it's planned to add this support soon or not  ?

**Comment by skotopes** [comment]
No plans on our side. There were some PRs but abandoned before I were able to merge them.

**Comment by FelixLgr** [comment]
Someone told me to use `ALTSTRING` to solve this problem but he writes numbers instead.

**Comment by skotopes** [comment]
Keyboard layout are now selectable in BadUSB config menu.
