### ISSUE TITLE
U2F on Android not working

### ISSUE THREAD

**Issue by LowSkillDeveloper** [flipperdevices/flipperzero-firmware#2022]
### Describe the bug.

I can't use U2F on my android smartphone. But everything works on the computer. 
Doesn't work for everyone or just me?

![fb335c31-22f5-4737-b37b-6bc9008c1b2e](https://user-images.githubusercontent.com/25121341/202025849-0ee385f2-ab11-4cf0-a2ff-e198808e762a.jpg)
![4f9215ec-226c-428d-a01c-a852ebe22b98](https://user-images.githubusercontent.com/25121341/202025906-318eaf9b-4d24-44c0-bc09-ce2b83ad3a27.jpg)
![728a505e-66c3-4c04-83d3-e03ac0ebc8a3](https://user-images.githubusercontent.com/25121341/202025955-76c567b8-5a4a-4960-93ef-90b3d8dc683c.jpg)

### Reproduction

1. Go to google accaunt settings
2. Security settings - two-factor verification - security key
3. Launching authorization through the key.
4. Сhoose USB
5. Insert the key. 
6. Flipper shows connected.
7. A confirmation message pops up, click ok on phone.

And that's it, nothing happens. Nothing has changed on the flipper and did not offer to press a button on it.

### Test on
Samsung Galaxy S20 (Android 13)
Samsung Galaxy S20 FE (Android 12)

**Comment by LowSkillDeveloper** [comment]
Now it works. Looks like the problem is solved in https://github.com/flipperdevices/flipperzero-firmware/pull/2073.

**Comment by cristian3602** [comment]
Hello Everyone, I'm just having the same behavior described on the original comment. I'm trying  to use the U2F with a Samsung S23.  The flipper firmware version is 0.105.0
