### ISSUE TITLE
Cannot connect to qFlipper on any machine I tried so far

### ISSUE THREAD

**Issue by dnns92** [flipperdevices/flipperzero-firmware#2028]
### Describe the bug.

Further to the described bug in #2027, I can also not connect my flipper to any machine I tried so far using

21H2 Build 2200.1219
21H2 Build 2200.1098
Ubuntu 22.04 with Kernel 5.15.0-50-generic

Windows logs (I tried plugging and replugging it in several times)
628 [APP] qFlipper version 1.2.1 commit 3ec0fd9d 2022-10-03T17:15:41
629 [APP] OS info: Windows 10 Version 2009 10 10.0.22000 Qt 5.15.2
894 [UPD] Fetched update information from https://update.flipperzero.one/firmware/directory.json
895 [UPD] Fetched update information from https://update.flipperzero.one/qFlipper/directory.json

Ubuntu logs look similar.

The flipper light is green, so apparently it's loading. Nevertheless I cannot get any connection from the pc to it, to e.g. flash the firmware on it.

### Reproduction

1. Connect to USB
2. See that it's not working.

**Comment by driquelme** [comment]
Hello @dnns92 I'm having the same issue, how did you solve it?

**Comment by driquelme** [comment]
NVM it was a cable issue.
