### ISSUE TITLE
IR signals from Haier TV for universal remote control in flipper

### ISSUE THREAD

**Issue by ghost** [flipperdevices/flipperzero-firmware#2029]
Hi! Here are some files from Haier TV for the universal remote control in Flipper

name: Mute
type: parsed
protocol: NEC
address: 04 00 00 00
command: 09 00 00 00
# 
name: VOL+
type: parsed
protocol: NEC
address: 04 00 00 00
command: 02 00 00 00
# 
name: VOL-
type: parsed
protocol: NEC
address: 04 00 00 00
command: 03 00 00 00
# 
name: CH+
type: parsed
protocol: NEC
address: 04 00 00 00
command: 00 00 00 00
# 
name: CH-
type: parsed
protocol: NEC
address: 04 00 00 00
command: 01 00 00 00

**Comment by ENIXBLAHAJ** [comment]
this is my old account, I deleted it, but I'm still here

**Comment by gsurkov** [comment]
Could you please open a pull request instead? It is the preferred way of proposing new features. 
Just add these signals to the end of [this file](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/assets/resources/infrared/assets/tv.ir).
