### ISSUE TITLE
BT remote Keynote vertical layout

### ISSUE THREAD

**Issue by Kami-no** [flipperdevices/flipperzero-firmware#2034]
### Description of the feature you're suggesting.

It would be great to have at least an option to switch Keynote button layout to vertical with buttons at the top. Horizontal button layout is not convenient if you're the speaker.

**Comment by gncnpk** [comment]
Hmm, would it make sense to have it be switchable or just have it always be a vertical layout?

**Comment by gncnpk** [comment]
If it's always gonna be vertical, I should be able to easily rewrite it.

**Comment by Kami-no** [comment]
For me the horizontal layout is useless.

**Comment by Kami-no** [comment]
I've checked all other BT remotes and it looks like only keyboard needs horizontal layout as it shows useful information on screen. Others would be more useful if buttons would be at the top and vertical layout as they don't have complex control.

**Comment by skotopes** [comment]
Make sense, but it's going to be difficult to make nice UI/UX for application in general

**Comment by Kami-no** [comment]
May be another copy of app with vertical layout?

**Comment by skotopes** [comment]
possibly

**Comment by Kami-no** [comment]
PR #2794

**Comment by skotopes** [comment]
Fixed in https://github.com/flipperdevices/flipperzero-firmware/pull/2794
