### ISSUE TITLE
Universal IR remote control for Toshiba TV

### ISSUE THREAD

**Issue by Kami-no** [flipperdevices/flipperzero-firmware#2035]
### Description of the feature you're suggesting.

Please add support for Toshiba TV or add an option to create custom layouts like Universal TV control has.

### Anything else?

Toshiba TV 32W1534DG (C)

```
Filetype: IR signals file
Version: 1
#
name: Power
type: parsed
protocol: RC5
address: 01 00 00 00
command: 0C 00 00 00
#
name: Mute
type: parsed
protocol: RC5
address: 01 00 00 00
command: 0D 00 00 00
#
name: Vol_up
type: parsed
protocol: RC5
address: 01 00 00 00
command: 10 00 00 00
#
name: Vol_down
type: parsed
protocol: RC5
address: 01 00 00 00
command: 11 00 00 00
#
name: Ch_up
type: parsed
protocol: RC5
address: 01 00 00 00
command: 20 00 00 00
#
name: Ch_down
type: parsed
protocol: RC5
address: 01 00 00 00
command: 21 00 00 00
```

**Comment by gsurkov** [comment]
Could you please open a pull request instead? It is the preferred way of proposing new features. 

Just add these signals to the end of [this file](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/assets/resources/infrared/assets/tv.ir). 
Don't forget to change the signal names using those already in the file as an example.
