### ISSUE TITLE
Sub-ghz protocol for electric shutters not recognised

### ISSUE THREAD

**Issue by Z4urce** [flipperdevices/flipperzero-firmware#2048]
### Describe the enhancement you're suggesting.

Hello there! I noticed that the firmware couldn't recognise my electric shutters (Dooya). They can be perfectly controlled when replaying the raw recording, however that would be even better if the firmware could recognise its type as well. These electric shutters are quite common, so that would be a welcome feature. I'll attach the raw recording of the Up button for sample.

[ElectricShutterUp.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10087166/ElectricShutterUp.zip)

Thank you and have a nice day!

**Comment by Skorpionm** [comment]
https://forum.flipperzero.one/t/my-remote-isnt-supported-how-to-add-new-sub-ghz-protocol-in-flipper-zero/2033/16

please do as described here. And recording one button is not enough.

**Comment by Z4urce** [comment]
@Skorpionm thank you for the guide. I've tried my best:
https://forum.flipperzero.one/t/dooya-and-clones-electric-roller-shutters-blinds/9369

**Comment by Skorpionm** [comment]
Done
