### ISSUE TITLE
Weather App Temp in Fahrenheit

### ISSUE THREAD

**Issue by Crsarmv7l** [flipperdevices/flipperzero-firmware#2061]
### Describe the enhancement you're suggesting.

Certain weather sensors (like inFactory) natively transmit in degrees F. inFactory in the weather app always show degrees C.

It would be nice be able to choose if you want F or C.

**Comment by Skorpionm** [comment]
I'm looking forward to per-application customization support functionality. then I’ll add this so that I don’t have to re-select the settings every time I start the application

**Comment by Crsarmv7l** [comment]
@Skorpionm 
While I could see how that would make things easier, I wasn't even thinking of actual persistent "settings", simply that right/left or up/down while viewing a weather station would cycle between F or C.

**Comment by skotopes** [comment]
Fixed in dev, will be included in next release.
