### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mikadev** [flipperdevices/flipperzero-firmware#2062]
### Describe the enhancement you're suggesting.

In France Vigik nfc or parking pass and Liftmaster parking pass are not working with flipper there is a way to fix or add this feature ?

**Comment by skotopes** [comment]
Vigik was mentioned previously in issues here, but sadly we do not have cards/readers to experiment with.
At least 2 generations of Liftmaster are supported, make sure that you are using latest firmware and correct frequency. In case if it still doesn't work for you check new protocol guide on our forum.

Also please 1 issue - 1 problem.
