### ISSUE TITLE
Send IR CODE when receive SUBGHZ

### ISSUE THREAD

**Issue by krisss117** [flipperdevices/flipperzero-firmware#2064]
### Description of the feature you're suggesting.

1. Read/select SUBGHZ
2. Read/select IR
3. Run some application
4. Set IR
5. Set SUBGHZ
6. Start application
When application get IR code, then send SUBGHZ signal

### Anything else?

It will be great when it support trigger for SUBGHZ, IR, NFC, RFID and support action for that too

**Comment by skotopes** [comment]
In theory possible, but sounds like idea for 3rd party application.
