### ISSUE TITLE
ST25TB nfc tag support

### ISSUE THREAD

**Issue by augustozanellato** [flipperdevices/flipperzero-firmware#2072]
### Description of the feature you're suggesting.

It would be nice to have support for ST25TB nfc tags. They're supported by [ST's RFAL](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/lib/ST25RFAL002/include/rfal_st25tb.h) so it shouldn't be hard to add support at least in `furi_hal_nfc`. 
I'd need the support for a FAP I'm developing that reads, parses and writes back data to various types of tags so I don't need support in flipper gui etc.
I wouldn't mind using RFAL directly myself but if I understood everything correctly it isn't supported nor recommended.

### Anything else?

It's a NFC-B tag btw, not sure if it would need additional infra in furi hal :thinking:

**Comment by skotopes** [comment]
Yep, RFAL is obsolete and going to be removed. @gornekich can provide more details...

**Comment by gornekich** [comment]
Hello @augustozanellato !
As @skotopes said, it's not recommended to use RFAL. I am working on new low level nfc driver. Once it's done (hopefully end of december 2022) I will let you know

**Comment by augustozanellato** [comment]
> Hello @augustozanellato ! As @skotopes said, it's not recommended to use RFAL. I am working on new low level nfc driver. Once it's done (hopefully end of december 2022) I will let you know

Thanks for the quick reply!

**Comment by augustozanellato** [comment]
Support added with #3076
