### ISSUE TITLE
NTAG203 info makes flipper crash on 0.72, while it worked on previous firmware versions

### ISSUE THREAD

**Issue by topouzid** [flipperdevices/flipperzero-firmware#2075]
### Describe the bug.

If I scan an NTAG203, save it and then choose Info on the saved tag, Flipper crashes and reboots.
If I scan and check "info" on the freshly scanned tag, info gets displayed correctly.
Emulation doesn't crash Flipper. The only thing that crashes it is "info" on a saved NTAG203. 

### Reproduction

1. NFC Read (reads successfully)
2. More -> Save...
3. Choose the saved tag from the menu and press "Info"
4. "Flipper crashed and was rebooted. NULL pointer dereference"

### Anything else?

The NTAG203 that I used is the following [NTAG203](https://flpr.app/s/#path=any/nfc/Nespresso_new.nfc&Filetype=Flipper+NFC+device&Version=2&Device+type=NTAG203&UID=04+C3+A5+4A+84+2A+80&ATQA=44+00&SAK=00&Data+format+version=1&Signature=00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00+00&Mifare+version=00+00+00+00+00+00+00+00&Counter+0=0&Tearing+0=00&Counter+1=0&Tearing+1=00&Counter+2=0&Tearing+2=00&Pages+total=42&Pages+read=42&Page+0=04+C3+A5+EA&Page+1=4A+84+2A+80&Page+2=64+48+00+00&Page+3=E1+10+12+00&Page+4=01+03+A0+10&Page+5=44+03+15+D1&Page+6=01+11+54+02&Page+7=65+6E+30+32&Page+8=32+30+30+34&Page+9=30+38+30+30&Page+10=35+33+30+30&Page+11=FE+00+00+30&Page+12=00+00+00+00&Page+13=00+00+00+00&Page+14=00+00+00+00&Page+15=00+00+00+00&Page+16=00+00+00+00&Page+17=00+00+00+00&Page+18=00+00+00+00&Page+19=00+00+00+00&Page+20=00+00+00+00&Page+21=00+00+00+00&Page+22=00+00+00+00&Page+23=00+00+00+00&Page+24=00+00+00+00&Page+25=00+00+00+00&Page+26=00+00+00+00&Page+27=00+00+00+00&Page+28=00+00+00+00&Page+29=00+00+00+00&Page+30=00+00+00+00&Page+31=00+00+00+00&Page+32=00+00+00+00&Page+33=00+00+00+00&Page+34=00+00+00+00&Page+35=00+00+00+00&Page+36=00+00+00+00&Page+37=00+00+00+00&Page+38=00+00+00+00&Page+39=00+00+00+00&Page+40=00+00+00+00&Page+41=00+00+00+00&Failed+authentication+attempts=0)
It's a Nespresso Club Member's card.

**Comment by skotopes** [comment]
Fixed in #2078
