### ISSUE TITLE
UART bridge EN/BOOT(rts/dts) ui control

### ISSUE THREAD

**Issue by dangerousvasil** [flipperdevices/flipperzero-firmware#2077]
### Description of the feature you're suggesting.

Hello!

please add to uart bridge function for control rts/dts pins.

user story:
1) I select uart bridge  
1) usb channel 0 and rtd/tds pin
1) in ui i see rtd/tds text if pins low and bold if pins are high
1) up  button i can change state rtd pin
1) down  button i can change state tds pin 

its like EN/BOOT on dev bord for noobie

**Comment by skotopes** [comment]
We already have configurable DTR/RST pins in UART bridge. As for manual control it looks like overkill and something that breaks standards.
