### ISSUE TITLE
Subghz fails with out error with a zero in .sub file

### ISSUE THREAD

**Issue by evilpete** [flipperdevices/flipperzero-firmware#2083]
### Describe the bug.

If a '0' is contained in the dot-sub file's RAW_Data, transmission will fail without error.

eg:
>RAW_Data: **0** -48 60 -44 60 -48 52 -52 56 -48 52 -52 52 -52 52 -52 52 -52 52 -52 52 -52

Flipper will not reported error and display transmission animation as normal

FSK will transmit an unmodulated RF burst, OOK does not appear to transmit anything

No Error is alert is displayed 

### Reproduction
[Ford_TPMS-good.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/10145601/Ford_TPMS-good.sub.txt)
[Ford_TPMS-error.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/10145602/Ford_TPMS-error.sub.txt)

download attached files
rename to from `Ford_TPMS-error.sub.txt` to  `Ford_TPMS-error.sub.txt`
and `Ford_TPMS-good.sub.txt` to `Ford_TPMS-good.sub.txt`

and load files  onto Flipper

run SDR software like rlt_sdr to look at the transmission 

this was transmitted with the `Ford_TPMS-error.sub` that contains a '0' in the data:

![Screen_Shot-with-error](https://user-images.githubusercontent.com/2381225/205422004-44b152eb-0429-49fd-8a55-77d9ac8ad7b0.png)

this was transmitted with the  file `Ford_TPMS-good.sub` without  '0' in the data:

![Screen_Shot-Good](https://user-images.githubusercontent.com/2381225/205422143-0791e325-1eaf-4c1f-9978-c7d4a8b06fe4.png)

**Comment by skotopes** [comment]
0 is invalid value that never should appear in the stream. How did you got it there?

**Comment by evilpete** [comment]
> 0 is invalid value that never should appear in the stream. How did you got it there?

wrote a script to convert `.ook` files generated by rtl_433 ([subghz_ook_to_sub.py](https://github.com/evilpete/flipper_toolbox/blob/main/subghz_ook_to_sub.py)) to `.sub` file and stumbled onto the bug.

(yes I fixed my code,  but figured the lack of error report with subghz was also a issue)

**Comment by skotopes** [comment]
@Skorpionm can we add extra checks?

**Comment by Skorpionm** [comment]
we can throw out unwanted values ​​and continue playing the file, but this simply cannot happen during normal recording of a RAW file. and if people write scripts to generate a RAW file, it would be logical to think about what the physical meaning of duration 0 is, and how 0 duration is obtained

**Comment by evilpete** [comment]
@Skorpionm   quite a few people are writing scripts to generate a RAW file,  I have a repo half full of them

(Also it would have to have a official format description)

**Comment by skotopes** [comment]
We'll add documentation for RAW format in next release.
