### ISSUE TITLE
NFC descripter with computer

### ISSUE THREAD

**Issue by ac1dburnz** [flipperdevices/flipperzero-firmware#2085]
### Description of the feature you're suggesting.

Create a way to help decrypt NFC via a flipper with a computer. For example, there is a cloner software that currently does this with their product when they can not decrypt against. The program is called Icopy.

**Comment by skotopes** [comment]
What exactly do you want to decrypt?

**Comment by ac1dburnz** [comment]
It would decrypt the  nfc tag using the computer and uses the flipper as a nfc reader for live decrypting. I’ve found that the flipper always has problems decoding my mifare classic 1k and maybe using a computer attachment might be a helpful workaround for decoding the keys

**Comment by skotopes** [comment]
What you want sounds like mfkey32 attack which already implemented and can be done with mobile or web companions.

**Comment by ac1dburnz** [comment]
but its not. Im talking about with the key its self. That methoid requires the reader. What i am suggesting would be like this video https://www.youtube.com/watch?v=0SewclaC8Y4 but with the flipper instead.

**Comment by skotopes** [comment]
Everything that is shown in this video is already implemented in Rfid, Nfc and Nfc magic apps.
