### ISSUE TITLE
Settings Option to toggle UI Menus between landscape/portrait

### ISSUE THREAD

**Issue by Az-Neter** [flipperdevices/flipperzero-firmware#2086]
### Description of the feature you're suggesting.

Holding the flipper in my left hand with my thumb on the button and the IR pointed outwards is the most comfortable way for me to use the device. 
I would like the ability to toggle menus in the UI between landscape and portrait so they can be more easily read and navigated while holding the device this way.

The animations do not need to be changed.

We already have proof that plugins like the calculator can look very good as a portrait display, and I think slightly shrinking the font of the menus and allowing them to be read in the same orientation as the calculator would vastly improve use-case scenarios.

### Anything else?

I love all of you who made this.
And I especially love Aquam1ne.
<3

**Comment by skotopes** [comment]
On system API level this is already implemented. In theory applications can implement both layouts(landscape and portrait) but not feasible on all cases and requires tremendous amount of work. We don't plan to add such feature.
