### ISSUE TITLE
Hard Freeze after attempting to format SD card

### ISSUE THREAD

**Issue by M-Gomez** [flipperdevices/flipperzero-firmware#2090]
### Describe the bug.

The backlight is stuck on and the screen reads "Format SD card? All data will be lost", it's been like this for 4 hours, the only way to exit is by rebooting.

### Reproduction
Go to
Settings > Storage > Format SD Card > Format

**Comment by hedger** [comment]
What are the size & manufacturer of your SD card?

**Comment by skotopes** [comment]
Are you experiencing this issue with all SD cards? Or only with one specific?

**Comment by skotopes** [comment]
Please check dev or 0.77 RC and reopen issue if problem persist
