### ISSUE TITLE
buffered_file_stream_open never returns when trying to open executable itself

### ISSUE THREAD

**Issue by QtRoS** [flipperdevices/flipperzero-firmware#2094]
### Describe the bug.

Facing this issue in my Hex Viewer app. When trying to view hex_viewer.fap itself, app hangs. Debug showed that `buffered_file_stream_open` (internally `file_stream_open`) function doesn't return control. Code is [here](https://github.com/QtRoS/flipper-zero-hex-viewer/blob/master/hex_viewer.c#L161). Seems that file is blocked by OS/app launcher. 

### Reproduction

1. Open [Hex Viewer app](https://github.com/QtRoS/flipper-zero-hex-viewer/) 
2. Navigate to the apps folder
3. Select hex_viewer.fap
4. App hangs, doesn't react to any input (while OS itself is alive, logs are going, qFlipper works)

**Comment by skotopes** [comment]
That's not a bug, that is a feature. Opening already open file is currently impossible.

**Comment by DrZlo13** [comment]
@skotopes yes, but in the case of an elf file, we don't need to keep that file open.
