### ISSUE TITLE
New Application "Password Bank" concept

### ISSUE THREAD

**Issue by LY2NEO** [flipperdevices/flipperzero-firmware#2095]
New Application "Password Bank" concept

"Password Bank" is a password manager application, which gives You safe (offline) and comfortable way to store, use and manage Your passwords. Stored passwords are used by simulating them with FlliperZero device as HID keyboard when You hit to use it. It stores Your passwords in encrypted passwords profile file. For encryption it use main password KEY (it salts encryption) which You have to enter to decrypt passwords profile file, to access profiles stored passwords. Each password profile has separate encrypted storage file. For example You could create own web page passwords profile, work passwords profile and etc.

Your passwords are protected by encryption and :
Also, when You leave You device with active "Password Bank" app it locks device with PIN lock after some time (for exaple after 30sec ), of course it could be improved with monitoring Bluetooth paired device and lock FlipperZero only when paired device became out of range and at the same time when it locks FlipperZero it could send and "Win"+L to lock and PC (for windows os).
If Your device is unplugged from usb it detects it and wipes decrypted profile data.

![image](https://user-images.githubusercontent.com/118531425/205869150-f8cff484-fa3b-47f8-a159-ae26adb2ec3d.png)

From my first view I think it could be the greate feature app and we could combine and create it form already made apps code, because what we need could use form such apps like BadUsb, USB HID keyboard, password generator and other... At this first step it would great to discuss is it really worth it or only one I am seeing the benefits of this feature??? For next it would be interesting to hears some advices how should I start , from what I should begin, because at this moment I am not very familiar with this framework?

Thanks for listening my idea and thanks for Your advices.

**Comment by Az-Neter** [comment]
Yes please, desperately needed. Not the first time it's been suggested either but this is the most detailed write up so far.
