### ISSUE TITLE
infrared_remote has screen errors after 255 entries 

### ISSUE THREAD

**Issue by evilpete** [flipperdevices/flipperzero-firmware#2096]
### Describe the bug.

Well generating a "IR signals file"  do you discover hidden menus I noticed that the infrared remote application has problems rendering after 253 or 255 buttons.

 there seems to be  a 255 (sometime 253)  button limit that not being enforced as no errors are generated
 
 
![screen-260](https://user-images.githubusercontent.com/2381225/205867567-5456d562-3acc-472c-b4cf-11dfde5a1c37.png)

### Reproduction

load attached example file
[IR-260.ir.txt](https://github.com/flipperdevices/flipperzero-firmware/files/10164448/IR-260.ir.txt)

The problem starts at 255, example file has 260 to make it more obvious....
(array overflow or 8bit index ?)

**Comment by skotopes** [comment]
Yep, sounds like something that we need to fix. @gsurkov will take a look on it.
