### ISSUE TITLE
USB-UART Bridge NULL pointer dereference

### ISSUE THREAD

**Issue by 247a** [flipperdevices/flipperzero-firmware#2103]
### Describe the bug.

Bug seen on https://www.reddit.com/r/flipperzero/comments/zedzkg/caught_a_bug_on_the_latest_firmware_0721/

Managed to reproduce on my own device running 0.72.1 (579e3b5f)

NULL pointer exception occurs when GPIO->USB-UART Bridge is loaded with no host connected. 

If a **_host is connected_** to the USB the crash will **_NOT_** occcur 

### Reproduction
- Factory reset
- Make sure flipper usb is not connected.
- navigate to `GPIO`
- navigate to `USB-UART Bridge`
- *The screen will briefly (aprox half a second) show the USB-UART screen, with the baud set as `????` and tx pin as 13 and rx pin as 14*
- *The screen will power off*
- *The screen will power on with the message `Flipper crashed and was rebooted NULL pointer dereference` *

**Comment by skotopes** [comment]
Fixed in #2108
