### ISSUE TITLE
Main menu customization via settings

### ISSUE THREAD

**Issue by makkarpov** [flipperdevices/flipperzero-firmware#2110]
### Description of the feature you're suggesting.

Every user has his own set of frequently used apps, including custom ones. Currently custom apps must be accessed either via BtnDown->'Favorites', or via 'Main menu' -> 'Applications' -> ... (too many clicks). And vice versa, you could have completely unused app in main menu (like 'Bad USB').

Suggestion is to allow customization of main menu via 'Settings', and leave just one fixed entry - 'Settings' itself.

**Comment by skotopes** [comment]
Hi. We may add it at some point in future, meanwhile I'll add it to backlog.

**Comment by skotopes** [comment]
Left and right button are reassignable, both short and long press

**Comment by makkarpov** [comment]
But reassignment of the buttons wasn't a topic of this request. Request was about re-ordering and customization of the main menu itself.

**Comment by skotopes** [comment]
@makkarpov reordering in main menu is quite problematic with its current architecture. There are no plans to change it (also our docs department very unhappy when we change something they've documented).
