### ISSUE TITLE
Weather Station - Units

### ISSUE THREAD

**Issue by mmiller7** [flipperdevices/flipperzero-firmware#2122]
### Describe the enhancement you're suggesting.

The weather station app currently appears to convert temperatures to Celsius.  It would be nice if you could set the units you want temperature displayed in.

**Comment by Skorpionm** [comment]
this is in the plans, there will be a setting in which to display the temperature
https://github.com/flipperdevices/flipperzero-firmware/issues/2061

**Comment by skotopes** [comment]
Fixed in dev, going to be included in next release
