### ISSUE TITLE
Support Radio sonde recieving

### ISSUE THREAD

**Issue by BrunoKlu** [flipperdevices/flipperzero-firmware#2123]
### Description of the feature you're suggesting.

Add feature \ app to recieve and decode weather ballon radio sonde signals

**Comment by skotopes** [comment]
In theory possible in real life not going to work. Biggest issue is a lack of good antenna and LNA in flipper.

**Comment by BrunoKlu** [comment]
Ok,Do you mean that Flippers reciever would not be sensitive enough ?

Radio sonde protocols are quite strong modulations, but you are probably right !

Thanks

**Comment by skotopes** [comment]
Flipper receiver itself is quite good. But it's not enough: you also need good antenna, LNA and band-pass filter to get it really right.

**Comment by daskalovst** [comment]
Yes, I agree. If we're using a flipper to receive signals from many kilometers away, it's definitely not the proper device for the task.

There are numerous software programs available that can predict where a radiosonde will fall to the ground. The concept here is to utilize the flipper to receive and decode the signal during the final stage of the radio-sonde's recovery, when we are in close proximity to it. At this point, the signal is very strong, making it more feasible for the flipper to successfully decode it. I believe the flipper can effectively decode signals from distances of 200-300 meters in this scenario.

**Comment by skotopes** [comment]
@daskalovst by the way external subghz module support has been available for some time. I think at this point everything to implement sonde support is ready.

However this is not topic of interest for us, so someone from community should try to implement it.

**Comment by pfrederiksen** [comment]
I'm working on an app for this, stay tuned.

**Comment by MrOAPhex** [comment]
> I'm working on an app for this, stay tuned.

Hey! Do you have updates for the app? It would be really helpful! Thanks

**Comment by pfrederiksen** [comment]
Try this: https://github.com/pfrederiksen/flipper-radiosonde-finder

I'm still testing it because radiosondes haven't been flying directly over lately, but I think it should work.
