### ISSUE TITLE
Allow libc functions in external applications (fap)

### ISSUE THREAD

**Issue by samuel** [flipperdevices/flipperzero-firmware#2125]
### Describe the enhancement you're suggesting.

Currently a number of the libc functions are not exposed to external fap in api_symbols.csv. For example strtok (and/or strsep), strcat/strncat, etc.

I ran into this when attempting to make nrf24sniff into a fap. While it's certainly possible include a version of the needed functions in the fap itself, it would be nice to be able to use the base implementations. Some of the functions might be excluded for sake of avoiding buggy code (e.g. strcat vs strncat), but the more of the libc interface exported the easier it is to use existing code and libraries.

**Comment by skotopes** [comment]
I'd recommend to use FuriString.

In general libc is quite big and unpredictable especially when linked into ext apps. So we intentionally removed functions that doesn't behaves well.
