### ISSUE TITLE
Add La Crosse TX29DTH-IT support for Weather Station

### ISSUE THREAD

**Issue by kaimi-** [flipperdevices/flipperzero-firmware#2130]
### Description of the feature you're suggesting.

Add La Crosse TX29DTH-IT support for Weather Station. 
rtl_433 supports this sensor: https://github.com/merbanan/rtl_433/blob/bb1be7f186ac0fdb7dc5d77693847d96fb95281e/src/devices/lacrosse_tx35.c.

Some samples (`rtl_433_64bit_static.exe -R 75 -f 868300000 -s 2M -S known`):
```
model     : LaCrosse-TX35DTHIT                     id        : 6
Battery   : 1            NewBattery: 1             Temperature: 23.9 C       Humidity  : 29 %          Integrity : CRC
```
[g001_868.3M_2000k.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10225110/g001_868.3M_2000k.zip)

```
model     : LaCrosse-TX35DTHIT                     id        : 6
Battery   : 1            NewBattery: 1             Temperature: 19.6 C       Humidity  : 26 %          Integrity : CRC
```
[g002_868.3M_2000k.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10225127/g002_868.3M_2000k.zip)

```
model     : LaCrosse-TX35DTHIT                     id        : 6
Battery   : 1            NewBattery: 1             Temperature: -0.6 C       Humidity  : 32 %          Integrity : CRC
```
[g003_868.3M_2000k.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10225223/g003_868.3M_2000k.zip)

```
model     : LaCrosse-TX35DTHIT                     id        : 6
Battery   : 1            NewBattery: 1             Temperature: -3.8 C       Humidity  : 35 %          Integrity : CRC
```
[g004_868.3M_2000k.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10225268/g004_868.3M_2000k.zip)

```
model     : LaCrosse-TX35DTHIT                     id        : 6
Battery   : 1            NewBattery: 1             Temperature: 19.0 C       Humidity  : 41 %          Integrity : CRC
```
[g005_868.3M_2000k.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10225419/g005_868.3M_2000k.zip)

**Comment by skotopes** [comment]
@Skorpionm please take a look

**Comment by Skorpionm** [comment]
![image](https://user-images.githubusercontent.com/85568270/207869552-845454ed-b5f9-4494-b8f7-c25a18209609.png)

transmission in FM modulation Deviation 68KHz, it is not supported in the flipper out of the box. and the recordings play crooked, I need a real sensor

**Comment by kaimi-** [comment]
Is it supported in any kind of custom fw? And by real sensor you mean the physical device? Or I can try to record those with some other software if you could tell which one

**Comment by skotopes** [comment]
More like you need to create custom preset and add it to subghz configuration files

**Comment by kaimi-** [comment]
@Skorpionm probably I don't understand something, but why are you showing 433.925 frequency? This sensor uses 868.3 frequency, which can be deduced from recording filename.

**Comment by Skorpionm** [comment]
just played on 433.92

**Comment by kaimi-** [comment]
@Skorpionm  Could you tell anything about those recordings, still crooked? Both should contain the same data.
```
model     : LaCrosse-TX35DTHIT                     id        : 6
Battery   : 1            NewBattery: 0             Temperature: -1.9 C       Humidity  : 68 %
Integrity : CRC
```
[g001_868.3M_2000k.cu8.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10257479/g001_868.3M_2000k.cu8.zip)
[g002_868.3M_2000k.cu8.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10257480/g002_868.3M_2000k.cu8.zip)

**Comment by skotopes** [comment]
Looks like we need real device to implement this protocol.

**Comment by skotopes** [comment]
We don't have ability to get this device right now so I'm going to close this ticket.
Could be that someone from community will implement it in future.
