### ISSUE TITLE
Smart Electricity Meters: Infrared SML / OBIS

### ISSUE THREAD

**Issue by 0x53A** [flipperdevices/flipperzero-firmware#2136]
### Description of the feature you're suggesting.

Smart Meters broadcast their current status every X seconds through an IR transmitter using SML (Smart Message Language) / OBIS (Object Identification System) codes.

It would be really cool if you could record a raw transmission and then interpret it as SML / OBIS.

Here is one link about SML / OBIS: https://esphome.io/components/sml.html

**Comment by skotopes** [comment]
Good idea for the app. Not sure if we are going to implement it.

**Comment by rklasen** [comment]
This was closed as "completed", but I can't find this anywhere in the docs. Is the app to read a compatible power meter available?

**Comment by skotopes** [comment]
As not planned.
