### ISSUE TITLE
HID Bluetooth problem

### ISSUE THREAD

**Issue by DiCollars** [flipperdevices/flipperzero-firmware#2145]
### Describe the bug.

After updating (release 0.73.1) I have to re-pair my device every time to make work 'bluetooth remote' plugin (PC windows 11).
Have no idea why It was broken after update, please fix it - cos it was one of my favorite feature.

### Reproduction

1.Unpair all devices
2.Open on flipper plugin 'bluetooth remote' -> 'KeyBoard'
3.Open on PC settings - bluetooth devices -> add new one -> connect -> everething does work
4.Exit plugin on flipper
5.Open again this plugin
6.No PC reaction on any command (I mean all - mouse, keyNote, keyBoard, even tikTokController)

**Comment by DrZlo13** [comment]
Thanks for the report. This is a known issue, we a working on it rn.

**Comment by skotopes** [comment]
Fixed in dev, going to be included in next release

**Comment by DiCollars** [comment]
Great! Thank you!
