### ISSUE TITLE
Mifare Ultralite Unlock with Reader function hangs 

### ISSUE THREAD

**Issue by tatramaco** [flipperdevices/flipperzero-firmware#2153]
### Describe the bug.

The Unlock with Reader function for MiFare Ultralite hangs and Flipper must be restarted

### Reproduction

1. Read Mifare Ultralite card with password protected pages
2. Select More and Unlock
3. Choose Unlock With Reader
4. ‘Touch the reader to get password…’ message displayed
5. Hitting back before presenting to the reader works.
6. Presenting Flipper to the reader causes red LED for unsuccessful auth and it then hangs and must be rebooted

**Comment by skotopes** [comment]
@gornekich please take a look

**Comment by nils1603** [comment]
Can confirm that this is not working and results in a freeze. Users on reddit also confirmed this:

https://www.reddit.com/r/flipperzero/comments/zwuip8/mifare_ultralight_c_unlock_with_reader_not_working/

**Comment by GMMan** [comment]
> Users on reddit also confirmed this:
> 
> https://www.reddit.com/r/flipperzero/comments/zwuip8/mifare_ultralight_c_unlock_with_reader_not_working/

That's a separate issue, Mifare Ultralight C doesn't use the same authentication protocol.

**Comment by nils1603** [comment]
I see. I am trying it with a Mifare Ultralight 11 card/reader

**Comment by mitchellmebane** [comment]
I had the same hanging issue while trying to copy my key card for an Assa Abloy lock.  Based on the design, I think it was the [VingCard Essence](https://www.assaabloyglobalsolutions.com/en/hospitality-solutions/electronic-locks-for-hotels/vingcard-essence-for-hotels).  Unfortunately, I didn't save the card scan, and I'm not at that hotel any more, so I can't provide any more details - all I recall is that the Flipper identified it as a Mifare Ultralight something, I think Ultralight 11.

**Comment by Robotto** [comment]
Confirmed with MF Ultralight 11 card.

**Comment by dontic** [comment]
Hey @skotopes @gornekich Having the same issue here. Need to reset the flipper every time. Mifare Ultralight 11 as well.
Tried to get some debug logs but not sure what you guys need. Let me know and I can grab those while I'm at the hotel.
Here's the issue in a GIF:
![giphy-downsized-large](https://user-images.githubusercontent.com/25914304/218546511-1392b8f3-5906-4755-a420-e2958b532e99.gif)

**Comment by GMMan** [comment]
FWIW a debug break using a J-Link or CMSIS-DAP would be more helpful. I already tried to get logs and it freezes before logging anything useful.

As a workaround, see if scanning the card, saving, then reloading before trying to unlock works. I think it's something not getting initialized properly during the scan that's causing the issue.

**Comment by dontic** [comment]
Huh, interesting thing happening here. 
I just read and saved the hotel key card. Then:

- If I select it and choose "Unlock With Reader", it hangs.
- If I select it and choose "Unlock With Password" and then "Unlock With Reader" it works just fine!  It detects the reader and then asks me to read the card again and works like a charm.

Sadly I have no J-Link here to log at all.

**Comment by firstel** [comment]
@gornekich this looks like enough info to resolve?

**Comment by skotopes** [comment]
@firstel yep

**Comment by panki27** [comment]
I ran into this today.

The Flipper doesn't hang, I can quit out with the Back button. But "Unlock with Reader" does not seem to work, it stays in the "reading" phase.

If I use "Detect Reader" directly from the NFC menu, it gathers 10 nonces.

**Comment by doomwastaken** [comment]
This was fixed a while back, also cannot reproduce on latest release (NFC refactor). Reopen the issue if problem persists
