### ISSUE TITLE
Long names scrolling: Missing last letter

### ISSUE THREAD

**Issue by ahumeniy** [flipperdevices/flipperzero-firmware#2161]
### Describe the bug.

The last letter of the file name is missing when the name is long, but the space appears to be available because the name is still scrolling.

### Reproduction

1. Open the file browser
2. Search for a file with a long name
3. Name will start scrolling, wait to the end.
4. The last letter of the extension is missing

**Comment by skotopes** [comment]
Fixed in #2160
