### ISSUE TITLE
Improve detect reader documentation

### ISSUE THREAD

**Issue by bettse** [flipperdevices/flipperzero-firmware#2164]
### Describe the enhancement you're suggesting.

In the flipper discord's #nfc channel we get more than a few people who have a mistaken impression about the Detect Reader function.  In at least one case they pointed back to the docs (https://docs.flipperzero.one/nfc) as to why.  I wanted to suggest some improvements to prevent this.

On the graphic:

![](https://cdn.flipperzero.one/Monosnap_Web_Image_2022-08-08_14-58-46.png?auto=format&ixlib=react-9.1.1&w=2582&h=902&dpr=2&q=50)

Change "Receive reader's keys", suggestions:
 * "Perform MFKey32 attack"
 * "Emulate Mifare Classic 1k for MFKey32"
 * "Recover add'l Mifare Classic keys"

For the text below
> Detect Reader — emulates an NFC card to receive authentication keys from logs sent by a reader.

Suggestions:

 * **Detect Reader** -- emulates a Mifare Classic 1k to collect data (nonces) used to calculate keys attempted by reader
 * **Detect Reader** -- emulates a Mifare Classic 1k to collect nonces to calculate add'l keys used by reader

**Comment by skotopes** [comment]
Thanks, forwarded to our technical writer. We'll update docs.

**Comment by skotopes** [comment]
Done. Please check updated page.

**Comment by bettse** [comment]
Thanks!!!

**Comment by skotopes** [comment]
U R Welcome )
