### ISSUE TITLE
Picopass text overflow on failed read

### ISSUE THREAD

**Issue by doomwastaken** [flipperdevices/flipperzero-firmware#2185]
### Describe the bug.

![image](https://user-images.githubusercontent.com/72250702/209342813-7dd1aded-7aa7-449b-bc7e-203772ffe067.png)

just text overflow

### Reproduction

Go into picopass and try to read any card, pull the card away in process to get an error message. 
Works on 0.73.1 and 0.74.0-rc / 0.74.1-rc (haven't tested on previous versions)

### Target

f7

**Comment by skotopes** [comment]
@bettse @pcunning Hi guys, can you take a look? )

**Comment by bettse** [comment]
is the font mono-spaced?  if so, I'm surprised we don't see it for all values.  I haven't had time to try to reproduce, but I suspect we just need to bump down the font size a couple points.

**Comment by bettse** [comment]
I couldn't reproduce, but I saw that "1" is super narrow, which can pretty much explain it.

**Comment by skotopes** [comment]
Please check dev or 0.77 and reopen if issue persist
