### ISSUE TITLE
Specify theme context for images in ReadMe.md

### ISSUE THREAD

**Issue by valentinegb** [flipperdevices/flipperzero-firmware#2191]
### Describe the enhancement you're suggesting.

Veeery minor enhancement, but, it would be nice if the "Show me the code!" image in the `ReadMe.md` had a dark-mode variant. Here's the similarly-named article from the GitHub blog discussing how to have theme context dependent images: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

### Anything else?

Just saw that the [flipperdevices/Flipper-Android-App](https://github.com/flipperdevices/Flipper-Android-App) repo has this already, what about the main firmware repository!

**Comment by skotopes** [comment]
Done
