### ISSUE TITLE
LUKS encrypted sdcard support

### ISSUE THREAD

**Issue by antifallobst** [flipperdevices/flipperzero-firmware#2196]
### Description of the feature you're suggesting.

Hey, what is the general opinion of the Flipper team/community about LUKS encrypted sdcards?

My Idea was, to implement support for Transparent sdcard encryption using the Linux Unified Key Setup, since this is an open standard and I think using LUKS encrypted sdcards with the Flipper would be very nice.

Transparent encryption means, that you have to enter the decryption key of the storage on boot, and from that moment it looks like an unencrypted storage to the system.
The storage driver just does an extra de-/encryption step when reading/writing data.
Now, if anyone steals your flipper, they can't do anything with the data, because on the storage medium its completly encrypted.

I could work on it, if people think, that this would be a cool feature :D

Edit:
I know about Issue #1201 but this is especially about LUKS

**Comment by skotopes** [comment]
It's even more complex than #1201. Also requires enormous computational power which flipper zero doesn't have.
