### ISSUE TITLE
Terminal app/plugin for the Flipper

### ISSUE THREAD

**Issue by antifallobst** [flipperdevices/flipperzero-firmware#2202]
### Description of the feature you're suggesting.

A App/Plugin for the Flipper, where you can access the flippers serial cli directly from the flipper.
This would need a hideable keyboard (show with **OK** in the console, and hide with a key on the keyboard).
This would give the user more control over the flipper itself and could be extended to control UART shells, etc.

**Comment by skotopes** [comment]
Good idea for an application. We have UART debug app that is very similar, can be used as a base.
