### ISSUE TITLE
IR flipper-to-flipper file transfer

### ISSUE THREAD

**Issue by Geddeon** [flipperdevices/flipperzero-firmware#2216]
### Description of the feature you're suggesting.

Long-long time ago mobile phones has IR ports with file transferring feature. Why not add it to flipper? AFAIK there is no possibility of sharing files between flippers except for switching MicroSD cards.

**Comment by nymda** [comment]
IR is a simple but terrible way of transfering data, this is a great idea but imo subghz or even NFC should be used instead

**Comment by ankris812** [comment]
or even ble is  better for that

**Comment by skotopes** [comment]
In theory possible, practically meaningless. If we talking about IrDA than is kinda complex to implement, if something more simple than any other transport supported by flipper will be better.

**Comment by nymda** [comment]
i disagree with "practically meaningless". being able to send NFC scans, nonces, etc wirelessly between two flippers could be very useful in actual pentesting applications

**Comment by skotopes** [comment]
@nymda my point is that there are better transports for this task: mobile apps supports sharing on the internet, and if you need local sharing than NFC or Sub-GHz should be used as transport.

Anyway, we already have sharing implemented in mobile apps. Anything else is a good idea for an app and you are free to implement it ;-)

**Comment by ankris812** [comment]
> @nymda my point is that there are better transports for this task: mobile apps supports sharing on the internet, and if you need local sharing than NFC or Sub-GHz should be used as transport.
> 
> Anyway, we already have sharing implemented in mobile apps. Anything else is a good idea for an app and you are free to implement it ;-)

or even ble, im working on doing that. ble is more reliable than ir. and about nfc, do you mean something like android beam?
