### ISSUE TITLE
Cannot read EM4305 cards

### ISSUE THREAD

**Issue by gloglas** [flipperdevices/flipperzero-firmware#2218]
### Describe the bug.

I cannot read the EM4305 cards.
Flipper reads EM4100 cards just fine and they should be compatible.

Here is a basic reading from proxmark and exterior appereance.

![20221229_112948](https://user-images.githubusercontent.com/6841112/209939120-1d0bdf12-0201-41f2-98a1-636cc6a41f27.jpg)
![SmartSelect_20221229_112055_RFID Tools](https://user-images.githubusercontent.com/6841112/209939124-f2ace022-6f75-4856-a4f4-70dd0af312b8.jpg)

### Reproduction

Press Ok from homescreen
Go to 125kHz RFID menu
Press Read and hold card in various distances and positions

### Target

0.74.2

**Comment by Astrrra** [comment]
Are you sure that it's an EM4305? Your proxmark screenshot shows that it's an EM4x50, when it should be EM4x05

**Comment by gloglas** [comment]
This it the datasheet that online shop provided me with: http://www.advanide.com/wp-content/uploads/products/rfid/EM4205-4305.pdf
The chip that I bought was advertised as EM4305.
Either way flipper is unable to read it.

**Comment by gloglas** [comment]
This is the EM4x05 readout and it is a EM4305.
That one above was set to auto search mode.
(I got bunch of these cards. So I set it aside so we can get some consistent data from now on. The reading above was probably not matching anyway.)
![Screenshot_20221229_201559_RFID Tools](https://user-images.githubusercontent.com/6841112/210001054-5ddb81ca-221a-43fa-9752-f30b3f947f25.jpg)

**Comment by Astrrra** [comment]
Ok, it looks like your EM4305 is not emulating an EM4100 card, but some other one (that's what the EM4x50 proxmark reading suggests). Can you write an EM4100 payload to it using your proxmark and try reading that with the Flipper?

**Comment by gloglas** [comment]
The EM4x50 is just a random noise. Please forget that I ever posted that.
I didn't successfully write EM4100 payload to the card but I am not sure if I did that correctly. So if you tell me what things you want me to try exactly _(iceman repo)_ I would be delighted to help you.

**Comment by skotopes** [comment]
Nothing specific from our side, just try standard programming routine for this chip and ensure that payload is correctly emulated with proxmark.
