### ISSUE TITLE
Ability to use a lowercase letter as the first character

### ISSUE THREAD

**Issue by Holmium67** [flipperdevices/flipperzero-firmware#2235]
### Describe the enhancement you're suggesting.

I was using the Authenticator app, attempting to put a key in. However, I was forced to use an uppercase letter for the first character of the string, preventing me from entering the key correctly. Several other apps have this issue.
I don't think the first character should be forced uppercase, since there are times where you would need that character to be lowercase.

**Comment by atsonkov** [comment]
I think adding "shift" on the keyboard that you can un-press is the best way to handle this. It would be even nice if it is 3-state (e.g. Single uppercase, then automatically back to lowercase )current default) => only lowercase => CAPS LOCK-like behaviour). I would like to even dream of long-pressing such button to get additional special characters -,.)(^ Nothing too crazy :)

(Another option might be long-press on the uppercase letter to result in lowercase one, but this does not feel as intuitive and clean as just showing special extra button and does not give you as many options as a multi-state button).

**Comment by skotopes** [comment]
We already have long press that changes character register. But I forgot to handle upper to lower. We'll fix it in next release.

**Comment by skotopes** [comment]
Fixed in #2280
