### ISSUE TITLE
BADUSB: demo_windows.txt contains a dead GitHub-link

### ISSUE THREAD

**Issue by nibrobb** [flipperdevices/flipperzero-firmware#2236]
### Describe the bug.

The link on line 83 of `demo_windows.txt` takes you to a 404 page on github. It seems @hak5darren has removed the repository linked to.

### Reproduction

1. Observe line 83 on `dev` branch https://github.com/flipperdevices/flipperzero-firmware/blob/dev/assets/resources/badusb/demo_windows.txt#L83
2. Try to open the link
3. 404 Not found

**Comment by geks52** [comment]
In line 82 on _dev_ branch demo_macos.txt https://github.com/flipperdevices/flipperzero-firmware/blob/dev/assets/resources/badusb/demo_macos.txt#L82  a same error

**Comment by LiamDroog** [comment]
I've addressed this in pr #2270
