### ISSUE TITLE
Add Baud Rates to GPIO USB-UART Bridge

### ISSUE THREAD

**Issue by bpienig** [flipperdevices/flipperzero-firmware#2240]
### Describe the enhancement you're suggesting.

I noticed that currently USB-UART bridge is missing a few common baud rates for debugging devices.

https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/main/gpio/scenes/gpio_scene_usb_uart_config.c

Is it possible to add a few more of the common baud rates for testing?   Specifically 1200, 4800, and 28800?

**Comment by skotopes** [comment]
Yep, possible
