### ISSUE TITLE
Add space key to keyboard for (re)naming items

### ISSUE THREAD

**Issue by timby3** [flipperdevices/flipperzero-firmware#2242]
### Requesting that a space key be added to the keyboard that appears when naming an item.

The keyboard doesn't have a space
![flpr-2023-01-04-13_52_33](https://user-images.githubusercontent.com/89540768/210559276-54481321-e75b-4295-82b5-5a617d2cdc14.png)

The mobile app can be used to rename items with certain symbols, including spaces
![flpr-2023-01-04-13_52_54](https://user-images.githubusercontent.com/89540768/210559303-993b2472-03c6-4718-8372-4096483ce342.png)

**Comment by SleepyYui** [comment]
I would personally say that using spaces in such applications is rather unusable, since whilst programming you can't just use space keys in variables. In general, creating files and folders with spaces in my opinion is not my thing. But to be honest I could see people using it since you can do it in the app.

**Comment by atsonkov** [comment]
I use Unleashed, but I am pretty sure it has to be working with the stock firmware too. To write space just long-press the OK button on the "_". (BTW you can also long-press on letters to make them UPPERCASE).
![flpr-2023-01-05-22:25:18](https://user-images.githubusercontent.com/10774549/210873880-f7367a20-b5a2-4038-a44e-43340c683c92.png)

**Comment by timby3** [comment]
I had no idea. idk why I didn't figure it out because I knew that you could long press letters but that's just me.

**Comment by fiveseven808** [comment]
> I use Unleashed, but I am pretty sure it has to be working with the stock firmware too. To write space just long-press the OK button on the "_". (BTW you can also long-press on letters to make them UPPERCASE). ![flpr-2023-01-05-22:25:18](https://user-images.githubusercontent.com/10774549/210873880-f7367a20-b5a2-4038-a44e-43340c683c92.png)

Holy cow, I did not realize that this was a thing! I'm commenting to reccomend that long-press actions be added and detailed in the flipper zero documentation.

**Comment by TinyTechPrints** [comment]
> I use Unleashed, but I am pretty sure it has to be working with the stock firmware too. To write space just long-press the OK button on the "_". (BTW you can also long-press on letters to make them UPPERCASE). ![flpr-2023-01-05-22:25:18](https://user-images.githubusercontent.com/10774549/210873880-f7367a20-b5a2-4038-a44e-43340c683c92.png)

hi, what is the ''_''????

**Comment by timby3** [comment]
It's the button left of the "save" button.
