### ISSUE TITLE
Ability to run subghz protocol parser on sub file outside Flipper

### ISSUE THREAD

**Issue by exander77** [flipperdevices/flipperzero-firmware#2254]
### Description of the feature you're suggesting.

I would like to improve some flipper modules and either I am missing something or it is not possible, but I would expect that it is way easier to run protocol parser outside Flipper on recorded sub files.

**Comment by fiveseven808** [comment]
What I want, is the ability to run subghz protocol parser on already recorded "read-raw" files! 

I think it would be really useful to be able to record a signal, run the parser, and have the parser automatically spit out the results for the various supported modulations. That way, someone can get a feel on what an unknown signal would look like if de-modulated in any of the supported modulations, and can maybe better pick the correct one for the "read" function.

**Comment by exander77** [comment]
@fiveseven808 
I think, you can do this using cli.

**Comment by skotopes** [comment]
Yep there is a CLI tool for RAW file decoding. As for GUI - best if it will be external app.

**Comment by exander77** [comment]
> Yep there is a CLI tool for RAW file decoding. As for GUI - best if it will be external app.

But that does not solve my issue. CLI runs inside Flipper.
