### ISSUE TITLE
Nvim (Astro Nvim) Setup guide

### ISSUE THREAD

**Issue by ASoldo** [flipperdevices/flipperzero-firmware#2257]
### Describe the enhancement you're suggesting.

I would like to continue to develop for Flipper Zero Firmware in Neovim (Astro Nvim) instead of VS Code. Currently what I've done is symlink compile_commands.json to root, from ./build/latest/compile_commands.json and that solved a lot of intellisense issues. Is there any other necessary step in order to fix this?

**Comment by skotopes** [comment]
Not sure if we can help you with your journey: no one from flipper developers use *vim nor we plan to support it.
Try to ask on discord or forum.
