### ISSUE TITLE
SubGhz Frequency Analyzer Logging

### ISSUE THREAD

**Issue by fiveseven808** [flipperdevices/flipperzero-firmware#2262]
### Describe the enhancement you're suggesting.

The frequency analyzer is my most used application on this thing. It's amazing and I find it incredibly interesting. Much like how we can wardrive, with wifi and GPS, can we get the Frequency Analyzer to do something similar? 

Maybe we can start with small changes:
Stage 1: For one, don't immediately exist the app upon hitting the back button, put a confirm on there or something so it doesn't exit in my pocket or accidental button press, losing all of the data. 

Stage 2: Have an option to save the logs upon exit and show them back up when you resume. Along with that, also put a clear logs button, and a save to file button. With this rudimentary functionality, someone savvy can record location and time on their phone and match the two up later. If I run it for a whole day, I would love to be able to get a CSV of timestamp + signal frequency + RSSI. It would be super cool!

Stage 3: Allow simple serial GPS data to be logged with the CSV file. Obviously this would eat the F0 battery like no tomorrow, but quite a few tiny, cheap, 3.3v GPS modules are readily available. https://www.racedayquads.com/products/micro-ublox-m8n-gps-glonass

### Anything else?

Maybe this is a job/project for someone else to do. Maybe this is better as a third party created *.fap? 

I think if I want to continue using the F0 daily, I will need an incentive like this (war... walking?) to continue having fun lol. 

Now that we have a tiny portable low power hardware extensible device that can listen to a wide subghz range, why not turn it into a potentially interesting subghz warwalking tool!

**Comment by skotopes** [comment]
Frequency Analyzer is a short range tool. It intentionally disconnects sub-ghz antenna and expects that your fob will be close enough to the device (1 inch close). Which makes idea of joining it with GPS kinda meaningless.

However you can take this feature as a base and make application that will do what you want.
