### ISSUE TITLE
Text editor/viewer? 

### ISSUE THREAD

**Issue by fiveseven808** [flipperdevices/flipperzero-firmware#2263]
### Description of the feature you're suggesting.

I copy a large number of files onto my SD card at a time, and I don't necessarily have time to go through all of the documentation before I do so. It would be awesome to be able to click on a txt/md/* file and just open it up as text and scroll through it. I don't even need to edit text lol. I just wanna be able to read with the tiny little screen. 

Of course it's far from optimal, but something would be better than nothing. 

### Anything else?

While we're at it, if someone makes this text reader, can we also make an option to flip the screen orientation 90 degrees counter clockwise? similar to how the IR remotes do? 

One handed text scrolling with the dpad at the bottom sounds pretty cool.

**Comment by skotopes** [comment]
There were discussions about this feature in the past: the best option if it will be implemented as an app. At this point we don't plan to do it, but will accept PR.
