### ISSUE TITLE
Battery display mode is not updated on change

### ISSUE THREAD

**Issue by alvarotorijano** [flipperdevices/flipperzero-firmware#2268]
### Describe the bug.

As user when I change the display mode for the battery level I have to reboot the device for the change to take effect. 
I would like to be advised or the change to be applied on runtime.

### Reproduction

Go to: Settings -> desktop -> (wait) -> battery view
Return to the desktop.

*The change is not applied

**Comment by skotopes** [comment]
That's clearly something from alternative firmware. Please report it to appropriate maintainers.
