### ISSUE TITLE
Renaming a remote control doesnt account for capitalisation

### ISSUE THREAD

**Issue by nymda** [flipperdevices/flipperzero-firmware#2273]
### Describe the bug.

Attempting to rename a remote control within the IR application does not account for changing capitalisations only. For instance renaming "Remote" to "REMOTE" gives an error saying the remote already exists. to do this rename you would have to do something like rename "Remote" to "RemoteA" to "REMOTE".

### Reproduction

-create a new remote control
-save the remote
-rename the remote to capitalise some letters within the name
-attempt to save

**Comment by skotopes** [comment]
Less like a bug, more like a feature: flipper file system is case insensitive and rename of such kind is pain in the ass to handle.

Not planning to fix it. But we'll accept PR with workaround if someone will implement it.
