### ISSUE TITLE
Support for BLE Theengs Decoder library

### ISSUE THREAD

**Issue by 1technophile** [flipperdevices/flipperzero-firmware#2277]
### Description of the feature you're suggesting.

Theengs Decoder Library enables to decode the manufacturer format of numerous BLE broadcasting devices
https://decoder.theengs.io/

![image](https://user-images.githubusercontent.com/12672732/211217379-c86d322e-b872-443c-8838-042004bb1ecf.png)

It could be an excellent addition to Flipper Zero to visualize the information of the BLE devices nearby on the screen with a human-readable format.

For example, XIaomi LYWSD03MMC, LYWSD02, Inkbird, Govee temperature sensors, Mi Scales, iBBQ sensors, TPMS...

Theengs supports more than 50 devices, and the list is growing. If you need support from the team to help you integrate the library, feel free to ping us below:
https://github.com/theengs/decoder/discussions

The flipper zero will have to scan for nearby BLE devices with a passive or active scan, retrieve the broadcasted data with their detailed information, name, servicedata, manufacturerdata mainly and pass it to the decoder as a json.
The decoder will reply with a decoded json in human-readable format.

**Comment by skotopes** [comment]
Currently it's impossible: we use radio stack version that doesn't support host mode.
