### ISSUE TITLE
Serial cli redirect over TCP/UDP through Flipper App

### ISSUE THREAD

**Issue by muziofg** [flipperdevices/flipperzero-firmware#2281]
### Description of the feature you're suggesting.

I've read the request #2202 and I would propose a feature extension.

It's possible to using the Flipper App to expose the serial cli of the Flipper zero over TCP/UDP port? This would make possible to control Flipper via other software present on the same device, in loopback address, or third remote devices into the same wifi network

**Comment by skotopes** [comment]
Quite complex topic. The best option in my opinion will be to expose RPC in some form. We are planning to return to this topic after v1.0 release.
