### ISSUE TITLE
Ideea

### ISSUE THREAD

**Issue by ghost** [flipperdevices/flipperzero-firmware#2290]
### Description of the feature you're suggesting.

How about puting the clock in brainiac mode too? Not only in games mode...

**Comment by Faddy96** [comment]
You can put it in brainiac mode yourself if you want to under settings -> desktop -> Primary/Secondary Favorite App. Then select Applications -> Clock.

Primary Fav App = Quick tap on Left button
Secondary Fav App = Hold down Left button

**Comment by ghost** [comment]
But it s smth if they add it themself

**Comment by Faddy96** [comment]
That truly is something. Do you want them to enable the Bluetooth on your Flipper as well since that seems to be too hard for you?

**Comment by ghost** [comment]
Ofc ur toxic

Cheers, Stefan
________________________________
