### ISSUE TITLE
[NFC] Magic Tag emulation

### ISSUE THREAD

**Issue by ComicBit** [flipperdevices/flipperzero-firmware#2295]
### Description of the feature you're suggesting.

It would be very useful to have the possibility of mimic a magic tag behaviour so that the emulation could work in every enviroment

**Comment by skotopes** [comment]
Are we talking about MFC, and you mean allow write to sector 0?

**Comment by ComicBit** [comment]
> Are we talking about MFC, and you mean allow write to sector 0?

Yes

**Comment by skotopes** [comment]
That is possible and we will accept PR if someone implement it.

**Comment by skotopes** [comment]
Meanwhile I'll put this task to backlog.

**Comment by skotopes** [comment]
After some thought we decided to not to implement it. Too much troubles for very niche things.

**Comment by ComicBit** [comment]
This is very sad :( that would have been one of the best functionalities ever for testing

**Comment by skotopes** [comment]
@ComicBit maybe someone from community will do it, maybe it will be you ;-)

**Comment by ComicBit** [comment]
> @ComicBit maybe someone from community will do it, maybe it will be you ;-)

I'd love to! But I have not much experience with programming such things
