### ISSUE TITLE
Architecture support 

### ISSUE THREAD

**Issue by krak3n77** [flipperdevices/flipperzero-firmware#2297]
### Description of the feature you're suggesting.

Arm64 linux toolchain support would be an amazing addition.

**Comment by FalsePhilosopher** [comment]
From what I remember they ported fbt to arm64 and you just run it like on an x86 machine.

**Comment by krak3n77** [comment]
> From what I remember they ported fbt to arm64 and you just run it like on an x86 machine.

There is no toolchain support for arm64.

**Comment by skotopes** [comment]
It should be possible to compile toolchain for arm linux, but supporting one more architecture is quite painful for us.
We are not planning to do it until critical mass is reached.

Meanwhile fbt supports 3rd party toolchains, so in theory you can build your own or just install components into the system.
