### ISSUE TITLE
[NFC] Reading some types of tag stops emulation from working until certain other types are read

### ISSUE THREAD

**Issue by TollyH** [flipperdevices/flipperzero-firmware#2298]
### Describe the bug.

After reading an EMV or DESFire NFC card, devices will no longer detect the Flipper when emulating other types of NFC (NTAG emulation is all I've tested so far). Scanning a Mifare Classic or an NTAG, or rebooting the Flipper, will fix the issue allowing emulation to be detected again.

### Reproduction

1. Scan either an EMV card or a DESFire card as normal from the NFC menu
2. Now attempt to emulate an NTAG device (like an Amiibo) from either the NFC menu, or the Archive
3. The Flipper will appear to emulate as normal without any log errors, but devices will fail to detect it
4. Either reboot the Flipper, or scan either an NTAG device or Mifare Classic card
5. Once again start emulating an NTAG device
6. Devices will now detect the Flipper as normal again

**Comment by skotopes** [comment]
Yep this is known issue. There were partial fix for it in previous releases and it will be fully fixed after NFC HAL refactoring.
Please let us know if issue persist for you in 0.77.

**Comment by TollyH** [comment]
At the moment I'm still having this specific issue in 0.77.0-rc

**Comment by skotopes** [comment]
@TollyH thanks, we'll try to address it next update

**Comment by nvx** [comment]
Is there a planned timeline for the NFC HAL refactoring @skotopes, or is it just on the todo list?

**Comment by skotopes** [comment]
Yes, it's currently work in progress.
As for specific time line: we are planning to open base part of new driver with MFC in one month. Then other protocols.

**Comment by skotopes** [comment]
Should be fixed in previous release. Please reopen if you still have this issue.
