### ISSUE TITLE
Frequency analyzer can't see my Princeton RF on 0.75.0

### ISSUE THREAD

**Issue by topouzid** [flipperdevices/flipperzero-firmware#2310]
### Describe the bug.

It seems like sub-ghz frequency analyzer is misbehaving on latest update 0.75.0. The frequency analyzer can’t see my alarm’s RF signals, the ones that if I use read, it can successfully read and decode. In fact, on each firmware release I let freq.analyzer running for a few minutes to see how many signals it can pick, and while it has some hits, 0.75.0 seems to be more silent (or rather more “deaf”) than previous versions.
If I use "Read", it picks Princeton 24bit at 433.92AM, reads and sends it successfully, but it doesn't show anything on Frequency analyzer. Under Test Packer function, it shows CC1101, freq 433.919.830, path 0, Packets: 14, RSSI 84(ish).

### Reproduction

1. Start Frequency Analyzer on Sub-Ghz and wait for signal
2. Trigger any Princeton 433.92MHz alarm device, motion detector, window contact, smoke detector, or press any key on the keyfob, arm, disarm, sos.
3. The frequency analyzer doesn't show any new signal.
4. Try another device like a car keyfob which operates on the same frequency, the frequency analyzer shows it.
5. Open Read from sub-ghz menu.
6. Trigger the same device that didn't show up on the frequency analyzer
7. Signal is read successfully.

**Comment by Skorpionm** [comment]
You probably didn't read the documentation.  the frequency analyzer sees only those devices that are in close proximity to the flipper.  Literally 5 cm between their antennas.  this is done on purpose so that the frequency analyzer does not catch other devices.
