### ISSUE TITLE
Sample battery temperature when the device is idle. Add app to show temperature graph.

### ISSUE THREAD

**Issue by antirez** [flipperdevices/flipperzero-firmware#2330]
### Description of the feature

When the Flipper is idle (assorbing very little current), the battery temperature is highly correlated with the ambient temperature, making the Flipper a portable theromoeter. However the device can display only the instantaneous temperature of the battery (and, in that moment, the user has the Flipper in her hands, altering the temperature of the device itself).

The feautre request suggests doing the following:
* Sample the Flipper temperature each 15 minutes, directly from a kernel process, so that no application needs to run. When sampling the temperature, record both the temperature *and* the device instantaneous current usage. Only sample the last 24h using a circular buffer, for a total of 96 data points. This will amount to very few bytes in total.
* Provide an API to access such history.
* Provide a simple default app to show the temperature graph, check the temperature at specific moments in the past 24h and so forth.

### Implementation

If this idea is approvde, I may write the implementation myself if needed. Thanks.

**Comment by skotopes** [comment]
That does sounds like quite niche thing. We are not going to implement it in firmware itself, but we are planning to implement user background services at some point and then you'll be able to implement it by your self.

Also all 3 temperature sensors(Gauge, Charger, MCU) are actually on the main board.
