### ISSUE TITLE
Kermit functionality

### ISSUE THREAD

**Issue by willcohen** [flipperdevices/flipperzero-firmware#2354]
Looking at trying to use the IR port to send files to an old [HP48GX](https://en.wikipedia.org/wiki/HP_48_series), and realizing that it should be able to work via [e-kermit](https://www.kermitproject.org/ek.html). Upon a little more reflection, the ability to natively send files/objects via kermit may be applicable for a large number of use cases -- see the [expansive](https://www.kermitproject.org/archive.html) list of platforms that have had kermit enabled over the decades, and there's a good chance that many applicable embedded devices have some kind of kermit protocol via many of the serial interfaces that Flipper has access to.

One option would be for me to begin work on a separate Kermit application that could handle these use cases, but before I go too far down that path I wanted to ask if there's any appetite for potentially adding `e-kermit` into the core firmware's `/lib` first. Rather than a separate app, I could try to add a new "Kermit" or "File Transfer" menu option to the Infrared app as a starting point, analogous to the existing remotes.

**Comment by skotopes** [comment]
That does sounds like idea for external application.

Also keep in mind that our infrared hardware is not IrDA compatible, so it's going to be quite painful to implement data exchange throw flipper's Infrared.
