### ISSUE TITLE
Flipper zero only uses the 1st edition of duckyscript for bad usb

### ISSUE THREAD

**Issue by Person-Who-Exists** [flipperdevices/flipperzero-firmware#2356]
### Description of the feature you're suggesting.

It would be really cool if any of you could find a way to implement 3rd edition duckyscript. This would be very useful since it is faster than 1st edition, and almost all the scripts that you can find online are for the 3rd edition. While it isn't to hard to port most scripts, some aren't possible.

**Comment by skotopes** [comment]
Ducky script is a proprietary product now. We don't plan to support it.
