### ISSUE TITLE
Add the possibility to set up a custom text on locked devices

### ISSUE THREAD

**Issue by auino** [flipperdevices/flipperzero-firmware#2364]
### Description of the feature you're suggesting.

I'd like to have the possibility to set up a custom text to show when the device is locked.
For instance, it may be useful to display contact information, in case the device is lost.

**Comment by skotopes** [comment]
I'll raise this topic internally to our UI/UX team.
And as for now leaving text file on SD Card with contacts will be easiest option.

**Comment by skotopes** [comment]
Also duplicate of #2243
