### ISSUE TITLE
Ergonomics of HID remote

### ISSUE THREAD

**Issue by willcohen** [flipperdevices/flipperzero-firmware#2371]
### Description of the feature you're suggesting.

Applicable for both USB and BT plugins — it’d be lovely if there could be a setting for something like “logical up” — where the arrow pad could be rotated 90, 180, or 270 degrees logically, depending on how the user were holding the flipper.

If the pad were rotated 90 degrees, for example, with a setting like “logical up: right”, then the right button would effectively be up, the down button would effectively be right, the left button would effectively be down, and the up button would effectively be left. This would make it so the remote for keynote and mouse and all non-keyboard remotes could be easily oriented so the device can be held with the keypad side of the flipper facing out, which feels more like a normal clicker. If a USB HID user wanted the cable sticking toward “up” this would make sense as well. Rotating so that the USB port were “down” (logical up: left) would also be useful for users who don’t want a USB sticking out in front of them and who would rather have it go to the back.

This seems like it would require having settings for the HID app to be saved somewhere, would require replacing all the directional key presses to call to a “logical_up” equivalent to pass the required rotated version, and, depending on the decisions on interface, would either just need the keypad GUIs to reflect the newly rotated key choices (simpler), or would need to rotate the GUI itself to be legible at the various rotations (more complex and not necessarily necessary).

**Comment by skotopes** [comment]
Possible, but going to cause some confusion. Also not all keyboards can be rotated easily and require redesign for it.
We are not planning to implement it, maybe someone from community will do.
