### ISSUE TITLE
Add clock to BT remote Keynote 

### ISSUE THREAD

**Issue by geks52** [flipperdevices/flipperzero-firmware#2396]
### Describe the enhancement you're suggesting.

I would like to see the clock in the application "BT remote Keynote"
I love this app!
Every evening I watch movies and use this application to change the sound volume and rewind.
Sometimes I forget what time it is, but in my hands only Flipper.

**Comment by skotopes** [comment]
Clock app is available as separate app. Embedding into BLE/USB remote sounds quite strange.
