### ISSUE TITLE
Pair bluetooth FZ with AndroidTV

### ISSUE THREAD

**Issue by Marcin84-dev** [flipperdevices/flipperzero-firmware#2406]
### Describe the enhancement you're suggesting.

Currently, when adding a bluetooth device to androidtv, the TV waits until the device enters the pairing state and unfortunately it does not find the device, is it possible to add such an option on FZ firmware?

**Comment by skotopes** [comment]
Are you using BLE remote?

**Comment by Ev3rPalestine** [comment]
That would have been a really cool feature to add. I wonder if its FZ bluetooth limitation or just needs additional work to be implemented
