### ISSUE TITLE
XP issue with ibutton app

### ISSUE THREAD

**Issue by itsweekly** [flipperdevices/flipperzero-firmware#2411]
### Describe the bug.

wrench 2/17/2023 - maybe it was smth else but i do remember one day i was playing around with it, checking the graphics i changed for reading stuff, never scanned anything but somehow got xp

This is an actual bug, i can't find the XP handler, I can fix it. im just blind.

### Reproduction

1. Open up ibutton
2. dont scan dont read, jsut play with the menu
3. you get XP

**Comment by gsurkov** [comment]
@itsweekly the user is supposed to get points for simply choosing the "Read" or "Emulate" options. There are also additional points given for each successful reading.
