### ISSUE TITLE
Avalanche transceiver

### ISSUE THREAD

**Issue by azaitsev** [flipperdevices/flipperzero-firmware#2412]
### Description of the feature you're suggesting.

Can flipper work on 457khz as avalanche transceiver? Or just as transmitter at least?
https://en.wikipedia.org/wiki/Avalanche_transceiver

**Comment by dogtopus** [comment]
Yes and no. It lacks the proper hardware to do so but you can always build your own hardware over GPIO and do pretty much anything via a custom plugin.

**Comment by skotopes** [comment]
In theory you can get 457khz on gpio with signal generator app. Other than that it is an idea for external module/app.
