### ISSUE TITLE
Badbutton detection for Somfy Telis remote

### ISSUE THREAD

**Issue by costimasca** [flipperdevices/flipperzero-firmware#2425]
### Describe the bug.

No matter what button I press on my Somfy Telis remote, Flipper will always detect the btn to be 0x0F.

### Reproduction

1. Go to SubGHZ
2. Go to Read
3. Set frequency to 433.42
4. Press a button on the Somfy Telis remote
5. Press another button on the Somfy Telis remote
6. Check the 2 decoded records - they will have the same code for the button

**Comment by Skorpionm** [comment]
No, it won't, the decoder was written from the original remote control, what is your remote control?  and what is the firmware

**Comment by skotopes** [comment]
@costimasca also can you provide recording of each button in RAW format?

**Comment by costimasca** [comment]
Firmware used: latest = 0.78.1

I've attached 2 buttons: up and down. 

More info:
When using normal Read, the counter and the key do increase on each button press. 
Still, no matter what button I press, the Btn value is 0x0F.

I've also attached a picture of the remote. Not sure if it's original or just Somfy compatible??


[Archive.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10870627/Archive.zip)
![somfy](https://user-images.githubusercontent.com/26381372/222412805-90b0c335-cc54-4100-8b35-682c68c04c04.jpeg)

**Comment by Skorpionm** [comment]
![image](https://user-images.githubusercontent.com/85568270/222539442-a2fb17b6-1603-43d2-9570-4df1c5a8ad34.png)

here is the original., I will look at your entries

**Comment by skotopes** [comment]
Please reopen if your issue is still there

**Comment by trueVinton** [comment]
Hi @skotopes, I am currently facing exactly the same issue described in this thread. Can we reopen it, please?

Additional context: I tried using "Add Manually" > Somfy Telis. In this case, I can see that pressing different buttons on Flipper sends different Btn codes. However, when I edit the previously created .sub file to adjust the remote SN and run it once again, it seems to break and only sends the Btn:0x0F value for any key pressed on the Flipper.
Let me know if you would like to see any diagnostic data.

**Comment by skotopes** [comment]
@Skorpionm wanna make 2nd take?
