### ISSUE TITLE
Unknown RFID (125 kHz) protocol support request

### ISSUE THREAD

**Issue by BinkyTheDoormat** [flipperdevices/flipperzero-firmware#2433]
### Description of the feature you're suggesting.

I've recently found an unidentified 125kHz RFID access card that looks like T5577 (and has some advertisement text on it yet nothing useful) that cannot be read both with Flipper and Proxmark. I was able to capture its contents in raw: 
[Sus_Card-raw.zip](https://github.com/flipperdevices/flipperzero-firmware/files/10833725/Sus_Card-raw.zip)

Could you please help me identify what this is (in case raw file has something useful on it) and tell if this protocol can be implemented in Flipper firmware?

**Comment by skotopes** [comment]
Are you sure that it is LF RFID? Also is it working properly?

**Comment by BinkyTheDoormat** [comment]
Almost 100% sure after I've investigated its guts with a flashlight. It works properly on an access control system it's designed for

**Comment by skotopes** [comment]
Also try to read it with NFC or Picopass app

**Comment by BinkyTheDoormat** [comment]
Tried already with no success

**Comment by skotopes** [comment]
ASK is empty, PSK doesn't contains valid data. Most likely it's not RFID. Try it with proxmark
