### ISSUE TITLE
gipo usb-uart bridge fails to work

### ISSUE THREAD

**Issue by Ethanol0001** [flipperdevices/flipperzero-firmware#2442]
### Describe the bug.

while trying to connect to a computer to your flipper using the gipo usb-utart bridge connection is able to read data but the computer is unable to recognize the flipper as a device this way 

### Reproduction

use a gipo to usb conversion tool to connect the flipper to, use male to female jumper cables and connect it appropriately to the converter, set the config on the flipper to match that of the device you are attempting to connect the flipper to.

### Target

Laptop USB via GIPO usb-utart connection

### Anything else?

The computer is able to detect something plugging into it but isn't registering it as a device. (will add debug logs here later when I get home and reattempt this)

**Comment by skotopes** [comment]
We still need logs. From your host operation system and flipper (at least till the moment of mode switch)

**Comment by skotopes** [comment]
Also versions of flipper firmware and host OS

**Comment by Ethanol0001** [comment]
not sure if there would even be any logs due to it only sending 1 byte of data to the computer when it detects power

**Comment by skotopes** [comment]
which port settings are you using?
