### ISSUE TITLE
Locking the Flipper does not turn off right away the display

### ISSUE THREAD

**Issue by ErSeraph** [flipperdevices/flipperzero-firmware#2453]
### Describe the bug.

Holding UP let you lock your Flipper (with PIN if already set), pressing a button displays a message, and after 1 second the display turn off every time until the unlock code or back 3 times are used.

Personally I use the no-PIN lock system every time, but I noticed that the display will not turn off the first time you lock the flipper, you have to wait seconds based on what you set in settings. This confuse me every time because I don't know if I locked it correctly, I know that there is an icon upper left but I wanted to warn about this.

### Reproduction

1. Lock your Flipper
2. Display does not turn off right away

**Comment by ErSeraph** [comment]
@andr0423 I think you referenced the wrong issue

**Comment by Ethanol0001** [comment]
are you talking about the animation that plays? Because the animation plays first before it locks. Also mind providing what version you are using such as release 0.78.1 or the release canadate?

**Comment by ErSeraph** [comment]
Sorry, I didn't thought that Im using a CF (Unleashed 33), but it's based on version 0.78.1. Im talking about that after you lock the flipper it will not turn off the screen, you have to wait 30 seconds or what you set in the "LCD and Notification" setting. Every time you press a button it say "To unlock press BACK BACK BACK" and turn off the display after one second, but not the first time. It's not a real problem but I have to check every time if I locked it correctly before putting in my pocket.

**Comment by andr0423** [comment]
> @andr0423 I think you referenced the wrong issue

Oh,  sorry for mistake.

**Comment by polarikus** [comment]
Is there a video?

Attach info about the firmware (Hold down for a long time, attach a screenshot of the photo with info).
I can't reproduce what is described on my flipper.

**Comment by ErSeraph** [comment]
I want to apologize to everyone, this issue is related to a custom firmware Im using and not to the official one, sorry for the mistake and wasting time.
