### ISSUE TITLE
furi_crash not report message after reboot when call in fap

### ISSUE THREAD

**Issue by polarikus** [flipperdevices/flipperzero-firmware#2471]
### Describe the bug.

When flipper reboot after crash - crash message don't show in desktop_scene_fault.
FW: 0.78.1

### Reproduction

1. Call furi_check(1 == 5) or furi_crash("Test/n/r") in code (I call in my FAP)

Expected Result:
Flipper rebooted and show message after reboot:
Title: "Flipper crashed
 and was rebooted"
Text: "furi_check failed\r\n" 

Actual Result: 
Flipper rebooted and show message after reboot:
Title: "Flipper crashed
 and was rebooted"

Text not show or showing trash ("%@ww1@$" or 
or similar)

### Logs
В консоли отображается корректно
furi_hal_console_puts(__furi_check_message);
[0;31m[CRASH][FN Tester] GGGGTst
	stack watermark: 3600
	     heap total: 182600
	      heap free: 129800
	 heap watermark: 119200
Rebooting system.

А вот после пререзагрузки ссобщения в регистре уже нет:
char* message = (char*)furi_hal_rtc_get_fault_data();
    FURI_LOG_D("desktop_scene_fault_on_enter", "%s", message);
    popup_set_text(popup, message, 60, 37 + STATUS_BAR_Y_SHIFT, AlignCenter, AlignCenter);
    popup_set_callback(popup, desktop_scene_fault_callback);
    view_dispatcher_switch_to_view(desktop->view_dispatcher, DesktopViewIdHwMismatch);
1191 [0;34m[D][desktop_scene_fault_on_enter] [0m

### Anything else?

Посмотрел по коду, похоже, что сообющение грузится из области памяти, ссылка на которую берется из RTC_BAK регистра. А поскольку ссылку на область памяти туда положила FAPка - в этой облости будет мусор после перезагрузки, так как fap не загружена в оперативку.

**Comment by skotopes** [comment]
yep, only messages from flash memory are valid. I'll check what we can do with it
