### ISSUE TITLE
description text field in application manifest 

### ISSUE THREAD

**Issue by suspicious-pineapple** [flipperdevices/flipperzero-firmware#2499]
### Description of the feature you're suggesting.

A field for some short description text in the .fam/application manifest.

Accessible from within flipper by selecting the App and long-pressing the center button. 

Either as a single page (limited length), or a full text viewer (markup?) with scrolling (Maybe not ideal, could tempt authors to bloat app size with plaintext).

Possible use cases:
- Instructions (GPIO pins, required hardware)
- Short tutorials for games
- Credits
- GitHub links (especially for Apps that came with a CFW, instead of being installed by the user)

Would make it easier for devs to include this information in simple Apps, without the overhead of adding a help page within the App's code.

And it would improve user experience by making some applications less "cryptic".

**Comment by hedger** [comment]
We're planning to add application details to app catalog, that's currently WIP.

**Comment by suspicious-pineapple** [comment]
nice!
(is there a list of currently WIP things somewhere?)

**Comment by hedger** [comment]
So, now we have fap_description in application manifests, and [minimal markdown support](https://github.com/flipperdevices/flipper-application-catalog/blob/main/documentation/Manifest.md#loading-values-from-files) for apps submitted to app catalog.
