### ISSUE TITLE
Increased power consumption after disconnecting GPIO module

### ISSUE THREAD

**Issue by 123jjck** [flipperdevices/flipperzero-firmware#2501]
### Describe the bug.

My Flipper's default power consumption is 9 mA. 
After connecting and disconnecting ESP32-WROOM to GPIO (3.3V, GND, TX and RX), the consumption becomes 2-3 mA more, i.e. 11-12 mA and does not drop until the Flipper reboot.
5V on GPIO is off

### Reproduction

1. Connect ESP32-WROOM to Flipper (i use [that ](https://github.com/UberGuidoZ/Flipper/blob/main/GPIO/ReadMe.md#esp32--esp32-wroom-pinout-to-flipper-zero)pinout)
2. Disconnect
3. Check power consumption

**Comment by skotopes** [comment]
Most likely this caused by SD-Card being reseted by power glitch on connect/disconnect. Try without SD Card.

**Comment by 123jjck** [comment]
> Try without SD Card

Doesn't help, same problem.

**Comment by skotopes** [comment]
Caused by USART subsystem waiting for someone to get data from RX pipe.
