### ISSUE TITLE
Launching external FAPs from the serial CLI

### ISSUE THREAD

**Issue by str4d** [flipperdevices/flipperzero-firmware#2502]
The `loader` CLI can be used to run applications that are built into the firmware. However, it does not appear to be possible to run applications built as external FAPs. When such an application is running, the CLI reports:
```
> loader info
Running application: Applications
```
and opening the FAP directly doesn't work:
```
> loader open /path/to/the.fap
/path/to/the.fap doesn't exist
```

It would be useful to be able to run external FAPs via the serial CLI, and be able to provide them arguments. If this is already possible and I just haven't found out how, it would be useful to update the documentation to explain how to achieve this.

**Comment by DrZlo13** [comment]
You can use `loader open Applications /path/to/the.fap`

**Comment by str4d** [comment]
Yay, thanks! I've confirmed this works, so it just needs to be documented. IDK if there's a nice way to expose the application arguments inside the `loader` CLI?

It also doesn't appear to support arguments? `loader open Applications /path/to/the.fap arg` results in the `Applications` app running and displaying:
```
Error
Preload failed
Invalid file
```

**Comment by hedger** [comment]
Passing arguments to .fap files is not supported at the moment. You can create a separate issue on that.

**Comment by str4d** [comment]
> Passing arguments to .fap files is not supported at the moment. You can create a separate issue on that.

Done: #2505.
