### ISSUE TITLE
Upside down screen in qflipper and Flipper Lab when using lefty mode

### ISSUE THREAD

**Issue by Milk-Cool** [flipperdevices/flipperzero-firmware#2510]
### Describe the bug.

When using lefty mode, the screen display in qflipper is upside down.

![image](https://user-images.githubusercontent.com/43724263/226088385-79007461-3de3-4286-a667-0523543c28d5.png)

### Reproduction

1. Eanble lefty mode in settings
2. Connect you flipper to a comouter
3. Install and open qflipper

### Target

Flipper Zero FZ.1 firmware version 0.79.1 with lefty mode enabled

**Comment by team-orangeBlue** [comment]
Feature in mobile app too.. telegram agrees
![image](https://user-images.githubusercontent.com/63470411/226088608-90cc5342-4a3a-46b7-a1b7-6b630c3b2444.png)

**Comment by skotopes** [comment]
Yep, we are working on it

**Comment by skotopes** [comment]
Should be fixed in all companion apps

**Comment by pyrophreak** [comment]
There is a Feature in Xtreme Firmware if your screen is flipped in the settings  menu there are 2 arrows in a circle that give you the option to flip it back and forth.
