### ISSUE TITLE
"str.replace is not a function" when running "Attach FW (blackmagic)" in VS Code

### ISSUE THREAD

**Issue by xouabita** [flipperdevices/flipperzero-firmware#2514]
### Describe the bug.

When running "Attach FW (blackmagic)" from VS Code, it ends up with "str.replace is not a function"

### Reproduction

1. After cloning I ran `./fbt` then `./fbt vscode_dist`
2. From VS code, Ran "[Debug] Flash (blackmagic)" and "[Debug] Build"
3. Try to run "Attach FW (blackmagic)"

![Sun 19 Mar 16:45:57 GMT 2023](https://user-images.githubusercontent.com/1368129/226192485-a75e5228-beff-42ce-a10c-0a5f11d9005d.png)

4. Ended up with "str.replace is not a function" error:

![Sun 19 Mar 16:46:06 GMT 2023](https://user-images.githubusercontent.com/1368129/226192506-b9517244-0a51-48f5-a7b9-91e1250f5bae.png)

### Anything else?

Is there anything I am doing wromg ? Anyone succeeded at debugging with VS Code using blackmagic probe ?

I think the issue could be in: https://github.com/Marus/cortex-debug

**Comment by hedger** [comment]
Please check with latest VSCode config, re-open if you have any issues.
