### ISSUE TITLE
Broken "OK" button on "Mounting SD card failed" screen

### ISSUE THREAD

**Issue by ValdikSS** [flipperdevices/flipperzero-firmware#2515]
### Describe the bug.

"OK →" button on "Mounting SD card failed" screen does not do anything. The screen does not disappear when pressing → D-pad on said screen, while all other buttons work fine.

### Reproduction

1. Insert completely blank MicroSD card (no partition layout) while Flipper is powered off
2. Power Flipper on
3. See "Mouting SD card failed" screen with "OK →" button
4. Press → D-pad button
5. Nothing happens. The screen does not disappear.

### Target

0.79.1

**Comment by Banditwon** [comment]
Did you figure out the issue?

**Comment by ValdikSS** [comment]
I've partitioned the card and created the file system on a PC. I didn't fix the bug.

**Comment by Banditwon** [comment]
Okay, thanks I will try that out.I was using the GPIO then all off a sudden it stopped working. I received that error message, now I can't update the flipper to a different firmware because I can't mount the sd card.

**Comment by tudorsss** [comment]
Happens for me too

**Comment by dralpine** [comment]
While updating my Flipper, I have same problem. No SD-Card is working, also the working SD-Card before updating with fresh formating FAT32.
Settings  > Storage > Mount SD Card > Unmount: The LED blinks a short time Green,
Settings > Storage > Mount SD Card > Mount: The LED The LED blinks 10x a long time purple and blinking 3x short red.
Then the Screen shows "Cannot Mount SD Card" "internal error"
Is there a solution for this problem?

There are more people, who have this issue:
https://www.reddit.com/r/flipperzero/comments/175x2t5/flipper_wont_mount_sd_card/

**Comment by Banditwon** [comment]
I gave up on customer support and just got another one.

**Comment by skotopes** [comment]
> I gave up on customer support and just got another one.

can you send me your ticket number?

For anyone who will have any issues with SD card please start here: https://docs.flipper.net/basics/sd-card

**Comment by ValdikSS** [comment]
@skotopes there aren't issues with the card, the bug is in firmware code.

**Comment by skotopes** [comment]
You can not skip Mounting SD Failed animation if such SD card is inserted. 
From the code perspective it's more a feature than a bug: system can not function properly if card failed to mount.
We'll remove OK button in next release.

**Comment by skotopes** [comment]
Fixed in  #3776
