### ISSUE TITLE
LCD Backlight off when using phone control

### ISSUE THREAD

**Issue by xhd4** [flipperdevices/flipperzero-firmware#2535]
### Description of the feature you're suggesting.

Turn off the backlight of the display when controlled from the phone. Is it possible to implement a function to turn off the backlight of the flipper screen when using phone control? But at the same time, the backlight will turn on after using the keys of the flipper itself. And add this setting as an item in Settings -> LCD and Notifications

**Comment by skotopes** [comment]
And use cases are?

**Comment by xhd4** [comment]
This LCD backlight turning on every time you use the remote control in the evening flipperzero and attracts the attention of others. All the more quickly drains the battery. It is also strange to turn on the backlight of the flipper, which is lying in the pocket, and the control is done through the phone.

**Comment by xhd4** [comment]
accidentally closed

**Comment by xhd4** [comment]
accidentally closed

**Comment by skotopes** [comment]
After some thought this feature looks quite niche and complex in implementation to make it right. So I'll close this issue.
