### ISSUE TITLE
Mifare Classic Write Support

### ISSUE THREAD

**Issue by optimus10ro** [flipperdevices/flipperzero-firmware#2542]
### Description of the feature you're suggesting.

I want to be able to read a tag and write it on other NFC tags, I could copy my gate key, and other stuff.

**Comment by AloneLiberty** [comment]
If you want to copy your tag to new tag, you will need tag that can change UID - Magic Gen1 tag. https://docs.flipperzero.one/nfc/magic-cards

**Comment by optimus10ro** [comment]
I want to be able to write saved cards

**Comment by AloneLiberty** [comment]
If you want to update data on your card from data that saved on Flipper you can use "Write to initial card" 
If you want to write saved data to new card you must use gen1 with Nfc magic app (other types of magic cards aren't supported yet). There is no way to change UID on regular MFC cards

**Comment by optimus10ro** [comment]
No like, i read a mifare classic, and i write on another blank one

**Comment by AloneLiberty** [comment]
If you want to write to another card you must use gen1 magic tag. Read docs for more details https://docs.flipperzero.one/nfc/magic-cards

**Comment by optimus10ro** [comment]
O want to write the data to another card, like create another key that has the same data

**Comment by skotopes** [comment]
> O want to write the data to another card, like create another key that has the same data

Normal cards doesn't allow to write block 0.

If it's ok, then dump new card, then copy blocks from old dump to new, then write new dump to new card
