### ISSUE TITLE
SPI Mem Manager Write Protection

### ISSUE THREAD

**Issue by LupMhee** [flipperdevices/flipperzero-firmware#2545]
### Describe the bug.

Can't write or erase with write protection IC.

### Reproduction

write or erase with write protection IC.

**Comment by Ethanol0001** [comment]
we need more details in the report, just saying write or erase doesn't help. Add a more detailed description along with a step by step guide on how to reproduce it, along with adding the logs for the bug too.

**Comment by dogtopus** [comment]
Did you pull the write protect pin up?

**Comment by LupMhee** [comment]
When you set "SRWD bit (Status Register Write Disable)" e.g. 0x9C, 0x8C, 0xFC, you can't write or erase.
normally it must be set 0x00 (Unprotect) before write or erase.
![Screenshot (162)](https://user-images.githubusercontent.com/24663208/228578711-2649cbf9-98a9-40de-ab67-e99e36fe472e.png)

**Comment by skotopes** [comment]
This is quite challenging task: different vendors got different ways of unlocking write access. Implementing it will require to do per vendor/chip analysis.

We'll accept PRs but not going to implement it by our self.
