### ISSUE TITLE
Read and emulate magstrip cards

### ISSUE THREAD

**Issue by rhysperry111** [flipperdevices/flipperzero-firmware#2556]
### Description of the feature you're suggesting.

I'm particularly interested in using the Flipper Zero to read and emulate magnetic stripe cards as I manage a building that uses them, and it would be useful to be able to test and store many cards.

I have seen [this post](https://habr.com/en/company/flipperdevices/blog/595325/) suggest it's possible with the 125KHz antenna out of the box, and the general idea of how it works can be seen in [MagSpoof](https://samy.pl/magspoof/). It also seems that there's a [similar feature request](https://github.com/DarkFlippers/unleashed-firmware/issues/193) for DarkFlipper's unleashed-firmware. If this does just work out of the box, it would be useful to know the best way of doing it and possibly mention it in the wiki. If it would be more practical to have this implemented separately as a new feature, that would be nice to see too.

Sadly I don't have much development experience, and I'm still waiting for my Flipper Zero in the mail, so I can't test it myself, but I'd be happy to help in any way I could.

**Comment by skotopes** [comment]
There is an implementation that was made 2 years ago for hackathon. Shouldn't take much time to port it for new firmware.

**Comment by rhysperry111** [comment]
The one from the hackathon used an external antenna. Should this issue not stay open until something is implemented?

**Comment by skotopes** [comment]
They told me that they've tested internal one too, also was working.

**Comment by skotopes** [comment]
Regarding closing issue: this sounds more like an idea for community project, so we are not planning to implement it.
