### ISSUE TITLE
Changing the size of address and command in struct InfraredMessage

### ISSUE THREAD

**Issue by achistyakov** [flipperdevices/flipperzero-firmware#2557]
### Describe the enhancement you're suggesting.

Is it possible to add the ability to support other IR protocols, such as Mitsubishi:
https://github.com/r45635/HVAC-IR-Control/blob/master/Protocol/Mitsubishi_IR_Packet_Data_v1.1-FULL.pdf

The length of his command is 18 bytes, and in the current implementation, due to the size of address and command in the InfraredMessage struct, this is impossible.

> lib/infrared/encoder_decoder/infrared.h
```
 typedef struct {
     InfraredProtocol protocol;
     uint32_t address;
     uint32_t command;
     bool repeat;
 } InfraredMessage;
```

**Comment by gsurkov** [comment]
Unfortunately, this would require too much work (for example, all of the existing protocol implementations will have to be rewritten). 

Viable alternatives to it would be either using the RAW mode or implementing a separate application for these kinds of remotes.
