### ISSUE TITLE
Adding new protocols/modulation-schemes to FW

### ISSUE THREAD

**Issue by nickyg543** [flipperdevices/flipperzero-firmware#2564]
### Describe the enhancement you're suggesting.

I'm looking for the correct place to add new protocols/modulations as defaults. For example, my Mazda 3 uses +/- 50 FSK centered at 315MHz (I know I can get close enough to this with the existing, but just as an example). Another example could be any SubGHz remote someone has debugged on a spectrum analyzer with analog demod. 

I know "firmware/targets/f7/furi_hal/furi_hal_subghz_configs.h" contains different radio configurations, and I'm confident I can fork one and edit it to contain any arbitrary protocol (within reason). My question is will this "propagate upwards"? If I add this protocol, will it become available in the list on my flipper? I'm assuming it will not. Where is the file in which I can add/name a new protocol to the default list?

With a clear method of adding new protocols, people can go out into the wild and add all sorts of interesting stuff.

### Anything else?

Any additional notes on playing with radio configs is greatly appreciated

**Comment by hedger** [comment]
You can add radio presets without modifying the main firmware. See https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/file_formats/SubGhzFileFormats.md#subghz-configuration-files.

However, to add a new decodable protocol, you currently have to implement it as a part of main firmware. We're planning to add support for externally-defined protocols and include an example with the firmware, but no ETAs on that.
