### ISSUE TITLE
0.81.0-rc: AVR programmer app crashes device on retry

### ISSUE THREAD

**Issue by henryjeynes** [flipperdevices/flipperzero-firmware#2573]
### Describe the bug.

Device crashes and reboots upon retrying Dump, Flash, or ISP Programmer functions of AVR programmer: "NULL pointer dereference"

### Reproduction

1. Update to 0.81.0-rc
2. Open AVR programmer with no microcontroller connected
3. Select Dump, Flash, or ISP programmer
4. Press left to retry

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/2574
check

**Comment by skotopes** [comment]
Fixed in dev and 0.81.1-rc
