### ISSUE TITLE
Set modulation via CLI

### ISSUE THREAD

**Issue by Crsarmv7l** [flipperdevices/flipperzero-firmware#2582]
### Description of the feature you're suggesting.

Request the addition of setting standard modulations (AM270, AM650, FM476, etc) via cli.

Serial cli allows for both receive and transmit, it makes sense to allow the user to set the modulation in a similar way.

Such added capability when used in conjunction with a project such as this: https://github.com/wh00hw/pyFlipper
Would allow users to utilize python scripts to more completely control flipper subghz.

**Comment by skotopes** [comment]
SubGhz cli interface originally was designed for testing and it lacks ability to extend it. Adding preset option will not be enough. We may revisit this topic later, meanwhile I'll close this issue.
