### ISSUE TITLE
disabling EMV support allowed UID emulation

### ISSUE THREAD

**Issue by suspicious-pineapple** [flipperdevices/flipperzero-firmware#2585]
### Describe the bug.

UID of unknown tags can be emulated, bank cards are now unknown tags.

### Reproduction

1. read bank card nfc
2. save or emulate

### Target

RC 0.81.1

### Anything else?

Before the recent update you could read bank cards, but not save/emulate them, which gave people an indication of what was going on/that it can't work.

now, you can try to save+emulate bank card UIDs, and then wonder why it doesn’t work.

possible solution: keep EMV support internally, so that they can be recognised + ignored by the firmware when detected.

**Comment by skotopes** [comment]
UID emulation without EMV part is not going to harm anyone. So it's ok.
