### ISSUE TITLE
(another) unknown RFID (125 kHz) protocol

### ISSUE THREAD

**Issue by hhenne1** [flipperdevices/flipperzero-firmware#2586]
### Description of the feature you're suggesting.

I stumbled across an RFID bracelet that would not be recognised.
Neither RFID, Picopass nor NFC showed any results.
Only the RAW recording function of the RFID app seems to have read something (40kb ask.raw, 256kb psk.raw).
Visually, it looked like an RFID chip, black housing without any labelling, used for small lockers and entry systems.
Since I have no experience with analysing RAW data like this, I thought maybe this would help or someone has a suggestion.
[RFID_RAW.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11237747/RFID_RAW.zip)

### Anything else?

thx for all the fiddling around fun and keep it up ♥

**Comment by Astrrra** [comment]
Hi! I've looked at the RAW recordings, they all seem to be random noise. Can you please try recording it once again? Make sure to place your flipper on the tag before starting the recording, and that you're doing it on a non-magnetic surface (something like a wooden desk).

Also, what's the name of the system? I've seen OLantis in the files, but I couldn't find any info on them online. Do you have any additional information? It can greatly help us :)
