### ISSUE TITLE
BadUSB large string crash Flipper Zero

### ISSUE THREAD

**Issue by Leptopt1los** [flipperdevices/flipperzero-firmware#2594]
### Describe the bug.

Trying to execute a BadUSB script containing ALTSTRING that prints a very long line causes "Flipper crashed and was rebooted. furi_check failed". F.E: Attached is a file that prints base64 of xz archive of approximately 470 kb to a .txt file

### Reproduction

1. Upload crash.txt to /ext/badusb
2. Execute it
3. It crash

### Target

FZ.1 0.81.1

### Anything else?

[crash.txt](https://github.com/flipperdevices/flipperzero-firmware/files/11264549/crash.txt)

**Comment by hedger** [comment]
Flipper reads and executes BadUSB scipts line-by-line. A line that long cannot fit into Flipper's memory - since there are only ~100K free when BadUSB is running.

Workarounds for that won't be implemented on firmware side.
