### ISSUE TITLE
Flipper cannot update sector trailers on Mifare Classic 1k

### ISSUE THREAD

**Issue by kulverstukas1** [flipperdevices/flipperzero-firmware#2597]
### Describe the bug.

I noticed this what I think is a bug.
I tried with a blank regular Mifare Classic 1k 4 byte UID card with factory keys and factory access bits.

I wrote everything down in the forums but I'm also posting here for more exposure (prolly should of posted here in the first place though)
https://forum.flipperzero.one/t/flipper-cannot-update-sector-trailers-on-mifare-classic-1k/15128

Maybe someone can confirm that this is really a bug?

### Reproduction

1. Read and Save the card dump
2. Edit dump with Flipper Android app
3. Save and synchronize (also verify on the Flipper itself that the file is modified)
4. Write to Initial card
5. Read and see that the keys haven't changed

### Target

NFC / Mifare Classic 1k

**Comment by Crsarmv7l** [comment]
AFAIK, you can only write to a Magic Mifare gen1a, not a regular "blank"

**Comment by kulverstukas1** [comment]
"Magic" cards differ from regular in a way that you can change the UID.

**Comment by Astrrra** [comment]
Yes, the "Write to initial card" feature assumes that the keys remain the same (otherwise the complexity grows very significantly), so it won't be able to reflect the key changes.

You can use the NFC Magic app to write arbitrary data to cards, though only the Magic cards are supported for that.
