### ISSUE TITLE
Generate file names that actually make sense

### ISSUE THREAD

**Issue by kulverstukas1** [flipperdevices/flipperzero-firmware#2598]
### Describe the enhancement you're suggesting.

Good day,
I'd like to suggest to have a setting to generate more sensible file names for NFC, Sub-GHz, etc. because right now naming all the files something like Thin_burov or Thick_aptheca is fun but becomes confusing when you're doing a bunch of NFC scans of the same card in a short time period, for example. More so when I can't see the file creation date (if one exists) in qFlipper and order by one.

I propose a naming scheme like so:
Someword_YY_MM_DD
NFC_YY_MM_DD
Or for the date maybe follow the date format set in the settings already.

**Comment by skotopes** [comment]
Original schema is a kinda part of the flipper lore, but we'll think about it.

**Comment by kulverstukas1** [comment]
Yes, I understand and respect that, it's quite fun. However not very useful in the long run :P if (q)Flipper could show file creation times it would be less of a problem, though still datetime would be nice.

**Comment by skotopes** [comment]
Fixed in #3002
