### ISSUE TITLE
another unknown RFID

### ISSUE THREAD

**Issue by VxTedxV** [flipperdevices/flipperzero-firmware#2600]
### Description of the feature you're suggesting.

Hi, as described in the new documentation, here is :
- ask file
- psk file
- photo of the card
... all in the [Archive.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11289258/Archive.zip) file

Thanks a lot for all your efforts !

**Comment by skotopes** [comment]
ASK file is empty, PSK - no meaningful data. Do you have proxmark?

**Comment by VxTedxV** [comment]
no :'(

**Comment by Astrrra** [comment]
Can you try recording the signal once again? Make sure to place the Flipper on the tag before starting the recording, and do it on a non-magnetic surface (like a wooden desk).

**Comment by VxTedxV** [comment]
Thanks again to investigate :)
Here is another raw recording of the card.
[Archive.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11680062/Archive.zip)
Note : I use this card almost everyday at work without issue.

**Comment by Astrrra** [comment]
Hi! I've looked at the new files, and they're still only containing random noise, no signal in sight. It seems that this card is either not 125kHz, or is an active card, which Flipper can't read and emulate. In any case, there's nothing we can do with those files, unfortunately.

**Comment by VxTedxV** [comment]
Thanks ! Still interesting.

**Comment by VxTedxV** [comment]
@Astrrra 
I think it's not an active card : slim, very short range, at least 3 years lifetime for now.
I tried the "NFC/RFID detector" app (video below). It says LF RFID and in less than 2 sec, shows 94.21 kHz and then multiple frequencies near 99 kHz, and finally 102.42 kHz.
Any clue to understand better ?

https://github.com/flipperdevices/flipperzero-firmware/assets/30288828/55e81cfc-4d64-4323-b9be-74407a42aec6

**Comment by skotopes** [comment]
https://www.idmanagement.com/id-cards/rfid-cards/cotag
https://www.proxmark.io/www.proxmark.org/forum/viewtopic.php%3Fid=1258.html

We do not support them currently, but proxmark got some kind of support. We may port it in future.

**Comment by skotopes** [comment]
Or maybe someone from community will do it first ;-)
