### ISSUE TITLE
Unknown RFID Card

### ISSUE THREAD

**Issue by alexdotpink** [flipperdevices/flipperzero-firmware#2602]
### Description of the feature you're suggesting.

I found an RFID card that can only be read using Read Raw.
Here's the files:
https://file.io/CGPgwW20cUxz

**Comment by EvanCarroll** [comment]
I'm guessing this isn't actionable as it has link rot? Maybe it can be closed?

**Comment by Astrrra** [comment]
Yes, please upload the files directly to the issue for them to not expire. I'll close this issue for now, you can open a new one if you need to.
