### ISSUE TITLE
 Adding a Wendox Weather Station Protocol

### ISSUE THREAD

**Issue by 0z0nize** [flipperdevices/flipperzero-firmware#2603]
### Describe the enhancement you're suggesting.

Hi, it would be great to add the Wendox protocol to the weather_station application. 
[Wendox_raw_ref_6729.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11301026/Wendox_raw_ref_6729.zip)
Data from the sensor and photo attached. 
Ready to add any information if needed
Thank you.

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/2604
check

**Comment by 0z0nize** [comment]
Need action on my part?

**Comment by doomwastaken** [comment]
@0z0nize yeah, could you checkout code from https://github.com/flipperdevices/flipperzero-firmware/pull/2604 and check whether implementation of Wendox protocol is working

**Comment by 0z0nize** [comment]
Thank you! Hope I did right thing 🙂
