### ISSUE TITLE
flipper zero can't build fw

### ISSUE THREAD

**Issue by UnsavorySpirit** [flipperdevices/flipperzero-firmware#2606]
### Describe the bug.

hi, when trying to compile my fw firmware i got this error
build\f7-firmware-D\applications\applications.c:188:15:` error: 'A_BadKb_14' undeclared here (not in a function); did you mean 'A_BadUsb_14'?
  188 |      .icon = &A_BadKb_14,
      |               ^~~~~~~~~~
      |               A_BadUsb_14
scons: *** [build\f7-firmware-D\applications\applications.o] Error 1
In file included from applications\main\bad_kb\scenes\bad_kb_scene_config.c:1:
applications\main\bad_kb\scenes\../bad_kb_app.h:24:33: error: 'FURI_HAL_BT_ADV_NAME_LENGTH' undeclared here (not in a function); did you mean 'FURI_HAL_VERSION_NAME_LENGTH'?
   24 | #define BAD_KB_ADV_NAME_MAX_LEN FURI_HAL_BT_ADV_NAME_LENGTH
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
applications\main\bad_kb\scenes\../bad_kb_app.h:39:18: note: in expansion of macro 'BAD_KB_ADV_NAME_MAX_LEN'
   39 |     char bt_name[BAD_KB_ADV_NAME_MAX_LEN + 1];
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
applications\main\bad_kb\scenes\bad_kb_scene_config.c:4:10: fatal error: xtreme/settings.h: No such file or directory
    4 | #include <xtreme/settings.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [build\f7-firmware-D\applications\main\bad_kb\scenes\bad_kb_scene_config.o] Error 1
In file included from applications\main\bad_kb\scenes\bad_kb_scene_config_layout.c:1:
applications\main\bad_kb\scenes\../bad_kb_app.h:24:33: error: 'FURI_HAL_BT_ADV_NAME_LENGTH' undeclared here (not in a function); did you mean 'FURI_HAL_VERSION_NAME_LENGTH'?
   24 | #define BAD_KB_ADV_NAME_MAX_LEN FURI_HAL_BT_ADV_NAME_LENGTH
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
applications\main\bad_kb\scenes\../bad_kb_app.h:39:18: note: in expansion of macro 'BAD_KB_ADV_NAME_MAX_LEN'
   39 |     char bt_name[BAD_KB_ADV_NAME_MAX_LEN + 1];
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
scons: *** [build\f7-firmware-D\applications\main\bad_kb\scenes\bad_kb_scene_config_layout.o] Error 1
In file included from applications\main\archive\views\archive_browser_view.c:1:
build\f7-firmware-D\assets\compiled/assets_icons.h:46:19: error: redundant redeclaration of 'I_Clock_18x18' [-Werror=redundant-decls]
   46 | extern const Icon I_Clock_18x18;
      |                   ^~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:37:19: note: previous declaration of 'I_Clock_18x18' was here
   37 | extern const Icon I_Clock_18x18;
      |                   ^~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:47:19: error: redundant redeclaration of 'I_Error_18x18' [-Werror=redundant-decls]
   47 | extern const Icon I_Error_18x18;
      |                   ^~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:38:19: note: previous declaration of 'I_Error_18x18' was here
   38 | extern const Icon I_Error_18x18;
      |                   ^~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:48:19: error: redundant redeclaration of 'I_EviSmile1_18x21' [-Werror=redundant-decls]
   48 | extern const Icon I_EviSmile1_18x21;
      |                   ^~~~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:39:19: note: previous declaration of 'I_EviSmile1_18x21' was here
   39 | extern const Icon I_EviSmile1_18x21;
      |                   ^~~~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:49:19: error: redundant redeclaration of 'I_EviSmile2_18x21' [-Werror=redundant-decls]
   49 | extern const Icon I_EviSmile2_18x21;
      |                   ^~~~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:40:19: note: previous declaration of 'I_EviSmile2_18x21' was here
   40 | extern const Icon I_EviSmile2_18x21;
      |                   ^~~~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:50:19: error: redundant redeclaration of 'I_EviWaiting1_18x21' [-Werror=redundant-decls]
   50 | extern const Icon I_EviWaiting1_18x21;
      |                   ^~~~~~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:41:19: note: previous declaration of 'I_EviWaiting1_18x21' was here
   41 | extern const Icon I_EviWaiting1_18x21;
      |                   ^~~~~~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:51:19: error: redundant redeclaration of 'I_EviWaiting2_18x21' [-Werror=redundant-decls]
   51 | extern const Icon I_EviWaiting2_18x21;
      |                   ^~~~~~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:42:19: note: previous declaration of 'I_EviWaiting2_18x21' was here
   42 | extern const Icon I_EviWaiting2_18x21;
      |                   ^~~~~~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:52:19: error: redundant redeclaration of 'I_Percent_10x14' [-Werror=redundant-decls]
   52 | extern const Icon I_Percent_10x14;
      |                   ^~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:43:19: note: previous declaration of 'I_Percent_10x14' was here
   43 | extern const Icon I_Percent_10x14;
      |                   ^~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:53:19: error: redundant redeclaration of 'I_Smile_18x18' [-Werror=redundant-decls]
   53 | extern const Icon I_Smile_18x18;
      |                   ^~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:44:19: note: previous declaration of 'I_Smile_18x18' was here
   44 | extern const Icon I_Smile_18x18;
      |                   ^~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:54:19: error: redundant redeclaration of 'I_UsbTree_48x22' [-Werror=redundant-decls]
   54 | extern const Icon I_UsbTree_48x22;
      |                   ^~~~~~~~~~~~~~~
build\f7-firmware-D\assets\compiled/assets_icons.h:45:19: note: previous declaration of 'I_UsbTree_48x22' was here
   45 | extern const Icon I_UsbTree_48x22;
      |                   ^~~~~~~~~~~~~~~
applications\main\bad_kb\helpers\ducky_script.c: In function 'bt_remote_rssi_range':
applications\main\bad_kb\helpers\ducky_script.c:38:9: error: implicit declaration of function 'bt_remote_rssi'; did you mean 'bt_remote_rssi_range'? [-Werror=implicit-function-declaration]
   38 |     if(!bt_remote_rssi(bt, &rssi)) return LevelRssiError;
      |         ^~~~~~~~~~~~~~
      |         bt_remote_rssi_range
applications\main\bad_kb\helpers\ducky_script.c: In function 'ducky_numlock_on':
applications\main\bad_kb\helpers\ducky_script.c:119:13: error: implicit declaration of function 'furi_hal_bt_hid_get_led_state'; did you mean 'furi_hal_hid_get_led_state'? [-Werror=implicit-function-declaration]
  119 |         if((furi_hal_bt_hid_get_led_state() & HID_KB_LED_NUM) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             furi_hal_hid_get_led_state
applications\main\bad_kb\helpers\ducky_script.c: In function 'bad_kb_worker':
applications\main\bad_kb\helpers\ducky_script.c:513:28: error: implicit declaration of function 'furi_hal_bt_is_connected'; did you mean 'furi_hal_hid_is_connected'? [-Werror=implicit-function-declaration]
  513 |                         if(furi_hal_bt_is_connected()) {
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~
      |                            furi_hal_hid_is_connected
cc1.exe: all warnings being treated as errors
In file included from applications\main\bad_kb\helpers\ducky_script.c:12:
applications\main\bad_kb\helpers\ducky_script.c:554:30: error: 'DolphinDeedBadKbPlayScript' undeclared (first use in this function); did you mean 'DolphinDeedBadUsbPlayScript'?
  554 |                 DOLPHIN_DEED(DolphinDeedBadKbPlayScript);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
applications\services/dolphin/dolphin.h:32:31: note: in definition of macro 'DOLPHIN_DEED'
   32 |         dolphin_deed(dolphin, deed);                              \
      |                               ^~~~
applications\main\bad_kb\helpers\ducky_script.c:554:30: note: each undeclared identifier is reported only once for each function it appears in
  554 |                 DOLPHIN_DEED(DolphinDeedBadKbPlayScript);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
applications\services/dolphin/dolphin.h:32:31: note: in definition of macro 'DOLPHIN_DEED'
   32 |         dolphin_deed(dolphin, deed);                              \
      |                               ^~~~
cc1.exe: all warnings being treated as errors
scons: *** [build\f7-firmware-D\applications\main\archive\views\archive_browser_view.o] Error 1
scons: *** [build\f7-firmware-D\applications\main\bad_kb\helpers\ducky_script.o] Error 1

********** FBT ERRORS **********
build\f7-firmware-D\applications\applications.o: Error 1
build\f7-firmware-D\applications\main\bad_kb\scenes\bad_kb_scene_config.o: Error 1
build\f7-firmware-D\applications\main\bad_kb\scenes\bad_kb_scene_config_layout.o: Error 1
build\f7-firmware-D\applications\main\archive\views\archive_browser_view.o: Error 1
build\f7-firmware-D\applications\main\bad_kb\helpers\ducky_script.o: Error 1

I'm trying to pass the badkb feature from xtreme to unleashed

### Reproduction

./fbt

**Comment by hedger** [comment]
Try reproducing the build issue on stock firmware.

Your logs look like there's a problem with your code, not the firmware itself.
