### ISSUE TITLE
[Multitask] Run apps in background

### ISSUE THREAD

**Issue by fred-corp** [flipperdevices/flipperzero-firmware#2610]
### Describe the enhancement you're suggesting.

Wouldn't it be great to be able to run apps in background ?

Here's how it could work : For example, when using the POCSAG app (pager app which uses the SubGHz radio), hold "back" button for 5s, a prompt would appear to exit the app or to run in background; if an application runs in background, press 5s on the back button, a prompt appears to go back to the app or to exit it. When you go back to the app, if you were using another app, that app would go to background.
If you want to run an app that uses the same ressources as the background app (for example POCSAG is in background and you want to use SubGHz), a prompt appears where you can select to kill/pause the background app, go back to it, or do nothing (dismiss prompt and don't open the new app)

**Comment by hedger** [comment]
Flipper is designed for running only a single application at a time. Allowing multiple ones would lead to conflicts for resources - imagine running POCSAG app in the background and loading a Weather Station or SubGhz app at the same time. 

That's the most obvious case. There are multiple subsystems that are designed for being used by a single app at a time, without a proper way to share access with other apps.
