### ISSUE TITLE
PicoPass: Elite Dict.Attack with no card present

### ISSUE THREAD

**Issue by doomwastaken** [flipperdevices/flipperzero-firmware#2612]
### Describe the bug.

Starting the attack promts you with "Lost the tag!" menu, additionally if you press "Skip", you get "Read Failed" with text not fitting in the screen. 

### Reproduction

No card next to flipper. 

**Steps:**
- Open PicoPass
- Elite Dict.Attack
- "Lost the tag!"
- [Optional] Skip
- Text overflow

**Expected behavior:** 
1. Promt for card placement
2. Text either scrolling / compact view / overflow to second line

![Screenshot-20230425-164432](https://user-images.githubusercontent.com/72250702/234296329-c2f7571c-ee74-42c2-aafd-582e5cb20c95.png)
![Screenshot-20230425-164417](https://user-images.githubusercontent.com/72250702/234296336-76154880-ec02-41a0-b306-f975a07d7b82.png)

### Target

f7

**Comment by doomwastaken** [comment]
@bettse could you please check it out

**Comment by bettse** [comment]
ugh.  yeah, not the first time the variable width font has bit me.  I won't be able to open a PR until this evening at the earliest

**Comment by doomwastaken** [comment]
Oh, not in a rush, we won't be able to fit into this release anyway, so 2 weeks to work with. Thank you !

**Comment by bettse** [comment]
@doomwastaken Thank you for reporting this.  You're helping us make it better!
