### ISSUE TITLE
Help modify menu display text to support UTF-8

### ISSUE THREAD

**Issue by LuckyFishGeek** [flipperdevices/flipperzero-firmware#2617]
### Describe the bug.

I want to change all the displayed text to the language of my own country. After compiling and reinstalling the firmware, the text cannot be displayed correctly.

### Reproduction

For example, I directly modified the applications/main/bad_usb/application.fam name="Bad USB" Bad USB text and recompiled and installed the firmware and it could not be displayed on the device.
![1682481158391](https://user-images.githubusercontent.com/29472751/234465742-f9e4d8b9-5518-4f79-814c-63a1aaa55ab3.jpg)

**Comment by skotopes** [comment]
You need to change font types to extended one that supports unicode in canvas module: https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/services/gui/canvas.c#L127.
Also it's going to cost a lot of internal space. You will need to compile firmware with DEBUG=0 COMPACT=1 to fit in flash.
Last but not least: our code that works with strings was never designed to be used with unicode, you are on your own.
