### ISSUE TITLE
Flipper Zero cannot read RFID at all. Attached RAW file.

### ISSUE THREAD

**Issue by LuciferShadows** [flipperdevices/flipperzero-firmware#2618]
### Description of the feature you're suggesting.

Hi,

I've added the raw file of the card. I'd like to know the type and any details.
My flipper zero doesn't seem to be reading RFID at all. NFC seems to be okay.
I'd like to know the format of the attached RAW file to see if this is something the flipper zero should already be able to read and emulate.

### Anything else?

[RFID.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11331021/RFID.zip)

**Comment by LuciferShadows** [comment]
![20230426_100945](https://user-images.githubusercontent.com/131750915/235067310-12f9e5f5-c073-4bc0-bbb9-5d195bc293d9.jpg)

This is a photo of the two tags. They can't be read under nfc, rfid, picopass, etc.

**Comment by skotopes** [comment]
This doesn't looks like RFID or it requires reader to send request.
Do you have proxmark?
