### ISSUE TITLE
Bug: Auto-Lock fails to prompt for pin

### ISSUE THREAD

**Issue by Swivelgames** [flipperdevices/flipperzero-firmware#2626]
After setting a pin, manually locking the Flipper Zero prompts the user to hit the back button three times and then enter their pin. However, when the Auto-Lock feature is enabled, it doesn't appear to be working. I'm not sure if this broke with a firmware upgrade. When you attempt to use the device, it prompts the user to hit the back button three times, but the pin entry is bypassed.

I also noticed that turning the device off and on again bypasses the pin.

Ultimately, until either of these are fixed, the pin is useless, as it's easily circumvented (which is a bit ironic given the nature of the device). This is especially since it ultimately exposes the U2F feature to use without the pin.

**Comment by doomwastaken** [comment]
@Astrrra confirmed it and added it to check lists
