### ISSUE TITLE
Suggestion: ability to take screenshots on actual flipper without phone connected, then save to SD card

### ISSUE THREAD

**Issue by Xbxjdjdjd** [flipperdevices/flipperzero-firmware#2631]

**Comment by skotopes** [comment]
Question is which key combo to use: all our keys are used in apps. We'll think about it

**Comment by magopeter** [comment]
Other ideas to trigger a screenshot: 
Using a timer, like on a camera: by enabling this feature in a menu (ex. "Take screenshot in 15s") and then navigating to what you want to capture. The buzzer could also beep progressively faster until capture.
OR with GPIO pins. This might be harder to use and needs jumper wires, but GPIO pin 17 can be shorted via the iButton pogo pins with a penny ;)

**Comment by skotopes** [comment]
That sounds quite crazy. Our UI/UX team is not going to be happy ;-)
I don't see how it can be implemented in user friendly manner so I'll close this ticket till someone propose acceptable solution.

**Comment by magopeter** [comment]
I never said it was a GOOD idea, just an idea :)  
It's obviously not user friendly, but it could be like an "easter egg" thing: If enabled in the Settings, shorting these GPIO pins will make a screenshot.
Anyway, I was just thinking of alternative input options. If not for a screenshot, maybe for something else in the future.
Thanks!
