### ISSUE TITLE
IR worker documentation outdated/incorrect

### ISSUE THREAD

**Issue by Brodan** [flipperdevices/flipperzero-firmware#2632]
### Describe the bug.

I'm trying to wrap my head about the infrared worker and build a flipper app that uses it. The documentation for `infrared_worker_tx_get_signal_steady_callback` is as follows:
```
/** Callback to pass to infrared_worker_tx_set_get_signal_callback() if signal
 * is steady and will not be changed between infrared_worker start and stop.
 * Before starting transmission, desired steady signal must be set with
 * infrared_worker_make_decoded_signal() or infrared_worker_make_raw_signal().
 *
```

However, neither the `infrared_worker_make_decoded_signal` or `infrared_worker_make_raw_signal` exist anywhere in the source code. This documentation is either misleading or completely incorrect. 

### Reproduction

Source code is located in `lib/infrared/worker/infrared_worker.h`.

**Comment by skotopes** [comment]
Fixed in #2677, merged in dev and will be included in release 0.84
