### ISSUE TITLE
Weather Station read/edit/send new values

### ISSUE THREAD

**Issue by krisss117** [flipperdevices/flipperzero-firmware#2635]
### Describe the enhancement you're suggesting.

Hi, it will be great to add ability to edit scanned parameters and send it to receiver.

**Comment by Skorpionm** [comment]
not cool, we don't condone the illegal use of flipper.

**Comment by skotopes** [comment]
Hi @krisss117, weather application is something we do in our free time. Saving, editing and transmitting clearly requires too much hustle with little to no use in real life.
However you are free to modify it.

**Comment by Crsarmv7l** [comment]
@krisss117 I have a repo that can create various flipper weather signals (Lacrosse, Nexus-TH, bresser3ch). A major problem with trying to "spoof" a weather station, is that they typically update at low intervals (every 1 minute, 5 minutes, etc), you don't know so you would need to be transmitting for a while.

I made this as a learning experience. It isn't very useful. 

https://github.com/Crsarmv7l/Python-Scripts-Flipper

Anything that can be decoded by rtl_433 can be recreated provided you have the time and knowledge (minimal python and the ability to get the timings from rtl433 src, then apply it all to triq's tx-tools) to do so.
