### ISSUE TITLE
Sub-Ghz allow to read Wether Station, add "Ignore Wether Station" in Config

### ISSUE THREAD

**Issue by krisss117** [flipperdevices/flipperzero-firmware#2636]
### Describe the enhancement you're suggesting.

Hi, it will be great to add ability to scan wether station in Sub-Ghz and allow to save it, edit parameters and sent it to receiver. If someone dont wont to read weather station, then they can go to Config and set Ignore Weather Station to ON.

When start scan i want to scan and decode all signals :) i can set ignore "Weather Station" when dont want to catch "Weather Station" :)

It will be great when the same settings will be in Decode

**Comment by hedger** [comment]
Weather Station exists as a separate app to save space on internal storage. Currently, code for weather station protocol decoding is only loaded when the app is started and does not take up any space on internal storage - and there's not much of it left. 

You can modify Weather Station for your needs yourself. Feel free to submit PRs with your changes.
