### ISSUE TITLE
saved infrared tx not generating correct carrier frequency

### ISSUE THREAD

**Issue by daviderud** [flipperdevices/flipperzero-firmware#2663]
### Describe the bug.

The infrared raw transmission seem to not correctly handle the parameter "frequency:" (nor "duty cycle:").

Example with frequency:56000, a 37 KHz carrier is obtained instead

![IMG_20230510_171350](https://github.com/flipperdevices/flipperzero-firmware/assets/103165301/4d7ead0a-b168-4edf-9f4a-91c114c035cf)

### Reproduction

1.Load a raw remote with frequency:56000. For example the attached one.

[ARRIS_test.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11448010/ARRIS_test.zip)

2.Activate the debug GPIO output and connect it to a scope.
3.Measure the subcarrier frequency

**Comment by gsurkov** [comment]
Yep, the code outright ignores these values. Working on it.

**Comment by skotopes** [comment]
Fixed in #2677, merged in dev and will be included in release 0.84

**Comment by daviderud** [comment]
Confirmed working the with involved HW. Thanks!
