### ISSUE TITLE
"Relay" app -- Listening event to Trigger an action  (Feature Request)

### ISSUE THREAD

**Issue by tagraf** [flipperdevices/flipperzero-firmware#2670]
### Description of the feature you're suggesting.

The Relay app is a powerful tool that can be used for a variety of purposes. Once opened, the app will display three tabs: Create, Saved, and About.

The Create tab is where you can create new relay conditions. To do this, select the IF row and choose a sub-system, file, or other object to listen for a signal. Once the signal is triggered, the THEN row will execute the selected action (such as a sub-system, file, or other object to execute it). You can also save your relay conditions for later use.

The Relay app has many potential uses. For example, you can use it to create a security monitor, a notification system, or even a prank. For example, you could set up the app to play a song when you press on your external remote or open your garage door when you press a button on your TV remote.

**Comment by skotopes** [comment]
Sounds quite specialized. We are not going to implement it as a part of firmware, but maybe someone from community will do.

**Comment by tagraf** [comment]
Respectfully, it's not specialized in a sense that I've provided the only example but as an applicability to any endpoint (GPIO, GHz, IR, RFID, or any subsystem as an object, an incoming signal as an event to trigger....the same whenever that is triggered, it'll execute at any endpoint as well as (GPIO, GHz, IR, RFID, or any ends)...If more example is needed then here's listed:
Relay_Ex-1:  IF(GHz signal is TRUE)...THEN(GPIO pin 7 pulsed ON)
Relay_Ex-2:  IF(IR signal is TRUE)...THEN(Emulate GHz file)
Relay_Ex-3:  IF(GHz signal is TRUE)...THEN(Emulate diff GHz file)
Relay_Ex-4:  IF(GPIO pin 2 is TRUE)...THEN(Emulate IR file)

You get to decide which endpoint to listen for an event and which endpoint to execute it.  Hence the concept of RELAY app for what it intends.
