### ISSUE TITLE
Please add XModem(vanilla/1k/CRC) send/receive support

### ISSUE THREAD

**Issue by YLSnewb** [flipperdevices/flipperzero-firmware#2676]
### Describe the enhancement you're suggesting.

Would like the ability to send and receive files via XModem and its various flavours (original checksum, 1k-block, CRC-16).

Files should be written directly to the SD card, accessible via qFlipper.
Files should be able to be read directly from the SD card, and selected from a folder on the SD card.  Files should be able to be written to the SD card via qFlipper.

If it can be integrated into the GPIO UART-USB Bridge, that would be even better.

Eventually I'd like to see ZModem implemented as well, but XModem is much simpler, so lets start there.

**Comment by skotopes** [comment]
This sounds like a good idea for external application. There are no plans to add it to main firmware.
