### ISSUE TITLE
Add the ability to pause BadUSB programs.

### ISSUE THREAD

**Issue by DrKoneko** [flipperdevices/flipperzero-firmware#2679]
### Describe the enhancement you're suggesting.

Sometimes when running BadUSB on a computer that is slower, the code will run before the computer is able to load the command. This could be solved by adding a pause button, allowing the computer to catch it's breath before continuing the code. Currently the only solution to this is to modify the BadUSB scripts which is not easy to do on the go.

**Comment by skotopes** [comment]
@nminaylov can we add pause button on when executing script?

**Comment by anna-oake** [comment]
have you seen #2544? or is that exactly what you mean by
> the only solution to this is to modify the BadUSB scripts

that approach seems more intuitive to me, as you can put these "breakpoints" in the specific parts of your script that need waiting. pausing the script mid execution manually might be pain in the ass, as you'd have to make sure you are doing that at the right moment.

on the other hand, both can exist... i just wanted to make sure you are aware of the `WAIT_FOR_BUTTON_PRESS` approach

**Comment by skotopes** [comment]
Implemented in https://github.com/flipperdevices/flipperzero-firmware/pull/2700
