### ISSUE TITLE
Lock should not disconnect active USB connection

### ISSUE THREAD

**Issue by kowalski7cc** [flipperdevices/flipperzero-firmware#2684]
### Describe the bug.

If autolock is enabled and fires or lock is manually activated, it will stop active USB connections.

### Reproduction

1. Enable PIN
2. Set autolock to 30s
3. Use RPC screen streaming or cli over USB on the desktop
4. Notice the disconnection

### Anything else?

Firmware on latest dev commit

**Comment by skotopes** [comment]
This is intended behavior. And it will be quite difficult to implement it with current architecture.
