### ISSUE TITLE
Global timezone

### ISSUE THREAD

**Issue by Kami-no** [flipperdevices/flipperzero-firmware#2695]
### Description of the feature you're suggesting.

Add global timezone to unify parameters for apps like Authenticator TOTP.

### Anything else?

It would be nice also to sync timezone via phone apps. It's not always obvious when phone app sync time for Flipper in new timezone and brakes TOTP.

**Comment by hedger** [comment]
As far as I know, TOTP has its own configuration of timezone offset.

For other apps, I can hardly imagine any extra use cases for that feature.

**Comment by Kami-no** [comment]
TOTP has it, but it's manual and a problem when you change timezone often...

**Comment by skotopes** [comment]
Sounds like reinventing unix timestamp to me. Unix timestamp already available in FuriHalRtc.
