### ISSUE TITLE
Another unknow fob 125khz

### ISSUE THREAD

**Issue by gauthi3r** [flipperdevices/flipperzero-firmware#2703]
### Description of the feature you're suggesting.

Hi,
i have one of these badge in 125khz, but my flipper can't read it : https://www.deister.com/uploads/tx_ttproducts/datasheet/tpx-keyfobs_datasheet_en_v160815.pdf 

Will we be able to read them soon with Hitag or Temic technology?

Thank,

**Comment by skotopes** [comment]
Which one from this datasheet is yours?
There were talks about hitag, as for Temic we need more info and raw records.

**Comment by gauthi3r** [comment]
The mine is TPX207 or 507 I don’t know exactly.
I send you raw file today.
Thx

**Comment by Astrrra** [comment]
Hi! Did you manage to make the RAW recording?

**Comment by g3kkorist** [comment]
Got m new Pet Yesterday and Check my 125khz fob, its a https://shop.deister.com/en/Keyfob-transponder-TPX207-OTP-125kHz-black/01588.000 and the little flipper wont read it. What can i do to help ?

**Comment by Astrrra** [comment]
Closing this as inactive, please open a new issue if the problem is still present and you can provide the RAW files.
