### ISSUE TITLE
Region not provisioned after update to latest official release firmware

### ISSUE THREAD

**Issue by alexminza** [flipperdevices/flipperzero-firmware#2704]
After updating to the latest official release firmware the provisioned region was lost and the Sub-GHz TX on legal frequencies is blocked. Previously provisioned region was for Romania / EU.

```
[12:59:57][debug]: < response(system(deviceInfo(hardware_region: 4)))
[12:59:57][debug]: < response(system(deviceInfo(hardware_region_provisioned: --)))
```

![IMG_5701](https://github.com/flipperdevices/flipperzero-firmware/assets/149919/17cd99b2-acbe-4e21-989c-9658aa51b986)

![IMG_5705](https://github.com/flipperdevices/flipperzero-firmware/assets/149919/b81afac0-895d-429d-8eef-140ada64b031)

![IMG_5706](https://github.com/flipperdevices/flipperzero-firmware/assets/149919/4cba143f-fca0-47d8-b44a-04a22e66f151)

FW Version Info: 0.83.1 [17-05-2023]

![IMG_5702](https://github.com/flipperdevices/flipperzero-firmware/assets/149919/83d098e0-c4e1-4d0a-96bd-3d70b616d665)

![IMG_5703](https://github.com/flipperdevices/flipperzero-firmware/assets/149919/422b9386-f31a-46f2-ab88-2f3a93724147)

### Reproduction

Menu -> Sub-GHz -> Saved -> [Select saved item] -> Emulate -> Send

### Logs

```Text
[12:59:57][debug]: < response(system(deviceInfo(hardware_region: 4)))
[12:59:57][debug]: < response(system(deviceInfo(hardware_region_provisioned: --)))
```
```


### Anything else?

_No response_

**Comment by tonyfreeman** [comment]
please report a bug through the app and post issue id here

**Comment by alexminza** [comment]
> please report a bug trough the app and post issue id here

How do you report a bug through the Flipper mobile app? Did not find any option for this...

**Comment by tonyfreeman** [comment]
Options -> Report a Bug

**Comment by alexminza** [comment]
> Options -> Report a Bug

No such option in the iOS app

**Comment by tonyfreeman** [comment]
ouch, it's still in beta https://testflight.apple.com/join/oLyR7YeT

**Comment by tonyfreeman** [comment]
if you don't want to install beta you could attach full log here, those two lines are not enough

**Comment by tonyfreeman** [comment]
also please check does `/int/.region_data` exist?
