### ISSUE TITLE
Trying to rename some files in Sub-GHz module ends with BusFault crash

### ISSUE THREAD

**Issue by marcinx64** [flipperdevices/flipperzero-firmware#2708]
### Describe the bug.

When trying to rename file on SD card from Sub-GHz menu, FW is crashing with BusFault error.

FW: UNLSHD-49E
FW: UNLSHD-50N

### Reproduction

1. Go to Sub-GHz
2. Click "Saved"
3. Pick file (in my case "433.92MHz_AM650_Better_Tesla_Charge_Port_Opener.sub")
4. Click "More"
5. Choose "Rename"
6. FW crash with BusFault error displayed after reboot

### Anything else?

This issue is not observed on Official FW (0.83.1)

**Comment by hedger** [comment]
Please reproduce the issue on official firmware and reopen if it's actually present.
