### ISSUE TITLE
Can we know if we are reading a mifare plus card?

### ISSUE THREAD

**Issue by UrSuLa360** [flipperdevices/flipperzero-firmware#2709]
### Description of the feature you're suggesting.

Im pretty sure im reading a mifare plus card but flipper says it is mifare classic.

I know mifare plus is compatible with mifare classic readers. 

But my question is: is it possible to detect when you are reading a mifare plus card type?

**Comment by AloneLiberty** [comment]
Mifare Plus in SL1/SL2 can work as Mifare Classic, you are probably reading Mifare Plus in SL1. Currently isn't possible to separate Mifare Plus from any other tags with same SAK/ATQA (ATS required). This will be possible after NFC refactor (#2529).

**Comment by skotopes** [comment]
@UrSuLa360 please check latest version. NFC refactoring changed way we detect card types in better and more reliable way.

**Comment by UrSuLa360** [comment]
Hello, I no longer have any mifare plus card. I will try to get one.

**Comment by UrSuLa360** [comment]
Got the card.
All interaction with the card was exactly like a Mifare Classic 1K.
![flipper_mifare_plus](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/e97d0225-02d6-4aac-a011-7907ca882478)

First time i read the card the dict attack found 1 key. 
The rest of keys were found using _mfoc-hardnested_ on the computer.
Then i added all keys to user_dict in flipper and i was able to read the full content.

so, flipper could not detect the real type of the card.

One thing i want to point is, i know the card it's a Mifare Plus because the company using this card SAID it is a Mifare Plus SE.
Here is the link where they describe the card used: [https://blog.renfe.com/asi-funciona-la-tarjeta-sin-contacto/](url)
(It is in spanish)

Edit: tested on 0.97.1, my UID is 4 bytes long.

**Comment by Tomi2965** [comment]
Same problem here. Fob: FDI Matelec France Mifare Plus (part nr. GB-010-229). Readed on latest dev (027ea9ea).

![flpr-2024-01-21-21:02:46](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/cb5bb746-f9c4-49c4-ae95-fbd8ba2b0078)

**Comment by skotopes** [comment]
Yes. Since MF plus detect support added in latest release

**Comment by ponty-pilot** [comment]
> Got the card. All interaction with the card was exactly like a Mifare Classic 1K. ![flipper_mifare_plus](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/e97d0225-02d6-4aac-a011-7907ca882478)
> 
> First time i read the card the dict attack found 1 key. The rest of keys were found using _mfoc-hardnested_ on the computer. Then i added all keys to user_dict in flipper and i was able to read the full content.
> 
> so, flipper could not detect the real type of the card.
> 
> One thing i want to point is, i know the card it's a Mifare Plus because the company using this card SAID it is a Mifare Plus SE. Here is the link where they describe the card used: [https://blog.renfe.com/asi-funciona-la-tarjeta-sin-contacto/](url) (It is in spanish)
> 
> Edit: tested on 0.97.1, my UID is 4 bytes long.

Please share the keys to the card. I want to try to write my train card to the flipper
