### ISSUE TITLE
New 125 kHz RFID Format 

### ISSUE THREAD

**Issue by PrinzJuliano** [flipperdevices/flipperzero-firmware#2715]
### Description of the feature you're suggesting.

I have an RFID Card that cannot be emulated by the flipper.
I would like for the flipper zero to understand the format and emulate it.

This does extend the existing 125 kHz functionality.

### Files
[Scan.ask.raw.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11611937/Scan.ask.raw.zip)
[Scan0.psk.raw.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11611949/Scan0.psk.raw.zip)
[Scan1.psk.raw.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11611939/Scan1.psk.raw.zip)
[Scan2.psk.raw.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11611938/Scan2.psk.raw.zip)

### Anything else?

I read the same card three times, and the PSK Files are all different sizes. I don't have any knowledge in this field and would like to learn more about it

**Comment by skotopes** [comment]
Attached data doesn't contain any RFID signal. It can be ReaderTalkFirst or NFC tag.
