### ISSUE TITLE
More than one Flipper is attached

### ISSUE THREAD

**Issue by johmarjac** [flipperdevices/flipperzero-firmware#2722]
Hi,

I just recursive cloned the repository on my MacBook Air M1, invoked `./fbt vscode_dist` to setup the vs code configuration (which unfortunately didn't fix include errors but that's not my problem rn), I copied the Example Thermo into applications_user folder, emptied it out so it really just is a baritone app and it compiles fine. But when I use command of VS Code to launch app on Flipper it says in console:

`2023-06-01 21:09:34,410 [ERROR] More than one Flipper is attached
2023-06-01 21:09:34,410 [ERROR] Failed to guess which port to use`

Can I somehow list my devices and maybe invoke a parameter to tell it which one to use? Although I only have one Flipper attached via USB lol.

**Comment by hedger** [comment]
Can you please show the output of `ls /dev/cu*` ?

**Comment by johmarjac** [comment]
> ls /dev/cu*

Sure here you go:
`johmarjac@AirvonJohannes flipperzero-firmware % ls /dev/cu*
/dev/cu.Bluetooth-Incoming-Port /dev/cu.JBLFlip5                /dev/cu.usbmodemflip_Iroola1    /dev/cu.wlan-debug
johmarjac@AirvonJohannes flipperzero-firmware % `

**Comment by hedger** [comment]
Oh I see. `JBLFlip5` is confusing Flipper detection code, since it uses the same prefix as Flipper's virtual COM ports.

Let me think of a workaround.

**Comment by johmarjac** [comment]
> Oh I see. `JBLFlip5` is confusing Flipper detection code, since it uses the same prefix as Flipper's virtual COM ports.
> 
> Let me think of a workaround.

Awesome thanks :D

**Comment by hedger** [comment]
Well, a quick and dirty fix is:
https://github.com/flipperdevices/flipperzero-firmware/blob/dev/scripts/flipper/utils/cdc.py#L9
Change "flip" -> "flip_"

**Comment by hedger** [comment]
Later I'll add an fbt option to specify Flipper name just for such cases.

**Comment by johmarjac** [comment]
> Well, a quick and dirty fix is:
> https://github.com/flipperdevices/flipperzero-firmware/blob/dev/scripts/flipper/utils/cdc.py#L9
> Change "flip" -> "flip_"

Yes this worked, Thanks now I can continue.
