### ISSUE TITLE
Firmware 0.84.1

### ISSUE THREAD

**Issue by Yahya611477** [flipperdevices/flipperzero-firmware#2724]
### Describe the bug.

I’m unable to update to this firmware no matter how much I’ve tried. I’ve done it on Mac, windows, and mobile. 

### Reproduction

1- buy a flipper zero without SD card with firmware 0.71.1 and missing database 
2- put an SD card in there and format it
3- try to update to 0.84.1

### Target

0.84.1

**Comment by hedger** [comment]
What error messages are you getting? Have you tried 0.84.2, since 0.84.1 had a bug related to radio updates?

**Comment by skotopes** [comment]
0.84.2 should solve your issue
