### ISSUE TITLE
KeeLoq versus Cnt

### ISSUE THREAD

**Issue by 8um1c4** [flipperdevices/flipperzero-firmware#2726]
### Describe the bug.

Iºm trying to reproduce a KeeLoq signal, but the cnt counter doesnºt increment.
In the file I donºt see where to store or change the cnt value. Is it a bug or a feature?

### Reproduction

Yes. Send signal recorded.

**Comment by hedger** [comment]
Flipper's firmware does not allow replaying captured signals that are non-static - that would desync the original remote. 

You can create a new remote in Flipper's menu and pair it with the access control system you own.
