### ISSUE TITLE
Pause Universal Remote + More

### ISSUE THREAD

**Issue by EasyAntiCheatSoftware** [flipperdevices/flipperzero-firmware#2728]
### Description of the feature you're suggesting.

There should be a feature to pause and resume the universal remote feature for the Flipper Zero. Also, there should be the ability to go back percentages of the universal remote and the ability to save that percentages remote so it can be used later on. So for example maybe on percentage 43% the Samsung remote is played, and there should be the option to save that.

**Comment by hedger** [comment]
Sounds like you need not a universal remote, but a particular one for a specific device.

**Comment by skotopes** [comment]
Yep, too niche thing. Will cause problems in UI/UX.
