### ISSUE TITLE
125khz RFID Protocol Request

### ISSUE THREAD

**Issue by f1yaw4y** [flipperdevices/flipperzero-firmware#2744]
[125_rfid.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11671518/125_rfid.zip)

https://fccid.io/NNHRKWM

Attached are raw readings of my RFID gym access card and a picture of the reader, along with the FCC ID info page. I would attach a picture of the actual card but it is full of identifying information both front and back. It is the size of a typical credit card or HID card and white with printed text / image of my face.

I'd like to request adding the card to the list of recognized protocols. I wish I could contribute but I have no idea how to analyze the file. 

Thank you for the help :)

**Comment by skotopes** [comment]
PSK record looks valid. Should be possible to implement protocol on top of it.

**Comment by skotopes** [comment]
Support added in https://github.com/flipperdevices/flipperzero-firmware/pull/3697 Thanks to @zinongli
