### ISSUE TITLE
125khz RFID Protocol Request

### ISSUE THREAD

**Issue by f1yaw4y** [flipperdevices/flipperzero-firmware#2745]
### Description of the feature you're suggesting.

https://fccid.io/NNHRKWM
[125_rfid.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11671581/125_rfid.zip)

Attached are raw readings of my RFID gym access card and a picture of the reader, along with the FCC ID info page.
I'd like to request adding the card to the list of recognized protocols. I wish I could contribute but I have no idea how to analyze the file.

Thank you for the help :)

### Anything else?

 I would attach a picture of the actual card but it is full of identifying information both front and back. It is the size of a typical credit card or HID card and white with printed text / image of my face.

**Comment by skotopes** [comment]
Duplicates #2744
