### ISSUE TITLE
Shared Bluetooth battery level

### ISSUE THREAD

**Issue by ErSeraph** [flipperdevices/flipperzero-firmware#2746]
### Description of the feature you're suggesting.

In the latest versions of Android and iOS the battery levels of Bluetooth devices are shown almost everywhere on the smartphone, in my case with Android 13 on a Pixel 7 the battery indicator is really very useful as it is shown in the Home, in the Always On Display, on the status bar, on the button to turn on or off the Bluetooth and also on a very nice widget. In some cases you get a notification if the device is about to die. Here a screenshot I found online:
https://9to5google.com/wp-content/uploads/sites/4/2022/03/Screenshot_20220307-140324.png?w=473

### Anything else?

It seems that this functionality depends on the type of connected device declared by the device itself, if you connect the Flipper to your phone using a plugin that simulates, for example, a bluetooth keyboard (input device), the smartphone will correctly detect the battery level. I don't know about you, but in my case when the Flipper is connected in standard mode it is seen as a generic device, a simple Bluetooth connection with no battery level, except in the application which obviously shows up correctly.

**Comment by crocboy06** [comment]
This could be of some help, i don't know, but i recently downloaded an app called Bluetooth Inspector on my iPhone, and it when i scanned my flipper's bluetooth signal it showed the correct battery level. that being said, flipper's battery level does not show up on any of my widgets.

**Comment by skotopes** [comment]
Technically we do expose this information throw the standard BLE GAT/GAP, but everything else is kinda custom. Most likely IOS/Android only works with some standard profiles.
