### ISSUE TITLE
Broken write support to iButton DS1971

### ISSUE THREAD

**Issue by MichaelGrafnetter** [flipperdevices/flipperzero-firmware#2749]
### Describe the bug.

The iButton Write Copy feature does not work properly with DS1971. Instead of the actual data, the iButton end up containing value 0xFF 32 times (256 ones in binary).

### Reproduction

1. Open the iButton menu.
2. Select "Read" and scan an existing DS1971 key.
3. Select "More"
4. Navigate to "Write Copy".
5. Write a different (or same) DS1971 key.
6. Select "Back", "Retry", "Exit".
7. Scan the iButton from step 5.
8. The 256-bit Internal EEPROM now contains only FF FF...FF instead of the expected data.

**Comment by doomwastaken** [comment]
Greetings, I've tried to repeat the issue on the 1971 key fobs that I have available and it appears to work correctly, could you please provide us description of the key (if possible, then with photos). Also if it would be great if you were able to test that key with other method. As far as I know, FF values mean that data was not written on it.

**Comment by MichaelGrafnetter** [comment]
Tried it again (both with 0.84 and 0.85 RC firmware), without any luck.

Trying to write this file:
```
Filetype: Flipper iButton key
Version: 2
Protocol: DS1971
Rom Data: 14 75 3A 07 09 00 00 4D
Eeprom Data: 50 68 <REDACTED...> 85 07 77 95 E0
```

Target is the same iButton, from which the data was originally fetched:

![image](https://github.com/flipperdevices/flipperzero-firmware/assets/8986376/2f3e9c62-adf4-49d3-a6dd-2189008f894a)

After I try to read the data from the iButton again after writing it, I always the same result:

![image](https://github.com/flipperdevices/flipperzero-firmware/assets/8986376/9ab7ffd2-3c96-4a0b-80cd-00862a9265f4)

The iButton is thus effectively bricked, as the entry system does not check the ID, but the EEPROM data.

Not sure how to troubleshoot this further.

**Comment by doomwastaken** [comment]
![16866529541191100176154361196694](https://github.com/flipperdevices/flipperzero-firmware/assets/72250702/c1b394c3-f664-4b20-bc2b-bcd367162f55)
I see, let me try and find your version of the ibutton

**Comment by doomwastaken** [comment]
Only ideas I have at this moment is to try with a different flipper if you have access to it. 

And I have a number of questions to ask first:

- Did this key work previously on any other version of software?
- Are you able to get a different version of DS1971F5?
- Do you have access to a logic analyzer and would you be able to record entire communication between flipper and reader?

If nothing of this works, then we will need access to the key fob to help you furher, sometimes they might be a replica of an actual ikey.

**Comment by MichaelGrafnetter** [comment]
@doomwastaken Thanks for testing it.

> Only ideas I have at this moment is to try with a different flipper if you have access to it.

I only have one Flipper.

> Did this key work previously on any other version of software?

Have not tested it previously.

> Are you able to get a different version of DS1971F5?

I don't have any blank ones unfortunately. And I would prefer not to erase/brick any more iButtons.

> Do you have access to a logic analyzer and would you be able to record entire communication between flipper and reader?

Nope. But would debug logs be of any help?

**Comment by doomwastaken** [comment]
Let me get back to you, if you have a link to where you purchased your key-fobs, we would order some, otherwise I need time to do some research

**Comment by MichaelGrafnetter** [comment]
Tried it after a while with the latest FW (0.87.0) and it is now working without any issues. Which is strange, as I do not see any relevant changes in the repo.

**Comment by MichaelGrafnetter** [comment]
I did some more testing and the success rate of writing data to DS1971 EEPROM is around 1:4. I wonder if Flipper could try to validate the data and re-write them in case of a mismatch.

**Comment by skotopes** [comment]
@doomwastaken any progress?

**Comment by doomwastaken** [comment]
I had re-tested it again on 1971 original and noname keys, did 10 writes with each of individual data sets, all seems to work correctly. I will close the issue. 

If you could provide us with information where to purchase same 1971 key that you are using, then I will order some and re-test this again.
