### ISSUE TITLE
Ability to detect multiple infrared signals

### ISSUE THREAD

**Issue by EasyAntiCheatSoftware** [flipperdevices/flipperzero-firmware#2765]
### Describe the enhancement you're suggesting.

just like subghz, it would be nice to detect multiple infrared signals and save them. It would be way faster to create a remote.

### Anything else?

also make it so we can change the places of the buttons on a remote

**Comment by skotopes** [comment]
Sounds like a good idea for external application. We'll leave it to community.

**Comment by EasyAntiCheatSoftware** [comment]
not planned? damn :(
