### ISSUE TITLE
Add bluetooth shutter button to flipper

### ISSUE THREAD

**Issue by geks52** [flipperdevices/flipperzero-firmware#2789]
### Description of the feature you're suggesting.

Hello!
Could you please tell me if it is technically possible to write an application to control the camera on mobile devices?
I would like to connect the flipper to my mobile phone, run the camera on it and take photos using the flipper.

Such devices exist, but are sold separately.
[Example.](https://www.amazon.com/bluetooth-remote-iphone-camera/s?k=bluetooth+remote+for+iphone+camera)
![изображение](https://github.com/flipperdevices/flipperzero-firmware/assets/67420165/f235eb42-6ed5-4659-8094-ecaf2f6bc58c)

It would be cool to add such a feature!
Thanks for listening!

**Comment by skotopes** [comment]
Already in `Bluetooth Remote` application. Media keyboard should do the thing.

**Comment by geks52** [comment]
@skotopes 
Thank you!
The problem was with the Google Camera app.
It is in this app that the flipper photo capture doesn't work. (Pixel 4a, Android 13)
If you install another photo shooting app, everything works.
