### ISSUE TITLE
USB MSC support (live usb)

### ISSUE THREAD

**Issue by bradyreetz** [flipperdevices/flipperzero-firmware#2797]
### Description of the feature you're suggesting.

Application in Flipper for Live USB. Will need to be able to reinitialize USB stack for MSC. Application should be able to live boot iso images stored in sd.

### Anything else?

It appear USB Stack should allow for USB MSC. But I haven't had a chance to.dig further into the development. I envision having hirens booted, kali, etc, ready at hand in flipper

**Comment by DrZlo13** [comment]
We have tested this and it will be practically unusable. Flipper has 12Mbit USB and an even slower SD Card interface.
