### ISSUE TITLE
Use external hardware Keyboard via USB-C

### ISSUE THREAD

**Issue by ClemontX** [flipperdevices/flipperzero-firmware#2806]
### Description of the feature you're suggesting.

I've tested to connect a keyboard via USB and realized it would not work to type something with the keyboard.
The keyboard wouldn't even connect.

For some things on-screen-keyboard isn't nice to use.
For example if you want to use the flipper as a portable UART console.

It would be nice, if we can use external keyboards to type something in the flipper.

**Comment by skotopes** [comment]
That requires USB host mode support, which is not available on our MCU.
