### ISSUE TITLE
[RFID] Electronic RFID hotel door lock system support

### ISSUE THREAD

**Issue by valik-svs** [flipperdevices/flipperzero-firmware#2815]
### Description of the feature you're suggesting.

I've added the raw file of the card.
My flipper zero doesn't seem to be reading RFID at all.
Please help me with my apartment door.
The door lock looks like this:
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/128388664/869066c7-ed08-477e-9132-cbe4ff7afe93)
card: 
![20230629_154449](https://github.com/flipperdevices/flipperzero-firmware/assets/128388664/879cadbc-75f3-4918-bc99-66348c4e5183)

raw files:
[Archive.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11906522/Archive.zip)
[Archive 2.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11906520/Archive.2.zip)

**Comment by skotopes** [comment]
Most likely this is NFC based lock. Check NFC application.
Also no meaningful data on raw files your provided

**Comment by valik-svs** [comment]
looks like it's my mistake. 

I uploaded corrects files 
[Archive.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11906522/Archive.zip)
[Archive 2.zip](https://github.com/flipperdevices/flipperzero-firmware/files/11906520/Archive.2.zip)

P.S.: `Most likely this is NFC based lock` - I tried to detect the card reader - no result.
Also, try to read via NFC reader - no effect.
Thank you for quick response!
And sorry for my gaps with file upload.

**Comment by skotopes** [comment]
There is a new app `NFC/RFID Detector` available in dev build, can be found in Tools. Try using it against reader to detect which carrier it uses.

**Comment by doomwastaken** [comment]
google image shows its a  OZLOCKS HL-F05/H/TM Mifare

**Comment by valik-svs** [comment]
> There is a new app `NFC/RFID Detector` available in dev build, can be found in Tools. Try using it against reader to detect which carrier it uses.

I checked, it's LF RFID

**Comment by skotopes** [comment]
Reader talk first most likely. we need that system in the office for analysis.
