### ISSUE TITLE
STRING_DELAY doesn't implement delay between special characters.

### ISSUE THREAD

**Issue by YLSnewb** [flipperdevices/flipperzero-firmware#2828]
### Describe the bug.

In the code:

STRING_DELAY 2000
PAGEDOWN PAGEDOWN PAGEDOWN

There is no delay between page-down commands.

I expect STRING_DELAY to also apply to individual special character commands.

If STRING_DELAY is paired with the STRING and STRINGLN commands, consider adding CHAR_DELAY for special characters.

### Reproduction

Use the sample code above in a BadUSB script, and see that it executes the special command characters without any delay applied.

**Comment by nminaylov** [comment]
STRING_DELAY is intended only for STRING command. You can use DEFAULT_DELAY to add delay between other commands.
