### ISSUE TITLE
USB keyboard utility can't hold down shift

### ISSUE THREAD

**Issue by onnimonni** [flipperdevices/flipperzero-firmware#2830]
### Description of the feature you're suggesting.

Hey!

Today I didn't have access to usb keyboard when resetting my old Windows PC before selling it.

To reset Windows machine one needs to be able to hold down SHIFT key and press restart button with mouse to access the factory reset screen.

Could we allow the keyboard to emulate that the shift modifier is hold down?

Currently if I press modifier down on flipper it doesn't send the modifier down command to the Operating System.

### Anything else?

Would be fantastic to have new software which would allow me to connect with Qflipper to the flipper and use my Laptop keyboard to send key presses through bluetooth to flipper which would forward them to the PC.

**Comment by skotopes** [comment]
Do I understand correctly, we are talking about USB/Bluetooth Remote app?

**Comment by onnimonni** [comment]
Yes sorry for being unclear here. I was talking about the USB app here.

**Comment by onnimonni** [comment]
>Would be fantastic to have new software which would allow me to connect with Qflipper to the flipper and use my Laptop keyboard to send key presses through bluetooth to flipper which would forward them to the PC.

And this was a separate convenience idea about that if I could connect the flipper to a separate PC as usb-keyboard and then control that keyboard through bluetooth from laptop running the Qflipper software

**Comment by skotopes** [comment]
> Yes sorry for being unclear here. I was talking about the USB app here.

We'll fix it.



> > Would be fantastic to have new software which would allow me to connect with Qflipper to the flipper and use my Laptop keyboard to send key presses through bluetooth to flipper which would forward them to the PC.
> 
> And this was a separate convenience idea about that if I could connect the flipper to a separate PC as usb-keyboard and then control that keyboard through bluetooth from laptop running the Qflipper software

That will require major redesign in different components. We don't plan to do that at this point.

**Comment by onnimonni** [comment]
> We'll fix it.

I'm assuming `We'll` is a typo from `Well` and you are not going to fix it by trying to say `We will fix it`?

If so I'm unsure how and would need feedback from you in order to do so.

It's quite clear in the title what the issue was about (USB keyboard) and it's hard to say how different readers will see this.

Now that you have the proper understanding about the issue how would you write it? I don't know what to improve there yet.

> That will require major redesign in different components. We don't plan to do that at this point.
I understand and this was probably not useful to add here in the first place.

How I read the PR template is that you would want to extra feedback/ideas like the ones I provided.

If you don't want to receive stuff like this I would remove following section in the **New issue** template:
```
### Anything else?
```

**Comment by skotopes** [comment]
`We'll fix it.` -> `We will fix it`. https://www.merriam-webster.com/dictionary/we'll
@nminaylov is already working on it.

`Anything else` section was meant to be used for additional related to the issue comments.

**Comment by skotopes** [comment]
@nminaylov any updates?
