### ISSUE TITLE
Users are able to go back a folder during selection

### ISSUE THREAD

**Issue by Ghdhdhdh** [flipperdevices/flipperzero-firmware#2831]
### Describe the bug.

Users are able to go back a folder during selection in "Saved" or "Apps".

### Reproduction

1.Turn On Your Flipper
2. Press The ok button to get to the main screen
3. go to apps
4. Press the Parent Directory Folder

### Target

N/A

### Logs

```Text
Not Needed
```

**Comment by skotopes** [comment]
That is intended behavior. Back button brings you back to app menu, but navigation with ok key on parent folder will bring you to upper level.
