### ISSUE TITLE
Implement modifier HOLD keys

### ISSUE THREAD

**Issue by onnimonni** [flipperdevices/flipperzero-firmware#2833]
### Description of the feature you're suggesting.

To circumvent the feature I was missing in #2830 I tried to make following BadUSB script:

```
REM Holds down shift key
​
INJECT_MOD
HOLD SHIFT
DELAY 30000
RELEASE SHIFT
```

But it fails to execute with error code:
```
ERROR: line 2 No keycode defined for
```

**Comment by nminaylov** [comment]
HOLD command already supports modifier keys. Your script doesn't work because of invisible Unicode character at second line and unknown INJECT_MOD command
