### ISSUE TITLE
Screen backlight wont change in setting only after restart

### ISSUE THREAD

**Issue by feasfeadawda** [flipperdevices/flipperzero-firmware#2843]
### Describe the bug.

I updated my flipper to 36.1 and now the backlight wont change only after a restart.The backlight time is dont working

### Reproduction

Update

**Comment by doomwastaken** [comment]
Are you using official firmware? On latest dev/release all works fine. Both backlight and delay

**Comment by skotopes** [comment]
36.1 ? we never released anything with those numbers.
