### ISSUE TITLE
[0.86.1] sub-ghz menu causes device crash after update

### ISSUE THREAD

**Issue by ghost** [flipperdevices/flipperzero-firmware#2854]
### Describe the bug.

when previously on version 0.85.2 everything still works fine even with a downgrade flipper is completely functional

upgrading to 0.86.1 by any means, just causes the sub-ghz menu to cause the flipper to crash
going into the menu works with the sdcard unmounted/removed, so it is either an issue with subghz databases or sdcard size? but i assume the latter as it works fine in downgraded versions perfectly
having no databases on the sdcard and i can still open the subghz menu

as soon as i flash databases with qFlipper sub-ghz menu does not work anymore

formatting and flashing the device and the sdcard, and trying to re-flash (qFlipper) does not suffice by any means

a brand new 256gb sandisk card about a month old is used (and only card at the moment)

im not sure what more info to input other than these logs when entering the sub-ghz menu from a cli session

### Reproduction

1. be on 0.85.2
2. verify going into sub-ghz menu
3. update using whatever (qFlipper)
4. updated to 0.86.1 and enter sub-ghz menu
5. flipper locks up and requires force reboot
6. ...
7. wtf

[going-into-buggy-subghz.txt](https://github.com/flipperdevices/flipperzero-firmware/files/11973561/going-into-buggy-subghz.txt)

### Target

f7?

### Anything else?

before posting im glad i had backed up my entire sdcard
some weird workarounds

being on firmware 0.86.1

1. starting off with a formatted sdcard (format using the flipperzero itself)
1a. reboot device

2. open qFlipper and databases are missing with green UPDATE button
2a. there is a prompt "go to flipp.dev/upd", ignore
2b. go into Sub-GHz menu, "no sdcard or database found", ignore
2c. menu should work with RX and TX

3. upload Manifest to "blank" sdcard
3a. reboot flipper

4. qFlipper says databases exist, and no database prompt after reboot
4a. go into Sub-GHz menu,get prompted about no sdcard or databases
4b. functionality still works

5. create path /subghz/assets/
5a. i dragged and dropped all backed up files (all file hashes matched with official files)
alutecha_at_4n
came_atomo
keeloq_mfcodes
keeloq_mfcodes_user.example
nice_flor_s
settings_user.example
5b. reboot device

6. no more prompts and sub-ghz menu works as intended
6a. dragged all my backed up data and device works like it should

-7. formatting the sdcard and trying to "update" using qFlipper causes the device to break like it did before

i am not sure what else to provide, and this workaround does not feel proper

important update!
apparently
sdcard/apps_data/subghz/plugins/radio_device_cc1101_ext.fal
differs in previous firmwares and is crashing my device in latest qFlipper update
deleting the plugin and rebooting makes device functional.

downgrading plugin breaks the device
removing the plugin file altogether make sub-ghz menu work again

so is something wrong with the plugin? or what is happening?!

i am actually going crazy here

**Comment by Skorpionm** [comment]
do you use the connected CC1101, through which do you update the firmware?  you can describe in detail the sequence of your actions, but it is better to shoot a video

**Comment by ghost** [comment]
sorry, what connected cc1101? i googled that and i do not have that
i dont have any external hardware

i literally update by plugging the flipper into the computer with a usb-c cable...hit update in qflipper on Release version...after update my the subghz menu doesnt work anymore and crashes my device

deleting the plugin file stated above is my only fix and i dont know why or how to fix if its a problem

the device is month old and i have only been updating it, nothing custom, this is the first time it "broke" on regular release stable update

**Comment by GDroid80** [comment]
Same here. Downgraded to old firmware and everything worked again.

**Comment by Skorpionm** [comment]
is it possible to provide a log at the time of loading the SubGhz application?  you also need to update the flipper, before launching the SubGhz application, enable the output of logs or through the debugger if there is, or CLI -> log and run SubGhz so that the flipper freezes, what exactly will be in the logs?

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/2857
I have not been able to replicate this behavior. but a possible error turned out to be the wrong choice of the external module CC1101 (when it is not available at all)
Will I put the firmware from this branch and check if the freezes are repeated?

**Comment by ghost** [comment]
#2857
i flashed the updater package with qFlipper

yes the error check fixed it the crashing issue

**Comment by liszkai** [comment]
Same on dev build 711e.
"Load error .. Unsatisfied links" on Sub-Ghz and Infrared app. All other works.
Downgrade are solve the problem.

**Comment by skotopes** [comment]
Can you list all files in `apps_data/subghz/plugins` folder on SD card?

**Comment by liszkai** [comment]
strange founding...
backup assets in Sug.Ghz and Infrared folders
delete them
reupload them
all two apps working again

**Comment by skotopes** [comment]
Could be corrupted file system. Make sense to check it with your PC/Mac or format and reinstall everything.

**Comment by liszkai** [comment]
file system was checked. no errors.
Sub_ghz app started once, but not working even with emty sd Sub-Ghz folder.
Infrared app still works.
Downgrade to any previous fw version still works. the problem exist only in 711 dev
![subghz](https://github.com/flipperdevices/flipperzero-firmware/assets/57450989/035e3716-9b25-4e30-bce1-89ac1fe45a2f)

**Comment by liszkai** [comment]
i think, it is somethong about, Sub-Ghz app moved to "external" apps.
In 704 Sub-Ghz only accessible from main menu, now accessible also from Applications menu
![subghz_menu](https://github.com/flipperdevices/flipperzero-firmware/assets/57450989/c349b9ac-476c-42fa-8f3a-3824c8477eae)

**Comment by skotopes** [comment]
How do you upgrade/downgrade? Which tool/companion/command do you use?

**Comment by liszkai** [comment]
qflipper on win11,  and web lab make same result

**Comment by skotopes** [comment]
Can you also get console log of update/app start process?

**Comment by liszkai** [comment]
I used mostly the web lab updater. Is it generate any log?
The upgade on flipper going without issues.
Can I download update log from flipper?

**Comment by skotopes** [comment]
Logs are available on serial console on external gpio. You’ll need some other device to connect to it(usb serial ttl adapter)

**Comment by liszkai** [comment]
no problem, I have tools.
Just I need to listen the RX TTL pin?

**Comment by skotopes** [comment]
Yep. 230400, just listen.

**Comment by liszkai** [comment]
downgrade to 704e then start sub menu
[704e+sub-menu.txt](https://github.com/flipperdevices/flipperzero-firmware/files/12006056/704e%2Bsub-menu.txt)

**Comment by liszkai** [comment]
711e upg + Sub-Ghz app fail
[711e+sub-menu.txt](https://github.com/flipperdevices/flipperzero-firmware/files/12006092/711e%2Bsub-menu.txt)

**Comment by liszkai** [comment]
Sub-Ghz app start with trace debug level
![subghz_menu3](https://github.com/flipperdevices/flipperzero-firmware/assets/57450989/1110915a-ac16-44d2-97cd-e649eda30fe4)

**Comment by liszkai** [comment]
problem solved with 712e...

**Comment by xMasterX** [comment]
> problem solved with 712e...

Please do not waste time of official team posting issues with my firmware here, I will remove dev builds from public access if I see things like that again
