### ISSUE TITLE
Companion app keyboard

### ISSUE THREAD

**Issue by gornstein** [flipperdevices/flipperzero-firmware#2858]
### Description of the feature you're suggesting.

The ability to use a phone keyboard in the Flipper companion app would be nice. 
Something like you open a text field on the flipper and with the companion app open a keyboard comes up on the phone to allow for faster typing.

**Comment by skotopes** [comment]
Yep, we've been thinking about it. Feasible, but quite complex.
Sadly we are not planning to implement it any soon, but consider it for future releases.
