### ISSUE TITLE
Enhanced Frequency Support for India Region

### ISSUE THREAD

**Issue by AmeyaVS** [flipperdevices/flipperzero-firmware#2870]
### Describe the enhancement you're suggesting.

Currently the default restriction for India Region lies:

![image](https://github.com/flipperdevices/flipperzero-firmware/assets/6262562/60c87a74-c3ce-492e-93b9-a919d0cf7774)

But as per the documentation available [here](https://dot.gov.in/spectrummanagement/rules-use-low-power-radio-frequency-devices-frequency-band-43305-43479-mhz), [pdf](https://dot.gov.in/sites/default/files/Rules%20for%20Use%20of%20Low%20Power%20Radio%20Frequency%20Devices%20in%20the%20frequency%20band%20433-434%20MHz%20(Exemption%20from%20License)%20Rules%2C%202022.pdf?download=1).

Snapshot attached from the document mentioned:
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/6262562/4e7b70f1-5ee4-414b-9402-b99ff7214b65)

Kindly enable the 433.05-434.79 MHz band for this region.

**Comment by skotopes** [comment]
I've updated India region data. Please reinstall firmware to apply new configuration.

**Comment by AmeyaVS** [comment]
It seems the other frequency are disabled now for the India Region.
This request was to enable additional frequency support for 433 MHz band.
The previous configuration for 312 - 315.25 MHz and 920.50 - 923.50 MHz are still valid.
Can this issue be reopened? or should I file new issues  for this regression?

**Comment by skotopes** [comment]
@AmeyaVS India doesn't allow those bands for unlicensed use.

**Comment by AmeyaVS** [comment]
The general understanding is using other bands is that one does not exceed certain transmission and interference clause.
Their are devices available in the market in the 300+/900 MHz range for very small (low power) range applications.

**Comment by skotopes** [comment]
@AmeyaVS it explicitly says `in the frequency band as specified in the Table given below`

**Comment by AmeyaVS** [comment]
I am not sure why the Indian Government Body have separate documents for every band.
The document linked above is specifically calling out the 433 MHz band.
https://dot.gov.in/spectrummanagement/rules-use-low-power-radio-frequency-devices-frequency-band-43305-43479-mhz
