### ISSUE TITLE
Lock your flipper in dummy mode

### ISSUE THREAD

**Issue by kamilskrzypek4** [flipperdevices/flipperzero-firmware#2899]
### Description of the feature you're suggesting.

Hello,
The feature I request is locking the device with pin combo in dummy mode.
It will work like this:

1. you will set a PIN combo (already there is this feature)
2. you will set if PIN affects brainiac mode (optional)
3. go to dummy mode
4. if you want to go back to brainiac mode you need to enter pin combo

This feature was described in your blog but I do not know if it's still planned
https://blog.flipperzero.one/pass-combo-update/

**Comment by skotopes** [comment]
@kamilskrzypek4 locking with pin now works in the same way for both modes. Separate PIN for dummy mode is not planned
