### ISSUE TITLE
Cannot update to 0.87.0 stable release from 0.86.2 stable release using Bluetooth update feature

### ISSUE THREAD

**Issue by AkechiShiro** [flipperdevices/flipperzero-firmware#2902]
### Describe the bug.

The Flipper Zero shows 
```
Update Failed 
Error#[1-20] 
```
Right after the uploading from Bluetooth has finished.
The Flipper Zero freezes despite showing press <center_button> to retry or press <return_button> to abort and the only way to reset is the hard reset combination key.

I have not tried to update through USB using qFlipper.
Flipper Mobile App Version : 1.2.1

### Reproduction

1. Switch on FP Zero
2. Connect to Bluetooth companion app
3. Try and update the FP Zero
4. See the error.

**Comment by AkechiShiro** [comment]
![signal-2023-07-20-16-37-30-287.jpg](https://github.com/flipperdevices/flipperzero-firmware/assets/14914796/133024f7-3f1d-4886-9aa6-3129bd757b49)

**Comment by AkechiShiro** [comment]
Not sure if it could be due to this : 
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/14914796/119038ef-6344-4279-bfc3-ff56ddc8554e)

**Comment by doomwastaken** [comment]
On our side updating was working on latest mobile app versions. If you are using 1.2.1, that is last years version, try updating the app

**Comment by AkechiShiro** [comment]
Thanks, my bad will retry with latest update of the app

**Comment by doomwastaken** [comment]
Just re-checked on latest firmware with 0.86.2 release to 0.87.0 release, works on iOS / Android. There might be device specific issues. If the issue persists, go to options inside the app and press "report a bug", after it give us the generated code, so we can show it to mobile team

**Comment by AkechiShiro** [comment]
Closing works on latest mobile app.
