### ISSUE TITLE
Bug in displaying certificates

### ISSUE THREAD

**Issue by andzhrv** [flipperdevices/flipperzero-firmware#2904]
### Describe the bug.

Сertification number of radio equipment displayed together with other certificates
![Screenshot-20230720-155921](https://github.com/flipperdevices/flipperzero-firmware/assets/28702439/40e91418-3d95-4278-ace0-ffbe4939538c)
![Screenshot-20230720-155906](https://github.com/flipperdevices/flipperzero-firmware/assets/28702439/9b231dd3-442d-4f35-b841-aaa5cc86b199)

### Reproduction

1. go to Settings > About
2. scroll to the page with radio equipment marking
3. press the Back button
4. certification number from the previous page displayed together with other certificates

### Target

FW version 0.87.0

**Comment by skotopes** [comment]
Fixed
