### ISSUE TITLE
Bluetooth Devices Scanner

### ISSUE THREAD

**Issue by Fishrock123** [flipperdevices/flipperzero-firmware#2906]
### Description of the feature you're suggesting.

It would be cool if Flipper Zero could scan for bluetooth devices and show detailed info.

I have a bluetooth device which I think may be malfunctioning since I can't detect it from an iPhone but I think flipper could do more, detect if there is any signal / information even if it is incorrect, for debugging other devices.

**Comment by skotopes** [comment]
That is possible with full radio stack. It requires additional space in flash memory which we don't have. So currently it is impossible.

We are currently talking with ST about that, we may return to this feature at some point in future.

**Comment by Fishrock123** [comment]
What is ST? Is it possible to make this as an application that can be downloaded onto the SD card from the list of applications?

**Comment by skotopes** [comment]
@Fishrock123 this one https://www.st.com/content/st_com/en.html
nope it's not application it's core2 firmware.

**Comment by jkramarz** [comment]
@skotopes, is BLE Central role still missing in the firmware?

**Comment by skotopes** [comment]
@jkramarz there is not enough memory(both ram and flash) for full stack.
