### ISSUE TITLE
Option to disable emotions

### ISSUE THREAD

**Issue by adryd325** [flipperdevices/flipperzero-firmware#2908]
### Description of the feature you're suggesting.

An option to disable emotions other than happy would be appreciated. I legitimately feel bad whenever I don't use my flipper for a while because of the angry mode

**Comment by skotopes** [comment]
That is a part of the character ;-)

**Comment by domints** [comment]
It's also unnecessarily wearing out EEPROM. It was fun for the first year, now it's more annoying than anything :) I'd love to skip on emotions and leveling. Just make flipper flip :)

**Comment by portasynthinca3** [comment]
By they way, we added an optional happy mode in #3863 (part of the 1.0 firmware release)

**Comment by domints** [comment]
Just got information from my friends about firmware 1.0, and that's great! But I looked at the PR and it looks like it didn't stop writing status info to eeprom, just ignores what's in there, doesn't it?
