### ISSUE TITLE
Flipper crashing on infrared remote loading

### ISSUE THREAD

**Issue by minchogaydarov** [flipperdevices/flipperzero-firmware#2914]
### Describe the bug.

Flipper crashes with "furi_check failed" when trying to use infrared remote.

### Reproduction

1. Select the IR remote
2. When opening it the Flipper crashes

Loading screen when remote is selected
![Screenshot-20230722-180408](https://github.com/flipperdevices/flipperzero-firmware/assets/134236905/8507377d-93e9-4bee-a1ad-2137f4c7c548)

Right after the crash
![Screenshot-20230722-180350](https://github.com/flipperdevices/flipperzero-firmware/assets/134236905/dd977d07-6965-4d70-84f5-645390c14316)

Remote used (it's a zip file as GitHub does not allow uploading of .ir files)
[Daikin FTXC35DV1B Full.ir.zip](https://github.com/flipperdevices/flipperzero-firmware/files/12136713/Daikin.FTXC35DV1B.Full.ir.zip)

**Comment by skotopes** [comment]
Basically it runs our of memory because of remote size. We'll change how we load big files in future updates.

**Comment by skotopes** [comment]
It's going to take some time because of required refactoring. Meanwhile you can split remote into multiple files.

**Comment by skotopes** [comment]
Was fixed some time ago. Latest release should work without issues.
