### ISSUE TITLE
Enhancement to BadUSB to support Flipper as USB networking device

### ISSUE THREAD

**Issue by marshallmassengill** [flipperdevices/flipperzero-firmware#2917]
### Description of the feature you're suggesting.

Thank you all for making this! It would be awesome to have support for attaching to a host over USB but appearing as a networking device. This is possible via TinyUSB with their implementation of emulating a RNDIS/CDC-ECM device (https://github.com/hathach/tinyusb/tree/master/examples/device/net_lwip_webserver). They actually go so far as to provide a DHCP server and web server with it.

It looks like the TinyUSB project does support the STM32WB55 as a target but I have no idea if this can be done with how the Flipper is setup. I'd love some input from folks with a bit more knowledge of the firmware stack to weigh in. It seems possible to me and I'm a bit shocked it hasn't been done already (or maybe it has and I just can't find it).

**Comment by skotopes** [comment]
That is possible, but requires additional RAM/ROM which will be quite difficult to allocate. We are planning to implement it after next hardware generation arrive.
