### ISSUE TITLE
GPIO: Second UART MiTM

### ISSUE THREAD

**Issue by mithrandir42** [flipperdevices/flipperzero-firmware#2932]
### Description of the feature you're suggesting.

Provide a second UART, maybe LPUART pins can be used for this, then the flipper can act as a transparent proxy and log the serial traffic to sd card. A replace pattern might be defined (maybe regex based) to manipulate the serial traffic between the serial devices. Might be useful.

**Comment by skotopes** [comment]
On API level both ports can be accessed simultaneously.
I think your idea can be implemented as external application and at this point we don't plan it implement as a part of firmware itself.
