### ISSUE TITLE
Achievements scenario

### ISSUE THREAD

**Issue by andzhrv** [flipperdevices/flipperzero-firmware#2945]
### Description of the feature you're suggesting.

Now there is a dolphin and its experience in the flipper, which grows when using the device, but the user can use only one function and get experience only for it.
It would be great to implement a scenario of achievements, to give achievements for different scenarios of using the device.
Here are some examples:
- the first nfc card reading
- the first reading of the animal chip
- connecting an external Sub-GHz module
- successful authorization using the u2f token

**Comment by skotopes** [comment]
We are going to redesign this system entirely for next device generation. Meanwhile I'll close this issue.
