### ISSUE TITLE
Name clipping during nfc emulation

### ISSUE THREAD

**Issue by Leptopt1los** [flipperdevices/flipperzero-firmware#2963]
### Describe the bug.

When emulating .nfc with some names, the last character of the file name is displayed incorrectly.

![gui_bug](https://github.com/flipperdevices/flipperzero-firmware/assets/53914086/fb74275c-53bd-4acd-81a1-4eff19a0a1b1)

### Reproduction

1. Create/add .nfc file with name "[AC] 008 - Timmy"
2. Emulate it

**Comment by skotopes** [comment]
fixed in #2967
