### ISSUE TITLE
RAW SubGHz Signal Editor

### ISSUE THREAD

**Issue by EasyAntiCheatSoftware** [flipperdevices/flipperzero-firmware#2979]
### Description of the feature you're suggesting.

An editor for RAW SubGHz files where you can cut off certain parts of a signal to get a cleaner signal. I know you can get a good signal with RSSI Threshold, but it would be useful to be able to edit the RAW capture later on. in addition, you should be able to merge raw signals together, so you can have one file to trigger multiple signals multiple times. this could be useful if you’re trying to combine a raw signal from the internet and one raw signal that you have recorded.

**Comment by skotopes** [comment]
We don't store RSSI value in RAW file, that make impossible to make meaningful editor for RAW files.

**Comment by EasyAntiCheatSoftware** [comment]
> We don't store RSSI value in RAW file, that make impossible to make meaningful editor for RAW files.

love how didn't talk about what I mainly suggested.

**Comment by skotopes** [comment]
@AmongusGaming you do understand what exactly we store in subghz RAW files? If you do understand, can you imagine some editing tool for it? How it will look like? 

Anyway, there are no plans on designing such tools from our side, but we may revisit this topic later.

**Comment by EasyAntiCheatSoftware** [comment]
> @AmongusGaming you do understand what exactly we store in subghz RAW files? If you do understand, can you imagine some editing tool for it? How it will look like? 
> 
> 
> 
> Anyway, there are no plans on designing such tools from our side, but we may revisit this topic later.

Ok, fair enough.

**Comment by Lechnio** [comment]
@EasyAntiCheatSoftware I've recently done one! 

https://github.com/Lechnio/SubGHz-RAW-Edit

for now version 1.4 allows to save/cut regions of RAW .sub files. Merging is planned for 1.5 along with some other cool stuff

**Comment by EasyAntiCheatSoftware** [comment]
> @EasyAntiCheatSoftware I've recently done one! 
> 
> https://github.com/Lechnio/SubGHz-RAW-Edit
> 
> for now version 1.4 allows to save/cut regions of RAW .sub files. Merging is planned for 1.5 along with some other cool stuff

That's awesome! Looks like my question was answered after 3 years. :) Your project looks great, thanks for putting the time into creating this!

**Comment by EasyAntiCheatSoftware** [comment]
> @AmongusGaming you do understand what exactly we store in subghz RAW files? If you do understand, can you imagine some editing tool for it? How it will look like? 
> 
> 
> 
> Anyway, there are no plans on designing such tools from our side, but we may revisit this topic later.

Looking back on this thread I know realize how stupid I sound in my response, haha

**Comment by Lechnio** [comment]
> > @AmongusGaming you do understand what exactly we store in subghz RAW files? If you do understand, can you imagine some editing tool for it? How it will look like?
> > Anyway, there are no plans on designing such tools from our side, but we may revisit this topic later.
> 
> Looking back on this thread I know realize how stupid I sound in my response, haha

Everyone's learning all the time :D For me this project is a good way to understand how signal processing works in Flipper ecosystem. 
For example today I've just added feature to load KeeLoq recognized signals as RAW again. So you can use regular Read and then save it all as RAWs. What I learned is 'decode' feature requires some additional empty data (~1.5ms) to properly decode RAW as KeeLoq again. I was to lazy to go out and check if the garage gate will understand the signal without this padding haha It would usefull gap between seperate merged signals tho
