### ISSUE TITLE
Unknown RFID (125 kHz) protocol identification/support request

### ISSUE THREAD

**Issue by FerralFred** [flipperdevices/flipperzero-firmware#2981]
### Description of the feature you're suggesting.

We recently got new cards to access the trash room in our building. It's a generic white card with no text on it. Flipper identifies the reader as 125kHz. I created a raw dump. ASK is empty, PSK is here: [RfidRecord22.psk.zip](https://github.com/flipperdevices/flipperzero-firmware/files/12334739/RfidRecord22.psk.zip)

Can anyone identify which type of card that is and if there is any chance flipper will support it?

**Comment by skotopes** [comment]
@FerralFred this recording doesn't contains any meaningful data, most likely this card is NFC or Reader Talk First RFID. Anyway we need more details on reader and system.

**Comment by skotopes** [comment]
We need system/card vendor and model number. Please reopen when you get it.
