### ISSUE TITLE
Some external apps are no longer available

### ISSUE THREAD

**Issue by dogtopus** [flipperdevices/flipperzero-firmware#2985]
### Describe the bug.

Some external apps (e.g. nfc_magic, dap_link, etc.) are no longer available in both the firmware and the new app catalog.

### Reproduction

1. Update to 0.89.0
2. Check the apps
3. Check the app catalog in the Flipper app
4. Some apps are no where to be found

### Target

f7

**Comment by hedger** [comment]
Should be fixed now - some builds were lost on their way to GitHub workflows.
Reopen if issue is still there.
