### ISSUE TITLE
RFID Card Support

### ISSUE THREAD

**Issue by scottod75** [flipperdevices/flipperzero-firmware#2991]
### Describe the enhancement you're suggesting.

I have RAW reading of my RFID cards. 
How can I make this work on my Flipper Zero?

### Anything else?

Here are the links to the raw data files:
[Card1](https://drive.google.com/file/d/1IM82S8uk7lNG2ezTFxhiDoFWhsrRqfVg/view?usp=drivesdk) 

[card2](https://drive.google.com/file/d/1WYKOxwqC3_hu5Vf8KtpwzfiLGYK1zIU1/view?usp=drivesdk)

**Comment by skotopes** [comment]
those files doesn't contain any meaningful data, it's either NFC or ReaderTalkFirst RFID. We need more info on this system

**Comment by skotopes** [comment]
We need system/card vendor and model number. Please reopen when you get it.
