### ISSUE TITLE
NFC-F Saving and Emulation

### ISSUE THREAD

**Issue by Jeshii** [flipperdevices/flipperzero-firmware#3020]
### Description of the feature you're suggesting.

There are some NFC cards show as "NFC-F" - while they can be read using flipper, they cannot be saved or emulated. It should treat them like any of the other NFC cards (like Amibos and whatnot) and have a More menu with Save and Emulate options.

**Comment by optix2000** [comment]
Relevant PR: https://github.com/flipperdevices/flipperzero-firmware/pull/2093

**Comment by skotopes** [comment]
Felica support arrived recently. However only card ID emulation.
