### ISSUE TITLE
Incorrect regional restrictions for Malaysia

### ISSUE THREAD

**Issue by yunaranyancat** [flipperdevices/flipperzero-firmware#3023]
### Describe the enhancement you're suggesting.

Currently, Malaysia is listed under 

![image](https://github.com/flipperdevices/flipperzero-firmware/assets/22954096/27de0a89-85ef-435f-a2d4-d5d0b81ec3f9)

However, based on the restrictions by MCMC's class assignment , [pdf](https://www.mcmc.gov.my/skmmgovmy/media/General/registers/cma/Class-Assignment-No-2-of-2022.pdf); it does not allow ;

- 315Mhz (which is included in the list)

![image](https://github.com/flipperdevices/flipperzero-firmware/assets/22954096/b1233c7c-5cc8-4154-870b-45ccc8339d36)

### Anything else?

Nothing

**Comment by skotopes** [comment]
@yunaranyancat There are multiple class assignments that can be used for flipper:

- Short-range Radiocommunication Device
- Remote Controlled Device
- Security Device
- Radio Frequency Identification Device
- Industrial, Scientific and Medical Device

Combination of them actually gives even richer band set. We'll talks with our certification lab to clarify which one we applied for and then I'll update configuration.

**Comment by skotopes** [comment]
Region was updated according to https://www.mcmc.gov.my/skmmgovmy/media/General/registers/cma/Class-Assignment-No-2-of-2022.pdf, paragraph 11. Security Device
