### ISSUE TITLE
Unsupported remote

### ISSUE THREAD

**Issue by xeowww** [flipperdevices/flipperzero-firmware#3039]
### Description of the feature you're suggesting.

Hello. Please help me to make the support of my remote of doors.
Frequency - 433.92
[Photos Remote 1](https://uploadnow.io/f/LsmK4qs)
[Records of RAW signals 1](https://uploadnow.io/f/yr41KFl)

**Comment by Skorpionm** [comment]
your links are not available.

**Comment by xeowww** [comment]
> your links are not available.

Now they are available, please check

**Comment by Skorpionm** [comment]
This is the Keeloq protocol and is supported in flipper. but there is no factory key for your remote manufacturer. To get it you need the chip itself on my table. but the result is also not guaranteed.

**Comment by skotopes** [comment]
Links are dead, please provide photos of the remote and vendor/system name/model.

**Comment by skotopes** [comment]
Feel free to reopen if you have with requested data.
