### ISSUE TITLE
FM1208-10 read does not read more than UID

### ISSUE THREAD

**Issue by team-orangeBlue** [flipperdevices/flipperzero-firmware#3041]
### Describe the bug.

Using FM1208-10 (Fudan MFC 1K + 7K Smartcard) with flipper does not work with the Mifare Classic part. Instead, the flipper stops immediately and says that the tag is of unknown ISO.

![image](https://github.com/flipperdevices/flipperzero-firmware/assets/63470411/bac51069-51ea-4c72-917c-27375cdc3ee0)

While you can force a Mifare classic read from extra actions, it appears to be useless and does not find any keys. The tag is keyed using default FF-FF keys, except for key 0A (but it is in the user dictionary): 
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/63470411/202a3ab9-46d1-4264-a528-b98ee8b3cd93)

### Reproduction

1. Get a FM1208-10 (they cost 2.8 CNY on taobao and are called "CPU card")
2. Use with proxmark, phone, so on, anything with Mifare Classic support - they read the memory.
3. Use with flipper - instantly quits even though SAK claims support for Mifare classic.

### Target

f-7

### Logs

```Text
433406 [I][DolphinState] State saved
434438 [I][FuriHalNfc] Deinit OK
434566 [I][FuriHalNfc] Init OK
434571 [D][DolphinState] icounter 3731, butthurt 0
434578 [T][FuriHalNfc] State change 0 -> 10
434707 [T][FuriHalNfc] State change 10 -> 20
434879 [T][FuriHalNfc] Timeout
434985 [T][FuriHalNfc] State change 0 -> 10
435112 [T][FuriHalNfc] State change 10 -> 20
435286 [T][FuriHalNfc] Timeout
435390 [T][FuriHalNfc] State change 0 -> 10
435517 [T][FuriHalNfc] State change 10 -> 20
435691 [T][FuriHalNfc] Timeout
435795 [T][FuriHalNfc] State change 0 -> 10
435922 [T][FuriHalNfc] State change 10 -> 20
436096 [T][FuriHalNfc] Timeout
436200 [T][FuriHalNfc] State change 0 -> 10
436335 [T][FuriHalNfc] State change 10 -> 11
436361 [T][FuriHalNfc] State change 11 -> 13
436374 [T][FuriHalNfc] State change 13 -> 30
436419 [I][FuriThread] NfcWorker allocation balance: 0

[ . . . ]
>: nfc detect
Detecting nfc...
Press Ctrl+C to abort
Found: NFC-A UID length: 4, UID:AE0F500B

>: _
```

### Anything else?

Did this happen from the EMV removal change? There probably should be an ATS checker (for FM1208-10 it is `10 78 80 90 02 20 90 00 00 00 00 00 [Tag UID here]`)

**Comment by doomwastaken** [comment]
@team-orangeBlue could you check your issue again with latest firmware, we need details after NFC refactor

**Comment by team-orangeBlue** [comment]
> @team-orangeBlue could you check your issue again with latest firmware, we need details after NFC refactor

[ Reply ETA approx. 6h30min ]

**Comment by team-orangeBlue** [comment]
> @team-orangeBlue could you check your issue again with latest firmware, we need details after NFC refactor

I like this approach...
thank you!
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/63470411/5fa5ccdb-a5c3-485b-b4a2-b73361962d13)


Hopefully there will be some sort of parsing ATS.
Oh also some post edit - MFC part works flawlessly

**Comment by gornekich** [comment]
@team-orangeBlue you can read your tag as ISO14443-4A and there will be parses ATS information on Info screen

**Comment by team-orangeBlue** [comment]
> @team-orangeBlue you can read your tag as ISO14443-4A and there will be parses ATS information on Info screen

By that I meant the "Unknown" part.
I tapped some Mifare plus tags, but they didn't have definitions either.
