### ISSUE TITLE
fsck the sd card

### ISSUE THREAD

**Issue by ThatServerGuy** [flipperdevices/flipperzero-firmware#3042]
### Description of the feature you're suggesting.

Need the ability to fsck the sd card from the firmware menu. 

### Anything else?

Had an app crash and the sd card is not functioning. Need ability to fsck from firmware to repair card. Otherwise you need to connect to another device to repair the file system.

**Comment by skotopes** [comment]
This task is memory and computational heavy. Performing it on flipper is impossible.
