### ISSUE TITLE
Toolchain version is not supported.

### ISSUE THREAD

**Issue by ajsdomingues** [flipperdevices/flipperzero-firmware#3054]
### Describe the bug.

receive this error ether on macos and on windows 

after this 

git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git

when I try to compile with ./fbt

get this all the time

scons: *** Toolchain version is not supported. Allowed: (' 10.3.',), toolchain:    Stop.

### Reproduction

git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git

./fbt

**Comment by unixispower** [comment]
I ran into this same issue on a fork of this firmware. I ran `source scripts/toolchain/fbtenv.sh` and then `env` and noticed toolchain directories in my `PATH` entries had a space in the filename. Removing the space from the name of the parent directory allowed me to run `./fbt` without error.

**Comment by Lixczyy** [comment]
@unixispower This fixed the issue for me. huge thanks. But now I get the error:         


LINK    build\f7-firmware-C\firmware.elf
g:/flipper_zero/unleashed-firmware/toolchain/x86_64-windows/bin/../lib/gcc/arm-n
one-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: build/f7-firmware-C/lib\li
bflipper7.a(furi_hal_bt.o): in function `furi_hal_bt_get_conn_rssi':
G:\flipper_zero\unleashed-firmware/firmware\targets\f7\furi_hal/furi_hal_bt.c:47
7: undefined reference to `gap_get_remote_conn_rssi'
collect2.exe: error: ld returned 1 exit status
scons: *** [build\f7-firmware-C\firmware.elf] Error 1

********** FBT ERRORS **********
build\f7-firmware-C\firmware.elf: Error 1
