### ISSUE TITLE
Keeloq unknown: Fantom/Highland T3401 gate remote

### ISSUE THREAD

**Issue by wosk** [flipperdevices/flipperzero-firmware#3085]
### Description of the feature you're suggesting.

This remote decoded by Flipper as KeeLoq with unknown manufacturer code.
Please add support for it.

![image](https://github.com/flipperdevices/flipperzero-firmware/assets/1042932/dbba55f9-2036-488c-afb6-da6f48875ef0)

433.92MHz
KeeLoq
FCC ID unknown

Initial link: https://forum.flipper.net/t/fantom-highland-t3401-gate-remote/16804
Also description about ancient S2x4.sub
![photo_2023-09-15_12-00-47](https://github.com/flipperdevices/flipperzero-firmware/assets/1042932/35e3e8b5-2b10-4847-aadb-48e066fa8e91)
Extra video https://youtu.be/EA10QZKUlQ0

[fantom.zip](https://github.com/flipperdevices/flipperzero-firmware/files/12617593/fantom.zip)

**Comment by skotopes** [comment]
We are waiting for this remote to arrive to our office.

**Comment by haliliceylan** [comment]
+1

**Comment by Skorpionm** [comment]
I got my hands on this remote control. and I managed to get the encryption key from it, but as always there is a “BUT”. this system uses Normal Learning encryption, that is, to obtain the encryption key, the serial number of the key fob + the manufactory key of the system is used and the resulting key is stitched into the key fob, that’s what I received, that is, it can only be used with a key fob with that serial number and not with the entire system
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/85568270/b7dbf7a4-dab2-4986-b336-41afc36d1ce3)
that is, the manufactory key is not physically stored in the key fobs of this system, and to obtain it you need to pick the receiver.

if you know the model of the receiver from this system, with an STM32 chip, I will get the manufacture key from it

**Comment by wosk** [comment]
Thanks for your efforts!
According to video https://youtu.be/EA10QZKUlQ0 algorithm is reversible in some kind without access to receiver.

Also in the video receiver R5403 was used.

**Comment by Skorpionm** [comment]
They got the man code for the system somewhere.  but their remote control with "Hold the button" works on the principle of re-sync, record through raw 10 consecutive presses of the button with holding for a second and try replaying

**Comment by tkerby** [comment]
>  ![image](https://private-user-images.githubusercontent.com/85568270/281320725-b7dbf7a4-dab2-4986-b336-41afc36d1ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzUxMDYsIm5iZiI6MTcwMjkzNDgwNiwicGF0aCI6Ii84NTU2ODI3MC8yODEzMjA3MjUtYjdkYmY3YTQtZGFiMi00OTg2LWIzMzYtNDFhZmMzNmQxY2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIxMjY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OWMxNTc2ZmQ5YzEyZTJjMTkyZjJmZjA1MWMyYWFiMWZlMWU2ZGI5ZmY5YmE2Y2VhMzliOWQzZGZjYTk5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._VTyJQAFxjW29Q9cgYH_hWbdjJV2LFg1fTBUFBEDNlo) 

Whats the app you're using there and is it available? I have a few systems I own I'm keen to find manufacturer keys for

**Comment by Skorpionm** [comment]
self-written, it is not publicly available

**Comment by Skorpionm** [comment]
is not possible, the manufacturing code is different for each key fob
