### ISSUE TITLE
Write Mifare Classic 1K

### ISSUE THREAD

**Issue by FlorinBuffet** [flipperdevices/flipperzero-firmware#3088]
### Describe the bug.

In the past i think i was already able to write a Mifare Classic 1K to another chip, this is not possible anymore, i can just update the original card.
Did i miss a nerf or am i just stupid?

### Reproduction

1. Read: Works
2. Emulate: Works
3. Write not available

**Comment by skotopes** [comment]
Never was possible in the first place.

Long story short: you need special card (MFC Magic Card) and NFC Magic app to write MFC dump.
Writing data to another card doesn't make sense because block with UID is read only.
