### ISSUE TITLE
Meshtastic app

### ISSUE THREAD

**Issue by BrunoKlu** [flipperdevices/flipperzero-firmware#3104]
### Description of the feature you're suggesting.

Ability to turn flipper zero into a Meshtascic node using Bluetooth/ meshtastic app / internal or external CC1101

www.meshtastic.org

**Comment by Stefan2483** [comment]
or more powerfull external options like EBYTE SX1278? I think there is an external module working on flipper: Rabbit-Labs - Flux Capacitor - Amplified based on this… there are options. So think of sending Mashtastic message from flipper zero or connected phone via bluetooth

**Comment by skotopes** [comment]
Sounds like idea for an app and hardware module ;-) 

Also at this point we are not planning such feature.

**Comment by grinjerFURRY** [comment]
😭
