### ISSUE TITLE
Flipper crashed an was rebooted: ST(R) Copro(R) HardFault

### ISSUE THREAD

**Issue by FlorianWupper** [flipperdevices/flipperzero-firmware#3113]
### Describe the bug.

After a few days, regardless of the use of my flipper I get the message on the display 
> Flipper crashed an was rebooted: ST(R) Copro(R) HardFault
s anything known in this regard? Is there a possible solution?

I use the firmware version 0.91.4 
The problem already existed in at least two previous versions. 

### Reproduction

Unfortunately, I can't give any hints on how to recreate it. The message simply appears after some time. 

### Target

Solutions, or something

### Anything else?

If further details are required, please let me know. 
Unfortunately, the tips on reddit have not helped me so far.

**Comment by skotopes** [comment]
Known issues, fixed in 0.92
