### ISSUE TITLE
Nightstand Clock | Missing battery level Indicator

### ISSUE THREAD

**Issue by aryanguenthner** [flipperdevices/flipperzero-firmware#3138]
### Describe the enhancement you're suggesting.

Nightstand Clock | Missing battery level Indicator

-Your Flipper could run out of battery and die if the battery percentage/icon is not visible when using Nightstand Clock.
-This is important because you can't see your battery level when using the Nightstand Clock.

**Comment by skotopes** [comment]
In general it's not very good idea to use flipper as night stand clock.
