### ISSUE TITLE
qflipper lost connection while updating the flipper

### ISSUE THREAD

**Issue by leolinchen** [flipperdevices/flipperzero-firmware#3140]
### Describe the bug.

when I download an extern firmware on my flipper, he lost the connection to qflipper or show me that core 2 is busy. But when I download the official firmware then nothing happens.

### Reproduction

1.download any external firmware with the qflipper

### Anything else?

I tried a lot of other things to download the firmware, like withe the chrome downloader or with the flipper lab, but many of them broke up

**Comment by skotopes** [comment]
Please address all questions regarding 3rd party firmware to their authors.
