### ISSUE TITLE
Add-Manually, Security+2.0, won't pair with LiftMaster 850LM

### ISSUE THREAD

**Issue by jamisonderek** [flipperdevices/flipperzero-firmware#3143]
### Describe the bug.

When you do an Add Manually for a Security+2.0, the majority of the time it will not pair with an official 850LM opener.  This is because the lowest 2 bits must be clear, the 2 bits 10-bits in must be clear, and the most significant bit must be clear. If you mask the 32-bit key with 0x7FFFF3FC (which has those 5 bits set to zero) then the key will work.

### Reproduction

Sub-GHz
Add Manually
Security+2.0_315
Save file
Load file
Click "Pair" button on 850LM receiver.
Press OK on Flipper multiple times.  
ACTUAL: Signal never gets paired or will not open the door.
EXPECTED: Flipper Zero is paired and can open the door.

### Target

subghz

**Comment by skotopes** [comment]
@jamisonderek since your PR was merged I'm closing this issue. Thank you for your contribution.
