### ISSUE TITLE
NTAG215 Write

### ISSUE THREAD

**Issue by jlaughter** [flipperdevices/flipperzero-firmware#3162]
### Description of the feature you're suggesting.

Ability to write saved/generated NTAG215 tags.  While emulating into a cellphone and then wroting is a workaround today, workflow would be streamlined by writing directly.

### Anything else?

Screenshots attached of tag and menu options available today.

![IMG_1457](https://github.com/flipperdevices/flipperzero-firmware/assets/53415135/ef9dd1c6-68c9-43fe-82d9-ba46d3df4e19)
![IMG_1458](https://github.com/flipperdevices/flipperzero-firmware/assets/53415135/1e222bf2-faea-45b9-900f-75f65e3a2a4d)
![IMG_1459](https://github.com/flipperdevices/flipperzero-firmware/assets/53415135/79e21a1f-82b1-487b-ad37-49e33d470e63)

**Comment by skotopes** [comment]
Like writing not to the same card but different one?

**Comment by jlaughter** [comment]
Basic write, erase, and lock/unlock of writeable tags/stickers/business cards.   Same card, different card, whatever as long as it’s writeable.  Thanks!

**Comment by CryoPhynix** [comment]
How can I access this?

**Comment by skotopes** [comment]
@jlaughter same card write should be available out of the box. Writing to magic cards(various mifare formats) available in NFC Magic app. Writing to different card with different UID will be available later.

**Comment by CryoPhynix** [comment]
Can I clone mifare 1k classic cards? Like copy the data from one card and write to another?

**Comment by skotopes** [comment]
> Can I clone mifare 1k classic cards? Like copy the data from one card and write to another?

yes. Full clone is only possible with a magic card. Partial clone requires manual actions(copy pasting data you want to destination card dump and writing it back)

**Comment by jlaughter** [comment]
I think there's a disconnect here.  This issue is specifically for NTAG215 tags - URLs, contact info, amiibos, etc.  NOT Mifare. 
 
For NTAG215, emulation is possible, but there's no write capability.   Most mobile phones support NTAG write, so there's a workaround, but it's messy:  Create or read tag with Flipper, Save, Emulate tag with flipper, read tag on mobile with NFC Tools or similar, then write to blank or rewriteable tag with mobile.

**Comment by jlaughter** [comment]
Just added screenshots to original request, linked here:

![IMG_1457](https://github.com/flipperdevices/flipperzero-firmware/assets/53415135/ef9dd1c6-68c9-43fe-82d9-ba46d3df4e19)
![IMG_1458](https://github.com/flipperdevices/flipperzero-firmware/assets/53415135/1e222bf2-faea-45b9-900f-75f65e3a2a4d)
![IMG_1459](https://github.com/flipperdevices/flipperzero-firmware/assets/53415135/79e21a1f-82b1-487b-ad37-49e33d470e63)

**Comment by gornekich** [comment]
Hello @jlaughter !
Took that into work. I will let you know when writing will be implemented

**Comment by gornekich** [comment]
Initial NTAG write came with #3246 . Now flipper can write NTAG213/215/216. The conditions are that both source and destination NTAGs are not locked. So they both have default PASSWORD and PACK and the lock bits are reset. In other case the logic of writing becomes very complicated.

Please, test this feature in lates RC or dev. Soon it will be in release. I will close this issue for now, please reopen it if you have any problems with writing data on unlocked NTAGs. If you have any suggestions on improving this feature, please open another issue with feature request.
