### ISSUE TITLE
It’s a hacking device

### ISSUE THREAD

**Issue by Seso102** [flipperdevices/flipperzero-firmware#3194]
### Description of the feature you're suggesting.

I see if this is a hacking device there shall be no boundaries such as if when you read a car key frequency and try to emanualate it it shouldn’t say not available also since car keys have a detector that doesn’t allow any thing other than the real key and anyway you cannot steal a car since the car has a sensor that detects the key and allows it to start if the real key is inside.
                                       Note 
This is extending a existing function

**Comment by dogtopus** [comment]
Even in its current form, it got quite a lot of bad PR. If there's no restriction at all, it would likely be way worse. Plus the firmware is completely open source and there's nothing really stopping you from adding unsupported features to it anyway.
