### ISSUE TITLE
NFC FeliCa emulation crashes Flipper with null pointer dereference

### ISSUE THREAD

**Issue by ntfshard** [flipperdevices/flipperzero-firmware#3203]
### Describe the bug.

In 0.94.1 seems we can make a shallow copy of FeliCa cards. But attempt to emulate it shows only animation (NFC tools see nothing, but able to see real card) and attempt to close emulation leads to nullptr dereference crash

### Reproduction

1. save any FeliCa card (e.g. Suica transport card)
2. from idle screen, press down to show NFC menu w/ cards. can be other button, but seems this is default
3. select pre-saved card -> middle button -> Run in app
4. animation starts, led starts blinking (but nothing in NFC tool)
5. press back button - crash

### Logs

```Text
Firmware version: 0.94.1 0.94.1 (e487bcd2 built on 01-11-2023)

>: <ERROR: The device has been lost.>
<DISCONNECTED>
```

**Comment by gornekich** [comment]
Hello @ntfshard ! Thanks for the report.
Felica emulation is WIP. The issue will be fixed with #3190 PR

**Comment by 167rgc911** [comment]
> Hello @ntfshard ! Thanks for the report. Felica emulation is WIP. The issue will be fixed with #3190 PR

I have a custom tree with #3190 merged ... will be testing the Felica feature since everything here (Japan) is Felica!
I captured my ICOCA (commuter pass) using old FW and will be emulating it with the dev FW.



*****

EDIT/UPDATE:
dev + #3190 FW does not crash trying to emulate a Felica card BUT readers can't decode the card!

by reader, I am using *actual vending machines* to try to read the emulated card on the Flipper.

**Comment by ntfshard** [comment]
> EDIT/UPDATE: dev + #3190 FW does not crash trying to emulate a Felica card BUT readers can't decode the card!
> 
> by reader, I am using _actual vending machines_ to try to read the emulated card on the Flipper.

I believe for real a vending machine it shouldn't work. I tried on electronic lock which I guess check only something public available data from card

**Comment by 167rgc911** [comment]
> > EDIT/UPDATE: dev + #3190 FW does not crash trying to emulate a Felica card BUT readers can't decode the card!
> > 
> > by reader, I am using _actual vending machines_ to try to read the emulated card on the Flipper.
> 
> I believe for real a vending machine it shouldn't work. I tried on electronic lock which I guess check only something public available data from card

My office ID badge is FeliCa. Read it with the Flipper and I just tapped the Flipper on the door access panel in the office.

Got the invalid card beep.

**Comment by ntfshard** [comment]
> > > EDIT/UPDATE: dev + #3190 FW does not crash trying to emulate a Felica card BUT readers can't decode the card!
> > > by reader, I am using _actual vending machines_ to try to read the emulated card on the Flipper.
> > 
> > 
> > I believe for real a vending machine it shouldn't work. I tried on electronic lock which I guess check only something public available data from card
> 
> My office ID badge is FeliCa. Read it with the Flipper and I just tapped the Flipper on the door access panel in the office.
> 
> Got the invalid card beep.

In some offices are using suica cards (transport cards) to enter

**Comment by Jeshii** [comment]
My FeliCa that I use to get into my office was able to be read and saved but there is no emulate button (0.95.0). My card does not work for transit. Let me know if there is anything I could help test

**Comment by 167rgc911** [comment]
0.95.0 OFW

this is other way to 'emulate'

from the idle screen, 
press DOWN button
select saved card, UP/DOWN, then CENTER
press CENTER again ("Run in app")

this is weird because 'Emulating Felica' crashes on OFW!

i built the FW previously 'dev + #3190' and there was NO crash. 3190 is FL-3640.

maybe FL-3686 is causing this crash?

**Comment by ntfshard** [comment]
Tried devel branch, it's working: not crashing, id emulates and door are opens.
Thanks!

**Comment by 167rgc911** [comment]
0.95.0 OFW does not include FL-3640/#3190! That's why i'm getting the crash again Orz~

**Comment by gornekich** [comment]
Now we can emulate FeliCa UID only. We are working to extend FeliCa tags support. 
I will close this issue for now. Please, reopen this Issue if you still have the problem.
