### ISSUE TITLE
Re-open of #1923: Subghz raw sub transmits an unwanted signal at the beginning (OOK 433MHz) #1923 

### ISSUE THREAD

**Issue by coded-with-claws** [flipperdevices/flipperzero-firmware#3228]
### Describe the bug.

Hi,
Following closure of #1923, I retried the same sub file. There is stil an unwanted preamble (but not exactly the same as before).

- unwanted preamble
  - sends ON for duration ~1065 (selected in blue on the screenshot)
  - sends OFF for ~1010 (just after the selected blue)
- then applies the content of the raw sub (1700, -900, etc.).

I'm not sure it's really disturbing the receiving devices generally, but if it's fixable, why not :)
[example.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13400652/example.sub.txt)
![unwanted_preamble](https://github.com/flipperdevices/flipperzero-firmware/assets/79459323/a1bb343f-513a-4d07-b1a9-8418ad7c0f93)

Thanks :)

### Reproduction

Download the attached .sub.txt file, rename to remove the ".txt" (which was added because of github supported file types).
Open it in the Subghz application and hit Send, and capture in urh with a RTL SDR dongle.

**Comment by skotopes** [comment]
Yep looks like 2nd transmission starts incorrectly. We'll fix it in next release.

**Comment by Skorpionm** [comment]
@coded-with-claws  check fix plz https://github.com/flipperdevices/flipperzero-firmware/pull/3230

**Comment by coded-with-claws** [comment]
@Skorpionm Nice your fix works great, I only get the signal configured into sub file now!! :) Thanks!! :+1:
