### ISSUE TITLE
Remove update file after install

### ISSUE THREAD

**Issue by polarikus** [flipperdevices/flipperzero-firmware#3240]
### Describe the enhancement you're suggesting.

After installing the firmware, any update's accumulate in the updates folder that need to be cleared manually. I suggest deleting the update file after successful installation.

There are two possible implementation options:
1. Add a "Delete update file" button in the window notifying you of a successful update. This option will be selected by default, but the user can simply select "OK" if they want to save the file.
2. Delete the file without asking the user.

### Anything else?

I could make a pull request for this improvement, unless there are some reasons that are not obvious to me to save the update files. If you accept this improvement, we can discuss implementation options.

**Comment by hedger** [comment]
Removing old updates is as easy as removing the "update" folder from the root of SD card. We're not planning to do that automatically.

Update packages are all placed in a single folder, don't take up much space and provide a way to quickly roll back the firmware and apps to any previous release you installed. Besides that, they contain a backup of internal storage which sometimes is useful for restoring an accidentally corrupted or formatted internal storage.
