### ISSUE TITLE
NFC emulation time

### ISSUE THREAD

**Issue by 4RH1T3CT0R7** [flipperdevices/flipperzero-firmware#3247]
### Describe the bug.

On the latest devbiild the time of mifare 1k emulation started to take as much as 3 seconds. Previously, such an action was instantaneous

### Reproduction

Emulate nfc
Bring it to the reader
Wait

**Comment by gornekich** [comment]
Hello @4RH1T3CT0R7 . Could you please specify what time your are talking about. What reader do you test with? Also could you please provide logs from Flipper during emulation

**Comment by 4RH1T3CT0R7** [comment]
> Hello @4RH1T3CT0R7 . Could you please specify what time your are talking about. What reader do you test with? Also could you please provide logs from Flipper during emulation

When you turn on emulation, it takes 3-4 seconds to trigger on the reader, before it was instantaneous. I can't find out the model of the reader, and how can I find the log files?

**Comment by 4RH1T3CT0R7** [comment]
> Hello @4RH1T3CT0R7 . Could you please specify what time your are talking about. What reader do you test with? Also could you please provide logs from Flipper during emulation

any news?

**Comment by 4RH1T3CT0R7** [comment]
also idk how to identify reader type

**Comment by gornekich** [comment]
I will add some logs during emulation to research why reader starts to read flipper's emulation longer. Currently the only possible way is to sniff communication between flipper and reader with another device, like proxmark

**Comment by 4RH1T3CT0R7** [comment]
> I will add some logs during emulation to research why reader starts to read flipper's emulation longer. Currently the only possible way is to sniff communication between flipper and reader with another device, like proxmark

I haven't got proxmark
Btw, I can send you 2 videos with emulation process: before refactor and after

**Comment by 4RH1T3CT0R7** [comment]
By the way, if you read with your phone, emulation happens as before, but the reader reacts after 5 seconds

**Comment by 4RH1T3CT0R7** [comment]
https://drive.google.com/drive/folders/1ziSt-ydii-sZwqtezFFtap5nkykGNdnn?usp=drive_link
Big thanks to FLozy for providing videos

**Comment by gornekich** [comment]
There were some issues fixed in MFC emulation. Please update firmware to latest RC or dev and try to reproduce this issue

**Comment by 4RH1T3CT0R7** [comment]
> There were some issues fixed in MFC emulation. Please update firmware to latest RC or dev and try to reproduce this issue

Still the same problem

**Comment by 4RH1T3CT0R7** [comment]
![IMG_20231220_092201_415](https://github.com/flipperdevices/flipperzero-firmware/assets/146867384/a712e808-0cda-4a2d-bc06-0ba3d86b363e)
Reader
Maybe PERCo-MK-KT02.9

**Comment by 4RH1T3CT0R7** [comment]
So? Any news?
