### ISSUE TITLE
API Services for communication between FAPs

### ISSUE THREAD

**Issue by leedave** [flipperdevices/flipperzero-firmware#3252]
### Description of the feature you're suggesting.

Applications should be able to offer Services to other applications. From my current understanding this is not possible or only in a very limited way. 

Example: If a new application wants to offer SubGhz features, it needs to rebuild the whole SubGhz/RxTx logic just to be able to send data. The official SubGhz app however is constantly being updated, new protocols implemented etc. Anything new will be missing in the app that rebuilt the logic. It would be nice if the SubGhz app could simple provide some service API, so that other apps can simply ping it with data that needs to be sent or request it to listen for a datastream. 

From my current knowledge this is currently not possible, if this feature however already exists, it would nice to have some instructions on how to do it.

**Comment by skotopes** [comment]
@leedave SubGhz and all other apps are split into layers: HAL + library + UI. Integrating with lib+hal layer already gives you what you want.
