### ISSUE TITLE
Add the ability to rollback a firmware update that has already been installed

### ISSUE THREAD

**Issue by PPPDUD** [flipperdevices/flipperzero-firmware#3255]
### Describe the enhancement you're suggesting.

Whenever the Flipper Zero does a firmware update, it saves a file on the micro-SD card, seemingly for performing update rollbacks.

However, I have not seen any implementation of this functionality on either the front or back end of the Flipper Zero and its associated companion apps.

### Anything else?

Consider deleting the oldest update rollback file every six updates, to save space.

**Comment by hedger** [comment]
Just navigate to the update folder from Archive Browser on your Flipper ("down" button on desktop) and pick the update file with a distinct icon.
