### ISSUE TITLE
Flipper CLI input command no longer works

### ISSUE THREAD

**Issue by ase1590** [flipperdevices/flipperzero-firmware#3256]
### Describe the bug.

attempting to do commands such as `input send up short` via flipper cli results in no UI change on the flipper itself. none of the other button types are working as well

### Reproduction

1. connect to flipper CLI via serial
2. attempt to use the `input` command in any fashion

### Anything else?

This seems to have been broken for quite some time, as rolling back from 0.95 all the way to 0.71 presented the same issue.

**Comment by jolly-exe** [comment]
same issue

**Comment by skotopes** [comment]
@jolly-exe @ase1590 you are doing it wrong.

All system input sources(including cli or rpc) must produce following sequence:
- press
- short or long 
- if it was long, then repeat
- release
