### ISSUE TITLE
Menu navigation buttons

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3257]
### Description of the feature you're suggesting.

Currently menu navigation works with "Up-Down-OK-Back". It's possible to add a "Left-Right" buttons? Like on a Samsung TV's. Left for back, right for OK.

**Comment by skotopes** [comment]
Can you elaborate? Are we talking about main menu, submenu, apps?

**Comment by Tomi2965** [comment]
Main menu, submenus, app list, file list. 

Example: I want to open NFC menu. On main screen hit OK, then scroll to NFC, press right, but then I want to go back, and open RFID. So press left (back to main menu), up (from NFC to RFID), right (open RFID). Then I want to open Read - just press right.  

As I see, in app list/file list is left for back working. Much better than press back button in main menu/submenus :)

**Comment by skotopes** [comment]
That was made intentionally to simplify UX.
