### ISSUE TITLE
Frequency analyzer: 434 subghz bug

### ISSUE THREAD

**Issue by h0us3c4ll** [flipperdevices/flipperzero-firmware#3259]
### Describe the bug.

When using the frequency analyzer, i have seen that the Flipper detects 434.189, but then records 434.176. this is not always, but sometimes. it is not hopping, but there is something wrong i think

### Reproduction

1. use frequency analyzer
2. wait for signal, Flipper finds 434.189
3. Flipper records it as 434.176 instead

**Comment by hedger** [comment]
So, what's the problem? Is something not working?

**Comment by skotopes** [comment]
@h0us3c4ll couple things to keep in mind:
- flipper is not precise lab measurement equipment
- your hardware oscillator frequency can deviate 
- flipper subghz oscillator frequency can deviate up to 40ppm
- detected frequency is approximation

Other than that I do not see any issues with acquired value, it deviates but will be usable in subghz app

**Comment by h0us3c4ll** [comment]
ok, thanks!
