### ISSUE TITLE
Dual NFC + RFID card emulation

### ISSUE THREAD

**Issue by Semper-Viventem** [flipperdevices/flipperzero-firmware#3266]
### Description of the feature you're suggesting.

There are access cards that combine EM4100 and Mifare Classic at once ([like this one](https://www.amazon.com/Frequency-125khz-EM4100-13-56Mhz-Classic/dp/B07C4NTKG5?th=1))
It would be nice to be able to run both applications at once

**Comment by skotopes** [comment]
Not going to work, we share some pins between RFID and NFC.
Also running NFC + RFID subsystems simultaneously is a challenge on its own.
