### ISSUE TITLE
Quansheng UV-K5 Radio programmer APP

### ISSUE THREAD

**Issue by BrunoKlu** [flipperdevices/flipperzero-firmware#3267]
### Description of the feature you're suggesting.

Quansheng UV-K5 radio brought firmware customization to portable radios. There are so many firmwares for it with different features that it happens a lot to switch from one to the other. I was wondering if it could be possible to make an app where we load a bunch of different firmwares on Flipper’s SD card, and then program the radio thru GPIO on demand.

**Comment by skotopes** [comment]
Possible. But this repo is only about FZ firmware.
