### ISSUE TITLE
USB - Universal reader for better production

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3269]
### Description of the feature you're suggesting.

It's possible to add a "Universal USB reader" function? I think, not only for me will this funtion make life much easier. 

At my work, we are using iButtons, RFIDs, and Mf/Mf+ tokens for customers. When we order a new tokens, I always need to add all tokens to evidence. So, I must use three different readers. It will be seriously fine, to allow FZ to be used as universal USB reader. After connect will FZ act as keyboard, and directly write readed UIDs. Scenario for example: new order arrived. Go to menu - RFIDs - select (new) Universal USB reader function - select Activate. Then FZ will read all RFID tokens, and send codes to USB. 

Another helpful function: after activate reading without USB connected, just store readed UIDs to file - this will be seriously helpful when needed to read more than one token "in terrain" (like when customer have 10 iButtons, numbers are not visible and I need to collect all 10 UIDs for permission change). After connect to USB just re-type like BadUSB, or download file from SD card. 

Configurable options: ending of code (CR, LF, CRLF, ...), buzzer on read, vibro on read, lock keyboard during reading, KBD layout, store to file. 

Complication: Mifare Classic 1K and Mifare+ tokens from manufacturer FDI Matelec (France) have reversed order of UID programmed in chip (code printed on token is for example 2BAF5678, but afetr read UID is 78 56 AF 2B). So, I can't imagine, how to make a proper settings/database for UID translation to desired format/output (I need UID to be reversed from 78 56 AF 2B to 2BAF5678). Mifare+ tokens are also reversed, but UID is longer of course. 

Thanks for any support.

**Comment by skotopes** [comment]
That does sounds like an idea for application. Some combo of APP with USB-HID will be right for your needs.
However this repository is only about FZ firmware itself.
