### ISSUE TITLE
CLI - Ability to load and transmit a raw subghz .sub file

### ISSUE THREAD

**Issue by rcork** [flipperdevices/flipperzero-firmware#3278]
### Description of the feature you're suggesting.

I've captured several subghz raw files that i'd love to be able to use the CLI to transmit. Currently the CLI doesnt' support loading a raw sub file and transmitting. If it was possible to use the CLI to load and transmit the raw signal, we could create automations using the CLI.

**Comment by Skorpionm** [comment]
check plz https://github.com/flipperdevices/flipperzero-firmware/pull/3302
CLI: subghz tx_from_file <file_name> [<repeat: count> <device: 0 - CC1101_INT, 1 - CC1101_EXT>]

plays any files, not just RAW

**Comment by Skorpionm** [comment]
added to dev

**Comment by Skorpionm** [comment]
done
