### ISSUE TITLE
Command Line Interface Bug

### ISSUE THREAD

**Issue by Hari-B6** [flipperdevices/flipperzero-firmware#3279]
### Describe the bug.

After opening **Flipper CLI** in Flipper Labs _(or any other CLI)_ and typing "nfc" or "nfc help", **nothing** shows in the command list.

### Reproduction

1. Connect Flipper Zero to PC via USB cable
2. Go to the Flipper Lab website _(https://lab.flipper.net/cli)_
3. Enter the CLI Tab
4. Type **_nfc_** or **_nfc help_**

**Comment by m1-ins** [comment]
On current build there are no commands available currently. A link to relevant documentation describing the usage of the NFC command can be found here:

https://docs.flipper.net/development/cli

TLDR: There is only one command, requires debug mode, and is used mainly in factory testing to control NFC communications field.

Obviously if people want commands to be created for the command line then they can be requested either on discord or as a feature request here! Perhaps a message should appear to inform the user that there are no commands available currently?

EDIT: See Issue #3276 for more information on this also.
