### ISSUE TITLE
UID display bug

### ISSUE THREAD

**Issue by daniiloss** [flipperdevices/flipperzero-firmware#3283]
### Describe the bug.

![Screenshot-20231211-143534](https://github.com/flipperdevices/flipperzero-firmware/assets/21144467/4e9e263a-0640-434b-853a-d117b680ea51)
As it is displayed on the screenshot, tag's UID is not displayed correctly 
the last letter was moved to the next line 

### Reproduction

you scan a card with a long UID

### Target

NFC

**Comment by skotopes** [comment]
should be fixed in latest version
