### ISSUE TITLE
help reading RFID

### ISSUE THREAD

**Issue by viosilva** [flipperdevices/flipperzero-firmware#3290]
hi. I'm new to the flipper zero. I'm trying to read my work ID it's a KERI card.  if you guys can help, That would be awesome.
[work keys.zip](https://github.com/flipperdevices/flipperzero-firmware/files/13653422/work.keys.zip)

**Comment by PRUDHVI69** [comment]
Can you explain me in detail what u want exactly ?

**Comment by viosilva** [comment]
hi thank you for Responding.  Wanted to know if there's any way, I can be able to emulate and write the card on my flipper.

**Comment by viosilva** [comment]
hi thank you for Responding. Wanted to know if there's any way, I can be able to emulate and write the tag on my flipper.I can only read it raw. I work construction and they break pretty frequently on me   when  it breaks on me. I have to drive like an hour or so to get a replacement one.

**Comment by skotopes** [comment]
Reading in RAW is not what you think it is. It's more like recording ambient sound, you may have some signal or not.

Your RAW recording are pretty much empty. There are couple possibilities:
- This is not LF RFID tag(can be HF RFID or UHF RFID)
- This may be Reader Talk First Tag like Hitag. They are currently not supported.

Try to find exact system/fob model.

**Comment by skotopes** [comment]
Reopen if you get some meaningful data or system vendor name/model
