### ISSUE TITLE
Official/Unleashed FW install bug

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3298]
### Describe the bug.

From time to time, I am trying functions of "Unleashed" FW for FZ ([https://github.com/DarkFlippers/unleashed-firmware](url)). When I am hopping between these firmwares, folder "/ext/apps/Bluetooth" on microSD card always dissapear for unknown reason.

### Reproduction

Upload any (out of FZ app store) BT app to BT folder (in my case BLE Spam 4.3)
Install any "Unleashed" FW release (folder still exist)
Again install any latest official FW (folder will dissapear)

### Anything else?

I am installing/hopping via FW's via FZ internal browser. Just open folder, then select update.

**Comment by Obsidien7** [comment]
I myself get caught in spam .for that is where the lambs reside.trapped
looking for the point of return

**Comment by hedger** [comment]
Please only report issues that can be reproduced on official firmware, not involving any 3rd-party versions.
