### ISSUE TITLE
NFC to USB

### ISSUE THREAD

**Issue by FalsePhilosopher** [flipperdevices/flipperzero-firmware#3313]
### Description of the feature you're suggesting.

Be able to send NFC file data through USB.
Example use is emulate Disney Infinity NFC figures being placed on the USB power portal.

**Comment by hedger** [comment]
That sounds like something that can be implemented as a custom application for app catalog https://lab.flipper.net/apps - not a part of the firmware.

**Comment by FalsePhilosopher** [comment]
> That sounds like something that can be implemented as a custom application for app catalog https://lab.flipper.net/apps - not a part of the firmware.

So the USB API supports sending NFC data through it already?
