### ISSUE TITLE
Wrong PollerEventType description in NFC API

### ISSUE THREAD

**Issue by blluv** [flipperdevices/flipperzero-firmware#3320]
### Describe the bug.

While developing an application with the new NFC stack, I noticed that the descriptions of PollerEventTypeError and PollerEventTypeReady were swapped.

https://github.com/flipperdevices/flipperzero-firmware/blob/c9e3f203140c7ad230ca58d360db394c92c6aeb9/lib/nfc/protocols/iso14443_4a/iso14443_4a_poller.h#L19-L22
https://github.com/flipperdevices/flipperzero-firmware/blob/c9e3f203140c7ad230ca58d360db394c92c6aeb9/lib/nfc/protocols/iso14443_3a/iso14443_3a_poller.h#L20-L23
...

lib/nfc/protocols/felica/felica_poller.h
lib/nfc/protocols/iso14443_4b/iso14443_4b_poller.h
lib/nfc/protocols/iso14443_4a/iso14443_4a_poller.h
lib/nfc/protocols/iso14443_3b/iso14443_3b_poller.h
lib/nfc/protocols/iso15693_3/iso15693_3_poller.h
lib/nfc/protocols/iso14443_3a/iso14443_3a_poller.h

### Reproduction

I apologize that I couldn't find the appropriate issue template and sent it to the bug template.

**Comment by gornekich** [comment]
Thanks! Fix will arrive with #3324
