### ISSUE TITLE
Not supported RFID protocol

### ISSUE THREAD

**Issue by Dioksin** [flipperdevices/flipperzero-firmware#3327]
### Describe the enhancement you're suggesting.

I could not read card hotel neither NFC reader or RFID reader. RFID Detector Application shown this is RFID  125 kHz card. The attached is raw data files. 
[RFID raw data.zip](https://github.com/flipperdevices/flipperzero-firmware/files/13792466/RFID.raw.data.zip)

P.S. I don't attached photo of hotel cards. It's usual white rectangular card without any text.

**Comment by skotopes** [comment]
@Dioksin ask raw data looks like it got some payload in it. Do you know name/model of the system?

**Comment by skotopes** [comment]
Please reopen if you have system vendor name and model
