### ISSUE TITLE
Cannot Read or Write Liftmaster Passport Passcard. 

### ISSUE THREAD

**Issue by sfazzina** [flipperdevices/flipperzero-firmware#3336]
### Describe the enhancement you're suggesting.

I have a Liftmaster Passport Passcard I am trying to read,  I cant read it.  It's part of the LiftMaster passport suite of products.    I just got my device today and I'm playing around with it.  This is the card I'm trying to read.   https://www.liftmaster.com/ppcsc-passport-30-bit-proximity-card/p/PPCSC

Some community members on Discord recommended I come here and share this. Hopefully we can add support for this card type. 

Thanks and have a great day

### Anything else?

Hi there, 
I have a Liftmaster Passport Passcard I am trying to read,  I cant read it.  It's part of the LiftMaster passport suite of products.   

 This is the card I'm trying to read.   https://www.liftmaster.com/ppcsc-passport-30-bit-proximity-card/p/PPCSC.  

Adding RAW captures as well - I had to rename to .txt otherwise, it wouldn't let me upload.  

Verified its an LF card. See photos 

![PasscardLF](https://github.com/flipperdevices/flipperzero-firmware/assets/19436528/7b1a90d0-1437-4d89-955c-69bab7627916)

![IMG_8472](https://github.com/flipperdevices/flipperzero-firmware/assets/19436528/bd0117c2-d2a6-48d8-99a1-2b5da5f23882)
![IMG_8471](https://github.com/flipperdevices/flipperzero-firmware/assets/19436528/1a9d1074-f13e-45f7-9762-c5a6150c6915)
[RfidRecord.ask.raw.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13824591/RfidRecord.ask.raw.txt)
[RfidRecord.psk.raw.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13824592/RfidRecord.psk.raw.txt)

**Comment by sfazzina** [comment]
Hi Team, Just wondering how long until I can read/test duplicate this card ?
I think your project is amazing. I love Flippers zero!!!!

**Comment by zinongli** [comment]
Some info that might be helpful:
Using [flipper-raw-rifl](https://github.com/hnesk/flipper-raw-rfid), I read this from Manchester demodulating the .ask.raw:

`100000000011001110111111111111111111111111010111010100011000111010111100011101111111111111111111`

96-bit long. If we flip every bit we get this sequence:

`0111111111 0 01100010 0 00000000 0 00000000 0 0000101|0 0 01010111 0 0111000|1 0 10000111 0 00100000 0 00000000 0 0000`

I formatted the sequence assuming spacers made of 0s between bytes. It appears to be that the 16 bits in between the vertical dashes (without spacers) encode card number.
`0 0 01010111 0 0111000`
remove spacers 
`00101011 10111000`
which is equal to 11192 in decimal, i.e. the card number shown in OP's photo of their card.

The long pulses are around 349 mu sec according to Flipper Lab's pulse plotter. I assume this is RF/40 which would yield 320 mu sec, the closest possible clock (the next closet is RF/50 corresponding to 400 mu sec). 

wiegand 26-bit uses the last 6 bits in the second byte to signify the bit length of encoded data. This might sound confusing but OP's link to the tag's official page is titled "PPCSC Passport 30-bit Proximity Card" while it actually says 34-bit in the product title. In any case, if we look at the digit where Securakey encode its bit length, we will get 100010 from
`                |this|                            `
`0111111111 0 01100010 0 00000000 0 00000000.....`
which equals to 34. 

@sfazzina : if you are still interested in this project, just let me know. To reverse engineer this card we might need some more back-and-forth: more raw readings (preferably of a different card) and a photo of the reader will be very helpful. I have a Securakey protocol script at hand which is a very similar format so adding compatibility for this shouldn't take more than an hour. But we can't do that before knowing what exactly each bit means.

**Comment by sfazzina** [comment]
Don't worry, worry about it. I was very interested in being able to duplicate this card but it's been a while now and we left the building and no longer need access. I have access to the facility in order to do any testing.  It's been a while and I completely forgot that I posted this. My apologies.

**Comment by skotopes** [comment]
Fixed in https://github.com/flipperdevices/flipperzero-firmware/pull/3697, thanks to @zinongli
