### ISSUE TITLE
NFC-B Support 

### ISSUE THREAD

**Issue by lemonchu** [flipperdevices/flipperzero-firmware#3341]
### Description of the feature you're suggesting.

NFC-B Simulate Request

The 0.97.1 release can read NFC-B card now, but it cannot stimulate NFC-B. If trigger a simulation, the simulation will not work and showed an error of “NULL pointer dereference”

**Comment by skotopes** [comment]
NFC-B emulation is not yet here, how did you manage to emulate it?

**Comment by lemonchu** [comment]
> NFC-B emulation is not yet here, how did you manage to emulate it?

In the app for iOS.

Click it and it appears a button to emulate. 
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/44695478/bca5bc9b-4f1b-43aa-a434-9bca04b83e35)

**Comment by skotopes** [comment]
That is a bug then. Firmware must tell you that emulation of NFC-B is not supported

**Comment by lemonchu** [comment]
Well, I am still wondering whether the NFC-B emulation will be supported in the future. Thanks~

**Comment by skotopes** [comment]
It will be

**Comment by gornekich** [comment]
@lemonchu on latest releases you will see card info instead of emulation attempt when opening your card. 

Unfortunately it's impossible to emulate NFC-B on flipper zero.

**Comment by yagueto** [comment]
> Unfortunately it's impossible to emulate NFC-B on flipper zero.

Is it impossible because of hardware/software or is it impossible _as of now_ (a.k.a. not yet implemented)? @skotopes said there would be support.

**Comment by skotopes** [comment]
@yagueto hardware limitations: nfc-b emulation is not supported by the NFC chip, software emulation is not possible because of the lack of computing resources to do it in real time.

**Comment by AntoineZoghbi** [comment]
@skotopes, will there ever be an NFC-B emulation support on the current Flipper Zero, or does there need to be a hardware update to do so?
