### ISSUE TITLE
subGhz: Keeloq: DTM System - remote protocol request

### ISSUE THREAD

**Issue by AABatteries** [flipperdevices/flipperzero-firmware#3345]
### Description of the feature you're suggesting.

I'm hoping that somebody can add support for DTM System (Keeloq based) protocol - I know DTM Neo protocol is already implemented but this seems to be a different protocol - maybe very similar so easy to add?
The transmission frequency is 433,868 MHz with AM modulation

# Subfiles
Below you will find 4 files with 10 keypresses from my 4-button remote, recorded as RAW files
[RAW_20231224-pola1.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13851597/RAW_20231224-pola1.sub.txt)
[RAW_20231224-pola2.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13851598/RAW_20231224-pola2.sub.txt)
[RAW_20231224-pola3.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13851599/RAW_20231224-pola3.sub.txt)
[RAW_20231224-pola4.sub.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13851600/RAW_20231224-pola4.sub.txt)

# Photos of the PCB
![PXL_20231224_210832327](https://github.com/flipperdevices/flipperzero-firmware/assets/999469/7f711607-3211-4bfc-9ee5-7de8f44c6f8f)
![PXL_20231224_210840809](https://github.com/flipperdevices/flipperzero-firmware/assets/999469/45b6259e-bb40-402e-b675-5b79d9106ff7)

I would love to be able to bind my gate remote with this protocol, finally I would have all of my remotes in my Flipper!
Thanks a lot!

**Comment by skotopes** [comment]
@AABatteries it's a little bit more complicated, we need this system in our office to figure out what kind of keeloq learning scheme used and if it got static manufacture key.

@Skorpionm can you guide @AABatteries throw the process?

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/issues/3085
This is where a similar system is used. To try to subtract a manufactory key from a key fob, I physically need an HCS301 microscope on my desk. you need to remove 1000+ very clean traces during nitring and use them to restore the factory key. BUT this does NOT guarantee that it will fit the entire system as in the topic above

**Comment by Skorpionm** [comment]
To add this protocol you need to know the manufacture key. it can be obtained by analyzing the HCS301 power traces during encryption. To do this I need this remote control. but since this protocol has several encoding methods, it is not at all a fact that the manufacture key that is in this remote control will fit the rest of the remote controls in this line, as happened here
https://github.com/flipperdevices/flipperzero-firmware/issues/3085

**Comment by Skorpionm** [comment]
I can’t help but encrypt by records

**Comment by carlosD2884MK** [comment]
> analyzing the HCS301 power traces

Hello, How can I perform the power trace analysis of the HC301?
