### ISSUE TITLE
Showing known credential name on read

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3346]
### Description of the feature you're suggesting.

I know, that this will be maybe a bit a hardcore, but, ... . When user sucessfully scan any type of credential (sub-GHz, NFC, RFID, iButton, ...), then show a name of existing credential (if exists) on screen with reading results.

**Comment by skotopes** [comment]
Short answer is impossible.

Long answer: this feature requires some kind of index that can be used for the search, which requires some system to maintain this index. Taking in account limited CPU/IO/RAM it doesn't make sense. But we plan such thing in next device generation.
