### ISSUE TITLE
Cloud-Based Badge Synchronization for Entry System

### ISSUE THREAD

**Issue by anonymous10download** [flipperdevices/flipperzero-firmware#3351]
### Description of the Feature

In response to issue #1345, it would be beneficial to introduce a cloud-based badge synchronization system. Consider the following use case: We have a badge-protected entry system (e.g., Badge O), where a counter is incremented on each scan of the NFC tag. Users can create copies (e.g., X1, X2, X3), and it's essential for users to synchronize their copies before and after each entry into a building.

### Sync Scenario

**Proposed Synchronization Scenario:**
Scan the badge and check against a known hash list of previous scans in the database:
- 1: Hash of the badge is known
  - 1.1 and identified as an old version: Download and write the latest version from the cloud.
  - 1.2 and identified as the latest version: No action needed; this badge is the most recent one that passed.
- 2: If the hash of the badge is unknown -> Read the badge and upload it to the cloud, defining it as the latest version.

Cloud services like Google Drive or other shared services can be utilized for this purpose.

### Synchronization Scenario Before and After Entering a Building

**Entering building using X1:**
Scenario for entering a building for the first time after copying:
- Pre-scan: Hash of the badge is not known (first scan), upload a copy to the cloud, and save the hash in the known list.
- Portal scan: The badge is desynchronized, and the counter is incremented.
- Post-scan: Hash of the badge is not known, upload a copy to the cloud, and save the hash in the known list.

**Entering Building using any X:**
- Pre-scan: Perform the synchronization scenario, usually downloading and writing the latest version.
- Portal scan: Badge is incremented.
- Post-scan: Perform the synchronization scenario, uploading the badge to the cloud.

### System Limitations

In the event that a user forgets to skip either the pre-scan or post-scan process even once, it may result in the detection of a copied badge.

**Comment by skotopes** [comment]
Hi. I believe you've already answered your question in last sentence.
Impossible to implement in a reliable way. Also too niche to be included into FZ firmware/companions.

**Comment by quantum-x** [comment]
@anonymous10download 
Head's up, this specific mechanism is patented in the AU/EU/US
https://data.epo.org/gpi/EP3797383A4-WIRELESS-ACCESS-TAG-SYSTEM-AND-METHOD
