### ISSUE TITLE
SubGHz: Missing FDI/URMET remote (4 channel 433MHz + 125kHz fob, yellow)

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3371]
### Describe the enhancement you're suggesting.

Hi. I want to report a currently unsupported remote. Can you add it please? Many thanks!

Manufacturer: FDI Matelec FR
Model nr.: FD-010-169
Channels: 4
Freq.: 433.92MHz
Battery CR2032
Chip: 10268A
Rolling code: no
Tested RAW files: yes, functional
RAW signal code (ch.1): 90339320
Note 1: number in circle on case is year of production
Note 2: colour of buttons identify this exact type (yellow = 433MHz + 125kHz fob)
Note 3: inside this RC is also a 125kHz fob, identified as "Viking", rewriteable, same ID as RF. Sucessfully rewrited and tested from Viking to HID. 

RAW files: [4b125.zip](https://github.com/flipperdevices/flipperzero-firmware/files/13941598/4b125.zip)

![IMG_20240115_130552](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/545293a0-6859-4eec-a33c-12f7e830fecb)
![2024-1-15 13-6-16](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/a4462ed9-dbc0-4812-b6d3-d3b37ab87cae)
![IMG_20240115_130508](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/ffa6b660-8718-4a7f-8861-de955da66368)
![IMG_20240115_130514](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/1f21c0c3-bef3-4c16-96b4-c3cd44c0ecb9)
![IMG_20240115_130547](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/6402a467-0bc4-4a51-9ddd-0eff1dea1a59)

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/issues/3370#issuecomment-1898627391

[4b125_key1.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13978472/4b125_key1.txt)
[4b125_key2.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13978473/4b125_key2.txt)
[4b125_key3.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13978474/4b125_key3.txt)
[4b125_key4.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13978475/4b125_key4.txt)

**Comment by Skorpionm** [comment]
I can’t help but encrypt by records
