### ISSUE TITLE
SubGHz: Missing FDI/URMET remote (4 channel 433MHz + Mifare fob, gray)

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3372]
### Describe the enhancement you're suggesting.

Hi. I want to report a currently unsupported remote. Can you add it please? Many thanks!

Manufacturer: FDI Matelec FR
Model nr.: FD-010-204
Channels: 4
Freq.: 433.92MHz
Battery CR2032
Chip: PMA7105
Rolling code: no
Tested RAW files: yes, functional
RAW signal code (ch.1): 2B932FD6
Note 1: number in circle on case is year of production
Note 2: colour of buttons identify this exact type (gray= 433MHz + Mifare fob)
Note 3: inside this RC is also a Mifare Classic 1k fob, with same ID as RF. 

RAW files: 
[4b13.zip](https://github.com/flipperdevices/flipperzero-firmware/files/13941663/4b13.zip)

![IMG_20240114_011513](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/a3086f45-a78c-4599-9814-e0d26a7dd19f)
![IMG_20240114_011648](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/0b064c64-a414-4a34-a66b-413469e12c46)
![IMG_20240114_011656](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/56e96cbb-5e6d-408e-b81d-f53e1de54aa9)
![2024-1-14 1-12-34](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/e541588d-5858-4fe6-b9d7-31109c1ff8a9)
![2024-1-14 1-13-17](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/d80e5c86-bd57-4233-9cb4-facad3807bb2)
![2024-1-14 1-13-29](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/be2afd40-ccc9-4d2c-ae41-c4f1a1ee9278)
![IMG_20240114_011443](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/d0f84eea-ac4e-4483-887c-1d8bd836b212)

**Comment by Skorpionm** [comment]
I can’t help but encrypt by records
