### ISSUE TITLE
SubGHz: Missing FDI/URMET remote (4 channel 868MHz + Mifare fob, blue)

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3373]
### Describe the enhancement you're suggesting.

Hi. I want to report a currently unsupported remote. Can you add it please? Many thanks!

Manufacturer: FDI Matelec FR
Model nr.: FD-010-172
Channels: 4
Freq.: 868.35MHz
Battery CR2032
Chip: 10268A
Rolling code: probably yes
Tested RAW files: yes, entry system says "Access denies (rolling code)" - sometimes show code, sometimes not
RAW signal code (ch.1): 0A1734EA
Note 1: number in circle on case is year of production
Note 2: colour of buttons identify this exact type (blue= 868MHz + Mifare fob)
Note 3: inside this RC is also a Mifare Classic 1k fob, with same ID as RF. 

RAW files: 
[4b868.zip](https://github.com/flipperdevices/flipperzero-firmware/files/13942159/4b868.zip)

![IMG_20240114_013700](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/6e380735-d573-42da-976f-66e567827a10)
![IMG_20240114_013731](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/183c17c9-9817-4729-8329-f31687788832)
![2024-1-14 1-38-1](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/33a05114-fd04-40bd-8a2d-321daa90bbbe)
![2024-1-14 1-38-24](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/cf008cbd-06b9-4d46-821d-95185d46f800)
![2024-1-14 1-38-33](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/83ee30b7-7610-4bc5-8d32-6b681ed00ad3)
![IMG_20240114_013520](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/61df5c6d-ae44-4541-bc58-6f90b00e9636)
![IMG_20240114_013530](https://github.com/flipperdevices/flipperzero-firmware/assets/152749132/f1226ac1-0042-4723-8aaf-462754aa16c5)

**Comment by Skorpionm** [comment]
I can’t help but encrypt by records

**Comment by franciscomfcmaia** [comment]
Did you ever figure out how to clone the RF on this? 🤔 @Tomi2965
