### ISSUE TITLE
Using submenu_add_item in a loop causes a ViewPort lockup warning

### ISSUE THREAD

**Issue by TollyH** [flipperdevices/flipperzero-firmware#3374]
### Describe the bug.

Using the `submenu_add_item` GUI method in a `for` loop causes the following warning to sometimes be outputted to the log:
`[W][ViewPort] ViewPort lockup: see applications\services\gui\view_port.c:180`

### Reproduction

1. Find a submenu scene that uses a loop to populate some or all of its items (for example NFC > Add Manually)
2. Repeatedly navigate in and out of the scene while monitoring logs (the warning may not appear every time)

### Logs

```Text
1995962 [I][Loader] Loading /ext/apps/NFC/nfc.fap
1995971 [T][StorageApi] File 00009DD0 - 0000AADC open (/ext/apps/NFC/nfc.fap)
1996111 [I][Elf] Total size of loaded sections: 58373
1996114 [T][StorageApi] File 00009DD0 - 0000AADC closed
1996116 [T][StorageApi] File/Dir 00009DD0 free
1996118 [I][Loader] Loaded in 156ms
1996123 [I][AnimationManager] Unload animation 'L1_Sleep_128x64'
1999577 [W][ViewPort] ViewPort lockup: see applications\services\gui\view_port.c:180
2003096 [W][ViewPort] ViewPort lockup: see applications\services\gui\view_port.c:180
2012261 [W][ViewPort] ViewPort lockup: see applications\services\gui\view_port.c:180
```

**Comment by skotopes** [comment]
Normally you shouldn't see this warning, but in complex apps it's kinda unavoidable. 
I'll close this issue for now. But we do have plan to change GUI architecture at some point to address it.
