### ISSUE TITLE
NFC: regression: Detect Reader seems to be broken 

### ISSUE THREAD

**Issue by philicious** [flipperdevices/flipperzero-firmware#3385]
### Describe the bug.

I am on FW `0.97.1` and tried to get the nonces from a Reader via `[Saved Tag] -> Detect Reader`
Flipper is successfully emulating the Tag and the Reader even accepts it. However the initial "Touch the reader" screen doesnt show any collected nonces or ask me to "touch reader again" as usual.

I also tried a different reader for same tag where I performed the attack successfully couple weeks ago and it also didnt work. I was on an earlier FW back then. Probably `0.95.0` or `0.94.1`. 

Hence I suspect a regression

### Reproduction

Try to sniff nonces from a reader

### Target

NFC MFClassic 1k

**Comment by skotopes** [comment]
@doomwastaken can you reproduce it with our readers?

**Comment by doomwastaken** [comment]
It worked fine with most our readers on autotests,  will check on Monday with all of them.

**Comment by philicious** [comment]
Hm. Thanks for investigating. So doesn't sound like a regression then. 

What else could be the reason?

I have one sniffed key from there already added to user dict. 
But that can't be a reason to my understanding, right?

**Comment by nekolab** [comment]
Encountered the same issue too, but I found if I attached a CLI and ran `log debug` (must be `log debug` but not `log`), the reader starts to react to the emulation. If I exit the `log debug`  (just press Ctrl-C), the emulation fails again. Hope this can help

**Comment by philicious** [comment]
Would you have any idea what could cause this issue or how it could be swarmed?

My only idea so far is to downgrade flipper to one of the versions that I probably was on when it was working last time and try again. 

But I'd rather get it working again with latest versions.

**Comment by olg857** [comment]
I’m trying to write the amiibo  on an amiibo app going to nfc > add manually > NTAG215 > emulate not able to detect it’s an 215 tag

**Comment by philicious** [comment]
@olg857 thats a different issue then described in here. pls create a separate issue

**Comment by philicious** [comment]
seems to be fixed with `0.98.2`
