### ISSUE TITLE
Add an Option for "always on mode" for backlight.

### ISSUE THREAD

**Issue by V4Cmeister** [flipperdevices/flipperzero-firmware#3393]
### Describe the enhancement you're suggesting.

It would be beneficial for apps such as 'PC Monitor' to have the ability to turn off the backlight timeout, ensuring that the screen never dims.
Additionally, it would be advantageous to add a feature that smartly reactivates the timeout automatically if the power cable is unplugged.

**Comment by skotopes** [comment]
Already implemented, see `notification_message(updater->notification, &sequence_display_backlight_enforce_on);`
