### ISSUE TITLE
curiosity

### ISSUE THREAD

**Issue by KaliStudio** [flipperdevices/flipperzero-firmware#3404]
I'm trying to understand the firmware, ... I would like to know where to find the following image? 

![Ldp52vXEmBh8AGG38GbZh_firmwareupdate](https://github.com/flipperdevices/flipperzero-firmware/assets/798505/eb52a4c9-e180-4ca4-8212-6ab7a8da17fb)

**Comment by skotopes** [comment]
this image streamed from companion through reverse screen

**Comment by KaliStudio** [comment]
where is it stored

**Comment by skotopes** [comment]
in companion app, whichever you use

**Comment by KaliStudio** [comment]
companion app qFlipper ?

**Comment by skotopes** [comment]
yes

**Comment by KaliStudio** [comment]
thank you, I will look
