### ISSUE TITLE
Software WiFi emulation

### ISSUE THREAD

**Issue by kovern** [flipperdevices/flipperzero-firmware#3407]
### Description of the feature you're suggesting.

Bluetooth and WiFi both operate in broadly similar RF range: 2.4 GHz. Although there are significant differences between the two communication technologies, the radio hardware itself can produce either signal.

This is called Cross-technology communication (CTC), which is a particular technology that enables direct communication between heterogeneous devices that use different wireless standards.

A lot of research has been done in this area in recent years, and it is now a proven fact that commercial wifi devices can emulate bluetooth signals with clever software, and vice versa: vanilla bluetooth devices can also communicate natively with wifi access points without any hardware modification.

**It would be a breakthrough hack, if Flipper Zero could employ such technology, and can emulate WiFi without any external hardware addon.**

Here are some research on the subject to start with:

1. [Unify: Turning BLE/FSK SoC into WiFi SoC](https://dl.acm.org/doi/10.1145/3570361.3592512)
2. [BlueFi: Physical-layer Cross-Technology Communication from Bluetooth to WiFi](https://dl.acm.org/doi/10.1145/3452296.3472920)
3. [FLEW: Fully Emulated WiFi](https://dl.acm.org/doi/10.1145/3495243.3517030)

**Comment by skotopes** [comment]
Nope, it can't.
