### ISSUE TITLE
BadUSB not working on Hyundai Nav unit via USB

### ISSUE THREAD

**Issue by Sliicy** [flipperdevices/flipperzero-firmware#3424]
### Describe the bug.

PR #2496 was issued last year to add support for older BIOSes that require the keyboard to support the "Keyboard Boot Protocol". I have tested both on the BIOS screen of a Dell Inspiron 5720 as well as my Hyundai Sonata 2021 navigation unit (via USB) and the Flipper fails in both instances to type.
Regarding the car, nothing types and the car doesn't recognize any external keyboard.
Regarding the laptop, only the first character prints out, failing to print the rest.

Video of bug:
https://www.youtube.com/watch?v=Sev4Nn5-d3o

Forum of issue:
https://forum.flipper.net/t/badusb-fails-to-type-to-a-hyundai-navigation-unit-car/23333

Script tested:
`STRING test`

Additionally, I tested changing the PID and VID of the Flipper, using en-US as the keyboard language, and I tried Bad-KB bluetooth. They didn't help.

### Reproduction

1. Save the following script to the Flipper: `STRING test`
2. Plug Flipper into car
3. Execute script
4. Nothing types

### Target

XFW-0052

### Anything else?

Tested on Unleashed and Xtreme (current).

**Comment by skotopes** [comment]
`Tested on Unleashed and Xtreme (current).` then why you've opened issue in the official fw repo?
