### ISSUE TITLE
BadUSB - Pause command

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3434]
### Describe the enhancement you're suggesting.

It's possible, to add a 'pause' command? I mean, add a line 'pause' to script, and FZ will wait until OK is pressed.

My case: when I do a PC fix for customer, many times I use my own scripts for lot of work. But, sometimes (or say better, many times), customer's PC is slow AF (so that's the reason why customer ask for service 😂😂😂)... . FZ run script, but sometimes (many times) next commands from FZ are run too soon. With a 'pause' command I will be able to continue script, when desired app is loaded. It's a bit sad to have a long delays in script plus I must always watch it, and start/stop manually.  Maybe - secondary - adding a 'skip' button until delay?

Yep, I was Googled, but, in Official FZ BadUSB manual is this command not mentioned..if this command exists, please close this case AFTER updating official documentation. Thanks a lot for any support!

**Comment by skotopes** [comment]
https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/file_formats/BadUsbScriptFormat.md#wait-for-button-press
