### ISSUE TITLE
NFC Emulation Time Limit

### ISSUE THREAD

**Issue by bluenazgul** [flipperdevices/flipperzero-firmware#3460]
### Describe the enhancement you're suggesting.

After the NFC Refactoring there is an Emulation Time Limit of 5min, before the Refactoring there was No Time Limit.

With this Limit it is Impossible to Play an full audio Like Emulation of an SLIX-L "TommyBox".

Please add an Option to select If you want endless Emulation or 5min emulation

**Comment by assasinfil** [comment]
Endless emulation is unsafe, there have been cases of severe heat from prolonged emulation.

**Comment by assasinfil** [comment]
This is a feature of the unleashed firmware and the emulation time limit is disabled there by enabling debug mode.
For implementation issues, you can contact @Leptopt1los.

**Comment by hedger** [comment]
Not reproducible in ofw.
