### ISSUE TITLE
Wrong block 1-2 order after writing EM to T5577

### ISSUE THREAD

**Issue by mishamyte** [flipperdevices/flipperzero-firmware#3463]
### Describe the bug.

The saved EM4100 tag, being written to T5577 with Flipper Zero has the wrong order of blocks 1 and 2. 
For most readers it's not crucial, but we faced the reader that rejected the tags written in such way. 

**The example of a tag written by Flipper Zero:**
![fz](https://github.com/flipperdevices/flipperzero-firmware/assets/5649656/8b906ff0-3b42-4f75-bd29-30acf64eae04)

**The example of a tag written by Proxmark3:**
![photo_2024-02-19_15-43-20](https://github.com/flipperdevices/flipperzero-firmware/assets/5649656/a976b02c-428d-4cd1-9100-2fdae9c503b4)

### Reproduction

1. Open RFID app
2. Choose saved EM4100 tag
3. Choose "Write" option
4. Attach T5577 tag to the FZ
5. Wait until the successful operation confirmation
6. Inspect the tag using Proxmark3 tool or similar

### Target

Release v0.98.3

### Anything else?

[EM4100 protocol reference](https://docs.rs-online.com/6ee7/0900766b8161beae.pdf)

**Comment by WildRat** [comment]
Seems like this issue also affects emuletion of EM4100 tags. I don't have Proxmark to verify this, but in current version (0,99,1) cardreader don't validate card emuleted by Flipper, that was previously worked perfectly. Reverting to previous firmware version resolves this issue.
