### ISSUE TITLE
Parser st25tb

### ISSUE THREAD

**Issue by KaliStudio** [flipperdevices/flipperzero-firmware#3465]
### Description of the feature you're suggesting.

is it possible to have an example to parse data from a st25tb card please? 
for example being able to detect if UID starts with D0 02 then retrieve the information from block 5 and display them: furi_string_cat_printf(parsed_data, "block 5: %d\n", app.block5);

**Comment by gornekich** [comment]
Hello @KaliStudio 
Have a look on mykey plugin. This card works on st25tb protocol
https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/main/nfc/plugins/supported_cards/mykey.c

**Comment by KaliStudio** [comment]
> Bonjour@KaliStudio 
Okay, thanks for this information, I'll take a look!

**Comment by KaliStudio** [comment]
does anyone have any mykey dumps?
