### ISSUE TITLE
NFC - Multi-protocol card - uid/atqa/sak wrong??

### ISSUE THREAD

**Issue by UrSuLa360** [flipperdevices/flipperzero-firmware#3466]
### Describe the bug.

I have a new nfc card detected as "multi-protocol card"

![Screenshot-20240218-170846](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/4ff6ecc3-ea96-4f6d-b0af-cd74da54e021)

I can read the card in the three modes.

![Screenshot-20240219-223158](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/0d029a0c-38a4-4f90-a44e-6b7a7c2ac705)

![Screenshot-20240218-170929](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/e8113718-e7d6-40cf-b035-5f5fcf4ac6b2)

![Screenshot-20240218-184052](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/c6eb2c3e-7a93-4bc0-be0f-ce051ff67278)

As you can see, the UID is the same in all the modes.

Here is the output using nfc-list

![Screenshot 2024-02-19 223913](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/e1d8a008-7e6d-44f6-87b5-cee73e474929)

At this point all seems right.  (yeah i already saw the SAK=38, but let's skip that for now)

The problem comes when i read it as Mifare 4k and save the dump.

(pic from app, more readable)
![WhatsApp Image 2024-02-19 at 22 48 09](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/22393eda-db7a-4ff0-9907-f632479fe93d)

The UID/ATQA/SAK are completly different in the dump.

(pic from flipper)
![Screenshot-20240219-225100](https://github.com/flipperdevices/flipperzero-firmware/assets/125646802/a89e58a4-d957-428f-ac2c-9b7672de99e3)

### Reproduction

NFC-->Read--> Read as MIfare Classic
Save the data.
Check saved data.

### Target

NFC

**Comment by skotopes** [comment]
@UrSuLa360 most likely it is some kind of javacard or some other smart card, they can have this kind of mismatch. So it doesn't looks like this is an issues on the flipper side.

Checking with proxmark or any other tool(NFC Tool for Android or IOS) most likely will confirm this mismatch.
