### ISSUE TITLE
SLIX-L Default Password

### ISSUE THREAD

**Issue by bluenazgul** [flipperdevices/flipperzero-firmware#3470]
### Describe the bug.

Right now there is an issue with saved .NFC Files of SLIX-L Tags that dont have "Privacy Mode: true" in this Case the F0 Sets the "Privacy Password" to "FF FF FF FF" this is Not correct. The Default NXP Password for SLIX-L Tags is "0F 0F 0F 0F"

Please make sure that the F0 uses this PW in Case the is No Privacy Mode Set, otherwise some Applications will have issue to read the Tags as the Default Password isnt working.

### Reproduction

1. Read SLIX-L Tag using "Extras -> Auth as TommyBox"

2. If Tag Had Privacy Mode Enabled the correct PW ist saved, of Not "FF FF FF FF" is saved as PW

**Comment by gornekich** [comment]
Thanks for the report. #3504 should fix the issue.
