### ISSUE TITLE
Flipper crashed after getting info of NFC-V tag

### ISSUE THREAD

**Issue by mxcdoam** [flipperdevices/flipperzero-firmware#3483]
### Describe the bug.

Flipper Zero randomly crashes with error "NULL pointer dereference" after reading several "ISO 15693-3 (Unknown)" tags (NXP TagInfo recognize them as ICODE SLIX  SL2S2002) and attempting to get tag's info.  This bug appears randomly, to capture it on video i had 4 reading/getting info attempts. 
FW is 0.98.3
Video is linked below.
https://www.youtube.com/shorts/CS9_5MMvPFo

### Reproduction

1) Read several ICODE SLIX tags without exiting NFC app
2) Get info of read tags.
2) After 3rd-7th tag is read , open menu and select "Info". 
Repeat until the crash occurs.

**Comment by skotopes** [comment]
@mxcdoam can you also reproduce this issues with latest rc or dev?

**Comment by mxcdoam** [comment]
> @mxcdoam can you also reproduce this issues with latest rc or dev?

I can't reproduce this issue on 0.99.0-rc, so it seems to be fixed.

**Comment by skotopes** [comment]
awesome ) then I'm closing issue
