### ISSUE TITLE
SubGHz - Unplugging external CC1101 causes freeze

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3497]
### Describe the bug.

When a external C1101 module is connected, and a VCC (or data) is disconnected by accident, FZ fill freeze, or can continue for example to config, but then freeze.

Tested on latest dev/release FW.

### Reproduction

Connect external CC1101
Run SubGHz app
Disconnect VCC
Try any function (config, back, ...)

**Comment by hedger** [comment]
External radio modules are not hot-pluggable, especially during operation.

**Comment by skotopes** [comment]
Yep, they are stateful by nature and reloading state is a challenging task.
