### ISSUE TITLE
Enable Frequency Analyzer to log detected frequencies to a file

### ISSUE THREAD

**Issue by gnarmy** [flipperdevices/flipperzero-firmware#3500]
### Describe the enhancement you're suggesting.

Please add functionality for the Frequency Analyzer of the Sub-GHz app to log frequencies it saw to a file, with time/freq, saved per session.
#Date/Time
Frequency: <123456000>

Showing the frequency and having the last 4 detected is handy, but is lacking in longer term historical logging.

**Comment by hedger** [comment]
You can create a dedicated app for that, with any level of logging or processing you need.
