### ISSUE TITLE
Video Game Module is not being recognized by Flipper Zero.

### ISSUE THREAD

**Issue by otanim** [flipperdevices/flipperzero-firmware#3509]
### Describe the bug.

Video Game Module is not being recognized by Flipper Zero when it's plugged in. Nothing happens, no notifications are popping up on Flipper Zero. When HDMI is plugged in to Video Game Module, it shows a small screen "Video Game Module is not initialized". Video Game Module Tool app is installed, as well as its firmware via the app.

The Firmware version: 0.98.3 (official)

### Reproduction

1. Connect Video Game Module to Flipper Zero.

**Comment by skotopes** [comment]
- Check device Settings: `Expansion Modules` -> `Listen UART` must be set to `USART`
- Disconnect VGM, reboot flipper with `Left` + `Back` key combo and reconnect VGM

If you still experiencing issue: contact support at https://support.flipper.net/hc/en-us

**Comment by otanim** [comment]
Thanks @skotopes, I'm all set now.
Sorry, should've read the docs attentively, your instruction was already been included in [docs](https://docs.flipper.net/video-game-module/quick-start#dX4LQ):
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/7108843/8cb58653-7ee5-49bc-9286-d997734b8109)
