### ISSUE TITLE
it says: Update needed when i open apps

### ISSUE THREAD

**Issue by TheGitUploads** [flipperdevices/flipperzero-firmware#3514]
### Describe the bug.

i updated my firmware to the latest firmware because i had to repair it (i have no sd card by the way) and when i opened an app it said update needed

### Reproduction

1. repaired and updated
2. open an app
3. says update needed

**Comment by TheGitUploads** [comment]
btw i also factory resetted (i forgot that)

**Comment by hedger** [comment]
You need an SD card for properly updating the firmware and apps.

https://docs.flipper.net/basics/first-start#1JGx9
