### ISSUE TITLE
There is no language specification for Flipper's subset of MJS

### ISSUE THREAD

**Issue by ihatecsv** [flipperdevices/flipperzero-firmware#3516]
### Description of the feature you're suggesting.

Flipper Zero FW implements a subset of MJS, which is itself a subset of JS. Due to this, I cannot use the MJS documentation as a language specification.

It is imperative that Flipper provides documentation for the unique Flipper JS-like language and Flipper's implementation of a std lib. Changes made to make the MJS engine run on the embedded platform should be documented.

`0.99.1` was pushed from RC to release without this.

**Comment by skotopes** [comment]
Original MJS documentation can be found here: https://github.com/cesanta/mjs 
Flipper part here: https://developer.flipper.net/flipperzero/doxygen/js.html
