### ISSUE TITLE
[SYSTEM NEW FUNCTION] Retrocompatibility for the 1.0.0 major update

### ISSUE THREAD

**Issue by Danucosukosuko** [flipperdevices/flipperzero-firmware#3523]
### Description of the feature you're suggesting.

I wish you could implement a new function, that when trying to open FAPs from previous firmwares, a message appears that the program will try to open it and that compatibility problems may occur.

**Comment by hedger** [comment]
We have multiple ways of providing automation for rebuilding apps to match any SDK - Flipper app catalog, ufbt, GitHub ufbt action and scheduled builds. We don't want to introduce major hard-to-debug compatibility issues by basically discarding the whole API versioning scheme.

**Comment by Danucosukosuko** [comment]
Ok
