### ISSUE TITLE
UART transfer data error

### ISSUE THREAD

**Issue by EstebanFuentealba** [flipperdevices/flipperzero-firmware#3531]
### Describe the bug.

I recently [updated my FAPs](https://github.com/flipperdevices/flipper-application-catalog/pull/305) to the latest version, and they worked perfectly. I heavily utilize UART and data transfer, and I also updated to the latest DateTime. But 🤔 I've encountered issues with the build generated with the latest version. I installed the FAP from the catalog (weighing 55kb), but when transferring via UART in my app, it gives a "[Parse Error](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/blob/fb7dba8c813a659c81fc37e5e7150c0b939fd4a7/flipper_companion_apps/applications/external/malveke_gb_cartridge/views/gb_cartridge_scene_1.c#L43)" (When I transfer a JSON from ESP32 to FZ, it means that it couldn't be deserialized). Perhaps this is related to some new changes in furi_stream_buffer, because in a FAP generated weeks earlier (60kb), it works perfectly fine.

**Fap From Catalog**
[malveke_gb_cartridge.fap.zip](https://github.com/flipperdevices/flipper-application-catalog/files/14695227/malveke_gb_cartridge.fap.zip)
![Screenshot-20240321-093557](https://github.com/flipperdevices/flipper-application-catalog/assets/442927/a8c1c255-0e1d-4565-bfea-ca821938710e)

**Fap generated weeks earlier**

[malveke_gb_cartridge.fap.zip](https://github.com/flipperdevices/flipper-application-catalog/files/14695262/malveke_gb_cartridge.fap.zip)

![Screenshot-20240321-093837](https://github.com/flipperdevices/flipper-application-catalog/assets/442927/f7f38a86-0381-43cf-9da6-d05bae34f5b6)

Both FAPs were run on the same firmware (latest version).

<img width="862" alt="Captura de pantalla 2024-03-21 a la(s) 09 39 26" src="https://github.com/flipperdevices/flipper-application-catalog/assets/442927/97c345ca-7be2-4584-88fc-c579bfed9057">

https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/issues/31

### Command And Response

The serial operation proceeds as follows:

- **MALVEKE**: The ESP32S2 board sets the baud rate to `115200` for serial data transmission.
- **F0**: Sends a `gbcartridge -i` command to retrieve cartridge information.
- **MALVEKE**: Responds with a `JSON:{...}\n` containing the requested information.
- **F0**: Receives the response, extracts the content between `JSON:` and `\n`, and parses it into JSON format.

<img width="1461" alt="Captura de pantalla 2024-03-21 a la(s) 09 52 34" src="https://github.com/flipperdevices/flipperzero-firmware/assets/442927/182596a3-fd04-47e5-ac6b-e36794b5af63">

### Reproduction

1. Install fap from catalog
2. Open app
3. Select "Cartridge Information"
4. Obtain Error

### Target

0.99.1

### Logs
I added a [`FURI_LOG_I("UART", "[in]: %c - %d", (const char)data[i], data[i]);`](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/blob/fb7dba8c813a659c81fc37e5e7150c0b939fd4a7/flipper_companion_apps/applications/external/malveke_gb_cartridge/uart.c#L126) which should print each received character.

```
Firmware version: 0.99.1 0.99.1 (90ae1f33 built on 14-03-2024)

>: log
Current log level: info
Use <log ?> to list available log levels
Press CTRL+C to stop...
8012594 [I][UART] [in]: J - 74
8012595 [I][UART] [in]: S - 83
8012595 [I][UART] [in]: O - 79
8012596 [I][UART] [in]: N - 78
8012596 [I][UART] [in]: : - 58
8012597 [I][UART] [in]: { - 123
8012597 [I][UART] [in]: " - 34
8012598 [I][UART] [in]: t - 116
8012599 [I][UART] [in]: y - 121
8012599 [I][UART] [in]: p - 112
8012600 [I][UART] [in]: e - 101
8012600 [I][UART] [in]: " - 34
8012601 [I][UART] [in]: : - 58
8012601 [I][UART] [in]: " - 34
8012602 [I][UART] [in]: i - 105
8012603 [I][UART] [in]: n - 110
8012603 [I][UART] [in]: f - 102
8012604 [I][UART] [in]: o - 111
8012604 [I][UART] [in]: " - 34
8012605 [I][UART] [in]: , - 44
8012605 [I][UART] [in]: " - 34
8012606 [I][UART] [in]: g - 103
8012606 [I][UART] [in]: b - 98
8012607 [I][UART] [in]: _ - 95
8012607 [I][UART] [in]: t - 116
8012608 [I][UART] [in]: y - 121
8012608 [I][UART] [in]: p - 112
8012609 [I][UART] [in]: e - 101
8012609 [I][UART] [in]: " - 34
8012610 [I][UART] [in]: : - 58
8012611 [I][UART] [in]: " - 34
8012611 [I][UART] [in]: g - 103
8012612 [I][UART] [in]: b - 98
8012612 [I][UART] [in]: c - 99
8012613 [I][UART] [in]: " - 34
8012613 [I][UART] [in]: , - 44
8012614 [I][UART] [in]: " - 34
8012615 [I][UART] [in]: g - 103
8012615 [I][UART] [in]: b - 98
8012616 [I][UART] [in]: _ - 95
8012616 [I][UART] [in]: s - 115
8012617 [I][UART] [in]: g - 103
8012617 [I][UART] [in]: b - 98
8012618 [I][UART] [in]: " - 34
8012618 [I][UART] [in]: : - 58
8012619 [I][UART] [in]: t - 116
8012619 [I][UART] [in]: r - 114
8012620 [I][UART] [in]: u - 117
8012620 [I][UART] [in]: e - 101
8012621 [I][UART] [in]: , - 44
8012622 [I][UART] [in]: " - 34
8012622 [I][UART] [in]: l - 108
8012623 [I][UART] [in]: o - 111
8012623 [I][UART] [in]: g - 103
8012624 [I][UART] [in]: o - 111
8012624 [I][UART] [in]: " - 34
8012625 [I][UART] [in]: : - 58
8012625 [I][UART] [in]: [ - 91
8012626 [I][UART] [in]: 2 - 50
8012626 [I][UART] [in]: 0 - 48
8012627 [I][UART] [in]: 6 - 54
8012627 [I][UART] [in]: , - 44
8012628 [I][UART] [in]: 2 - 50
8012628 [I][UART] [in]: 3 - 51
8012629 [I][UART] [in]: 7 - 55
8012630 [I][UART] [in]: , - 44
8012630 [I][UART] [in]: 1 - 49
8012631 [I][UART] [in]: 0 - 48
8012631 [I][UART] [in]: 2 - 50
8012632 [I][UART] [in]: , - 44
8012632 [I][UART] [in]: 1 - 49
8012633 [I][UART] [in]: 0 - 48
8012633 [I][UART] [in]: 2 - 50
8012634 [I][UART] [in]: , - 44
8012634 [I][UART] [in]: 2 - 50
8012634 [I][UART] [in]: 0 - 48
8012635 [I][UART] [in]: 4 - 52
8012635 [I][UART] [in]: , - 44
8012635 [I][UART] [in]: 1 - 49
8012635 [I][UART] [in]: 3 - 51
8012636 [I][UART] [in]: , - 44
8012636 [I][UART] [in]: 0 - 48
8012636 [I][UART] [in]: , - 44
8012636 [I][UART] [in]: 1 - 49
8012637 [I][UART] [in]: 1 - 49
8012637 [I][UART] [in]: , - 44
8012637 [I][UART] [in]: 3 - 51
8012637 [I][UART] [in]: , - 44
8012638 [I][UART] [in]: 1 - 49
8012638 [I][UART] [in]: 1 - 49
8012638 [I][UART] [in]: 5 - 53
8012638 [I][UART] [in]: , - 44
8012639 [I][UART] [in]: 0 - 48
8012639 [I][UART] [in]: , - 44
8012639 [I][UART] [in]: 1 - 49
8012639 [I][UART] [in]: 3 - 51
8012640 [I][UART] [in]: 1 - 49
8012640 [I][UART] [in]: , - 44
8012640 [I][UART] [in]: 0 - 48
8012640 [I][UART] [in]: , - 44
8012641 [I][UART] [in]: 1 - 49
8012641 [I][UART] [in]: 2 - 50
8012641 [I][UART] [in]: , - 44
8012641 [I][UART] [in]: 0 - 48
8012642 [I][UART] [in]: , - 44
8012642 [I][UART] [in]: 1 - 49
8012642 [I][UART] [in]: 3 - 51
8012642 [I][UART] [in]: , - 44
8012643 [I][UART] [in]: 0 - 48
8012643 [I][UART] [in]: , - 44
8012643 [I][UART] [in]: 8 - 56
8012644 [I][UART] [in]: , - 44
8012644 [I][UART] [in]: 1 - 49
8012644 [I][UART] [in]: 7 - 55
8012644 [I][UART] [in]: , - 44
8012645 [I][UART] [in]: 3 - 51
8012645 [I][UART] [in]: 1 - 49
8012645 [I][UART] [in]: , - 44
8012645 [I][UART] [in]: 1 - 49
8012646 [I][UART] [in]: 3 - 51
8012646 [I][UART] [in]: 6 - 54
8012646 [I][UART] [in]: , - 44
8012646 [I][UART] [in]: 1 - 49
8012647 [I][UART] [in]: 3 - 51
8012647 [I][UART] [in]: 7 - 55
8012647 [I][UART] [in]: , - 44
8012647 [I][UART] [in]: 0 - 48
8012648 [I][UART] [in]: , - 44
8012648 [I][UART] [in]: 1 - 49
8012648 [I][UART] [in]: 4 - 52
8012648 [I][UART] [in]: , - 44
8012649 [I][UART] [in]: 2 - 50
8012649 [I][UART] [in]: 2 - 50
8012649 [I][UART] [in]: 0 - 48
8012649 [I][UART] [in]: , - 44
8012650 [I][UART] [in]: 2 - 50
8012650 [I][UART] [in]: 0 - 48
8012650 [I][UART] [in]: 4 - 52
8012651 [I][UART] [in]: , - 44
8012651 [I][UART] [in]: 1 - 49
8012651 [I][UART] [in]: 1 - 49
8012651 [I][UART] [in]: 0 - 48
8012652 [I][UART] [in]: , - 44
8012652 [I][UART] [in]: 2 - 50
8012652 [I][UART] [in]: 3 - 51
8012652 [I][UART] [in]: 0 - 48
8012653 [I][UART] [in]: , - 44
8012653 [I][UART] [in]: 2 - 50
8012653 [I][UART] [in]: 2 - 50
8012653 [I][UART] [in]: 1 - 49
8012654 [I][UART] [in]: , - 44
8012654 [I][UART] [in]: 2 - 50
8012654 [I][UART] [in]: 2 - 50
8012654 [I][UART] [in]: 1 - 49
8012655 [I][UART] [in]: , - 44
8012655 [I][UART] [in]: 2 - 50
8012655 [I][UART] [in]: 1 - 49
8012655 [I][UART] [in]: 7 - 55
8012656 [I][UART] [in]: , - 44
8012656 [I][UART] [in]: 1 - 49
8012656 [I][UART] [in]: 5 - 53
8012656 [I][UART] [in]: 3 - 51
8012657 [I][UART] [in]: , - 44
8012657 [I][UART] [in]: 1 - 49
8012657 [I][UAR[in]: 7 - 55
8012658 [I][UART] [in]: , - 44
8012658 [I][UART] [in]: 1 - 49
8012658 [I][UART] [I][UART] [in]: 7 - 55
8012659 [I][UA8012659 [I][UART] [in]: 3 - 51
8012660 [I][UART] [in]: , - 44
8012660 [I][UART] [in]: , - 44
8012661 [I][UA8012661 [I][UART] [in]: , - 44
8012662 [I][UA[in]: 2 - 50
8012663 [I][UART] [in]: 3 - 51
8012663[in]: 2 - 50
8012664 [I][UART] [in]: 0 - 48
8012664 [I][UART] [in]: 4 - 52
8012664 [I][UART] [I][UART] [in]: 2 - 50
8012665 [I][UA[in]: 2 - 50
8012666 [I][UART] [in]: 2 - 50
8012666[in]: 1 - 49
8012667 [I][UART] [in]: 5 - 53
8012667
8012668 [I][UART] [in]: 5 - 53
8012668 [I][UART] [in]: 9 - 57
8012668 [I][UART] [in]: , - 44
8012669 [I][UART] [in]: 1 - 49
8012669 [I][UART] [in]: 8 - 56
8012669 [I][UART] [in]: 7 - 8012669 [I][UART] [in]: 1 - 49
8012670 [I][UA8012670 [I][UART] [in]: 5 - 53
8012671 [I][UA8012671 [I][UART] [in]: 2 - 50
8012672 [I][UART] [in]: ] - 93
8012672 [I][UART] [in]: l - 108
8012673 [I][U8012673 [I][UART] [in]: _ - 95
8012674 [I][UA8012674 [I][UART] [in]: r - 114
8012675 [I][U[in]: " - 34
8012676 [I][UART] [in]: : - 58
8012676[in]: " - 34
8012677 [I][UART] [in]: s - 115
801267
8012678 [I][UART] [in]: e - 101
8012678 [I]8012678 [I][UART] [in]: : - 58
8012679 [I][UA8012679 [I][UART] [in]: m - 109
8012680 [I][U8012680 [I][UART] [in]: a - 97
8012681 [I][UA[in]: : - 58
8012682 [I][UART] [in]: " - 34
8012682[in]: " - 34
8012683 [I][UART] [in]: c - 99
012706 [I][UART] [in]: B - 66: k - 107
8012707 [I][UA8012707 [I][UART] [in]: s - 115
8012708 [I][U[in]: 4 - 52[UART] [in]: 4 - 52
8012709 [I][UART] [in]: , - 44
8012709[in]: o - 111n]: , - 44
8012710 [I][UART] [in]: m - 109 [in]: t - 116
8012788 [I][U8012688 [I][UART] [in]: : - 58
8012711 [I][UART] [in]: A - 65] [in]: K - 75
8012711 [I][8012711 [I][UART] [in]: e - 101
8012712 [I][U8012712 [I][UART] [in]: : - 58
8012713 [I][UA8012713 [I][UART] [in]: 6 - 54
8012714 [I][UART] [in]: 7 - 55n]: L - 76
8012714 [I][UART] [in]: r - 114
8012715 [I][U8012715 [I][UART] [in]: : - 58
8012716 [I][UA8012716 [I][UART] [in]: m - 109
8012717 [I][UART] [in]: a - 97
8012717 [I][UART] [in]: p - 112
8012717 [I][UART] [in]: p - 112
8012718 [I][UART] [in]: e - 101- 102
8012718 [I][UART] [in]: r [in]: : - 58 - 101
8012719 [I][UART] [in]: " - 34 [in]: a - 97
8012719 [I][UART] [in]: M - 77
8012719 [I][UART] [I][UART] [in]: C - 67
8012720 [I][UA8012720 [I][UART] [in]: " - 34
8012721 [I][UART] [in]: R - 82
8012721 [I][UART] [in]: O - 79
8012721 [I][UART] [in]: M - 77
8012722 [I][UART] [in]: S - 83d - 100
8012722 [I][UART] [in]: i - 10[in]: e - 1014
8012723 [I][UART] [in]: " - 34 [in]: " - 34
8012724 [I][UA8012704 [I][UART] [in]: 1 - 49
8012724 [I][UART] [in]:   - 32
8012724 [I][8012724 [I][UART] [in]: , - 44
8012725 [I][UA8012725 [I][UART] [in]: M - 77
8012726 [I][UA8012726 [I][UART] [in]: e - 101
8012727 [I][UART] [in]: " - 34
8012727 [I][UART] [in]: : - 58
8012727 [I][UART] [in]: " - 34
8012728 [I][UART] [in]: 3 - 51
8012728 [I][UART] [in]: 2 - 5[in]: K - 75
8012729 [I][UART] [in]: B - 66
8012729
8012730 [I][UART] [in]: 
 - 10
 ```

```Text
This is what the ESP32 sends once it reads the GAME BOY cartridge: a string that I deserialize as JSON using cJSON.

JSON:{"type":"info","gb_type":"gbc","gb_sgb":true,"logo":[206,237,102,102,204,13,0,11,3,115,0,131,0,12,0,13,0,8,17,31,136,137,0,14,220,204,110,230,221,221,217,153,187,187,103,99,110,14,236,204,221,220,153,159,187,185,51,62],"logo_correct":1,"success":1,"message":"","checksum":"047C","title":"POKEMON YELLOW","isCamera":false,"ramBanks":4,"ramEndAddress":49151,"romBanks":64,"romEndAddress":32767,"rev":0,"mapper":"MBC5","ROMSize":"1 MB","RAMSize":"32 KB"}
```

**Comment by skotopes** [comment]
Sadly we don't have this module to reproduce this issue.

Let's try to start from the other side:
- Which API is misbehaving?
- Can you show us your code that misbehaves?
- Can you make simple code example that we can test without additional hardware?

**Comment by EstebanFuentealba** [comment]
I will create a demo.ino file that can be flashed onto any ESP32 board with the bug.

**Comment by EstebanFuentealba** [comment]
> Which API is misbehaving?

Build with 0.99.1 (FuriHalSerial, stream_buffer?)

> Can you show us your code that misbehaves?

I suspect the error could be in this section:

https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/blob/fb7dba8c813a659c81fc37e5e7150c0b939fd4a7/flipper_companion_apps/applications/external/malveke_gb_cartridge/uart.c#L45-L55

Since it shouldn't be reading the entire block sent by the ESP32.


> Can you make simple code example that we can test without additional hardware?

This is a simple .ino code that can be flashed onto any ESP32.

<img width="528" alt="Captura de pantalla 2024-03-21 a la(s) 12 17 27" src="https://github.com/flipperdevices/flipperzero-firmware/assets/442927/27780034-62ca-4627-bcd3-fb743d8dae9f">

```ino
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.println("Bug: #3531");
}
String getSerialInput() {
  String input = "";

  if (Serial.available() > 0)
    input = Serial.readStringUntil('\n');

  input.trim();
  return input;
}

void loop() {
  String input = getSerialInput();
  if (input == "gbcartridge -i") {
    Serial.println("JSON:{\"type\":\"info\",\"gb_type\":\"gbc\",\"gb_sgb\":true,\"logo\":[206,237,102,102,204,13,0,11,3,115,0,131,0,12,0,13,0,8,17,31,136,137,0,14,220,204,110,230,221,221,217,153,187,187,103,99,110,14,236,204,221,220,153,159,187,185,51,62],\"logo_correct\":1,\"success\":1,\"message\":\"\",\"checksum\":\"047C\",\"title\":\"POKEMON YELLOW\",\"isCamera\":false,\"ramBanks\":4,\"ramEndAddress\":49151,\"romBanks\":64,\"romEndAddress\":32767,\"rev\":0,\"mapper\":\"MBC5\",\"ROMSize\":\"1 MB\",\"RAMSize\":\"32 KB\"}");
  }
}
```

**Video Demo**: 
[<img with="100%" src="http://i3.ytimg.com/vi/yl29lCPHQ7E/hqdefault.jpg" alt="YouTube Video" />](https://youtu.be/yl29lCPHQ7E)

**Comment by skotopes** [comment]
@EstebanFuentealba I've took a look at your code: you are using `FuriHalSerialRxEventIdle` incorrectly. You must not read data if you are using async_rx and receiving idle event because there is nothing to read. Use furi_hal_serial_async_rx  only with FuriHalSerialRxEventData event.

However if you are using `furi_hal_serial_dma_rx_start` then Idle also must be used for reading.

**Comment by skotopes** [comment]
Please let me know if it fixes your issue.

**Comment by EstebanFuentealba** [comment]
I made the change by removing `FuriHalSerialRxEventIdle`, but it didn't work.

<img width="679" alt="Captura de pantalla 2024-03-29 a la(s) 20 52 42" src="https://github.com/flipperdevices/flipperzero-firmware/assets/442927/f2179b88-bf32-4a00-a1e5-14b6c806a9a5">

I also switched to using the method `furi_hal_serial_dma_rx_start`, but that didn't work either. 
<img width="1468" alt="Captura de pantalla 2024-03-29 a la(s) 20 45 56" src="https://github.com/flipperdevices/flipperzero-firmware/assets/442927/dd170e60-e49c-48ef-83e1-227644d8d5b8">


I'm going to clone the firmware and search for the commit where it was last working.

**Comment by EstebanFuentealba** [comment]
🤔 @skotopes I cloned the Flipper Zero repository and placed the code for my app in the directory 
```bash
applications_user/malveke_gb_cartridge
```

I began testing commit by commit on the **dev** branch using 
```bash
./fbt launch APPSRC=malveke_gb_cartridge
```
The app worked correctly in all of them. I also tested the latest commit on the **release** branch, and it worked as well.

I then conducted a test with the latest commit from the release branch but this time with UFBT. 
```bash
ufbt update --channel release
```
I navigated to the directory 
```bash
cd applications_user/malveke_gb_cartridge && ufbt launch
```
which resulted in a "[Parse Error](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/blob/fb7dba8c813a659c81fc37e5e7150c0b939fd4a7/flipper_companion_apps/applications/external/malveke_gb_cartridge/views/gb_cartridge_scene_1.c#L43)" again. Could it be an issue with UFBT?

Application generated with **FBT**.

<img width="682" alt="Captura de pantalla 2024-03-29 a la(s) 21 42 58" src="https://github.com/flipperdevices/flipperzero-firmware/assets/442927/8c3d3620-a7ec-48aa-86f9-df713054cb58">


Application generated with **UFBT** (Same code).

<img width="687" alt="Captura de pantalla 2024-03-29 a la(s) 21 44 31" src="https://github.com/flipperdevices/flipperzero-firmware/assets/442927/0d219360-9721-42f0-8810-c74d94d1c2ed">

```bash
(base) estebanfuentealba@koalanetwork malveke_gb_cartridge % ufbt --version    
SCons by Steven Knight et al.:
        SCons: v4.6.0.e5eef322a4a727b96358a436dca46e8085ac8692, Sun, 19 Nov 2023 17:22:20 -0700, by bdbaddog on M1Dog2021
        SCons path: ['/Users/estebanfuentealba/.ufbt/toolchain/arm64-darwin/lib/python3.11/site-packages/SCons']
Copyright (c) 2001 - 2023 The SCons Foundation
```

**Comment by EstebanFuentealba** [comment]
Hi @skotopes  I have been comparing the `malveke_gb_cartridge.impsyms` files generated by **ufbt** and **fbt**, and in the one generated by **ufbt**, `strcpy U` is added.

```diff
--- /Users/estebanfuentealba/flipperzero-firmware/build/f7-firmware-D/.extapps/malveke_gb_cartridge.impsyms	2024-04-03 09:03:12
+++ /Users/estebanfuentealba/.ufbt/build/malveke_gb_cartridge.impsyms	2024-04-03 09:04:44
@@ -95,6 +95,7 @@
 storage_file_write U         
 storage_simply_mkdir U         
 strcmp U         
+strcpy U         
 strdup U         
 strlen U         
 strncmp U         
```

With this information, I checked the compilation flags used by **ufbt**, and in the `/Users/estebanfuentealba/.ufbt/current/sdk_headers/sdk.opts` for release, it has `-Os`, which is compiler optimization, perhaps affect some functions (like `strcpy`) from `string.h` that my code uses.

I also tried compiling with `-O1` (Basic optimization level), and the FAP works 🤓.

I've been searching, and perhaps changing `-Os` to `-O1` is most likely to work.

https://github.com/flipperdevices/flipperzero-firmware/blob/d32f1955578782efd2c9735476d8c6048c54043f/firmware.scons#L44

https://github.com/flipperdevices/flipperzero-firmware/blob/d32f1955578782efd2c9735476d8c6048c54043f/firmware.scons#L56

I'm not sure what the specific reason might be for the optimization to affect some functions 🤔.

**Comment by EstebanFuentealba** [comment]
To solve the issue, I will add the following lines to my project file.

```c
#pragma GCC optimize("O1")
```

https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/blob/807db133c64f7de1b356e095b63fda5b163fc9fe/flipper_companion_apps/applications/external/malveke_gb_cartridge/helpers/cJSON.c#L87-L89


Perhaps, in future versions of my projects, the optimal choice might be to remove JSON and utilize Protobuf for information exchange.
