### ISSUE TITLE
App installation

### ISSUE THREAD

**Issue by CorvusGei** [flipperdevices/flipperzero-firmware#3540]
### Describe the bug.

After updating to the latest release version (0.99.1) the Flipper doesn't start outdated apps anymore.
AND the outdated apps don't appear on the Flipper Android app anymore, so the only way I can detect and/or remove these apps is lab.flipper.net with the Chrome browser.
So it would be a big enhancement if I could remove them or see them in the Flipper Android app. Or you could extend the qFlipper-Tool to the functionality to add and remove apps.
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/101200194/902accca-9904-4997-b9da-809c2f54962d)
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/101200194/0a9bb41e-012c-45d1-b8bb-8e073ea2557a)
Now here the Screenshot from lab.flipper.net:
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/101200194/a463505d-6a0d-423b-adb3-d6bb8ee1c447)
So the only way to see and/or remove outdated apps is the lab.flipper.net-site. This functionality should at least be available in the mobile app, too.

### Reproduction

1. Update your Flipper
2. Try to use one of the outdated apps

**Comment by skotopes** [comment]
Those apps uses outdated API and catalog failed to build them for latest firmware version. 
Please contact apps developers and ask them to update apps for new API.
