### ISSUE TITLE
Access to Discord server

### ISSUE THREAD

**Issue by vanguacamolie** [flipperdevices/flipperzero-firmware#3558]
Hello, I would like to be able to send messages in the Flipper Devices Discord server. Unfortunately, I need to give Discord phone number in order to send messages there, which I am unwilling to do. Is there any other way to gain access? My username on Discord is `guacamolie`.

---

Sorry for the unconventional issue, but this seemed to be the best way to reach out since, well, I'm unable to send messages on Discord.

**Comment by mxcdoam** [comment]
Second that, I want to participate too, but can't if I don't give discord my phone number. Forum is almost dead, and not all subjects are appropriate for "issues" on firmware github

**Comment by skotopes** [comment]
@mxcdoam @vanguacamolie sadly that is how discord works, we can not do anything with it.
