### ISSUE TITLE
decode the dooya DD remote control line, it is bi-directional like DD2702H 

### ISSUE THREAD

**Issue by filzek** [flipperdevices/flipperzero-firmware#3562]
### Description of the feature you're suggesting.

decode the dooya DD remote control line, it is bi-directional like DD2702H  currently they are the best blinds avaliable and it is very important to decode it and be able to reproduce and play with it.

**Comment by skotopes** [comment]
@filzek should be possible, but will require specialized application for it so we can not integrate it into current subghz application.
Maybe someone from community would like to implement it.
