### ISSUE TITLE
SubGHZ: KeeLoq: transmitter manufacturer key

### ISSUE THREAD

**Issue by santomet** [flipperdevices/flipperzero-firmware#3582]
### Description of the feature you're suggesting.

I have some [Satel brand transmitters](https://www.satel.pl/en/products/intruder-alarms/radio-controllers/keyfobs/t-4/) and I would like to try to get their manufacturer key.

From previous issues I know that @Skorpionm does the power analysis when he gets the transmitter physically. Of course, I would like to have his SW to use on the data I can obtain from an oscilloscope. But I can understand that you do not want to share your app.

However, I can not find any info about how to communicate with Skorpionm and where to actually send him the transmitter for analysis. Therefore, I am opening this issue and will wait for him to contact me :) 

Thanks in advance.

**Comment by Skorpionm** [comment]
Good afternoon, well, first you need to look at what exactly is inside your keychains.  Can you take normal photos of the insides so that the markings of the parts can be seen?

**Comment by santomet** [comment]
Good morning, thanks. Yes, I took one photo as only one side of the PCB has visible traces and some components:
![satel](https://github.com/flipperdevices/flipperzero-firmware/assets/13346000/199d2c0b-893b-46dd-9c76-abf68076fb37)

**Comment by Skorpionm** [comment]
In theory, it is possible to remove power curves, but in 80% of cases the manufacturer's key is unique for each key fob.  and the game is not worth the candle.  + we need delivery to Russia, but now it’s difficult

**Comment by santomet** [comment]
Very well, according to the Satel manual, the learning process requires pressing any button on the fob twice. Also, there is explicit support for all Satel fobs. So there is apparently Normal learning only.

Therefore, I think that finding out Satel manufacturer's key is worth it in this case.

There are ways how to send anything to Russia but there might be alternatives. If possible, please contact me at [keeloq@santomet.eu](mailto:keeloq@santomet.eu) and we can talk about the details. Thanks!

**Comment by Skorpionm** [comment]
It is not possible without this system in my hands

**Comment by santomet** [comment]
Hello again, I understand, that is why I would like to send it to you if possible and why I asked you to write me to keeloq@santomet.eu
I would really like to talk to you directly if possible. If not, just say so please. Thanks
