### ISSUE TITLE
Remove circular reference to fap_icon_assets in documentation

### ISSUE THREAD

**Issue by vguttmann** [flipperdevices/flipperzero-firmware#3588]
### Describe the enhancement you're suggesting.

Remove the circular reference in the documentation when it comes to fap_icon_assets - [AppsOnSDCard.md](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/AppsOnSDCard.md) says "See Application Manifests for more details", and [AppManifests.md](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/AppManifests.md) says "See FAP Assets for more details"

**Comment by skotopes** [comment]
Sure, closing this issue, more details in https://github.com/flipperdevices/flipperzero-firmware/issues/3588
