### ISSUE TITLE
Nfc: ability to write MIFARE Ultralight tags back to original card

### ISSUE THREAD

**Issue by mxcdoam** [flipperdevices/flipperzero-firmware#3592]
### Description of the feature you're suggesting.

This feature is pretty much as the title says: right now flipper zero can only read and emulate Ultralight tags. Is it possible to also implement writing within the FW? Are there any plans for that? I'm talking about simple Ultralight tags without passwords, counters and encryption.

**Comment by skotopes** [comment]
@mxcdoam full writing is implemented in Nfc Magic app(requires gen4 magic card). Normal cards can not be fully written because of the immutable blocks.

**Comment by mxcdoam** [comment]
> @mxcdoam full writing is implemented in Nfc Magic app(requires gen4 magic card). Normal cards can not be fully written because of the immutable blocks.

Sorry, I was talking about scenario: read card -> save -> edit data -> update original card, not touching UID and OTP. Also, MifareMagic doesn't support direct write ultralights, sadly.

**Comment by skotopes** [comment]
@gornekich @Astrrra do we have any reason why we can not implement it? Like we have for MFC?

**Comment by gornekich** [comment]
No reason. We already have write to initial card for NTAGs, it will be not difficult to add this for Ultralights

**Comment by mxcdoam** [comment]
Thank you!
