### ISSUE TITLE
Suggestion/Feature Request - Add scheduling with ability to open the default apps and their functions

### ISSUE THREAD

**Issue by jmd-aKBar** [flipperdevices/flipperzero-firmware#3594]
### Description of the feature you're suggesting.

A potentially useful tool in the Flipper Zero would be a Scheduler (based on current time, which is sync'd when the FZ is connected to a PC/Phone anyways) and exposing various default apps and their functions. 
This will open up possibilities for casual users to "smart-ify" some mundane tasks.

### Anything else?

This idea came about when I was thinking of scheduling a command to be sent via the IR remote connection and wanting to script it. I asked in the Discord in the #newbie channel, where I was informed that FZ currently doesn't support scheduling.

This would help a casual FZ enthusiast in me become lazier by scheduling Aircon on/off at various fixed schedules in my day :)

However, I am fairly certain other users would also benefit. 

Another example scenario - opening the Garage door after about 20-30 seconds of unlocking the car in the morning.

**Comment by skotopes** [comment]
That sounds interesting but very niche. Also it will be quite time consuming in terms of implementation.
So we are not planning to implement it. However flipper got CLI which can be used for automation.
