### ISSUE TITLE
Install App via Hub on Dev Release 

### ISSUE THREAD

**Issue by rbartolome** [flipperdevices/flipperzero-firmware#3606]
### Description of the feature you're suggesting.

Would be great, having an option to install apps via lab.flipper.net or mobile app when running on dev release. I use the git repo for developing but can’t use it in the Apps library. Most of the apps are running anyway I would say.

**Comment by skotopes** [comment]
We intentionally don't build/install apps for dev. Dev tends to break API, that makes building and delivering apps quite problematic.
