### ISSUE TITLE
bit_buffer Documentation improvement

### ISSUE THREAD

**Issue by bettse** [flipperdevices/flipperzero-firmware#3608]
### Describe the enhancement you're suggesting.

Two things:
- I think the `bit_buffer_get_parity` documentation was copied from `bit_buffer_get_data` and not changed: https://github.com/flipperdevices/flipperzero-firmware/blob/dev/lib/toolbox/bit_buffer.h#L224-L229
- Could examples be added to the header doc comment for `bit_buffer_write_bytes_with_parity` and `bit_buffer_copy_bytes_with_parity`?  The system I am working with has parity integrated as every the 9th bit in the bit stream, (`DDDDDDDD PDDDDDDD DPDDDDDDD DP...`) which has the parity starting at the most significant bit and gradually moving down, whereas I believe (https://github.com/flipperdevices/flipperzero-firmware/blob/dev/lib/toolbox/bit_buffer.c#L113-L114) the bit_buffer methods put the 0th parity bit at the 0th (least significant) position in the byte to start with.  I recognize that either is valid, and it was just after testing the bit_buffer version I realized it didn't work for me.  A documentation example could have saved me a little time.

**Comment by skotopes** [comment]
@Astrrra can you update documentation?
