### ISSUE TITLE
Replacement screen contrast compatible

### ISSUE THREAD

**Issue by HubertYoung** [flipperdevices/flipperzero-firmware#3619]
### Describe the enhancement you're suggesting.

My flipper screen is damaged and needs to be replaced. However, after replacing it, the display is completely black and I need to adjust the contrast to -16 to display it. What do I need to do to clearly show it without modifying any code?
![微信截图_20240427225703](https://github.com/flipperdevices/flipperzero-firmware/assets/20985039/ea8c5004-bc6f-4929-ba37-fb2c4231e6e8)

**Comment by skotopes** [comment]
There are 2 screens that we use and they are kinda incompatible with each other. Information about used display is flashed into OTP memory and it's impossible to change it. 

There are 2 options that you have:
- send message to [support](http://support.flipper.net) and get coupon to buy replacement display for your flipper 
- patch `targets/f7/furi_hal/furi_hal_version.c` force  `furi_hal_version_get_hw_display` to return `FuriHalVersionDisplayErc`
