### ISSUE TITLE
125kHZ RFID Keyring wont be read by flipper

### ISSUE THREAD

**Issue by AdolfoMelilli** [flipperdevices/flipperzero-firmware#3637]
Hello, here is the raw dump of a 125Khz keyring that can't be read by flipper, it keeps cycling between ASK and PSK, the led flashes Green...
[unreadable 125K keyring.zip](https://github.com/flipperdevices/flipperzero-firmware/files/15221401/unreadable.125K.keyring.zip)

**Comment by skotopes** [comment]
@AdolfoMelilli No meaningful data in raw files. 
It's either NFC or Reader Talk First RFID.
