### ISSUE TITLE
Discord unban

### ISSUE THREAD

**Issue by masterhacka** [flipperdevices/flipperzero-firmware#3639]
### Description of the feature you're suggesting.

Hi my Discord token got hacked so someone spammed some trash with my account. I am sorry for that but changed the password so everything should be fine now. Is there any way you can unblock me?

Discord tag: xxcyanidexx

**Comment by masterhacka** [comment]
@hedger why did you close without naming any reason?
My account got compromised so this ist not fair to get a penalty.

**Comment by hedger** [comment]
Github is not the place for handling issues like that, it's for firmware-related discussions.

Anyway, your account should be unbanned now.
