### ISSUE TITLE
Add wait/pause timing for subghz protocol playback

### ISSUE THREAD

**Issue by smolbun** [flipperdevices/flipperzero-firmware#3649]
### Description of the feature you're suggesting.

I came across a RF remote that uses princeton protocol,  I can only replay it using the save .sub file from "Read RAW".
Inspecting the signal out by replaying using the protocol directly shows ~7ms of pause/wait time before the next signal is played. In actuality the pause/wait time is ~9ms.

Would it be possible to measure the estimate of the pause/wait time and store it in the .sub similarly to how "TE" is measured?

URH image played directly using the protocol:
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/45829953/f21169e7-22e1-41d8-9da8-72f8ea709c5b)

[edit]
One way I can get 9ms to to change the default 30 to 38
```cpp
instance->encoder.upload[index++] = level_duration_make(false, (uint32_t)instance->te * 38);
```
If te is 244 then the pause/wait timing would be 244 * 38 = 9272us

**Comment by skotopes** [comment]
@Skorpionm what do you think?

**Comment by Skorpionm** [comment]
I think this is some kind of custom Princeton.  Normally the pause is 30*te.  If this is changed, many systems based on the original protocol will stop working.

But is the receiver from this system definitely not receiving a signal with a pause of 7.5 ms?

**Comment by smolbun** [comment]
Yeah its not receiving at all, no matter how long I press it. I was thinking if it could be dynamically calculated instead, like by taking the maximum or the average pause timing then dividing by te. Would that be a safer approach instead?

**Comment by Skorpionm** [comment]
no, this will break the work of already saved Princeton files.  since they do not store the duration of the pause between sendings.  as an option, record the signal in Read raw mode with the threshold function enabled, only the useful signal will be recorded, almost without unnecessary noise

**Comment by smolbun** [comment]
Ah yeah make sense, currently I'm recording at as raw then decoding it if I need to analyze the transmission. Would it then be possible to introduce an optional parameter so that it can fall back to the default 30 if not specified?

**Comment by Skorpionm** [comment]
why are you decoding it?  if it’s a simple keychain, then the parcels don’t change; if you’re trying to force the system for issuing orders in food court, I’m against it.  Yes, and it’s wrong to drive in another crutch

**Comment by smolbun** [comment]
I'm confused with your response, the captured transmission is from my fan remote. I'm looking for a more efficient way to store the decoded transmission with a custom pause timing without having to use the raw transmission.

**Comment by Skorpionm** [comment]
check https://github.com/flipperdevices/flipperzero-firmware/pull/3671

**Comment by smolbun** [comment]
It works, I got `Guard_time: 37`. Thanks for the implementation, you may close this now.
