### ISSUE TITLE
Incorrect subghz frequency bands for Thailand region (TH)

### ISSUE THREAD

**Issue by panangam** [flipperdevices/flipperzero-firmware#3650]
### Describe the bug.

The subghz module does not allow transmitting frequencies in the range ~433Mhz, saying "Transmission is blocked". According to the [Thai website](https://www.nbtc.go.th/spectrum_management/%E0%B9%81%E0%B8%9C%E0%B8%99%E0%B9%81%E0%B8%A1%E0%B9%88%E0%B8%9A%E0%B8%97/%E0%B8%95%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%87%E0%B8%81%E0%B8%B3%E0%B8%AB%E0%B8%99%E0%B8%94%E0%B8%84%E0%B8%A5%E0%B8%B7%E0%B9%88%E0%B8%99%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%96%E0%B8%B5%E0%B9%88%E0%B9%81%E0%B8%AB%E0%B9%88%E0%B8%87%E0%B8%8A%E0%B8%B2%E0%B8%95%E0%B8%B4/National-Table-of-Frequency-Allocations-B-E-2555.aspx), this range is allowed for amateur radio. In fact, I live in Thailand, and have been receiving signals in this frequency range from various of my RF remotes already, so it seems to be widely used. 

![Screenshot_20240516_142504](https://github.com/flipperdevices/flipperzero-firmware/assets/17264683/5e49f63e-7828-4bc0-bf22-e825f218abc1)

![IMG20240516142750](https://github.com/flipperdevices/flipperzero-firmware/assets/17264683/6a70a774-fc32-4290-b4a6-9d0c762e6bad)

### Reproduction

1. Update firmware to the latest version using the mobile app while in Thailand (not sure how the app figures out the region).
2. Navigate to Subghz -> Region Information and see that the ~433Mhz range is not listed. 

### Anything else?

It seems to be using the same frequency bands as the Japanese region. I would try to open a pull request, but somehow could not find anywhere in the source code where the "TH" region is even defined.

**Comment by CookiePLMonster** [comment]
The region database indeed seems to assign Japanese frequencies to Thailand:
https://update.flipperzero.one/regions/api/v0/bundle
`"TH":["F_JP_312","F_JP_920"]`

**Comment by panangam** [comment]
> The region database indeed seems to assign Japanese frequencies to Thailand:
> https://update.flipperzero.one/regions/api/v0/bundle
> `"TH":["F_JP_312","F_JP_920"]`

Interesting. Is there anyway to contribute to this list?

**Comment by CookiePLMonster** [comment]
> Interesting. Is there anyway to contribute to this list?

Not that I am aware.

**Comment by skotopes** [comment]
> > The region database indeed seems to assign Japanese frequencies to Thailand:
> > https://update.flipperzero.one/regions/api/v0/bundle
> > `"TH":["F_JP_312","F_JP_920"]`
> 
> Interesting. Is there anyway to contribute to this list?

This repository is exactly where it should be done. I'll take a look on provided papers tomorrow and update list if our certification lab accepts it.

**Comment by skotopes** [comment]
I've updated region data, should be correct now
