### ISSUE TITLE
Flipper won't read this RFID

### ISSUE THREAD

**Issue by dbmiller65** [flipperdevices/flipperzero-firmware#3656]
### Description of the feature you're suggesting.

Here are the raw RFID fils

[Archive.zip](https://github.com/flipperdevices/flipperzero-firmware/files/15366921/Archive.zip)

### Anything else?

Please let me know next steps

**Comment by skotopes** [comment]
@dbmiller65 no meaningful data in files.
It is either NFC or Reader Talk First RFID
