### ISSUE TITLE
Some strange problems with firmware

### ISSUE THREAD

**Issue by chenpotatos** [flipperdevices/flipperzero-firmware#3665]
I replaced the memory chip for my Flipper Zero and it is now having a white screen issue, what tool can I use to re-flash the firmware for it.Please contact email:ohlinj2021@outlook.com for further solution.:(

**Comment by skotopes** [comment]
There are no memory chips in Flipper, only MCU. And Since MCU replacement is hell of a challenge, most likely you are taking about SD-card.

In that case update firmware with companion app(qFlipper or mobile app or https://lab.flipper.net). That will provision all missing assets to SD.
