### ISSUE TITLE
NFC Ultralight C Unlock Manually Password Too Short

### ISSUE THREAD

**Issue by zinongli** [flipperdevices/flipperzero-firmware#3668]
### Describe the bug.

When an Mifare Ultralight C card is read and found to be password protected, there is the option to Unlock - Enter Password Manually. ULC's password is 16-byte long, but in this manually input interface, there are only 4 bytes allowed (see below).

![Screenshot-20240527-161004](https://github.com/flipperdevices/flipperzero-firmware/assets/131403964/7b8e47ec-2e4f-4682-8903-5a3fd5eaffba)

There appears to be left and right arrows to the side of the password box, but pressing left or right button only allows one to select different bytes but not go to a next or a previous page. 

![Screenshot-20240527-161017](https://github.com/flipperdevices/flipperzero-firmware/assets/131403964/3ee04664-98e2-4794-a6bb-f2842b876ec1)

I've also got suggestions from NFC Gandalf and NFC Samwise on Discord to ask for a new feature to have the default 3des key to be tried in the read procedure for ULC

### Reproduction

Read a password protected ULC card, go to Unlock - Enter Password Manually. You will discover that it won't allow going to the next 4 bytes.

**Comment by mxcdoam** [comment]
Yes, it is a bit confusing. I wanted to unlock my tag with "BREAKMEIFYOUCAN!" key and saw only four bytes to fill in.

**Comment by skotopes** [comment]
@gornekich should we give @Astrrra this task?

**Comment by gornekich** [comment]
@skotopes yes. We need to add authentication for Ultralight C

**Comment by miladhatami1393** [comment]
this task?

**Comment by gornekich** [comment]
@zinongli could you please try #3720 ?

**Comment by zinongli** [comment]
> @zinongli could you please try #3720 ?

Good stuff! But there has to be a little delay. I'm on a work trip and didn't bring the ULC card with me. I will once I get back home on 22nd.

**Comment by zinongli** [comment]
@gornekich I can confirm I can type in the password and try unlocking the card with #3720 . However, since I didn't know the password of the card, and my guessed password was probably wrong, it just stucked in the "Don't move" page. I'm sure you have ULC cards on your end of which you know the correct password.

There is a small caveat: when I typed in the wrong password in Unlock, and quit during "Don't move" page, try reading the card again without quitting the app, it was unable to read the card. It stucked at the "Don't move" page in Read. But after I quit the NFC app and reenter, Read works again.
