### ISSUE TITLE
418 is blocked in MX region but it's what a lot of doors use here

### ISSUE THREAD

**Issue by RnD-AIM** [flipperdevices/flipperzero-firmware#3691]
### Describe the bug.

Most access control remotes use controls at 418 MHz. I had several that I was working with stored, and now I can no longer transmit at that frequency.

### Reproduction

![WhatsApp Image 2024-06-06 at 09 07 37_b433fb35](https://github.com/flipperdevices/flipperzero-firmware/assets/132378414/5abf3b1b-9877-47a2-9cb6-8254faa6a5fb)
Here's the image of one of the ones I have saved.

**Comment by hedger** [comment]
If you believe the regional limitations for a particular country are incorrect, please provide links to official regulations that explicitly specify unlicensed frequency ranges.

**Comment by skotopes** [comment]
Mexico currently uses same bands as US and CA.
Please provide link to official band allocation table and some examples of the devices that operates in 418MHz band.
