### ISSUE TITLE
RFID 125khz: simple thin white card without markings

### ISSUE THREAD

**Issue by mrg00l** [flipperdevices/flipperzero-firmware#3693]
### Description of the feature you're suggesting.

Can't read it.
[RFIDRAW240607.zip](https://github.com/user-attachments/files/15740191/RFIDRAW240607.zip)

**Comment by mrg00l** [comment]
The reader (unknown) does not emit without a card, but when the card is presented, the RFID DETECTOR determines the frequency (125khz).

**Comment by skotopes** [comment]
No meaningful data in payload. Most likely it's ReaderTalkFirst protocol or not LFRFID.
Do you have proxmark?

**Comment by mrg00l** [comment]
I have a card. I have access with a reader (there are about a dozen of them). But so far I don’t understand how it works. Reader does not emit without a card, RFID DETECTOR show nothing. Only when card detected, it shows 125 khz.

**Comment by skotopes** [comment]
Most likely it's a HiTag.
