### ISSUE TITLE
write dump to orignal card HI! CARD TAGS  NFC 

### ISSUE THREAD

**Issue by jOIDIJI** [flipperdevices/flipperzero-firmware#3700]
### Describe the bug.

hi please help i have dump HI! CARD after dump need write to orignal card i am error
<img width="256" alt="Screenshot-20240609-150417" src="https://github.com/flipperdevices/flipperzero-firmware/assets/170568175/38a939a0-3d5f-4df2-8dde-dde0e64bc89d">
<img width="256" alt="Screenshot-20240609-150410" src="https://github.com/flipperdevices/flipperzero-firmware/assets/170568175/d63a1848-f17e-4b1b-b02c-644f0ca78cba">

### Reproduction

dump writ to orignal card no acces on  card

### Target

HI! CARD coffee machine key

**Comment by skotopes** [comment]
Please provide meaningful description of the issue.
