### ISSUE TITLE
Feature Request: NFC 14443a I-Block chaining

### ISSUE THREAD

**Issue by bettse** [flipperdevices/flipperzero-firmware#3701]
### Description of the feature you're suggesting.

Based on my read of iso14443_4_layer_decode_block (https://github.com/flipperdevices/flipperzero-firmware/blob/dev/lib/nfc/helpers/iso14443_4_layer.c#L49-L63) I believe the flipper is lacking I-Block chaining support.  I've done a dump of a card interaction and the first is 0x12 (0b00010010) which I think is chaining based on this: https://github.com/RfidResearchGroup/proxmark3/blob/master/armsrc/iso14443a.c#L2953 .  I'm by no means a low level 14a dev, so I might be wrong.

I'd love to have I-block chaining so I could have further interaction with this javacard.

**Comment by gornekich** [comment]
Working on this right now. Should be ready this week

**Comment by gornekich** [comment]
Still working on it, should be ready on next release

**Comment by P-L-K** [comment]
> Still working on it, should be ready on next release

Does the release of 1.0 help?

**Comment by bettse** [comment]
Someone linked me https://github.com/flipperdevices/flipperzero-firmware/pull/3918

Tested my ndef app with dev and 🎉  no iblock problem anymore!
