### ISSUE TITLE
Flipper not detecting Mifare Desfire Ev3

### ISSUE THREAD

**Issue by SpyGdev** [flipperdevices/flipperzero-firmware#3708]
### Describe the bug.

When I try to read a mifare DESfire key fob (NFC), it is unable to recognize the card type. When I got the flipper i scanned my house key and it gave the information and the card type. Now after about a 1 month of use (do not think hardware damage). It is giving unknown info and just the UID. this can be conformed with the use TagInfo.
![IMG_0974](https://github.com/flipperdevices/flipperzero-firmware/assets/88950166/2791b6c1-a884-4f92-8dc6-bcfbf412ca30)
![IMG_0975](https://github.com/flipperdevices/flipperzero-firmware/assets/88950166/afd72f8f-456c-4e4a-8319-d020726a87cc)
![IMG_0976](https://github.com/flipperdevices/flipperzero-firmware/assets/88950166/7b5e8cef-db7c-453a-b759-ce65a55e3106)

### Reproduction

Scan the MIFARE DESFire key fob with the Flipper.
Observe that only the UID is returned, and the card type is not recognized.

### Anything else?

Possible Causes:

Software bug or recent firmware update affecting NFC reading capabilities.
Potential degradation in NFC reading hardware, though hardware damage is unlikely

Other Key types
Sadly I do not have any other keys that i have previously saved and have with me

**Comment by doomwastaken** [comment]
Tried with our office EV3 2k card as well as other available ones and they seem to be working fine. Do you have any other versions of this card available for test? 
Also if this card is available for sale, could you provide a link so we could order one. 

Tested our cards on latest dev / 0.102.3 release

**Comment by doomwastaken** [comment]
Also try positioning card differently during read, moving the card in process might give this result

**Comment by doomwastaken** [comment]
Greetings, @SpyGdev which firmware version did you use?

**Comment by SpyGdev** [comment]
sorry for the late reply, I was using 0.98.2, but updating to latest has seem to fix the issue

**Comment by ERoCx420** [comment]
im having an issue with this NFC also it reads it but when i emulate this type on my apt door it doesnt unlock. it just flashes  blue not green
