### ISSUE TITLE
[DEV] NFC stuck at reading screen when trying to read Mi Band chip.

### ISSUE THREAD

**Issue by GitHuBBBBert** [flipperdevices/flipperzero-firmware#3709]
### Describe the bug.

Actual dev build. After trying to read my Mi Band nfc flipper getting stuck at reading screen. Need to hard restart.

### Reproduction

NFC > Read > Bring flipper to Mi Band > STUCK, no matter what you will do later. 

### Target

FZ, OFW, DEV Build

**Comment by skotopes** [comment]
@gornekich @doomwastaken ping

**Comment by doomwastaken** [comment]
@GitHuBBBBert Greetings! Could you please verify whether issue persists on latest dev build?

**Comment by GitHuBBBBert** [comment]
@doomwastaken Nope. No issue at latest dev :)
