### ISSUE TITLE
Incorrect subghz frequency bands for Dominican Republic region (DO) 

### ISSUE THREAD

**Issue by emiltejeda** [flipperdevices/flipperzero-firmware#3714]
### Describe the bug.

The subghz module does not allow transmitting frequencies in the range ~433Mhz, saying "Transmission is blocked". According to the [INDOTEL Dominican Institute of Telecommunications](https://indotel.gob.do/wp-content/uploads/2022/10/pnaf5.pdf) page 36, this range is allowed for amateur radio (Aficionados), this also match with attribution of ITU Region 2 Dominican Republics belongs to.
![image](https://github.com/flipperdevices/flipperzero-firmware/assets/11150484/1363bc99-ca4f-4956-8ec4-71bf12f050a3)

### Reproduction

1. When the region is determined as Dominican Republic.
2. Navigate to Subghz -> Region Information and see that the ~433Mhz range is not listed.

### Anything else?

Using ITU region to determined the correct frequency for regions where not information is available might be a better option than defaulting to 312.00 - 315.25 MHz and 920.50 - 923.50 MHz as it seems to be the case at the moment

**Comment by skotopes** [comment]
@emiltejeda good catch. I've updated region data for Dominican Republic.
And yes, moving to ITU region zoning by default make sense.
