### ISSUE TITLE
hey can you please give an IPA file? im on iOS 15 and the app needs iOS 16 (Unless its using newer API)

### ISSUE THREAD

**Issue by Mido7050** [flipperdevices/flipperzero-firmware#3750]
hey can you please give an IPA file? im on iOS 15 and the app needs iOS 16 (Unless its using newer API)

_Ursprünglich gepostet von @Ixolaro in https://github.com/flipperdevices/Flipper-iOS-App/issues/233_

**Comment by skotopes** [comment]
Please wait for reply in https://github.com/flipperdevices/Flipper-iOS-App/issues/233
