### ISSUE TITLE
R/W NFC file while emulating it

### ISSUE THREAD

**Issue by FalsePhilosopher** [flipperdevices/flipperzero-firmware#3754]
### Description of the feature you're suggesting.

Please add a secondary type of emulation made for NFC chips that are very regularly read/written to.

### Anything else?

The disney infinity toys can be scanned to find the UID and run infsha.py to get the key and scanned again to get the full figurine image and it successfully emulates the figurine in the game. The problem is that the game expects the figurine to be placed on the nfc reader at all times and updates the stats of the figurine regularly. So there is no current way to save to progress of emulated figurines.

**Comment by skotopes** [comment]
We'd rather not to hear words starting with N and D here ;-) Also your question is lacking technical details. Please start with our discord NFC channel https://discord.com/channels/740930220399525928/954422716138676254
