### ISSUE TITLE
CC1101: Impossible to change registers without resetting the device

### ISSUE THREAD

**Issue by krzys-h** [flipperdevices/flipperzero-firmware#3759]
### Describe the enhancement you're suggesting.

Currently, the `subghz_devices` API assumes that you will load one of the register setting presets, and use it for the duration of the transmission. Changing any of the registers, except for the frequency, requires loading a new preset, which does a full reset of the CC1101 chip, likely requiring waiting for re-calibration etc.

This may be fine when using the chip for transmitting raw data, but when using the built-in packet engine, there are situations where changing a register at runtime is required. For example, when working with fixed-length protocols (#3758) you may know that the response length is different from the request packet you just sent. The datasheet even specifies that you are allowed to re-program this register in the middle of the packet, as this is required to handle packets that are more than 255 bytes long.

The `ADDR` register and related address check config bits are another example of something that you might want to change without resetting the entire radio.

You may also want to temporarily change the "what state to go to after TX/RX complete" bits, e.g. to send two packets in rapid succession.

Since the API already allows you to set arbitrary registers using the custom preset API, I think it should also expose a way to change registers at runtime.

**Comment by skotopes** [comment]
see https://github.com/flipperdevices/flipperzero-firmware/issues/3758#issuecomment-2212399680
