### ISSUE TITLE
Wrong allowed frequency for SM

### ISSUE THREAD

**Issue by ctosae** [flipperdevices/flipperzero-firmware#3780]
### Describe the bug.

San Marino (state within Italy) adopts the same rules as Italy and the European community as permitted frequencies, but not correctly mapped in Flipper

### Reproduction

Geolocate in San Marino

**Comment by hedger** [comment]
Please provide exact discrepancies between current limitations and what's legally allowed. Also please back it up with government-issued spectrum regulations stating permitted frequency ranges.

**Comment by ctosae** [comment]
I'm referring in particular to 433MHz (remote controls, etc.).
San Marino is a very small state within Italy (where the Italian language is spoken) and there are no these documents, but there are gates and automations at 433MHz as in all of Italy and Europe

**Comment by hedger** [comment]
Thank you, a fix is coming soon.

**Comment by skotopes** [comment]
Fixed, please update firmware
