### ISSUE TITLE
Documentation suggestion: mention most 125khz RFID a person receives are read-only

### ISSUE THREAD

**Issue by bettse** [flipperdevices/flipperzero-firmware#3786]
### Describe the enhancement you're suggesting.

The page on Mifare Classic Magic taags starts with a great line about UID
> Standard NFC cards have unique identifier (UID) numbers assigned by the manufacturer. These numbers can't be changed.

I was seeing that the t5577 page (https://docs.flipper.net/rfid/write-data) didn't give context for why one would want a t5577.  My suggestion would be including a line to give that context, something like:

> In general, the 125khz RFID cards and fobs given out are read-only, or when they are not, they have a password and are based on a chip not supported for writing by the flipper zero.

**Comment by skotopes** [comment]
Done
