### ISSUE TITLE
Documentation: furi string

### ISSUE THREAD

**Issue by bettse** [flipperdevices/flipperzero-firmware#3795]
### Describe the enhancement you're suggesting.

furi string documentation cites `STRING_FAILURE` (https://github.com/flipperdevices/flipperzero-firmware/blob/4258db38883e39ef2e79bb3a9a4a0dc3df7c8129/furi/core/string.h#L320-L352) should be `FURI_STRING_FAILURE`.

**Comment by skotopes** [comment]
Fixed in https://github.com/flipperdevices/flipperzero-firmware/pull/3803
