### ISSUE TITLE
Feature Request: Mental Health Champion

### ISSUE THREAD

**Issue by ivuorinen** [flipperdevices/flipperzero-firmware#3843]
### Description of the feature you're suggesting.

Currently the dolphin is very quick to start getting sad, mad and then leaving. This, for me at least, has resulted keeping the device mostly switched off.

I'm requesting a setting that would instead of getting sad and ultimately leaving, possibly triggering feelings of guilt, or even trauma responses, that would cheer you up and be your personal support dolphin, for lack of better name.

Some ideas for screen texts:

- "Let's go out and explore!"
- "Adventure time?!"
- "I think I heard a signal"
- "Wanna go for out & scan?"

I think this would make a positive impact, and help people feel better and use the device more.

Thanks for considering this!

**Comment by ivuorinen** [comment]
Thank you @portasynthinca3 for taking the time to implement the Happy Mode ❤️

**Comment by skotopes** [comment]
Fixed in #3863
