### ISSUE TITLE
LFRFID: EM4100 detected as GProxII

### ISSUE THREAD

**Issue by korden32** [flipperdevices/flipperzero-firmware#3847]
### Describe the bug.

Looks like #3796 broke detection for EM4100 tags starting with 3D.

### Reproduction

- get EM4100 tag starting with 3D (e.g. create EM4100 with ID 3D00000000 and write to a T5577 or emulate on another flipper/pm3)
- read it
- during ASK search it'll be detected as GProxII, not EM4100

**Comment by skotopes** [comment]
fixed in #3869
