### ISSUE TITLE
Add an Bluetooth signals Spamming/copying App either for GPIO or base app

### ISSUE THREAD

**Issue by Killer74-hub** [flipperdevices/flipperzero-firmware#3854]
### Description of the feature you're suggesting.
_No response

**Comment by Killer74-hub** [comment]
but why?

**Comment by hedger** [comment]
@Killer74-hub 
Please put more effort in describing your requests.

Also non-essential applications are managed in Flipper Application Catalog, so you can either develop an app and submit it yourself or find someone who would do that.
