### ISSUE TITLE
GPIO USB UART Bridge disconnects on confirm dialog

### ISSUE THREAD

**Issue by Tomi2965** [flipperdevices/flipperzero-firmware#3882]
### Describe the bug.

Today I found a small bug in GPIO USB UART Bridge. 

When bridge is active, and then you press back, exit confirm dlg appears. This dialog asks left for exit right for stay. But, at this point, is bridge disconnected from USB. I think,  this is a bug. 

Many thanks for fix!

### Reproduction

For best preview, use Putty.

1. Connect to usb
2. Start Putty, select com port, open connection
3. When connection is open, press back on FZ. Exit dlg appears, and Putty will show error, that device is disconnected.

**Comment by Tomi2965** [comment]
@portasynthinca3 thanks for fix! :)  I can confirm - this fix works. May I kindly ask you for small additional change? On confirm dialog - on press back key - same function as right button (stay). Thanks a lot.

**Comment by portasynthinca3** [comment]
> @portasynthinca3 thanks for fix! :) I can confirm - this fix works. May I kindly ask you for small additional change? On confirm dialog - on press back key - same function as right button (stay). Thanks a lot.

Sorry, looks like I missed your request before the PR got merged

**Comment by Tomi2965** [comment]
@portasynthinca3 as I see now, the PR was removed. Any chance to make a fix? Thanks a lot.
