### ISSUE TITLE
Feature Request: Mood Changer

### ISSUE THREAD

**Issue by G2Dolphin** [flipperdevices/flipperzero-firmware#3891]
### Description of the feature you're suggesting.

In addition to new [Happy Mode](https://github.com/flipperdevices/flipperzero-firmware/pull/3863) in recent v1.0.1 release, I suggest to implement a simple Flipper mood setting.

Presumably only visible with Debug enabled, the main reason for that setting I see is that it may allow users to see animations they could not see in common device usage. For example, I use device a lot and basically never saw bad Flipper mood and all the great custom animations for it.
In some distant future it may be useful to debug any possible interactions in specific Flipper mood.

### Anything else?

Thanks for all your hard work, I guess <3

**Comment by skotopes** [comment]
Most likely we will not accept this PR. Happy Mode was kinda exception, but everything else that messes with dolphin is no go.
