### ISSUE TITLE
Javacard Emulation

### ISSUE THREAD

**Issue by WilliamHF** [flipperdevices/flipperzero-firmware#3914]
### Describe the enhancement you're suggesting.

Implement a Javacard emulation protocol (if Flipper Zero has enough memory).

The idea would be to port or load applications such as https://github.com/darconeous/gauss-key-card to allow flipper to act as various type of cards, such as a Tesla Vehicle Key for instance. 

Would F0 hardware allow it and can it be implemented in a future firmware version?

**Comment by skotopes** [comment]
In theory possible, in practice quite a challenge. We are not planning to implement it right now. But maybe someone from community will.
