### ISSUE TITLE
C# Serial terminal not registering as computer

### ISSUE THREAD

**Issue by GameLord2011** [flipperdevices/flipperzero-firmware#3919]
### Describe the bug.

So, I made a serial terminal in C# since my current terminal is... well... not great. i tried it and I think the flipper will not or cannot receive the signal. i know it is sending something because when i use the usb-uart bridge i get a signal back

### Reproduction

1. download [my app](https://drive.google.com/drive/folders/1eY2xSr0XEbMKSH0D8EZhM4B8vpR8aNio?usp=drive_link)
2. open it
3. configure for flipper

### Target

Firmware

**Comment by skotopes** [comment]
No google drive links please. Show us your source code on github.

**Comment by GameLord2011** [comment]
[here](https://github.com/gameking2011/Serial-Terminal.git)

**Comment by GameLord2011** [comment]
I made it in visual studio 2022

**Comment by skotopes** [comment]
Letter A in UART means asynchronous, see dotnet examples on how to read data from serial port. You do need reader thread.

**Comment by GameLord2011** [comment]
How would I modify my code to receive a multiline string from the serial port?

**Comment by skotopes** [comment]
@gameking2011 you should ask in some C# community about that.
