### ISSUE TITLE
JavaScript: toString uses base 10 but global.t.ts says default is base 16

### ISSUE THREAD

**Issue by jamisonderek** [flipperdevices/flipperzero-firmware#3960]
### Describe the bug.

The Intellisense comment for JavaScript toString(value, base) incorrectly shows the default base as 16, when the actual value of 10 is used.

### Reproduction

In VS Code, edit the applications\system\js_app\examples\apps\Scripts\badusb_demo.js file
Hover over the "toString" call on line 42.

Intellisense from applications/system/js_app/types/global.d.ts prints "base Integer base (`2`...`16`), default: *16*"
The expected comment is "base Integer base (`2`...`16`), default: *10*"

NOTE: `print(toString(42));` // prints "42" (base 10) not "2A" (base 16).

### Target

js

**Comment by portasynthinca3** [comment]
Good catch! Gonna fix this soon.

**Comment by portasynthinca3** [comment]
@Willy-JL has fixed this in his backport-cubed PR: https://github.com/flipperdevices/flipperzero-firmware/pull/3961/files/d2a3c16d8078354ed32a2830c8eaf10082c4db0c..26643d3ecaaea095ed4293d4f351b5730fa37419#diff-c3044cee5ace373b001714956746cf4b29df9fdd3e9fa3776fa940b0773bf5abR17
