### ISSUE TITLE
Rearrange order of favourites

### ISSUE THREAD

**Issue by j-lakeman** [flipperdevices/flipperzero-firmware#3970]
### Describe the enhancement you're suggesting.

It would be nice if the order of the favourites could be rearranged, just like the buttons of the saved infrared remotes.

### Anything else?

Maybe this could even be implemented into the app, as rearranging the order is probably easier using a touchscreen.

**Comment by skotopes** [comment]
press and hold Ok, choose move

**Comment by j-lakeman** [comment]
Sorry, missed that. THX for the swift reply!
