### ISSUE TITLE
test_index.c link in docs

### ISSUE THREAD

**Issue by ivanbarsukov** [flipperdevices/flipperzero-firmware#3972]
### Describe the bug.

https://github.com/flipperdevices/flipperzero-firmware/blob/f8fa71c575b2bf14d26c0ab6f5a4b0e4d6fb99d9/documentation/UnitTests.md?plain=1#L23

### Reproduction

1. Open https://developer.flipper.net/flipperzero/doxygen/unit_tests.html#autotoc_md418
2. Click on test_index.c

### Target

Documentation

**Comment by portasynthinca3** [comment]
This is related to #3862

**Comment by portasynthinca3** [comment]
Fixed in #3977.
