### ISSUE TITLE
FURI: fix bugs

### ISSUE THREAD

**Issue by glitchcore** [flipperdevices/flipperzero-firmware#59]
One of the most important component of Flipper Core is [FURI](https://github.com/Flipper-Zero/flipperzero-firmware-community/wiki/FURI) (Flipper Universal Registry Implementation). It helps control the applications flow, make dynamic linking and interaction between applications.

In fact, FURI is just wrapper around RTOS thread management and mutexes, and callback management.

We have draft implementing of it, but there are some issues:

- [x] value mutex not implemented (`test_furi_concurrent_access` failed)
- [ ] any API returns `bool` or `pointer | NULL`, maybe add enum with error statuses
- [x] function `furi_open` has 6 arguments, maybe pass bitmask of flags
- [x] at `furiac_start` we have array for task stack and descriptor and don't reuse its elements after some task ends
- [x] you can subscribe to changing record state by passing `state_callback` to `furi_open` but it is not used (`test_furi_mute_algorithm`, part 3 failed). Also I suggest leave 1 callback for data and state (with "type" argument)
- [ ] `test_furi_nonexistent_data` not implemented
- [ ] part of `test_furi_mute_algorithm`  not implemented
- [x] Mute algorithm only partially implemented, if you want to do this, contact @glitchcore and get some vision from my mind
- [ ] Opened records not close on app exit.

Also I think about implement FURI completely in Rust

We have 2 limitations here:
* You cannot "send some data and get answer" (only take pointer to function and call it)
* Bidirectional pipes.

**Comment by willstar7222** [comment]
I am now getting furi_check

**Comment by innuendoz** [comment]
I started getting this trying to update my firmware. I was able to get rid of it and run the firmware update without reformatting or replacing my SD card by turning off "extend subghz" in the settings
