### ISSUE TITLE
iButton/NFC editing. Saving without confirmation

### ISSUE THREAD

**Issue by HydroSausager** [flipperdevices/flipperzero-firmware#674]
`Firmware version - 0.27.1-rc (zeronights)`

While editing saved iButton and NFC keys it updates the key without confirmation by clicking "save", you can just change some bytes, press back and it will be saved. This is not very convenient because you can accidentally change it and forget the original key. But when editing "125 khz" its saving only after pressing "save" button what is correct

<details>
  <summary>Video</summary>

![Alt Text](https://user-images.githubusercontent.com/45184745/131142790-da801aed-3a1c-443d-9202-83efef42c612.gif)

</details>

**Comment by anna-oake** [comment]
Internal issue: FL-1748
