### ISSUE TITLE
IDE for development

### ISSUE THREAD

**Issue by elektronika-ba** [flipperdevices/flipperzero-firmware#706]
Which IDE is recommended/preferred for flipper firmware development?
Thanks

**Comment by skotopes** [comment]
At this point project build and debugging toolchain is console oriented and doesn't depends on IDE.

Here is what we use:
- SublimeText
- Visual Studio Code
- Vim
- Clion
- QtCreator

Any other IDE that is capable to work with external build system is ok.

**Comment by ErezBinyamin** [comment]
If someone were to contribute a Flipper0 VScode plugin (or other IDE plugin) what requirements/features would you want to see?

**Comment by skotopes** [comment]
> If someone were to contribute a Flipper0 VScode plugin (or other IDE plugin) what requirements/features would you want to see?

- Cross platform
- Easy to use.  @DrZlo13 and @Skorpionm already using vscode + cmake to build project, but their toolchain is quite complex in terms of setup, I'm sure that they have something to add ;-)

**Comment by anna-oake** [comment]
Someone has set up a Segger Embedded Studio environment, please take a look: https://github.com/hedger/flipperzero-sesproject

We will also think of convenient solutions as we finish working on a new build system which will allow simpler and cross-platform build.
