### ISSUE TITLE
User apps subsystem

### ISSUE THREAD

**Issue by DrZlo13** [flipperdevices/flipperzero-firmware#73]
# Problem
Flipper zero must run user applications.

# Constrains
**Static storage**: solved, recently we get a sd card.
**Executable storage**: we have only 128k ram. Flash storage is not an option because according to the datasheet inner mcu flash has only 10k rewrites.
**Speed**: user apps must run native code, because some protocols require tight gpio timings, eg.

By speed constrains we can't use any of script-driven languages for apps. By exec storage constrains we can't design all systems like a user-app. 

# Solution
1) Divide apps by two groups. First — "embedded" apps, its a "basic functionality" like a iButton emulator app, and this group embedded into firmware. Second group — real "user" app. It limited in, says, 100k of ram+rom (i think 28k of ram for core is enough), because it will be loaded and executed in ram.
2) Load and exec only one user app at a time. Sounds bad, but I don't see any real cases for running two user applications at the same time. It free us of dynamic ram manager and ram defragmentation problem.
3) Load user apps from .elf with dynamic linking on load, so we get more flexibility in core api. Also we can get more ram in future, so in theory loading two and more user apps is not a problem (besides defragmentation).

# My role
I can design and implement dynamic linking because I have a lot of experience in this area.

**Comment by clasqui** [comment]
Has this discussion been continued somewhere else,  with the upcoming release 1.0.0? I read somwhere this is still an expected feature for the first stable release.  Or is this still blocked? Can't find a newer issue here, neither a related post on the forum.

**Comment by skotopes** [comment]
@clasqui this feature will be a part of v1.0.0. We are currently working on external application and SDK. Please check our roadmap.

**Comment by clasqui** [comment]
@skotopes Nice, thank you for the clarification. Is there somewhere where I can follow the discussion on the implementation and the development of this feature? I mean, a post, a discord channel, an issue, a branch...

**Comment by skotopes** [comment]
Yes, we do Q&A sessions on discord and update roadmap from time to time.

**Comment by skotopes** [comment]
Also https://github.com/flipperdevices/flipper-questions-and-answers
