### ISSUE TITLE
Ibutton emulation bug

### ISSUE THREAD

**Issue by HydroSausager** [flipperdevices/flipperzero-firmware#733]
**Describe the bug**
When you trying to emulate stored key (dallas in my case) it wont work untill you read any other ibutton key.

**To Reproduce**
1. Reboot flipper
2. Try to open the door by emulating stored Ibutton key (only dallas tested)
3. Will not work
4. Read Ibutton key (only dallas tested)
5. Try to open the door by emulating just readed ibutton key (or go back and use saved one)
6. Will works fine untill reboot. (exit from ibutton application doesnt break emulation once it fixed)

**Target**
F6 0.32.0-RC

**Comment by anna-oake** [comment]
Internal issue: FL-1891
