### ISSUE TITLE
Snake Game Feedback

### ISSUE THREAD

**Issue by OlegSchwann** [flipperdevices/flipperzero-firmware#848]
# What are you want to add or change
https://github.com/flipperdevices/flipperzero-firmware/pull/829 was merged, but since this is the first game, it's not perfect of the box. I have heard some notes about unintuitive timings. As an author who knows the inner workings, I can't see by the user's eyes myself. 

# What questions do you have
Please tell us about your impressions when you first ran the game. What did you expect that didn't come true? Each of us has some kind of experience, where did I not guess it?

**Comment by OlegSchwann** [comment]
I asked people: it must not drop button presses. They should be queued up and applied sequentially at a point suitable for turning, not overwritten like they are now.
https://github.com/flipperdevices/flipperzero-firmware/blob/68274b6c2796243f93404ce59b0944023f7a2be5/applications/snake-game/snake-game.c#L353-L364
I need to correct that.

**Comment by LionZXY** [comment]
Two main ways to improve snake game:
- Increase snake grid
- Store all pressed button in local storage and repeat it in this order

**Comment by OlegSchwann** [comment]
Some discussion here
https://t.me/flipperzero/4248

**Comment by karasevia** [comment]
Difficult, inconvenient, not intuitive, absolutely minimalistic, there is not even a table of records.
And it's perfect!!!
Please don't change anything

**Comment by anna-oake** [comment]
Closing the stale issue.

**Comment by JulyIghor** [comment]
Wrong keys behavior. If you press fast, previous direction ignored.
It is need to be a key press queue.
Good example is here https://www.googlesnake.com
