### ISSUE TITLE
IRDA send doesn’t work in learn but work ok in saved

### ISSUE THREAD

**Issue by temamagic** [flipperdevices/flipperzero-firmware#874]
**Describe the bug**

I cloned the signal from my remote and tried to reproduce it. Expected reaction - a signal is sent to each click and the TV reacts, in fact, the TV only responded sometimes, while the remote works well

Looks like send doesnt work on every time only when you in "learn" menu, saved remotes work fine

**To Reproduce**
1. Learn new remote
2. Send learned before save
3. Wait when tv is on/off
4. Save
5. Open saved
6. Send saved

**Expected behavior**
TV reacts every time when you click send

**Target**
[sony tv](https://www.sony.ru/electronics/support/televisions-projectors-lcd-tvs/kdl-40ex521)

**Additional context**
Power SIRC A:01 C:15
![telegram-cloud-photo-size-2-5291924030145804187-y](https://user-images.githubusercontent.com/15264697/144892229-a35e44bf-eea4-4768-9c08-8d305c22de54.jpg)

[Video bug demo](https://user-images.githubusercontent.com/15264697/144893011-711c84b0-a188-4d7c-af20-ea34f0297088.mp4)

**Comment by temamagic** [comment]
Looks like send doesnt work on every time only when you in "learn" menu, saved remotes work fine

**Comment by albkharisov** [comment]
@temamagic , thanks for reporting!
SIRC (Sony) remote sends each button signal at least 3 times. In learn menu we send signal only once, while in saved remotes menu we send signals continuously while button is pressed.
So I suppose this is the root of trouble.
I think we should implement continuous signal sending in Learn menu too. Created task.

**Comment by temamagic** [comment]
Yeah, it seems to be true

I checked it manually, it works if you send a lot of signals quickly (lol but, it turns out in the video I did it too)

**Comment by skotopes** [comment]
fixed in 0.49.0

Please reopen issue if problem persist.
