### ISSUE TITLE
Add fucntions with UI to save and send dynamic protocols. Add bruteforce for static as Came Top, Nice Flo, princeton, etc. 8-32 bits

### ISSUE THREAD

**Issue by r3df0xx** [flipperdevices/flipperzero-firmware#882]
It would be great if someone could implement in flipper's source code saving and proper replay of encrypted signals to emulate all known protocols. Also its possible to add brute-force app for picking codes for simple static remotes as Came Top and Nice Flo, princeton, etc. 8 - 32 bits and simple app for jamming frequencies. Some sources that may be usefull: https://yadi.sk/d/i06wszZ3ak2ceA

**Comment by DrZlo13** [comment]
This will not happen in our firmware. We consider this illegal and morally unethical.

**Comment by skotopes** [comment]
As @DrZlo13 told, saving and replay of encrypted signals are intentionally not included.

Came and Nice flo are supported, please provide us with recorded signal if you have issues with them.

**Comment by r3df0xx** [comment]
There is 4 versions of keeloq_mfcodes files. If I add all unique hex lines from all of them into one file will it work properly on flipper? Also what kind of manufacturer (keys) are present in there?

**Comment by skotopes** [comment]
@r3df0xx you can put your own manufacture keys to /subghz/keeloq_mfcodes_user those keys are stored in plain form 

As for keys in encrypted storage - no comments.
