### ISSUE TITLE
[Sub-Ghz] Add notification if catched key allready saved. Add new protocols.

### ISSUE THREAD

**Issue by r3df0xx** [flipperdevices/flipperzero-firmware#895]
Add notification if recieved signal allready saved and show its name on display so memory will not fill with same keys. Add ability to calculate codes for all buttons if recieved only one button from multibutton remote (2 or 4 as ex.). Add ability to manualy change CNT param and other parsed data on device. Add ability to calculate parcels for keeloq secure.

Add support for protocols: 

Doorhan
FAAC SLH
Beninca 
Dea
Allmatic
Marantec
Ditec
Genius
DTM
An-Motors
Roger
GSN
Elmes
Aprimatic
Novoferm
Normstahl/Crawford
Comunello
Kinggates
Moovo
BFT Mitto 2/4(N)
Ducati, Prastel
Clemsa (Mutancode)
SOMFY

**Comment by anna-oake** [comment]
> Add notification if recieved signal allready saved and show its name on display so memory will not fill with same keys. 

Would require keeping all the saved keys in memory and iterating over them on every received key, which is too complicated. 

> Add ability to manualy change CNT param and other parsed data on device. Add ability to calculate parcels for keeloq secure.

We won’t implement edit and/or send features for received dynamic keys. 

> Add support for protocols:

Thank you for the list. We’re trying to add as many protocols as possible, but this takes time.
