### ISSUE TITLE
Bug while interacting with "Settings" and Android App via bluetooth

### ISSUE THREAD

**Issue by HydroSausager** [flipperdevices/flipperzero-firmware#899]
**Describe the bug**
While phone is connected to flipper using android app, some interactions with "settings" can break flipper.

**To Reproduce**
[Steps ](https://t.me/flipperzero/9420)to reproduce the behavior:
1 Connect flipper to android app
2 Start screen streaming in app
3 Navigate flipper to "Settings" -> "LCD and notifications" and exit (you can change setting or not) 
4 Flipper freezes until reboot 

(without screen streaming it just breaks ble connection)

**Target**
tested on F6 
firmware - 58ce9373 953 12-12-2021

**Comment by Uptrend-john** [comment]
I don't have that exact problem my settings page is just a screen of Red (Android Device)

**Comment by skotopes** [comment]
I'll check it after we merge #1021

**Comment by skotopes** [comment]
@gornekich @nminaylov reproducible on IOS and Android.
#1033 improves device behaviour but issue still persist in BLE transport for RPC

**Comment by skotopes** [comment]
fixed in 0.52
