### ISSUE TITLE
IRDA Universal TV Library Progressbar goes beyond boundaries

### ISSUE THREAD

**Issue by temamagic** [flipperdevices/flipperzero-firmware#900]
**Describe the bug**
Progressbar in Universal TV Library goes beyond boundaries when send "POWER" sygnal
It happens when you add codes in irda/universal/tv.ir

I have not yet understood the nature of the bug, tried different options, so far it only works on a large file from the example below

I tested files with duplicates, without them and only caught when there are too many lines. Up to 303 lines, I did not experience problems, I did not begin to measure the limit line by line

I have an example file that is buggy, below

**To Reproduce**
1. Replace contents your irda/universal/tv.ir with this - https://gist.github.com/temamagic/a615d3303f601b7c676ad498649a9e25
2. Open Infrared -> Universal library -> TV's
3. Click "POWER"
4. There it is

**Expected behavior**
Progressbar don't go beyond the boundaries

**Target**
Firmware 0.40.1
Build 1 dec 2021

**Video Demo**

https://user-images.githubusercontent.com/15264697/146033669-efd9f7c0-91c3-4402-826a-a805d9e622d6.mp4

**Comment by skotopes** [comment]
Should be already fixed
