### ISSUE TITLE
[Sub-Ghz] Do not show "all unsaved data will be lost" screen after saving

### ISSUE THREAD

**Issue by temamagic** [flipperdevices/flipperzero-firmware#905]
**Describe the bug**
When you capture the raw signal and save, you will be shown “all unsaved data will be lost”, but it doesn't matter because you saved it before.

**To Reproduce**
1. Open Sub-Ghz
2. Open Read Raw
3. Capture signal and save them
4. Press "back" button

**Expected behavior**
If you have saved the signal, there should be no warning.

**Target**
Firmware 0.40.1
Build 1 dec 2021

![image](https://user-images.githubusercontent.com/15264697/146243786-b452426f-7108-433e-a33f-c53e9cf19842.png)

![image](https://user-images.githubusercontent.com/15264697/146243732-e08ff5c0-3642-4e8f-8c3f-e3078e2821e6.png)

**Comment by temamagic** [comment]
UPD: this screen is shown even when you go to "Saved" and select a previously saved "raw" and then exit SAVED

**Comment by Skorpionm** [comment]
already done. https://github.com/flipperdevices/flipperzero-firmware/pull/910
