### ISSUE TITLE
WIP: IR USB Dongle

### ISSUE THREAD

**Issue by ashpool37** [flipperdevices/flipperzero-firmware#944]
## WIP fork: https://github.com/rwxecut/flipperzero-firmware-irusb

This issue will track the continuation of work that began as a [hackathon project](https://github.com/flipperdevices/flipper-hackathon-moscow/issues/7) and at some point [will](https://habr.com/ru/company/flipperdevices/blog/595325/) be considered for incorporation into the mainline Flipper Zero firmware. The project aims to implement a plugin to the Flipper Zero firmware that enables using the device as an infrared receiver for PC and other USB hosts.

### MVP TODO
This is the bare minimum before the project is considered functional and a PR is opened.

- [x] Receive and decode certain IR commands.
- [x] Send certain USB HID reports upon receiving the commands.
- [ ] Load the dispatch rules from the SD card.
- [ ] Use GUI to switch between different sets of rules.
- [ ] Support remote definitions and app definitions as rules.
- [ ] Not [crash at start-up](https://github.com/rwxecut/flipperzero-firmware-irusb/issues/2) or at any point.
- [ ] Write documentation.

### Stretch goals
These items are considered optional and may be pursued before or after merging the PR.

- [ ] Isolate the dispatch logic from remote definitions and app definitions.
- [ ] Support loading the dispatch table from the SD card.
- [ ] Display the resulting key map after all rules are processed.
- [ ] Support customizing the rules inside the app.
- [ ] Support SubGHz as input.
- [ ] Support the on-screen keyboard as input.
- [ ] Support the Flipper keypad keys as input.
- [ ] Support BLE HID as transport.
- [ ] Become a HID multitool.

**Comment by skotopes** [comment]
Looks dead ;-)
