### ISSUE TITLE
[WIP] Mifare Classic support

### ISSUE THREAD

**Issue by ezhevita** [flipperdevices/flipperzero-firmware#963]
### Necessary features
- [ ] Read MFC 1/2/4K tag using card key map and key dictionary
- [ ] Saving MFC dumps and card key maps in FFF
- [ ] Emulation of MFC tag with all the data

### Additional features
- [ ] Attacking MFC to get keys using nested/hardnested/darkside attack with bruteforcing on external device

**Comment by skotopes** [comment]
MiFare Classic read add in 0.52.0

**Comment by guilhem** [comment]
> MiFare Classic read add in 0.52.0

@skotopes Do we have to create other issues for saving, emulation and attack?

**Comment by skotopes** [comment]
@guilhem saving already here. As for emulation we are working on it. And yes it make sense to create one more ticket to track emulation development progress.
